### ISSUE TITLE
Org-mode ordered and unordered list's Src Block' indent incorrectly.

### ISSUE THREAD

**Issue by jadestrong** [hlissner/doom-emacs#1049]
### Observed behavior

Org-mode ordered and unordered list's Src Block' indent incorrectly.
![1](https://user-images.githubusercontent.com/18475217/49914556-b946ab80-fecc-11e8-9d0d-8c1cc97b20f5.png)

### Expected behavior

correct indent src block in  list

### Steps to reproduce

1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.

### System information

<details>
<summary>Click to expand</summary>

```
Replace this line with the output of *one* of these commands:

- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.1 (Nov 29, 2018)
- Doom: 2.0.9 (develop 8c5e080afc17968ccba96439c9f6b57320311d92)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin bogon 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  modules:   (:feature evil (syntax-checker +childframe) workspaces :completion company ido (ivy +fuzzy) :ui doom doom-modeline doom-quit evil-goggles hl-todo nav-flash (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :tools editorconfig magit :lang cc data emacs-lisp javascript markdown (org +attach +babel +capture +export +present) php python qt (sh +fish) web :config default)
  packages:  (js-doc)
  exec-path: (/usr/local/opt/openssl/bin/ /usr/local/opt/qt/bin/ /usr/local/opt/llvm/bin/ ~/.nvm/versions/node/v6.11.4/bin/ ~/.cargo/bin/ ~/.pyenv/plugins/pyenv-virtualenv/shims/ ~/.pyenv/shims/ ~/.pyenv/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.4/libexec/emacs/26.1/x86_64-apple-darwin18.2.0/)
  ```
```
</details>

**Comment by hlissner** [comment]
Does setting this fix the issue?

```elisp
(setq org-src-preserve-indentation nil)
```

**Comment by hlissner** [comment]
It would appear `org-src-preserve-indentation` is definitely the issue. 

If it is non-nil (Doom uses this default), src blocks will obey their native indentation. e.g. You'll get proper Emacs Lisp indentation in an Emacs Lisp block, as you would python indentation in a python block, etc.

If it is nil, you will get naive indentation provided by org-mode for all source blocks, regardless of the language.

I think setting it to `t` and living with this consequence is the better option. It just means that you have to prepend spaces to src blocks in sublists manually. You'd only have to do this for the first line, because `org-return-indent` should indent consecutive lines correctly. You'd have to be careful not to reindent the whole block too.

This may be considered a bug in org-mode, rather than Doom.

**Comment by jadestrong** [comment]
Thank you,  I add `(setq org-src-preserve-indentation nil)`, and It works.  But in this case, if I use `==` to indent the `#END_SRC` line, it will become like this:
<img width="469" alt="wx20181213-130857 2x" src="https://user-images.githubusercontent.com/18475217/49916997-46433200-fed8-11e8-952f-f13eef8dde46.png">
Maybe setting it to `t` is the only way to go first.

**Comment by hlissner** [comment]
I'm afraid it is one or the other. This should probably be brought up to the org devs, but in any case, I'll consider this issue resolved.
