### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by cheerydo** [hlissner/doom-emacs#1051]
Hi there @hlissner, I've been using doom-emacs over my own wandering init.el for the past few months and I was wondering if you had any way of accepting donations for all your (and contributors) hard work.

If not, thanks for all the hard work anyway - please know it's very appreciated.

**Comment by areinisc** [comment]
Currently, the best method to give financial support is through [hlissner's liberapay page](https://liberapay.com/hlissner/).

Source: this topic was responded to once on the Discord ::

> Henrik 05/29/2018
> @Sovereign Bleak Thank you! I appreciate the sentiment and help. I have a liberapay profile (https://liberapay.com/hlissner/) that I intend to add a badge for in the post-2.1 readme, but I haven't thought much more about it. I'm impressed with fosspay and will look into it.

**Comment by hlissner** [comment]
It comes a bit late, but thank you so much for the sentiment and the support.

Working on Doom has been a blast so far and I can't see that changing. It took me a while to warm up to the idea of accepting donations, because I wasn't sure Doom was worthy of it (it's hard to shake that "it's just something I do on my spare time" mentality).

I've since realized that this can enable me to do more, and there _is_ more I'd like to do for the Doom and Emacs communities, like extract parts of Doom into plugins and PR monkey-patched fixes upstream to the benefit of the Emacs community. Tutorial/workflow videos/write ups for Doom are another common request I'm considering. In any case, on top of that list is to finish the new documentation and get Doom out of this `develop` branch limbo!

Anyhow, as of ead07de, the project now has a sponsor button. If you haven't already, consider joining us on [Discord](https://discord.gg/bcZ6P3y). Thanks again!
