### ISSUE TITLE
Why not copy environment variables from the shell under Linux?

### ISSUE THREAD

**Issue by yurimx** [hlissner/doom-emacs#1053]
Hello:

I am curious why you are not using `exec-path-from-shell` or similar configuration under Linux.

I saw your point of view in #741 . I think it would be better to do your own env system like Spacemacs. This can avoid the problems caused by `exec-path-from-shell` and ensure the accuracy of environment variables. Because many application launchers don't copy shell environment variables (especially user-defined).

Thank you.

**Comment by hlissner** [comment]
I apologize for the late response. 

>I think it would be better to do your own env system like Spacemacs. This can avoid the problems caused by `exec-path-from-shell` and ensure the accuracy of environment variables.

I'm not sure what this means. What does Spacemacs do to address exec-path-from-shell's shortcomings? A cursory glance [at their source](https://github.com/syl20bnr/spacemacs/blob/master/layers/+distributions/spacemacs-base/packages.el#L184-L189) suggests they don't.

> am curious why you are not using `exec-path-from-shell` or similar configuration under Linux.

1. I don't think exec-path-from-shell is a good enough solution. It only copies select variables. This half-correct environment is then propagated to child processes, which can cause unpredictable issues down the line. I cannot prepare for every possible environment variable. I'd rather Emacs inherit your shell environment correctly (and completely) or not at all (then configured from your private config). Anywhere in between is unpredictable and breeds a class of bug report I cannot deal with.

2. When it concerns the system environment, Doom, by design, trusts the user to know what they're doing. If their system is misconfigured, it should behave like it's misconfigured. It's predictable and frontloads the debugging process rather than hiding it until it you least want to deal with it.

3. Depending on your shell config, exec-path-from-shell can be slow. If I can't reasonably expect a user to  know how to fix a shell config problem on Linux, I can't reasonably expect anything from their shell config at all.

4. There is nothing stopping the user from installing exec-path-from-shell themselves. Then they can tailor it to their precise needs.

5. Linux users have many good options to resolve the issue without exec-path-from-shell: They can 1) configure their application launcher to use the correct shell, 2) launch the app launcher itself from the correct shell/environment, 3) correct a *.desktop file for Emacs, or 4) add an `emacs` shim somewhere in your PATH (higher than your system emacs) that spawns Emacs from your default shell.

   Mac users have fewer options and none of them are very good. They involve either digging into plist files or replacing the Emacs binary in its .app bundle with a shim script (this is what `bin/doom patch-macos` does). Both are undone when Emacs is updated. You could start Emacs from the terminal (or special app launcher), but you'd have more to deal with if the daemon is involved. In any case, I accept exec-path-from-shell as a necessary evil for mac users.

---

I understand it's an inconvenience but I hope that answers your question!

**Comment by yurimx** [comment]
@hlissner Thank you for your reply!

> I'm not sure what this means. What does Spacemacs do to address exec-path-from-shell's shortcomings? A cursory glance [at their source](https://github.com/syl20bnr/spacemacs/blob/master/layers/+distributions/spacemacs-base/packages.el#L184-L189) suggests they don't.

Spacemacs's `core/core-env.el` file is their solution... 

 I will close the issue and maintain my personalized doom-emacs (for my own use, not for distribution) to make sure My environment variables can be passed correctly in all the desktop environments I use (this can get very bloated, but I don't care about the startup speed. Even if it really has 30 minutes).

In terms of performance and feature selection, I feel that you prefer to improve performance (this is hard work, thank you!), and I pay more attention to the completeness of the function. After all, my Emacs really don't start and shut down often.

**Comment by hlissner** [comment]
Just a heads up: after a second look at Spacemacs' approach I thought it was a great idea, so I've adapted it to Doom in 2dc52bc to replace exec-path-from-shell (for Mac users as well). The new `bin/doom env` command can be used to manage it.

Thanks for bringing it to my attention!
