### ISSUE TITLE
Questions on doom popups

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1171]
I have few issues with the popup management in doom that I am trying to debug.

- In my config file I have `(setq TeX-debug-warnings t)` to get a window including a list of errors after compiling my latex documents. This new window is treated as a popup (which I am happy with). But then if I press return to navigate to an error a new window is created to display the source instead of using the one I have open (which is the usual behaviour if I don't enable the doom popups). The focus also stays in the popup rather than move to the newly created frame (again as is usual when not using doom's popups). If I press 'C-x o' to switch to the new created window, the popup stays open but I cannot go back to it using `C-x o` (unless I enable ace-window or switch-window or use the mouse). 

- This last issue is a general issue. Navigating away from popups using `C-x o` is possible in some cases, but switching back to them is not possible, forcing me to use the mouse to focus back to the pop-up and kill it.

- Finally, can I specify that certain popups be vertical instead of horizontal? Specifically, when editing an org-mode source block (or viewing an agenda) a vertical view would be much more natural (on my wide display at least).

**Comment by hlissner** [comment]
Sorry for the late response. I'm not a big latex user, so I'm unable to readily test this myself, but I'll try my best to answer your questions:

> In my config file I have `(setq TeX-debug-warnings t)` to get a window including a list of errors after compiling my latex documents.

It'd be better to use flycheck instead of `TeX-debug-warnings`. Flycheck should produce the same warnings, provided they use the same checkers. It provides an error list popup that works correctly with the popup manager, which can be invoked with `SPC c x` or `:errors` (for evil users). You can also navigate between errors in-buffer with `]e`/`[e` (for evil users) and `next-error`/`previous-error` otherwise.

> This new window is treated as a popup (which I am happy with). But then if I press return to navigate to an error a new window is created to display the source instead of using the one I have open (which is the usual behaviour if I don't enable the doom popups). The focus also stays in the popup rather than move to the newly created frame (again as is usual when not using doom's popups). 

Can you tell me what command is bound to RET in that popup buffer? With it selected, press `SPC h k RET` and it should tell you. I'll be able to figure out the problem with that.

Unfortunately, the mechanism that Doom's popup manager uses to control how buffers are displayed isn't foolproof. There are many ways around it through incorrect code or weird/archaic hacks that, I'm afraid, latex and auctex are full of. I'll need to dig deeper.

> If I press 'C-x o' to switch to the new created window, the popup stays open but I cannot go back to it using `C-x o` (unless I enable ace-window or switch-window or use the mouse).

This is a different issue. Popup windows have the `no-other-window` parameter on them to prevent them from being reused inadvertantly, but it has the side effect of rendering the `other-window` command incapable of selecting popups. Here are some solutions:

+ If you have the `:ui window-select` module enabled, `C-x o` should invoke `ace-window`, which will ignore the `no-other-window` parameter.
+ There's `C-x p` (`+popup/other`), which does what `other-window` does, but traverses popups. 
+ If you're an evil user, the `C-w {h,j,k,l}` keys (`evil-window-{left,down,up,right}`) can cross over into popups as well.

> Finally, can I specify that certain popups be vertical instead of horizontal? Specifically, when editing an org-mode source block (or viewing an agenda) a vertical view would be much more natural (on my wide display at least).

Certainly, with a popup rule:

```elisp
(after! latex
  ;; NOTE: I don't know the name of the warnings buffer, so this is just a guess. You'll 
  ;; have to adapt the regexp:
  (set-popup-rule! "^\\*Latex warnings\\*" :side 'left))
```

----

If all else fails, you can also the popup manager not to deal with the warnings buffer at all. e.g.

```elisp
(after! latex
  ;; NOTE: I don't know the name of the warnings buffer, so this is just a guess. You'll 
  ;; have to adapt the regexp:
  (set-popup-rule! "^\\*Latex warnings\\*" :ignore t))
```

I hope that helps!

**Comment by haji-ali** [comment]
> It'd be better to use flycheck instead of `TeX-debug-warnings`. Flycheck should produce the same warnings, provided they use the same checkers. Not only will it highlight problem regions, but it also provides an error list popup that works correctly with the popup manager, which can be invoked with `SPC c x` or `:errors` (for evil users). You can also navigate between errors in-buffer with `]e`/`[e` (for evil users) and `next-error`/`previous-error` otherwise (I think those are bound to `M-g n` and `M-g p` in vanilla Emacs, or `C-n`/`C-p` in non-evil Doom).

Hmm.. I don't think flycheck shows the same warning as the errors and warning that TeX shows. I think flycheck uses the tool chktex which does not compile the tex file to find those errors and warnings.
 

> Can you tell me what command is bound to RET in that popup buffer? With it selected, press `SPC h k RET` and it should tell you. I'll be able to figure out the problem with that.

It's bound to `TeX-error-overview-goto-source`. 
The usual behavior (when popups are disabled) is that a new popup shows up with details about the error and the "main" window is used to navigate to the source of the error.

>     * There's `C-x p` (`+popup/other`), which does what `other-window` does, but traverses popups.
Thanks! I didn't know about this command.
For consistency, maybe pop-ups should lock focus when they are open. So that I cannot navigate away from them unless I close them (like a true popup) or use a special command. Is there way to add a local hook when a particular window loses the focus and reset the focus to it?

**Comment by hlissner** [comment]
>For consistency, maybe pop-ups should lock focus when they are open.

I don't think that's a good idea. There are a multitude of reasons to open a popup, and ways to interact with the contents of a popup. It isn't uncommon to copy text then dip out of the popup to paste it elsewhere (only to return to the popup).

That said, you can control where the focus is after a popup opens: this is controlled by the `:select` property in a popup rule. The default (in `+popup-defaults`) is `#'ignore`, which means "hands off, let the opener decide". If set to `t`, the popup is always focused. If set to `nil`, the origin buffer keeps focus.

> Is there way to add a local hook when a particular window loses the focus and reset the focus to it?

Doom has a `doom-switch-window-hook` hook, which triggers when the selected window changes.

-----

In other news; quite a few things have changed in the past few months. Do you still have this issue with the `TeX-debug-warnings` window?

**Comment by haji-ali** [comment]
Thanks! Due to all the complications of the popup with latex I decided to disable this feature until I have more time to customize it to my liking.

With that being said, I just enabled it again and tried the `TeX-debug-warnings` window and I am having the same issues with it.

> I don't think that's a good idea. There are a multitude of reasons to open a popup, and ways to interact with the contents of a popup. It isn't uncommon to copy text then dip out of the popup to paste it elsewhere (only to return to the popup).

Agreed. I am not using popups at the moment, so perhaps I should leave this discussion to someone who's more familiar with them. However, it might be a more consistent interface to allow moving away from a pop using a command that allow moving back in to it (i.e., `C-x p` `(+popup/other)`). While `other-window` which normally ignores a popup should also not move away from a popup. This is somewhat pedantic on my part since I can easily customize this behavior, but I just wanted to throw in my two cents.
