### ISSUE TITLE
How to switch to treemacs with keyboard

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1177]
When I open treemacs, I am able to navigate to a file in my project then open it, but then how do I go back to treemacs' window using the keyboard (as opposed to the mouse?) Pressing `C-x o` switches to all other windows except treemacs.

**Comment by filalex77** [comment]
I have just the thing for you. I have this function in my private config:

```elisp
(defun +private/treemacs-back-and-forth ()
  (interactive)
  (if (s-contains-p "Treemacs-Framebuffer" (buffer-name))
      (evil-window-mru)
    (treemacs-select-window)))
```

And I have it bound to `SPC -` (dired inspired):

```elisp
(map! :after treemacs
      :leader
      :n "-" #'+private/treemacs-back-and-forth)
```

Hope this helps.

**Comment by haji-ali** [comment]
Thanks! Is there any reason why treemacs window is different from other windows?
Especially considering I can switch to it using ace-window if I have more than two windows open.

**Comment by filalex77** [comment]
Hey, I just found the answer. It's `treemacs-is-never-other-window` variable, by default set to `t` in [ui/treemacs/config.el#6](https://github.com/hlissner/doom-emacs/blob/cee851f55bb95132aa7e763f3d56c0b350dbd3c2/modules/ui/treemacs/config.el#L6). You can set it to `nil` and use `ace-window` or `other-window` freely :)

**Comment by hlissner** [comment]
@haji-ali Rather than changing `treemacs-is-never-other-window`, perhaps remove `treemacs-mode` from `aw-ignored-buffers`:

```elisp
(after! (:and treemacs ace-window)
  (setq aw-ignored-buffers (delq 'treemacs-mode aw-ignored-buffers)))
```

If you're an evil user, the `C-w {h,j,k,l}` keys (`evil-window-{left,down,up,right}`) can be used to traverse popups/treemacs as well. Same for the `windmove-{left,right,up,down}*` family of commands (but they have no default keybinds, afaik).

To explain the mechanics: treemacs (and other Doom popups) are given the `no-other-window` parameter. It is used to prevent Emacs from reusing those windows to open things (e.g. when following a link or opening a file), but as the name suggests, it makes `other-window` ignore it. There's no helping other-window, specifically, since it doesn't respect the `ignore-window-parameters` variable, like other window commands do.

**Comment by Alexander-Miller** [comment]
The idiomatic way to select treemacs is to call `treemacs-select-window`. Like all autoloaded treemacs commands it does not have a keybinding, the official recommendation (and how spacemacs binds it) is to use `M-0` so as to integrate with winum. 

> (s-contains-p "Treemacs-Framebuffer" (buffer-name)

The official answer to that question is `treemacs-is-treemacs-window?`.

**Comment by filalex77** [comment]
> The official answer to that question is `treemacs-is-treemacs-window?`.

Thanks, good to know! Yes, mine is kinda hacky, didn't research :sweat_smile:
