### ISSUE TITLE
Disabling C-g killing process (shell, R)

### ISSUE THREAD

**Issue by robertamezquita** [hlissner/doom-emacs#1183]
Is there a way to disable the `C-g` command from killing a process such as shell or R?

**Comment by hlissner** [comment]
I think what you're describing is a feature of the popup management system. By default, it will kill the popup buffer (and associated processes) when it is closed. To make it behave differently, you'll need to create a popup rule for it. E.g.

```elisp
(after! ess
  (set-popup-rule! "^\\*R\\*$" :quit nil :ttl nil))
```

The :quit property controls what happens when you press ESC or C-g in a popup. A value of `nil` tells it to do nothing.

`:ttl nil` informs the popup manager never to auto-kill the buffer/process when the popup is closed.

I hope that helps!

**Comment by hlissner** [comment]
I'll consider this question answered and close this. Feel free to follow up here if that isn't the case!
