### ISSUE TITLE
Language server support

### ISSUE THREAD

**Issue by hqhs** [hlissner/doom-emacs#1186]
Hi, 1+ year doom emacs user here, thanks for awesome work! 
I'm primary a go developer and find features for go somewhat slow (go-to-definition etc.), my proposal is to add support for [langserver](https://langserver.org/), it has emacs & company [support](https://github.com/emacs-lsp/lsp-mode), much faster in go case and could be added as standalone feature in init.el. I would love to make a pr with basic features for go & python with some help. As a side question: what's your plan for next stable release? I searched threw issues, but found nothing. 
Sorry for any mistakes. English is not my native language.

**Comment by myrgy** [comment]
Hi, here is LSP support PR https://github.com/hlissner/doom-emacs/pull/716

**Comment by hqhs** [comment]
Oh, I guess, my search ended to early. Sorry for bothering, thanks for answer!

**Comment by hlissner** [comment]
lsp-mode has changed drastically since #716 was authored, so it is wildly outdated. I'll implement basic LSP support over the weekend, including go and python support.

As for the next stable release (2.1), I'm not sure. It's waiting on me to finish the new documentation, but bug reports and general support are eating up most of my spare time.
