### ISSUE TITLE
(ivy +fuzzy) with counsel-rg doesn't work as it should

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1292]
### Observed behavior

Setting `(ivy +fuzzy)` in my `~/.doom.d/init.el` and having `rg` installed in my machine. However, `counsel-rg` is not mapped to use `ivy--regex-plus` like `counsel-ag` or `counsel-grep`. So when you try to make a search in project using `SPC / p`, you get an almost useless search. 

For example, this is what I get when trying to search this repo for `ivy`:

![2019-03-30_00-29-31-screenshot](https://user-images.githubusercontent.com/844343/55270846-fb7cd880-5282-11e9-9be6-4dfd538f0fbf.png)

Should be a easy fix. Just add `(counsel-rg . ivy--regex-plus)` here:
https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/config.el#L232

### Expected behavior

When I put the following line in my `~/.doom.d/config.el`:

```elisp
(setq ivy-re-builders-alist
      (append '((counsel-rg . ivy--regex-plus)) ivy-re-builders-alist))
```
I got the following results:
![2019-03-30_00-30-49-screenshot](https://user-images.githubusercontent.com/844343/55270860-1e0ef180-5283-11e9-806a-122a0c9983a2.png)

That seems much more sane. 

### Steps to reproduce

1. In `~/doom.d/init.el`, enable `(ivy +fuzzy)`
2. Open a project, use `SPC / p`
3. Try to search some term that you expect to see in your project

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (mar 17, 2019)
- Doom: 2.0.9 (develop 99aefd6e022fc092c3c8e22a3c42b78cec0823d2)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux mirai-linux 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company (ivy +fuzzy) :ui doom doom-dashboard evil-goggles hl-todo modeline nav-flash neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired electric imenu vc :tools ansible docker editorconfig flycheck magit make terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +present) python ruby (sh +zsh) web :config default)
  packages:  (ag lispyville ripgrep sort-words uuidgen (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/.emacs.d/bin ~/.zit.d/asdf/shims ~/.zit.d/asdf/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
At some point, just setting it for `counsel-ag` would also affect `counsel-rg` and `counsel-pt`. I suppose this is no longer true. As of 49bbc71 I did as you suggested. Thanks for bringing it to my attention!

**Comment by randomizedthinking** [comment]
I hit the very issue at a different angel today. Personally, I think the fuzzy search is a good thing because we can search for multiple components at the same time. That the current ag/rg can only search for continuous string is a big limit to me.

I also use Ag/Rg search in vim, and the research results are quite reasonable. Here i attach a screenshot of Rg in vim. It might be a good idea to keep fuzzy search. What @thiagokokada experienced might be something related to search options used for `ag/rg`.

![image](https://user-images.githubusercontent.com/5283430/67595542-c43cb000-f71b-11e9-8358-416446933d72.png)

**Comment by hlissner** [comment]
>  That the current ag/rg can only search for continuous string is a big limit to me.

@randomizedthinking With +fuzzy disabled, you can get around this constraint by separating terms with spaces, or using regexp. `ivy c m d` would've yielded the same results. Double spaces = literal spaces.

It doesn't seem like the state of fuzzy search in ivy or helm have improved since last I tried it, even with `+prescient`, so I'd rather not make it the default. I don't use it (its non-fuzzy search capabilities are far more precise and performant), but it is easy enough to customize yourself:

```elisp
(after! ivy
  (setf (alist-get 'counsel-ag ivy-re-builders-alist)
        #'ivy--regex-fuzzy)

  ;; Alternatively, for +prescient users
  (setf (alist-get 'counsel-ag ivy-re-builders-alist)
        #'ivy-prescient-re-builder))
```

If you have any ideas on improving its situation I'd happily accept a PR, but between flx and prescient, the two supposed powerhouses of fuzzy search in Emacs, I find the fuzzy search abysmal:

![image](https://user-images.githubusercontent.com/510883/67597601-95353700-f739-11e9-82a1-9c80e5565a70.png)

----

This is better (non-fuzzy):

```elisp
(setf (alist-get 'counsel-rg ivy-re-builders-alist)
      'ivy--regex-plus)
```

![image](https://user-images.githubusercontent.com/510883/67598171-e2fe6f00-f73a-11e9-8ea0-a1c61eacb6c5.png)

----

Or if you'd like ivy to disregard order (also non-fuzzy):

```elisp
(setf (alist-get 'counsel-rg ivy-re-builders-alist)
      'ivy--regex-ignore-order)
```

![image](https://user-images.githubusercontent.com/510883/67598208-00cbd400-f73b-11e9-8f19-bdadd8337d65.png)

**Comment by randomizedthinking** [comment]
Thanks for the detailed explanation.

I will look into the `ag/rg` options in emacs. Just bear with me that I just started to learn emacs.
