### ISSUE TITLE
`s` do not replace symbol on the cursor

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#1307]
### Observed behavior
pressing `s` do not replace symbol on the cursor - it's pasting >2 to the command line

### Expected behavior

I expected to replace symbol on the cursor and change to insert mode

### Steps to reproduce

1. Select some line of code
2. Press `s`

**Comment by hlissner** [comment]
This is intentional. `s` and `S` have been replaced by `evil-snipe` (which provides 2-character versions of the `f`/`F` motion keys, ala vim-seek or vim-sneak).

It was done because the original substitution behavior of `s` and `S` can already be preformed with `cl` and `cc` respectively.

If you want to restore the old behavior, simply disable `evil-snipe-mode`:

```elisp
;; in ~/.doom.d/config.el
(after! evil-snipe
  (evil-snipe-mode -1))
```

Otherwise, I suggest using `cl` and `cc` instead.

**Comment by idoo** [comment]
@hlissner it's nice to know. What do you think if we'll add it to the wiki?

**Comment by hlissner** [comment]
That's a good idea. I will be publishing some new documentation soon (including a new FAQ with common issues), I will be sure to add this to it. Thanks! In the meantime, I'll consider this resolved.
