### ISSUE TITLE
how to make package's major mode attach with leader-key-map

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1314]
@hlissner, I add some package in my private config, but some package define its own mode and  key map, thus the `SPC` key has binding,  how I  binding package's command to the leader-key-map, then I could press `SPC` to trigger some command belong to the package. 

Thanks a lot!

**Comment by hlissner** [comment]
What package did you install? 

Generally, you'll have to bind leader keys yourself. e.g.

```elisp
(map! :leader
      :prefix "x"
      "a" #'package-a
      "b" #'package-a
      "c" #'package-a)
```

**Comment by chengyi** [comment]
@hlissner I install `blog-admin`, its mode bind the `SPC`, so I can't use doom-emacs's default leader key binding.

**Comment by hlissner** [comment]
I looked at the [package](https://github.com/dangxuandev/blog-admin) but couldn't find any `SPC` keybinds.

What evil state does blog-admin start in? If it's `emacs`, you must use `M-SPC` instead of `SPC`. If it's any other evil state, `SPC` should have higher precedence than any minor map.

You can get it to start in normal mode with:

```elisp
(after! blog-admin
  (set-evil-initial-state! 'blog-admin-mode 'normal))
```

If `SPC` is _still_ being highjacked by blog-admin, then what is it bound to? `SPC h k SPC` will tell you.

**Comment by chengyi** [comment]
@hlissner the [blog-admin](https://github.com/dangxuandev/blog-admin) use something called `ctbl`, the `ctbl` define `ctbl:table-mode-map` which hijack the `SPC` binding. just use:
``` emacs-lisp
(unmap! ctbl:table-mode-map "SPC")
```
then the doom-emacs key-map work normal.

as you inspire me in https://github.com/hlissner/doom-emacs/issues/1313#issuecomment-480665450 

thanks
