### ISSUE TITLE
Go-mode auto complete not invoked automatically 

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#1356]
I checked this https://github.com/hlissner/doom-emacs/issues/77

and had this in my config:
```
(after! go-mode
  (set-company-backend! 'go-mode '(company-go company-yasnippet)))
```

However this doesn't work. I still need to press `C-@` to get a dropdown.

**Comment by ericsolomon** [comment]
Just curious but do you have `(company +auto)` in your init.el? I have also played around with this and finally got it to work, but I was working with go modules which the linked gocode repo doesn't support (see https://github.com/mdempsky/gocode#githubcommdempskygocode). I ended up having to go get https://github.com/stamblerre/gocode to support go modules.

**Comment by hlissner** [comment]
Idle auto completion is disabled by default. You need to either enable :completion company's `+auto` flag, or enable it yourself:

```elisp
(setq company-idle-delay 0.2
      company-minimum-prefix-length 3)
```

Since completion appears to work when you invoke it manually, then I think it's safe to assume completion is working as expected, otherwise. If that isn't the case, let me know and I will reopen this.

**Comment by andyafter** [comment]
@hlissner I noticed that there has been discussion about enabling company mode will slow down when typing, is it because of go-mode or because I installed a newer version of go?

**Comment by hlissner** [comment]
@andyafter Idle completion will cause those kinds of slowdowns, yes. That's why it is disabled by default. This applies to all languages (with company support), not only go, but if the underlying tool a company backend is slow (or the shell used to invoke it is slow), then it will certainly make the matter worse.
