### ISSUE TITLE
Can you add pyim configuration for doom?

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1371]
As a chinese user, it is quite annoying to use emacs when IME (input method) on. There is PYIM (https://github.com/tumashu/pyim) to be an Emacs native input method. However, I failed to configure it with Doom. Following its configuration, I got a quite slow startup for Emacs. And trying to defer load pyim, I can't make it work. 

Is it possible to add Doom pyim support like spacemacs does?

**Comment by hlissner** [comment]
fadbfb3 adds the `:input chinese` module which installs pyim. Unfortunately, I cannot test this myself (I don't know how to use it, much less read the language), so I would appreciate any help to polish this module. Even if only to walk me through how it is used.

**Comment by Infinemen** [comment]
Thank you for your excellent work! I finally got free time to upgrade doom emacs to the latest version. I noticed that you have thoughtfully added the Chinese input method to doom emacs. I have checked that I can actually input Chinese. However, I personally prefer to use the system's built-in input method (fcitx).  I can trigger the Chinese input method and type out the words, but I can't get them into the file edited by doom emacs. Wondering if there's a way to make it work? By the way, in the previous versions, I learned that this problem can be solved by adding the sentence "export LC_CTYPE =" zh_CN.utf-8 "" in the /etc/environment file for ArchLinux, can not make it work now. I'm sorry to bother you the second time because of the Chinese input method.
