### ISSUE TITLE
auth-source-pass should always be installed from MELPA

### ISSUE THREAD

**Issue by bricewge** [hlissner/doom-emacs#1438]
`auth-source-pass` is kept at v2 when using emacs >= 26, while v5 as already been released. This is the only package in the repo that follow this behavior.

**Comment by hlissner** [comment]
As of 6b6ea699, the tools/pass module installs the latest version of auth-source-pass directly from HEAD. Allowing this are a few commits leading up to 6b6ea699 to fix Doom's package management so that quelpa packages with psuedonyms aren't endlessly uninstalled and reinstalled when running `bin/doom refresh`.

Thanks for bringing it to my attention. Let me know if it gives you any issues.
