### ISSUE TITLE
Can't disable packages with (package! package-name :disable t)

### ISSUE THREAD

**Issue by valignatev** [hlissner/doom-emacs#1454]
Hi, thanks for this great Emacs distribution, its really cool, and I love it!
My issue is that I can't disable `pyvent` package. I've tried:
1) put `(package! pyvenv :disable t)` into my `~/.config/doom/packages.el`
2) put `(def-packages! pyvent :disabled t)` into my `config.el`

After that, I tried to execute `doom refresh` (or make recompile and make autoloads), but I still have `pyvenv-*` interactive functions under my M-x.

I've tried to disable couple other packages (magit, for example), but without any luck.

There have to be something obvious, but I miss it for some reason.

**Comment by hlissner** [comment]
This is because pyvenv is a dependency of the pipenv package. `(package! pyvenv :disable t)` will disable any `def-package!` and `after!` blocks for pyvenv _but_ will not uninstall a package if it is a dependency of another package. As long as a package remains installed, its autoloads file is loaded, which is what declares the pyvenv commands you see in `M-x`. Unfortunately there is no reliable way to do address this (and I wouldn't recommend trying, in case it breaks packages that depend on pyvenv).

**Comment by hlissner** [comment]
For future reference, you can see a) a package's dependencies, b) what Doom modules a package belongs to and c) where the package is configured within Doom Emacs with `SPC h d p pyvenv` (or `SPC h p pyvenv` in recent versions of Doom).

**Comment by valignatev** [comment]
Thanks a lot for the explanation, it totally makes sense. I guess `No unused packages to remove` during the refresh tells exactly about it
