### ISSUE TITLE
Evil repeat not working in visual mode

### ISSUE THREAD

**Issue by danprince** [hlissner/doom-emacs#1463]
A common pattern I use in Vim is to select some text, indent it then continue indenting it using the repeat operator, but this doesn't seem to work in Doom because `.` is bound to `+evil:apply-macro` in visual mode.

**Steps to reproduce**

* `S-v` to visually select the current line
* `>` to indent the selection
* `.` to indent further

**Expected behavior**
Expected it to reapply the indent operation to the visually selected block of text.

**Actual Behaviour**
It prompts for the name of the macro to apply, rather than repeating the operation.

I haven't ever run into this problem in Emacs with Evil mode before, so it seems like Doom is doing the rebinding in visual mode for a reason, I just can't work out why.

The `.` operator works fine outside of visual mode. It's also worth noting that running `M-x evil-repeat` manually after performing an operation in visual mode just prints `: is undefined`.

**System information**

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 28, 2018)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD 32e266cf 2019-05-31 22:01:10 -0400)
- Graphic display: nil (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB THREADS
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +habit +present +protocol) sh :config default)
  packages:  n/a
  exec-path: (~/.cargo/bin ~/dev/go/bin ~/.deno/bin ~/.cargo/bin ~/dev/go/bin ~/.rbenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /usr/local/Cellar/emacs/26.1_1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```

**Comment by hlissner** [comment]
>I haven't ever run into this problem in Emacs with Evil mode before, so it seems like Doom is doing the rebinding in visual  mode for a reason, I just can't work out why.

That's surprising. Evil doesn't bind `.` in visual mode, by default, because evil doesn't support repeating from visual mode at all. This is why I've bound `+evil:apply-macro` to it. In fact, evil aggressively stops you from binding `evil-repeat` on `.` with [this line in evil-maps.el](https://github.com/emacs-evil/evil/blob/master/evil-maps.el#L349).

It also [appears to be a known issue](https://github.com/emacs-evil/evil/issues/742).

-----

What Doom _does_ change from default evil behavior is it persists visual mode after `>` or `<` (ala `vnoremap < <gv` and `vnoremap > >gv` in vim).

So I'm afraid this is a trade off. You have two options:

1. undo this visual-retaining behavior by restoring the old keybinds:

   ```elisp
   (map! :v "<" #'evil-shift-left
         :v ">" #'evil-shift-right)
   ```

2. Or simply reuse `>`/`<`, because your selection will still be active. E.g. `>>>` will do what you're used to doing with `>..`.

Without a proper fix from upstream, I'm afraid that's as good as it gets. Evil's repeat functionality isn't quite primitive, unfortunately.

**Comment by danprince** [comment]
Very odd as I never had any problems transitioning `V>...` from Vim to the minimal Emacs + Evil that I've been using for the last few months.

Persisting visual mode seems like a good call, it works well as an alternative. Thanks again!
