### ISSUE TITLE
Melpa packages do not show up

### ISSUE THREAD

**Issue by fabio-oesch** [hlissner/doom-emacs#1472]
I'm trying to install [keychain-environment](https://melpa.org/#/keychain-environment) packages but the package does not show up in `M-x package-install` or when I just try to add in my config with 
```
(def-package! keychain-environment
  :init
  (keychain-refresh-environment))
```
The problem in general is that I cannot see any of the Melpa packages. I tried to `M-x package-refresh-contents` and `M-x package-initialize` but neither of them seemed to add the Melpa packages.

I'm sure I'm making some problem somewhere, but it seems that Melpa is not activated for me. Do I need to activate it specifically because when I look in `core/core-packages.el` I can see that Melpa is in there. So I'm just kind of confused how exactly I should go about doing this.

**Comment by hlissner** [comment]
Package management in Doom is declarative. Packages installed with `M-x package-install` will only be visible until you restart Emacs (and will be uninstalled next time you run `doom refresh`). The package will be hidden from `package-install` if you've installed it previously with `M-x package-install` and restarted Emacs (because Emacs can tell the package exists, even if it isn't available to be loaded).

You must add a `(package! keychain-environment)` statement to `~/.doom.d/packages.el` to make it permanent (and run `doom refresh` to ensure the package is properly installed.

Let me know if that fixes your issue.

**Comment by fabio-oesch** [comment]
That worked. Thank you for the help and the fast response. I just wasn't sure how exactly I had to set it up.
