### ISSUE TITLE
workspace/switch-to-last switches to latest created workspace, not the last selected

### ISSUE THREAD

**Issue by ln-nl** [hlissner/doom-emacs#1480]
Is that intentional?

I would like to have function like that instead:

```emacs-lisp
(defun +workspace/switch-to-previously-selected ()
  "Switch to the previously selected workspace."
  (interactive)
  (+workspace/switch-to +workspace--last))
```

**Comment by hlissner** [comment]
This was intentional, yes. I've added a `+workspace/other` command plus a <kbd>SPC</kbd><kbd>TAB</kbd><kbd>`</kbd> keybind to do what you were expecting, and have renamed `+workspace/switch-to-last` to `+workspace/switch-to-final` to avoid ambiguity. Let me know if that causes you any issues and I will reopen this. Thanks for bringing it to my attention.

**Comment by ln-nl** [comment]
Thank you!
