### ISSUE TITLE
ivy/ripgrep does not escape spaces in project search (SPC / p)

### ISSUE THREAD

**Issue by intpl** [hlissner/doom-emacs#1487]
hi. it just started recently and I could not manage to debug what exactly caused this. 

problem: after selecting string with spaces in it, ripgrep results with"error code 2"

steps to reproduce:
1. press SPC / p
2. type random two words with space inbetween them

OR

1. select text with spaces
2. press SPC / p

workaround:
escape " " (spaces) with backslash, like this: "one\ two\ three"

i don't know if it helps, but i noticed that even when second argument is a valid directory path, the issue persists.
issue persists even when reverting https://github.com/hlissner/doom-emacs/commit/4ef345fe5052ccd608630e7f288b7fb27821db25
i don't know how to append elisp code to escape spaces with backslash using regexp there

**Comment by hlissner** [comment]
6f3c1c6 will fix the second workflow (select & search).

I cannot reproduce nor address the first workflow (search & type two words). I suspect it's an unrelated issue. Spaces have a special meaning to ivy, depending on what backend you're using (fuzzy, non-fuzzy, precient, etc). It makes sense to escape the spaces in a selection, because I can assume that the user wants a literal search, but if the user explicitly inputs a space, I cannot assume what the user wants, so I will assume the user knows what they're doing and not modify default behavior.

**Comment by intpl** [comment]
after your commit from couples of minutes ago and this change it solved everything and works like before, thanks! https://github.com/intpl/.doom.d/commit/f90b0c9db09345d3b7cb1d69d9a286e250a23a73#diff-64ed6d0a7a4f2eaf33cacc2454a19cffR35
