### ISSUE TITLE
Can't run go-errcheck when saving go file

### ISSUE THREAD

**Issue by 02040402** [hlissner/doom-emacs#1508]
When using doom emacs edit a go file, got error below:

![Screen Shot 2019-06-24 at 13 34 37](https://user-images.githubusercontent.com/49627449/59992130-1b0a7e00-9685-11e9-8066-6022e14f501d.png)

```
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
```

```
$ ls $HOME/go
bin pkg src

$ ls $HOME/go/bin
asmfmt  dlv  errcheck  fillstruct  gocode  gocode-gomod  godef  gogetdoc  goimports  golint  gometalinter  gomodifytags  gorename  gotags  gounit  guru  iferr  impl  keyify  motion

$ whereis go
go: /usr/local/go
```

---

~/.doom.d/init.el

```
(doom! :input
    go
    flycheck
    ...
)

**Comment by hlissner** [comment]
Please provide 1) your `M-x doom/info` and 2) the output of `M-; (executable-find "go")`.

**Comment by 02040402** [comment]
@hlissner 

1)

![Screen Shot 2019-06-26 at 11 17 48](https://user-images.githubusercontent.com/49627449/60146343-38198b00-9804-11e9-9d0e-c538bc5f8913.png)

2)

Got `nil`

**Comment by hlissner** [comment]
This appears to be a PATH issue. Either:

1. Your envvar file is outdated. `doom env refresh` will regenerate it. You'll need to do this whenever your shell environment is changed (i.e. your shell dotfiles).
2. If you're a bash user, you have configured your PATH (for go) in `~/.bash_profile`. You need to do this in `~/.bashrc`, because `doom env` reads your shell environment from an interactive (non-login) shell, which only reads .bashrc, and not .bash_profile.

**Comment by 02040402** [comment]
@hlissner 

Thank you for your answer! I tried your way `~/.emacs.d/bin/doom env refresh`, got:

```
Regenerating envvars file at "~/.emacs.d/.local/env"
Scraping env from ’/bin/bash -ic /bin/env’
```

Then edit a go file and save it. The error didn't happened again!
I'm using the zsh shell.

**Comment by hlissner** [comment]
It's odd that it thinks your shell is bash, however, since it resolved your issue I guess it's a happy accident.

I'll consider this resolved, but if this gives you trouble in the future, try adding `(setq shell-file-name (executable-find "zsh"))` in `~/.doom.d/init.el`. Thanks for bringing it to my attention!
