### ISSUE TITLE
Weird behavior after default install in terminal?

### ISSUE THREAD

**Issue by DrawnWren** [hlissner/doom-emacs#1533]
To reproduce:
Fresh install of emacs-plus and doom on MacOS
spc - o - t
enter any text into the command line then enter visual mode and hit $

The bug:
The cursor will be on the next line, which by itself isn't too annoying but it seems that visual mode just doesn't work w/ the default terminal? a/i in visual always go to the end of the command regardless of cursor position and edits in visual mode (i.e. with x/S) seem to not actually affect the command processed

**Comment by hlissner** [comment]
There is no terminal module enabled by default, so I'll assume you're talking about either the `:term term` or `:term vterm` modules. Unfortunately, this is a technical limitation of `term` and `vterm`. If you want total control over the contents of your shell prompt, you'd have to use `M-x shell` or the `:term eshell` module instead.

The difference between shell/eshell and term/vterm is that the latter are terminal emulators. It's reflects the contents of the shell in an Emacs buffer and forwards keypresses to the underlying process. It is not aware of "the emacs buffer" in the sense that, if you make arbitrary changes to the buffer, it will somehow transmit them to the underlying process. Visual mode simply isn't useful for editing in term buffers.

shell/eshell, on the other hand, are not emulators, they are more like REPLs. Rather than sending individual keystrokes, they read the entire command on the prompt when you press enter. Therefore, you could edit this command however you like and send it when you're ready to.

There is no :term shell module, but I will either implement it into `:term term` or add a new `:term shell` module soon.

**Comment by DrawnWren** [comment]
That's interesting. Spacemacs visual mode works fine w/ multiterm, is this not the same module?

**Comment by hlissner** [comment]
We use multi-term too, but perhaps Spacemacs enables `term-line-mode` by default? Try `M-x term-line-mode` from the terminal buffer and see if that helps.

**Comment by DrawnWren** [comment]
So I did a lot of digging on this. There are a few things. As of Emacs 26, ``term-mode`` sets two variables to stop people from editing the buffer ``term-char-mode-point-at-process-mark`` and ``term-char-mode-buffer-read-only``. ``point-at-process-mark`` keeps the cursor at the point where term has sent the data to the inferior process (the shell) and ``buffer-read-only`` makes, well, the buffer read only. Setting both of these to ``nil`` improves the experience a little, but ``term-char-mode`` (as you already stated) sends each char to the inferior process as it's typed. 

You're using ``evil-collection-term`` which has the effect of switching between ``term-line-mode`` in visual mode and ``term-char-mode`` in insert mode. Afaict, spacemacs doesn't use ``evil-collection`` but I can't find where they handle the mode switch in the shell or how they're dealing w/ the ``term-char-mode`` limitations. It's possible this is a symptom of Emacs 26 and not doom.

**Comment by hlissner** [comment]
Since I'm not sure this is an issue that I can solve on my end (simply an natural incompatibility between term-char-mode and visual mode editing), I'll close this issue. Feel free to follow up here if you have any new insights into the matter!

PS. Doom now has a `:term shell` module.
