### ISSUE TITLE
lsp-python-ms as an alternative python LSP server

### ISSUE THREAD

**Issue by rassie** [hlissner/doom-emacs#1534]
As of [recent commit](https://github.com/emacs-lsp/lsp-python-ms/commit/e987d3d7702873d3ff3c8ce9df57a42573132bc0), `lsp-python-ms` supports auto-configuration, i.e. extensive compilation with .NET is not necessary anymore. Maybe it could be added as an alternative to the current python LSP server.

**Comment by hlissner** [comment]
Sorry for the late response. lsp-python-ms support was added to the lang/python module in 850c0bbb61ed. I've disabled its behavior of auto-installing the server if it isn't present (since pyls and anaconda exist as alternatives, installing the lsp-python-ms server should be a deliberate act, and can be easily done with `M-x lsp-python-ms-setup`), but with this I think we can consider this issue resolved. Thanks for bringing it to my attention!
