### ISSUE TITLE
Magit windows ignore window-purpose

### ISSUE THREAD

**Issue by utrack** [hlissner/doom-emacs#1539]
I've installed purpose-mode (window-purpose) and it works OK except magit windows that ignore Magit window purpose. It works OK in vanilla emacs.

**Comment by hlissner** [comment]
Try disabling the `:ui popup` module and add this to your `~/.doom.d/config.el`:

```elisp
(after! magit
  (setq magit-display-buffer-function #'magit-display-buffer-traditional))
```

**Comment by utrack** [comment]
Yep, second snippet works, but a frozen keymap buffer appears when working w/ magit (don't know how to properly name the buffer). However, disabling `popup` fixes it as well.
Steps to reproduce the keymap bug:
- open a code buffer, `SPC-g-g` - magit buffer opens in a split
- return to code buffer w/o closing magit, do `SPC-L-l`

Thank you! Doom looks really cool so far :)

**Comment by hlissner** [comment]
What is bound to `SPC L l`? There is no default keybind for that, so it must be a custom one.

Also, could you provide a screenshot of this keymap buffer?

>Thank you! Doom looks really cool so far :)

Thanks! I'm glad it's useful for you!

**Comment by utrack** [comment]
Sorry - I've meant `SPC g g` and then `l l` when being @ Magit status; this list on the lower left:

![image](https://user-images.githubusercontent.com/3862920/60985612-6e97ef80-a346-11e9-90b5-ba50dcec4a58.png)

**Comment by hlissner** [comment]
> but a frozen keymap buffer appears when working w/ magit

This is magit's transient popups. They can be closed with C-g or ESC. Magit controls these. I don't 

> However, disabling popup fixes it as well.

So disabling :ui popup resolves these issues?

I'm afraid this issue is merely an incompatibility between `:ui popup` and window-purpose. They have the same goal of "window management" so this appears unavoidable; there will be a lot of crossover. You'll have to use one or the other, not both.
