### ISSUE TITLE
could not find ditaa.jar...

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1545]
When I write the ditaa example with org-babel, `C-c C-c` reports:
`org-babel-execute:ditaa: Could not find ditaa.jar at /Users/mls/.emacs.d/.local/packages/elpa/contrib/scripts/ ditaa.jar.`

It seems that there is no such problem before, and I don’t understand what it is.

After `brew install ditaa`, although there is /usr/local/bin/ditaa, it doesn't seem to be the ditaa.jar it wants, it doesn't work.

**Comment by hlissner** [comment]
You need to set `org-ditaa-jar-path` to the location of `ditaa.jar`. The default location appears to be `"~/.emacs.d/local/packages/elpa/contrib/scripts/ditaa.jar"`, which will never exist, because the `contrib` folder will never exist.

It hasn't been changed on Doom's end, so I don't know why it would've stopped working for you.

**Comment by flyingns** [comment]
Yes, this is my mistake and did not attract my attention.

I really apologize.

**Comment by hlissner** [comment]
No problem! I'm glad we could figure it out.
