### ISSUE TITLE
Feature request: lock entered key sequence

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1556]
Let's suppose I have 4 split windows open.
I want to completely rearrange and resize them.
For this I will have to keep pressing `<SPC> w` before each window-related command.
Is there a way to lock all "modifier" keys at any point of typing a shortcut with a "special" key/keystroke and just press HJKL to move windows, hjkl to move between windows, <>-+ to resize etc.?
I know about `C-x z` but I think it's not as efficient as locking modifier keys.
If you don't want this implemented in Doom could you share some ideas of how would one go about doing this?
Thank you.

**Comment by hlissner** [comment]
I commonly see this in users' configs:

```elisp
;; Easier window movement
(map! :n "C-h" #'evil-window-left
      :n "C-j" #'evil-window-down
      :n "C-k" #'evil-window-up
      :n "C-l" #'evil-window-right)
```

Otherwise, here are a few alternatives:

- `C-w C-w` invokes ace-window, letting you target, specifically, what window to switch to.
- `C-w C-S-w` like ace-window, but swaps the current window with the target window.
- `C-w C-c` like ace-window, but deletes the targeted window

- `C-w S-{h,j,k,l}` swaps the current window with the next one in the respective direction. e.g. h = far left, j = far bottom, etc.
- `C-w C-S-{h,j,k,l}` moves the current window to the respective edge of the frame.

You can also set the width/height of a window in one go with `<N> C-w |` and `<N> C-w -` where `<N>~ is the number of characters wide/tall. e.g. `50 C-w |` will make the current window 50 chars wide.

-----

Otherwise, you could define a hydra for this sort of thing:

```elisp
(defhydra doom-window-resize-hydra (:hint nil)
  "
             _k_ increase height
_h_ decrease width    _l_ increase width
             _j_ decrease height
"
  ("h" evil-window-decrease-width)
  ("j" evil-window-increase-height)
  ("k" evil-window-decrease-height)
  ("l" evil-window-increase-width)

  ("q" nil))
```

Hope that helps!

**Comment by sooqua** [comment]
Thanks for the detailed answer!
Seems like hydra is the answer I was looking for. And it's an already implemented feature! I just couldn't find it on google...
And thanks for the tips. Although it's a bit weird that you can invoke e.g. the same window management with `C-w` and `<SPC> w`. I guess it's a matter of preference, but is useful to know if I were to remap some of the duplicate shortcuts for my own... Like invoking your hydra snippet! I'm gonnna do that now.
Anyway, this answers all my questions.
