### ISSUE TITLE
[QUESTION]  Is org-mode pdf export supported?

### ISSUE THREAD

**Issue by lanrete** [hlissner/doom-emacs#1560]
What would you like to know?

I tried to export my .org file into a PDF file through latex, but couldn't find option to export to latex and PDF. I thought this function is supported in Org mode natively? Do we need to configure that by ourselves in doom emacs? Or am I missed anything?

**Comment by hlissner** [comment]
Does the following fix your issue?

```elisp
;; in ~/.doom.d/config.el
(after! org
  (add-to-list 'org-export-backends 'latex))
```

**Comment by lanrete** [comment]
Thank you for the rapid rapid response! yes it does solve the issue, but I don't understand why `'latex` is taken out of the `org-export-backends`. It seems like the value is in the list during the definition.  I will try to see if `org-export-backends` get overwritten somewhere else

**Comment by hlissner** [comment]
This is Doom's doing. Unnecessary backends are removed from `org-export-backends` to speed up org's loading process. That said, if the `:lang latex` module is enabled, `'latex` is added to `org-export-backends` for you.

That said, org has changed since this design decision was made (some number of years ago), and it no longer eagerly loads its export backends, so I will restore `org-export-backends`'s original value shortly.

**Comment by lanrete** [comment]
Yeah I found that it's overwritten `/modules/lang/org/config.el`. Thanks for the explanation,  doom indeed impressed me a lot during the loading process, it's lightning fast comparing to other emacs configuration I've been using earlier.  You're doing such a great job.

I am closing this issue now

**Comment by hlissner** [comment]
Happy to help!

Also, `org-export-backends` has been restored as of 157cb52.
