### ISSUE TITLE
[BUG] Failed to download ‘gnu’ archive.

### ISSUE THREAD

**Issue by kokx** [hlissner/doom-emacs#1651]
**Describe the issue**
The gnu archive cannot be downloaded, causing installation to fail installing undo-tree, and by extension the evil packages (because they depend on undo-tree).

When running `doom quickstart` on a new computer, I encountered a problem where evil was not installed. Investigating a bit more, it was because it depends on undo-tree, which isn't installed because it is on the GNU repository.

I ran it with `DEBUG=1` and found the following:

```
Debugger entered--Lisp error: (file-error "https://elpa.gnu.org/packages/archive-contents" "Bad Request")
  signal(file-error ("https://elpa.gnu.org/packages/archive-contents" "Bad Request"))
  package--download-one-archive(("gnu" . "https://elpa.gnu.org/packages/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  (progn (message "Refreshing package archives") (package-refresh-contents) (doom-cache-set (quote last-pkg-refresh) t 1200))
```
(full error contents: https://gist.github.com/kokx/98f5cf9216dfe4948536f683f7e01072 )

Iit seems that the GNU elpa repository responds with Bad Request. Trying to request the same URL with `curl` yields no issues, and gives me a (seemingly correct) response.

**Steps to reproduce**
1. Start with a clean system (I guess without `.emacs.d` and `.doom.d` folders)
2. `git clone https://github.com/hlissner/doom-emacs ~/.emacs.d`
3. `~/.emacs.d/bin/doom quickstart`

**System information**
Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  packages:  n/a
  exec-path: (/opt/esp-open-sdk/xtensa-lx106-elf/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.config/composer/vendor/bin ~/.local/bin ~/.emacs.d/bin ~/.node_modules/bin ~/.config/composer/vendor/bin ~/.local/bin ~/.emacs.d/bin ~/.node_modules/bin /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
  ```

**Comment by filalex77** [comment]
Currently, there are a lot of issues with `develop` branch (because of ELPA/MELPA stuff, mostly). The development is focused on the `straight` branch now, which should bring a new package management system - along with a *lot* of fixes and improvements.

If you feel adventurous (and have some time to allow for reinstalling all your packages and/or some post-install debugging), feel free to switch to the `straight` branch via [these instructions](https://github.com/hlissner/doom-emacs/issues/374#issuecomment-513627824). Basically you need to:

1. Switch branches
2. `rm -rf ~/.emacs.d/.local`
3. `~/.emacs.d/bin/doom refresh`
4. Hope it works out well?

If that's not up your alley - please allow some time for `straight` to be integrated into `develop`, with all the major bugs figured out.
