### ISSUE TITLE
[QUESTION] Concerning which-key labels

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#1705]
Hi Henrik,

a few days ago we briefly talked on the discord channel about which-key labels for key-bindings and you explained to me why the labels that I added didn't work. (I added labels to bindings in minor-mode key-maps).

It seems that which-key has gained support for key-bindings in minor modes somewhat recently. At least this is my understanding of the following comment of which-key's maintainer:

https://github.com/justbur/emacs-which-key/issues/212#issuecomment-503368293

I don't know if you were aware of which-keys `which-key-enable-extended-define-key` option and if it can be used to add more labels to doom' key-bindings so I thought I bring it to your attention.

If you think it would be desirable to use the new which-key labeling option, I can try to make the neccessary changes, despite of my quite bad elisp skills :-).

Cheers!

**Comment by hlissner** [comment]
This setting is on my radar, but I'm afraid is not a perfect solution. First, it would require a non-trivial amount of work to implement (setting `which-key-enable-extended-define-key` won't be enough; `map!` would need to be rewritten and we'd have to jury rig [general](https://github.com/noctuid/general.el/issues) to use the new way of declaring which-key labels, rather than the old, or replace general altogether, which is deeply woven into Doom).

Second, this new approach doesn't support remapped commands, which are used extensively (at least a third of all our commands are remapped, depending on what modules you have enabled, not counting any remapping done by the plugins we install). To demonstrate this issue:

```elisp
(defun command-a ()
  (interactive)
  (message "hi"))
(defun command-b ()
  (interactive)
  (message "bye"))

(define-key global-map (kbd "C-c .") '("A" . command-a))
(define-key global-map (kbd "C-c ,") '("B" . command-b))
```

Upon which-key opening, `C-c .` has the "A" label and `C-c ,` has the "B" label, as expected, until...

```elisp
(define-key global-map [remap command-a] #'command-b) 
```

`C-c .` no longer has a label, at all. This won't work either:

```elisp
(define-key global-map [remap command-a] '("Remapped B" . command-b))
```

-----

These are show stoppers and, between sacrificing which-key labels for keys on arbitrary keymaps and labels for our leader/localleader keys, I think the latter is less acceptable than the former. What's worse, I don't think there's an obvious or simple solution (on which-key's end) to this issue of remapped commands, besides simply associating labels with commands directly (i.e. rather than associating them with key sequences, keymaps or modes).

Personally, I wish I could get rid of 90% of our which-key labels altogether. I don't think obscuring the underlying command with an arbitrary label adds any value _except_ in the case of prefix keys, anonymous functions, or the occasional command whose names are especially obtuse. One day I'd love to figure out a better alternative to which-key -- maybe develop an inhouse alternative to it to suit our specific needs -- but for now I think this is the best we've got.

**Comment by hlissner** [comment]
Since the original question was answered I'll consider this issue resolved, even if the which-key issue itself hasn't been solved (we'll just have to wait for a breakthrough somewhere, for the time being). Thanks for bringing it to my attention!
