### ISSUE TITLE
[BUG] doom-big-font-mode has small completion popup

### ISSUE THREAD

**Issue by magnetophon** [hlissner/doom-emacs#1706]
doom-big-font-mode has small completion popup.

**System information**

```
((emacs
  (version . "26.2")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "aug 24, 2019")
  (buildopts "--prefix=/nix/store/s1bcqafkvmr8i0wp76w5zcn0prm3kgks-emacs-26.2 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> straight ea34b111 2019-08-23 18:57:57 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/zsh")
  (uname . "Linux 4.19.67 #1-NixOS SMP Fri Aug 16 08:12:54 UTC 2019 x86_64")
  (path "~/bin" "/run/wrappers/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/bart/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "~/.fzf/bin" "/nix/store/s1bcqafkvmr8i0wp76w5zcn0prm3kgks-emacs-26.2/libexec/emacs/26.2/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company (ivy +prescient) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired vc :tools eval flycheck flyspell (lookup +docsets) magit :lang data emacs-lisp markdown nix (org +attach +babel +capture +export +habit +present +protocol) sh :email mu4e :app irc :config default)
  (packages "helm-mu" "mu4e-conversation" "aggressive-indent" "(magit-todos :disable t)")))
```

**Comment by hlissner** [comment]
Can you provide a screenshot? I'm unable to reproduce this on the same setup:

![image](https://user-images.githubusercontent.com/510883/63645523-f73bd680-c6cd-11e9-9e20-8b64ca9a3983.png)

**Comment by magnetophon** [comment]
Sure:
![2019-08-25-122433_1600x900_scrot](https://user-images.githubusercontent.com/7645711/63648709-f50c6300-c733-11e9-8a5b-4be693406abc.png)

**Comment by hlissner** [comment]
Odd. It looks like you're using `company-box`, but you do not have `:completion (company +childframe)` enabled. I don't see `company-box` in your installed packages, so perhaps you've installed it with `package-install-p` or use-package's `:ensure t` instead of Doom's package manager.

Since I cannot reproduce this with `:ui (company +childframe)`, please give that a try. If you have a good reason for not using it, then please link your config.

**Comment by magnetophon** [comment]
I already had ``:completion  (company +childframe)`` enabled.

**Comment by hlissner** [comment]
Is this still a problem? I recently attempted to reproduce this on 26.1 and 26.3 (on nixos) with no luck.

![image](https://user-images.githubusercontent.com/510883/66356620-9e509680-e939-11e9-93a8-39d7f7b3b99f.png)

> but you do not have :completion (company +childframe) enable

This turned out to be an unrelated bug with `doom/info`, which I fixed a while back.

**Comment by magnetophon** [comment]
Yeah, nothing changed here.
I'm on the latest develop.

**Comment by hlissner** [comment]
Finally figured this one out! As of e7de811 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by magnetophon** [comment]
Yup, that does it!
Thanks a lot for your tireless effort creating the greatest editor on earth (and mars).
