### ISSUE TITLE
[REQUEST] [.doom.d] replace hardcoded '~' with (getenv "HOME")

### ISSUE THREAD

**Issue by rprimus** [hlissner/doom-emacs#1737]
**Describe the feature**
Respect $HOME and locate `.doom.d` directory under $HOME

For people that startup emacs by providing an envvar:
```
HOME=/tmp/ emacs
```
for doom,  the relevant `.doom.d` directory will be found and used, vs having to symlink `~/.doom.d` to the 'relevant' location.
I do now know of the `-p` option,  but this didn't exist when I first started using `Doom`.

It occurs in four places:
```
: ; ag -i 'default-directory' | ag -i '~'
core/core-projects.el:89:  (let ((default-directory "~"))
core/test/test-autoload-buffers.el:39:      (with-current-buffer d (setq default-directory "~"))
core/cli/install.el:38:  (let ((default-directory (doom-path "~")))
core/doctor.el:26:(let ((default-directory "~"))
```

Cheers.

**Comment by hlissner** [comment]
Such a substitution shouldn't be necessary. `~` expands to `HOME`.

```sh
HOME=/tmp/ emacs --batch --eval '(princ (expand-file-name "~"))'
# => /tmp/

HOME=/tmp/ emacs --batch --eval '(let ((default-directory "~")) (princ (expand-file-name ".")))'
# => /tmp
```

`~/.doom.d` expands to `$HOME/.doom.d`, i.e. `/tmp/.doom.d`. I haven't been able to reproduce any other behavior.

> I do now know of the -p option, but this didn't exist when I first started using Doom.

The `-p` option has been around since `bin/doom` was first introduced in f0585053 1yr 3months ago.

-----

There's also the `DOOMDIR` and `EMACSDIR` envvars (they must end in slashes however).

**Comment by rprimus** [comment]
Sat Aug 31 12:40:58 BST 2019

Based on your examples,  I've confirmed the above.

The confusion stemmed from comparing all `doom-*-dir` variables.  Only `doom-private-dir` contained '~' while the others were fully-qualified paths.  (Should have used `expand-file-name`.)
