### ISSUE TITLE
[QUESTION] Is there a module-create function?

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1747]
@hlissner I remember there is a module-create function which is used to create module.
but I can't find now. Could you tell me?

**Comment by hlissner** [comment]
There is no module create command. The `:editor file-templates` module offers file templates for doom modules (config.el, packages.el and README.org), but otherwise you have to create the files and directory yourself. 

General commands to assist with extending Doom in general are planned, but it will take a while for me to get there. I'll keep you posted.

**Comment by chengyi** [comment]
@hlissner thanks
