### ISSUE TITLE
[BUG] the package! highlight disappear when disable magit module

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1753]
**Describe the issue**
the package! highlight disappear when disable magit module

**Steps to reproduce**
1. disable `magit` module
2. open a `packages.el`

**System information**
<details>

```
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      4月 13, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
doom    version    2.0.9
        build      HEAD -> develop, origin/develop abcc7d06 2019-09-04 16:07:52 +0800
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.66-1-MANJARO #1 SMP PREEMPT Fri Aug 9 18:01:53 UTC 2019 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) workspaces prow-hydra :editor file-templates snippets :term term :tools gtags :lang emacs-lisp :email mu4e :config default)
        packages   (n/a)
        elpa-packages (n/a)
```
</details>

**Comment by hlissner** [comment]
This isn't really a bug. It happens because magit loads itself after a short delay, after startup, which pulls in package.el, which causes Doom to initialize all its package management metadata (including the definition for `package!`, which causes it to be highlighted).

Without the :tools magit module, nothing causes this chain of events and Doom's package management system is never loaded (until you load the package.el or straight.el library).

**Comment by chengyi** [comment]
@hlissner this sounds strange.

**Comment by hlissner** [comment]
Emacs highlights macros that have been defined. Since core-package.el (where `package!` is defined) is lazy loaded, `package!` calls will not be highlighted until it is loaded.

If you disable the magit module and open `~/.doom.d/packages.el`, you'll see `package!` is unhighlighted. Then do `M-x load-library RET core-packages` and you'll see it become highlighted. If you load `package` or `straight`, it will load core-packages [because of these lines](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L509-L513).

It would be easy to have it highlighted no matter what with this:

```elisp
(font-lock-add-keywords
 'emacs-lisp-mode '(("\\_<package!\\_>" . font-lock-keyword-face)))
```

But I think it's more important to _not_ hide the fact that a macro hasn't been loaded. Syntax highlighting is a good indicator that a macro hasn't been loaded in the current session.

**Comment by chengyi** [comment]
@hlissner thanks for your reply:+1:
