### ISSUE TITLE
[BUG] Stylus mode doesn't launch

### ISSUE THREAD

**Issue by socksy** [hlissner/doom-emacs#1775]
1. Open a stylus file

Here's some dummy stylus to test with: 
 
```stylus
.foo
  padding gridSize(0.5) gridSize(0.5) gridSize(0.5) gridSize(3)
  cursor default
  position relative
  overflow hidden
```
2. Notice that there is no syntax highlighting
3. Try executing `stylus-mode` with M-x
4. Get the following in *Messages*
```
helm-M-x: Cannot open load file: No such file or directory, sws-mode
```

Possibly a solution is to just install `sws` in the web module? Installing `sws` definitely seems to work for me.

**Comment by hlissner** [comment]
Very strange. `sws-mode` is [declared as a dependency of stylus-mode](https://github.com/brianc/jade-mode/blob/master/stylus-mode.el#L5), so it ought to be installed along with it, but it isn't. 

It may be because the sws-mode package lacks a Version: header, or that stylus-mode depends on version "0" of sws-mode.

In any case, the lang/web module now explicitly installs sws-mode as of f9feaec, which should resolve this issue. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
