### ISSUE TITLE
can't run doom as root in Linux manjaro i3[BUG] 

### ISSUE THREAD

**Issue by WeissP** [hlissner/doom-emacs#1818]
With [getting started](https://github.com/hlissner/doom-emacs/wiki/Getting-Started) I have emacs and doom so installed:
```
pacman -S emacs
git clone -b develop https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom quickstart
```
If I type 'emacs' in commandline is everything ok, but if I type 'sudo emacs' , only original emacs can be run.

**Comment by filalex77** [comment]
This is not a bug. When you run `sudo emacs`, it loads `/root/.emacs.d` instead of `$USER/.emacs.d` - which does *not* exist.

If you want to edit files as `root` from Emacs, try using a TRAMP prefix.

For example, to open file with `sudo`, use `/sudo:`

```
/sudo:user@host:/etc/passwd
```

Your completion backend (`helm`, `ivy`, etc.) should provide completions for both `user@host` and the file name.

**Comment by WeissP** [comment]
> TRAMP prefix
sovled! Thanks : )
