### ISSUE TITLE
[BUG] style files are not loaded in tex mode (causes and solution found)

### ISSUE THREAD

**Issue by jonathye** [hlissner/doom-emacs#1910]
**Describe the issue**
auctex will automatically load various style files (e.g., listings.el) for various latex packages, which will do a bunch of configurations for the macros and environments provided by these packages. However the style files are not loaded in doom-emacs.

**Steps to reproduce**
1. open any latex file.
2. add `\usepackage{listings}` in the preamble, and save the file.
3. edit `lstlisting` environment or `lstinline` macro. Observe that the fontification, filling instructions, and other configurations do not take effect.

**Causes and solution**
After a few hours of debugging, I finally figured out the causes of this problem. There are 3 of them.
1. auctex's subdir `style` is somehow missing in `straight/build/auctex` (and hence not byte-compiled). This is an upstream bug in straight that I just reported. See raxod502/straight.el#423.
For the time being, I set `TeX-data-directory` to `straight/repos/auctex` to get around this problem.

2. In `modules/lang/latex/config.el`, a few variables are set *after* loading tex package. See https://github.com/hlissner/doom-emacs/blob/957e1dd0809e353fa73e64a32e40cd3995b49376/modules/lang/latex/config.el#L31-L42.

However, these variables are defined by `defcustom`. Simply `setq` after loading tex is problematic. For example, if you inspect the value of `TeX-style-path`, you will find out it uses the old value of `TeX-auto-local`.

Instead, we should set them before loading tex. (alternatively we may set them by calling `customize-set-variable` after loading tex, but I have not tried this approach). I sent a pull request for this.

3. If we fix the above 2 issues, at least we can load the style files manually by calling `TeX-normal-mode` (C-c C-n). But it won't be done automatically when we open a tex file, although we set `TeX-parse-self` to `t` by default. That is because doom somehow removed a hook added by auctex: https://github.com/hlissner/doom-emacs/blob/957e1dd0809e353fa73e64a32e40cd3995b49376/modules/lang/latex/config.el#L61-L67

I am not sure why doom removed it. The comment says it is for not prompting for master files. But on the one hand, it breaks style loading function. On the other hand, doom also sets `TeX-master` to `nil`, which enables prompting and they seem pretty contradictory to me: https://github.com/hlissner/doom-emacs/blob/957e1dd0809e353fa73e64a32e40cd3995b49376/modules/lang/latex/config.el#L47-L48

I suggest 3 ways to fix this issue.
a) Remove this `add-hook!` tweak from config.el. This allows prompting for master files.
b) Remove this `add-hook!` tweak from config.el, and set `TeX-master` to `t`. Prompting for master files is disabled this way.
c) If you insist that we should keep it as it is, we should at least give this piece of code a name. For example,
```emacs-lisp
  (add-hook! 'TeX-mode-hook
    ;; Necessary because it is added as an anonymous, byte-compiled function
    (defun +latex/remove-find-file-hook () (remove-hook 'find-file-hook
                 (cl-find-if #'byte-code-function-p find-file-hook)
                 'local)))
```
So people can easily remove it from TeX-mode-hook in their own config file.

Any suggestions?

**Comment by UndeadKernel** [comment]
Hey @jonathye. I might be able to shed some light on some of your questions.
Regarding the master file questions and the hook. I wrote that to enable Doom to use the file template system `:editor file-templates`. However, now that I take a look at the directory `.emacs.d/modules/editor/file-templates/templates`, I see that there are no latex templates anymore. In the past, there were some basic templates that would populate a newly open latex file with the basics (you know, some default document type, usepackage statements, etc).

The template system would not work if auctex asked for the master file. In the past, setting `TeX-master` to `nil` was not sufficient because of how auctex treated that variable in the background. It would not enable the `file-templates` module to do its work.

I see that both Auctex and Doom have changed a lot since those lines of code were introduced. It's a good idea to reevaluate if they should be there or not. To begin, there is no template anymore. So the question is, do we want to reintroduce a template for newly created `.tex` files? If so, does the template module still clashes with Auctex with the hook (that I removed)? I will try this and report back.

**Comment by UndeadKernel** [comment]
After doing some tests. I've come to the conclusion that the hook removal is no longer needed. Templates are loaded correctly even with the hook is in place. Also, you are correct that the variable `TeX-master` should be set to `t`.

The reason why it was set to `nil` and the hook removed, now that I recall, was to get around an issue with Auctex that is not there anymore.

Would you like to create a PR to fix these issues or should I do it (I'd be happy to do it as well).

**Comment by jonathye** [comment]
@UndeadKernel  Thanks for your clarification and testing! That clears up my confusion. I could do the PR (it seems simple enough anyway :))

**Comment by hlissner** [comment]
Has #1913 fixed this issue?

**Comment by jonathye** [comment]
I was waiting for response from straight. But everything works perfect now!
