### ISSUE TITLE
The dimensions of the doom dashboard's components are not frame independent

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#192]
While the doom dashboard is open, create a new frame (C-x 5 2). Resize the new frame and see how the dashboard in both frames changes its positioning.

It would be expected to have frame local (is there such a thing in elisp?) variables dictating the positioning of the dashboard elements. 

On a side note, newly created frames do not use the default frame size. Should I open a new issue for this?

**Comment by hlissner** [comment]
This is both intentional and non-trivial to fix. Only one dashboard buffer exists in a session and the centered elements are padded with newlines and spaces. I could a) make per-window clones of the dashboard buffer that could be manipulated individually, b) use window-local margins to do the centering work, or c) do away with center-aligning entirely. These all have their own issues. I'll revisit it some time, but I consider it low priority.

> newly created frames do not use the default frame size

Doom doesn't specify a default frame size, so I assume you are setting your own? In either case, yes, please open a new issue for it.

**Comment by hlissner** [comment]
A half-solution is now in master. The good news: it's pretty effective at window-local centering width-wise. The bad news: it still uses newlines for vertical alignment, which cannot be window-local. That said, I don't think this is enough of a problem to warrant a more hardcore solution (like dashboard clones or something).

So for the time being I'll consider this resolved.
