### ISSUE TITLE
[Question] How to change `org-directory`

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#196]
Hi @hlissner, 
I want to change `org-directory` as the following
```lisp
;; /private/$USER/config.el
(after! org
  (setq +org-dir "~/Dropbox/workspace")
  .......
  )
```
However, it still point to your default path at `~/work/org` when i open an org file.

**Comment by hlissner** [comment]
Here are two options:

1. Remove the `(after! org ...)` and simply do `(setq +org-dir "~/Dropbox/workspace")`.
2. Or move `(setq +org-dir "~/Dropbox/workspace")` to `private/$USER/init.el`.

The problem was you were changing `+org-dir` too late. Many org variables build paths with `+org-dir` so `+org-dir` must be changed before that happens. Since the `org/org` module is lazy loaded, changing it in `private/$USER/config.el` without an `after!` block will do it _unless_ you forcibly load org earlier than your private module for whatever reason.

If you put it in `private/$USER/init.el`, this race condition will never occur.

**Comment by babygau** [comment]
Thank you @hlissner, the path is set properly now 👍
