### ISSUE TITLE
[Question] How to change doom-theme background color?

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#197]
I see `doom-one` is used as default theme for `emacs` but I'd love just different background color. How could I achieve that? 

```lisp
(custom-set-faces
  '(default ((t (:background "#1d2021")))))
```
The above snippet only work within the buffer, not neotree or modeline....

**Comment by hlissner** [comment]
Doom uses [solaire-mode](https://github.com/hlissner/emacs-solaire-mode) to help differentiate file-visiting buffers from the rest of Emacs (giving them a different background for the buffer, mode-line faces and more).

If you'd like to keep `solaire-mode`, you'll need to modify `solaire-default-face` too (and any other `solaire-*-face` face you want to modify). 

Otherwise, you may disable `solaire-mode` completely by adding this to your private module:

```emacs-lisp
;; private/$USER/init.el
(def-package-hook! solaire-mode :disable)

;; private/$USER/packages.el
(package! solaire-mode :ignore t)
```

**Comment by babygau** [comment]
Thank you @hlissner, the prob solved, I could use `gruvbox theme` for now 👍

**Comment by sophana** [comment]
commands for disabling solaire-mode don't work.
I've changed default and solaire-default-face, but there is still the currentline under the cursor which is not changed. Do you know which font to change?

**Comment by mreishus** [comment]
This worked for me
```
(custom-set-faces
  '(hl-line ((t (:background "#000000")))))
```
