### ISSUE TITLE
[BUG] Org-mode cursor is not visible if at end of line or beginning of new line

### ISSUE THREAD

**Issue by mihai-dinu** [hlissner/doom-emacs#1988]
**Describe the issue**
When in an org file, the cursor is not visible if it's at  the end of the line or the beginning of a new line. In case it's inside a sentence, then the cursor is visible.

It doesn't have anything to do with a specific theme and it doesn't happen in any other file type. I'm running emacs27, but I don't think it has anything to do with this since I've tried Spacemacs as well and it didn't have the same behavior. 

Here's a video:
![org-cursor2](https://user-images.githubusercontent.com/26204012/67870905-d9f11180-fb2f-11e9-9f52-f6258782acfd.gif)

This problem started a week or two ago. I thought I could ignore it, but I can't anymore. My two cents is that it might be from the package that draws a black highlight over the text at the current line (not `hl-line-mode`). It widens as more text is written, i don't know how to explain it any better. 

**M-x describe-char**
<details><pre>

```
             position: 122 of 313 (39%), column: 0
            character: C-j (displayed as C-j) (codepoint 10, #o12, #xa)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x0A
               script: latin
               syntax:   	which means: whitespace
             to input: type "C-x 8 RET a" or "C-x 8 RET LINE FEED (LF)"
          buffer code: #x0A
            file code: #x0A (encoded by coding system undecided-unix)
              display: no font available

Character code properties: customize what to show
  old-name: LINE FEED (LF)
  general-category: Cc (Other, Control)

There is an overlay here:
 From 122 to 123
  face                 hl-line
  priority             -50
  window               #<window 3 on test.org>


There are text properties here:
  fontified            t
  line-prefix          [Show]
  wrap-prefix          [Show]
```
</pre></details>

**Steps to reproduce**
Nothing special. Just try to write an org file

**System information**
<details><pre>
```
emacs   version    27.0.50
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
        build      okt 27, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-THfQKC/emacs-snapshot-99081=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD d407b3355 2019-10-30 00:03:39 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64
        path       (~/.local/bin/ /snap/bin/ /usr/local/bin/ ~/.local/bin/ /snap/bin/ /usr/local/bin/ ~/.nvm/versions/node/v10.16.0/bin/ ~/.local/bin/ /snap/bin/ /usr/local/bin/ ~/.local/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ ~/.local/share/fzf/bin/ /usr/lib/x86_64-linux-gnu/emacs/27.0.50/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :tools ansible docker eval flycheck (lookup +docsets) lsp magit pass :lang common-lisp data emacs-lisp (javascript +lsp) markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
This appears to occur only on the most recent commits (within the past month) of Emacs 27. I cannot reproduce it with the month-old build of 27 available to me on NixOS (https://github.com/emacs-mirror/emacs/commit/dd162a3f2264940e3e329d0bfb195f56d00ed08f).

The reason Spacemacs doesn't suffer this issue is likely due to the fact that Doom uses the latest version of org (v9.3.x), while Spacemacs uses the `org` package built into Emacs (v9.1.9 in Emacs 27).

What's more, there've been a number of changes to Emacs' face spec (mainly, the addition of an `:extend` property, which could cause an issue like this).

It's really hard to tell and, unfortunately, I cannot easily test this at the moment.

There are a few things you can do to test where the fault lies, however:

1. See if you can reproduce this in [Doom's sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox), with the following code:

   ```elisp
   (defun +org--release-a () "9.3")
   (fset 'org-release #'+org--release-a)
   (fset 'org-git-version #'ignore)
   (advice-add #'org-release :override #'+org--release-a)
   (advice-add #'org-git-version :override #'ignore)
   (require 'org)
   (find-file "some/org/file.org")
   ```

   a) Test this in vanilla Emacs by pressing `C-c C-c`, 
b) Test this in vanilla Doom by pressing `C-c C-d`,
c) And test this in vanilla doom+ (doom minus your private config) by pressing `C-c C-p`

2. Try any other theme besides the ones included in the `doom-themes` package (to rule out the possibility that this is a theme issue).

3. Add this to your config and see if the issue goes away.

   ```elisp
   (remove-hook 'org-load-hook #'+org-init-appearance-h)
   ```

**Comment by dinkonin** [comment]
`(remove-hook 'org-load-hook #'+org-init-appearance-h)` fixes this for me for `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12, cairo version 1.17.3) of 2019-10-26`.

**Comment by mihai-dinu** [comment]
@dinkonin is right. Removing the `#'org-init-appearence-h` hook from the `org-load-hook` fixed the problem for me as well. 

I've done some more digging and the problem in the `#'org-init-appearence-h` function is this:
```lisp
(setq org-startup-indented t)
```
This enables `org-indent-mode` which in turn triggers the problem. I can reproduce this just by `M-x org-indent-mode` in an org buffer to toggle it on or off. It's not much, but hopefully this helps narrowing down the problem some more.

**Comment by hlissner** [comment]
This suggests that the problem is [the latest version of the org package](https://code.orgmode.org/bzg/org-mode). Can it be reproduced in the sandbox?

**Comment by mihai-dinu** [comment]
Good news, bad news.

Can't reproduce it in the vanila emacs sandbox, even with `org-indent-mode` enabled. 
I can reproduce it in the sandbox, but in the vanila doom sandbox (`C-c C-d`) **with** `org-indent-mode` enabled. But! the silver lining is that if I disable `hl-line-mode` in vanila doom, then I can't reproduce it anymore. 

So, I think it's some strange interaction between `org-indent-mode` and `hl-line-mode`

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
;; in ~/.doom.d/config.el
(custom-set-faces!
  '((hl-line solaire-hl-line-face org-indent) :extend t)
```

**Comment by mihai-dinu** [comment]
Funnily enough, there has been one commit recently in `hl-line-mode` that has to do something with faces: https://github.com/emacs-mirror/emacs/commit/e1b5e80aad46bba39831ae4c0aa863e69c915b4c#diff-1a66ecafbabcd5a684d87d8155af59ad

**Comment by hlissner** [comment]
Otherwise, try disabling `:extend` and see if it has any effect.

**Comment by mihai-dinu** [comment]
Looking good with:
```
;; in ~/.doom.d/config.el
(custom-set-faces!
  '((hl-line solaire-hl-line-face org-indent) :extend t)
```
Can't see the problem anymore. Woohoo!

**Comment by hlissner** [comment]
Great! Then the onus is on [doom-themes](https://github.com/hlissner/emacs-doom-themes) to fix this (at least, for doom-themes' themes). There is already an open issue for it here: https://github.com/hlissner/emacs-doom-themes/issues/342. I'll keep this issue open until it is resolved.

**Comment by mihai-dinu** [comment]
That's great news! Thank you for the help and for providing a work around for this. This little bug was so annoying the way it was manifesting.

**Comment by mihai-dinu** [comment]
After some more org-mode editing, I saw that the workaround only partially works. In case you have a heading or some text and there is no new lines under it (even empty lines will do), then the problem still is there. 

Non-working example:
```
* My heading
 ** My subheading|  <-- cursor is not visible
<EOF> <-- no new line, just EOF
```

Working example:
```
* My heading
 ** My subheading|  <-- cursor is visible  
<-- new empty line
<EOF>
```

**Comment by hlissner** [comment]
Seems like the solution just needs to be expanded to include headings:

```elisp
(custom-set-faces!
  '((outline-1 outline-2 outline-3 outline-4 outline-5 outline-6 outline-7 outline-8) :extend t)
```

**Comment by wedens** [comment]
I've noticed that some recent changes in emacs27 break `highlight-indent-guides` (with `character` mode) when `hl-line-mode` is enabled (cursor disappears when you start typing). 

Probably related to the same `:extend` change.  `(custom-set-faces '(hl-line ((t (:extend t)))))
` doesn't help.

**Comment by hlissner** [comment]
@wedens Try it with [one of highlight-indent-guides' faces](https://github.com/DarthFennec/highlight-indent-guides/blob/master/highlight-indent-guides.el#L76-L110) then.

**Comment by mjkramer** [comment]
Spacemacser checking in, Emacs 27, Org 9.2.6 (org-plus-contrib-20191118 from MELPA). I'm having essentially the same issue:

- Without `org-indent-mode`, everything is kosher, with or without `hl-line-mode`.
- With `org-indent-mode`, with or without `hl-line-mode`, cursor disappears at end of any line in a block (including header/footer)
- With `org-indent-mode` AND `hl-line-mode`, cursor disappears at end of ANY line (except top-level headings!) after the first heading in the file

For now I'm using the following partial workaround (I wish Spacemacs had the equivalent of `custom-set-faces!`):

```emacs-lisp

(dolist (face '(hl-line org-indent))
  (set-face-attribute face nil :extend nil))

(dolist (face '(org-block org-block-begin-line org-block-end-line))
  (set-face-attribute face nil :extend nil :background nil))
```

The only reason I'm setting `:background` to `nil` is because the Monokai theme gives blocks a different background, which becomes "ragged" when `:extend` is `nil`.

The drawback of this hack, aside from losing the background shading for blocks, is that hl-line no longer spans across the whole window. But at least I can see the damn cursor now.

I have no idea why this behavior only seems to show up in `org-indent-mode`, or whether this should be regarded as a bug in Org or in Emacs.

**Comment by hlissner** [comment]
I've added :extend to a number of faces upstream, in doom-themes, which should resolve this issue. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
