### ISSUE TITLE
[HOWTO] use a custom branch or different repository for a package

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#2058]
**What I want to achieve**
Use custom repository or branch of a package version

This is more of a workflow question and I have managed to get by manually changing the .el files but any suggestions on how to do it is appreciated

Let's say I am using some package that already is part of doom-emacs configuration say lsp-mode. I want to contribute something a bug fix or enhancement for eg: I fork the repo and make my changes. How do I get doom to use my forked version of the repo to test my changes?

**Comment by gagbo** [comment]
I use my own fork of emacs-doom-themes

`(package! emacs-doom-themes :recipe (:host github :repo "gagbo/emacs-doom-themes" :branch "master"))` in packages.el

go to `~/.emacs.d/.local/straight/repos/emacs-doom-themes`

Set up the "upstream" repository url

And then whenever I want to push a PR I create a feature branch, cherry-pick some commits, push it and create a PR.

Otherwise, when I'm using day-to-day I'm always on my master branch

**Comment by RBckmnn** [comment]
What about

https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#changing-a-built-in-recipe-for-a-package

**Comment by vikigenius** [comment]
Cool thanks for the answers everyone

**Comment by dapritchard** [comment]
The link provided by @RBckmnn has changed (I believe) to <https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#changing-a-recipe-for-a-included-package>. 

Also, please note the instructions given in the above link to run `doom sync -u` (rather than `doom sync`), otherwise the change to the recipe won't get picked picked up. Additionally, you will presumably want to unpin the package or change the commit being pinned.
