### ISSUE TITLE
[QUESTION] Trying to use javascript-eslint before lsp-ui

### ISSUE THREAD

**Issue by rebyatyonok** [hlissner/doom-emacs#2068]
Hi! I'm kind of newbie in emacs and Elisp, so maybe it is a stupid question.
I try to run javascript-eslint trough the Flycheck before lsp-ui checker. 

The problem is that every time I open js/ts file, first checker is always lsp-ui, and second is javascript-eslint. This configuration shows errors only produced by lsp and ignores all by local eslint.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/26152668/69009309-31331680-0965-11ea-8ed0-34c1802a7b53.png">

To fix that, I run "flycheck-select-checker" and select javascript-eslint, or just click on the button "select". And after that it works perfectly. It shows errors by eslint and lsp. 

So I want to set it in my config.el file, but I didn't figure out yet how to do it properly. Things like flycheck-add-next-checker is not working because of 'lsp-ui is not a proper checker.

Can you help me to set it up to be permanent?

**Comment by smashedtoatoms** [comment]
+1

**Comment by Rogergonzalez21** [comment]
You can just configure ESLint to run in LSP, check the documentation here: https://emacs-lsp.github.io/lsp-mode/page/lsp-eslint/

**Comment by JRigotti** [comment]
@rebyatyonok Did you have any progress here? I am also trying to achieve the same.

**Comment by rebyatyonok** [comment]
@JRigotti it seems to work perfectly fine for now. But I literally do nothing special. 

Also I've noticed that there is no lsp-ui as a checker at all. It uses usual lsp instead.

**Comment by lalitmee** [comment]
@rebyatyonok I am also facing the same problem. Actually if I use `javascript-eslint` checker it works fine without showing me any typescript-langauge-server error. I also haven't figured out how to enable `javascript-eslint` in lsp for javscript by default and disable `lsp-ui` because that give too many unrelated warnings and errors.

@hlissner can you please help?

**Comment by rebyatyonok** [comment]
@lalitmee you can try something like this:

```
(defun js-ts-config ()
  (flycheck-disable-checker 'lsp-ui)
  (flycheck-select-checker 'javacript-eslint))

(add-hook 'typescript-mode-hook #'js-ts-config)
(add-hook 'js2-mode-hook #'js-ts-config)
```

But as far as I know, lsp-ui is no longer a checker for flychek because it was merged with (or replaced by?) usual `lsp`.

**Comment by lalitmee** [comment]
@rebyatyonok Yeah, I am talking about the `lsp`. Sorry for saying `lsp-ui`.

I tried putting the code as it is in `config.el` but it is not working. Still the default checker for `flycheck` is `lsp` and it also says that `javascript-eslint` is not a `flycheck-checker`.

**Comment by rebyatyonok** [comment]
Hmm, maybe I find a better solution: 
```
(defun ts-js-config ()
  (setq lsp-disagnostics-provider :none)
  (flycheck-add-next-checker 'javascript-eslint 'lsp)
  (flycheck-select-checker 'javascript-eslint))

(add-hook 'typescript-mode-hook #'ts-js-config)
```

**Comment by lalitmee** [comment]
@rebyatyonok , yeah it will work because you are setting that `lsp-diagnostics-provider` to `none`. But I think `doom-emacs` was updated yesterday and in that it was fixed. Now I can add my default checker using this command
```elisp
(setq-hook! 'js2-mode-hook flycheck-checker 'javascript-eslint)
```

I saw the commit before updating and I saw that there was some typo or something. BTW, thanks for your help. :+1:
