### ISSUE TITLE
[Emacs Lisp Question] When to use back quote in defmacro?

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#211]
Hi @hlissner,
Follow up my last question abt `elisp`. This week I'm trying to get my head round with `defmacro`. I'm wondering why you don't use back quote starting from the body of `defmacro`, but just small part of its body instead? 

For example with [`map!`](https://github.com/hlissner/doom-emacs/blob/895d59f9b43f0ef9f529daeeef9feb279cfbf9cc/core/core-keybinds.el#L138-L238)

From line 138 to 238, you just use normal elisp inside the macro and it still works properly. Why did it happen? Did I overlook sth from *Intro Elisp Manual*?

**Comment by hlissner** [comment]
A lisp macro is essentially a function that returns lisp forms to be evaluated. And lisp forms are simply regular lists. For example...

```emacs-lisp
(defmacro say-hi-1 (name)
  `(message "Hello %s" ,name))

(defmacro say-hi-2 (name)
  (list 'message "Hello %s" name))

(defmacro say-hi-3 (name)
  (let (forms)
    (push name forms)
    (push "Hello %s" forms)
    (push 'message forms)
    forms))
``` 

These all expand into `(message "Hello %s" "world")`, just in different ways. It's metaprogramming. Macros let you write dynamic lisp. You can test macros with `macroexpand`:

```emacs-lisp
(macroexpand '(say-hi-1 "world")) ;; #=> '(message "Hello %s" "world")
```

All `map!` does differently is it constructs these forms using more complex logic. I urge you to try `macroexpand` on a `map!` form to see what it produces.

But perhaps more importantly, you should understand something about macros: they expand _at compile-time_ and the expanded code is evaluated _at run-time_. Take this for example:

```emacs-lisp
(defmacro say-hi (name)
  (message "foo")
  `(message "Hello %s" ,name))

(message "bar")
(say-hi "world")
```

This produces the following output:

```
foo
bar
Hello world
```

Notice that the foo and bar are reversed. To put it simply: the elisp interpreter expands macros (among other things) before actually running your code. So "foo" is printed during compile time, then "bar" and "Hello world" are printed at run time (in the expected order).

If you byte-compile your code, `"foo"` will get printed out while compiling. Then, when you run the compiled program, the output will be:

```
bar
Hello world
```

That's because macros are permanently expanded when elisp is byte-compiled (i.e. the macro isn't needed in the compiled code). I exploit this fact a lot for performance; any time-consuming logic used in your macros are no longer needed.

I hope that helps!

**Comment by babygau** [comment]
Actually I can't use my computer today, I will test it asap. 

One question keeps lingering in my head atm is `defmacro` return a list to be evaluated. In its body, we must use *quote* to those we don't want evaluate, for example special forms like `if`, `while`, `setq`.... but in your codes, those quotes are missing.

**Comment by hlissner** [comment]
Quotes are not required in a macro. Quotes are just one of several ways to create a list in lisp. These all produce the same list:

+ `'(1 2 3)`
+ `` `(1 2 3) ``
+ `(list 1 2 3)`

A macro needs to return a form to be evaluated. This form can be a list of forms, and there are many ways of building this list.

+ You can do so with quotes: `'(if var 5 10)`
+ Or without quotes `(list 'if 'var 5 10)`
+ Or with logic (note: the let-form isn't quoted):

  ```emacs-lisp
  (let (forms)
    (push 10 forms)
    (push 5 forms)
    (setq forms (append '(if var) forms))
    forms)
  ```

The result of all these methods is a list of forms: `(if var 5 10)`, which will replace the macro call.

**Comment by babygau** [comment]
Thank you so much @hlissner, it's much clearer to me now. Just one question left. Why in the last example, you dont quote `let`? I thought lisp would evaluate `let` as value without quote and producing exception error.

**Comment by babygau** [comment]
I think I figured it out. If I understand correctly, the returned list form is the most important part of `defmacro`. My first thought was `elisp` will evaluate everything inside `defmacro`body, from top to bottom. But I'm wrong, aren't I? It just evaluate the returned list forms (or the last list form in the body). 

If this is correct pls close this issue. Otherwise I beg you pardon for further explanation 😅

**Comment by hlissner** [comment]
Ah, my bad. I missed the notifications for your messages!

The way you used the word 'evaluate' confused me a little. The Elisp interpreter _does_ evaluate the macro body in order to produce elisp forms, then it evaluates those lisp forms. It is essentially a two-step evaluation, with the possibility of removing the first step if you byte-compile. Does that make sense?

**Comment by babygau** [comment]
Thank you @hlissner for further explanation. You're right, my English is suck 😞 . Now `elisp macro` is not a thing too dreadful for me as it was 👍 thanks to you!
