### ISSUE TITLE
[HOWTO] Profile very slow text input in a large org-mode file

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#2118]
I have a large `org-mode` file (~70 KB). When I try editing it, each key press takes a considerable amount of time (relatively) before the text is updated on screen.

How do I profile this slow behaviour? I started by doing testing doom's sandboxes and vanilla Emacs and vanilla Doom do not suffer from this problem.
However, Doom + modules (without my private config) seems to have this problem. I also cannot see this problem on a small org-mode.

Any help is appreciated.

**Comment by hlissner** [comment]
You can toggle the profiler with `SPC h T`. The second time you invoke it, it will produce a profile report which should detail samples of functions that ran during that time.

I am unable to reproduce this slowness in files that 937kb org files across three PCs, so it's difficult to guess what could be causing this. Is it possible that a compositor is to blame (e.g. compton)?

**Comment by haji-ali** [comment]
I don't think that's the case. I should clarify that I am editing elisp code inside the org file.  

Here's what I tried to investigate this. I wrote this simple script in my sandbox
```
(defun time-input()
  (let (time (start (current-time)))
    (dotimes (number 50 time)
      (let ((command (key-binding "a")))
        (setq last-command-event ?a)
        (setq this-command command)
        (call-interactively command)
        (redisplay t)))
    (setq time (float-time (time-subtract (current-time) start)))
    time))
(find-file "~/.doom.d/config.org")
(doom/toggle-debug-mode 0)   ;; Since debug mode is disabled in vanilla emacs
```

Then, I executed the command `time-input` in an elisp code block in my large org file, I saw the following times:
- Vanilla emacs: 0.0349458 seconds
- Vanilla doom: 0.0427021 seconds
- Doom with modules: 0.0894318 seconds

So doom is more than twice slower when editing. I also can feel this very acutely when editing files normally rather than using a simulated function. 

Is there a way in the sandbox to have modules enabled one by one to figure out the culprit without having to edit the init file and restart emacs for every module? 

Here's my init file:
<details>

```
(doom! :completion company (ivy +icons)

       :ui
       workspaces doom hl-todo modeline treemacs vc-gutter
       (window-select +switch-window)

       :editor fold multiple-cursors rotate-text snippets   

       :term eshell term

       :emacs (dired +icons) electric

       :tools eval (lookup +docsets) flycheck flyspell magit make

       :lang
       (cc +irony +rtags) data emacs-lisp (latex +latexmk)
       markdown (org +attach +babel +capture) python (sh +fish)
       swift

       :email mu4e

       :app calendar  regex

       :config (default +bindings +smartparens))
```
</details>

**Comment by hlissner** [comment]
These results are not particularly shocking or problematic. Your test benchmarks the aggregate time it takes to press <kbd>a</kbd> and `redisplay` 100 times, and it takes it 89ms for you and <20ms for me. Still, that's 0.00089s (0.89ms) per key, which is faster than any human could manually enter a key (and still faster than any keyboard is mechanically able to send input to the computer).

It is also no surprise `redisplay` consumes so much time because it is inherently an expensive operation, and this test forces it to run on every iteration (a force redisplay is more expensive than Emacs' standard redisplay algorithm).

No, the real problem lies elsewhere. I am inclined to suspect something is wrong with your system, your OS (your compositor perhaps?) and/or your build of Emacs, rather than your emacs config. Especially since my tests yields sub 20ms results, even on my slowest systems (a 2011 MBP with a core 2 duo, 4gb and no ssds, or a mojave VM on virtualbox) and I get ~12ms on my main drivers (a decent i7+32gb+ssd desktop and i7+16gb+ssd laptop, both running nixos, bspwm and compton).

----

In any case, you can try disabling our font-locking commands:

```elisp
(remove-hook! (prog-mode conf-mode) #'highlight-numbers-mode)
(remove-hook! 'emacs-lisp-mode-hook 
  #'rainbow-delimiters-mode
  #'highlight-quoted-mode
  #'outline-minor-mode)
(setq +emacs-lisp-enable-extra-fontification nil)

(after! org
  (setq org-startup-indented nil))
```

But overall, I'm not convinced this is a Doom issue.

**Comment by haji-ali** [comment]
I divide by 100 before printing the time. So the times are actually per character.

Still, I take your point. It might be a problem with my computer (although I have no idea how to troubleshoot it). The reason I thought it's Doom is because the slower behaviour only shows up in a Doom (with modules) sandbox. I executed the commands you listed and time improved to 0.0472853 instead of 0.0894318 and typing is much smoother! 

This is still faster than what I can type. However, before when I just press `a` repeatedly (or type quickly) some redraws are skipped altogether. I thought this way of profiling is a more quantitative way of comparing different setups. Also, I just ran my toy function an my large org file vs an empty file in fundamental-mode (for doom with all modules after executing your script) and I got  0.0472853 and 0.00668501 respectively. So clearly there is a speed hit for the large file in org-mode.

In any case, I will close this issue until I have a better idea of the reasons behind the sluggishness.

**Comment by torresomar** [comment]
I'm really new to emacs and doom, I had the same issue of slow text input in an org-mode file. The file contains code blocks and text. The first issue I had and I think it may be the culprit is that autocompletion was active in this org-mode buffer, this buffer is not in the directory set in `(setq org-directory "~/...")`. I checked some blog posts around custom doom configurations and this configuration helped with my issue. 
``` lisp
  (remove-hook 'after-save-hook #'+literate|recompile-maybe)
  (set-company-backend! 'org-mode nil)
```

**Comment by yubrshen** [comment]
I'm having similar issue with eshell or shell when doing remote ssh, with Doom's configuration (by uncommenting the respective in ~/.doom.d/init.el, 
When typing the 2nd character of a command, such 's' in `ls`, it takes a few seconds to see the echo of 's', and then I can continue to input.

If I don't uncomment eshell or shell in init.el, then the problem disappeared, but  didn't have command and argument completion! I also tried Spacemacs with the default configuration, it worked much faster without noticeable hindrance. 

I guess that if performing the following, 
`(set-company-backend! 'org-mode nil)`
then there will not be command completion?
