### ISSUE TITLE
Cannot override packages

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#222]
I have added a package file `private/amos/packages.el` like this,
```
;; -*- no-byte-compile: t; -*-
;;; private/amos/packages.el
(package! centered-window-mode :recipe (:fetcher github :repo "amosbird/centered-window-mode"))
```
However it still uses the original package.

Doing `make update` fails without verbose error messages.
```
Looking for outdated packages...
1 packages will be updated:

+ centered-window-mode   20170528.25    -> 20171005.1538

Proceed? (y or n) y
Updating centered-window-mode
  FAILED
Finished!
Reloading...
Recompiling
Recompiled 0/234 file(s) (0 ignored)
Compiling /home/doom/.emacs.d/core/core.el...
```

**Comment by hlissner** [comment]
Ah, the package was already installed by another module (installed with package.el). You recipe is trying to install it with quelpa and fails because it can't tell where the existing package was installed from.

I'll look into a fix for this over the weekend. For the time being you can fix this by manually deleting `~/.emacs.d/.local/packages/elpa/centered-window-mode*`, then running `make install` again.

**Comment by hlissner** [comment]
A solution for this is now in `develop`. It needs a little more testing, but should make its way into master within the next couple of days.

**Comment by hlissner** [comment]
This is now in master.

**Comment by amosbird** [comment]
Hi, I still cannot replace elpa package with quelpa.

```
 ❯ make install                                                                              (4s 401ms)
1 packages will be installed:

+ dired-k (ELPA -> QUELPA)

y
Installing dired-k
  ALREADY INSTALLED
Proceed? (y or n)
```
