### ISSUE TITLE
[HOWTO] Could you publish an example private package?

### ISSUE THREAD

**Issue by Overdr0ne** [hlissner/doom-emacs#2248]
I want to define my own package to put in my $DOOM/modules dir, but I'm having trouble getting things working. An example module would be very helpful.

I've been following https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#writing-your-own-modules . If it matters, specifically, I was trying to pull in the https://github.com/rakshasa/ibuffer-persp project. More specifically I wanted to have persp make its perspectives look like just another ibuffer filter, so I could stack filters to get just buffers for a single major mode in a perspective for example. Anyway, I often want to integrate random code I find on the internet. So far I've just been using load!. An example private module I could use as a template would get me going a lot quicker I think.

**Comment by gagbo** [comment]
Maybe not the easiest example, but in my config I built a small private module to use [telephone-line](https://github.com/dbordak/telephone-line) as a modeline : https://framagit.org/gagbo/doom-config/tree/master/modules/ui/telephone-line

As you can see, this is meant to be cloned in my `~/.config/doom` folder (so the full path is `~/.config/doom/modules/ui/telephone-line`), and to activate it, since the path under modules is `ui/telephone-line`, I have `telephone-line` in the `:ui` section. There's also a `my-cc` module I almost entirely stole from ccls' maintainer MaskRay.

Maybe the doc should be more precise, but it's pretty straightforward to create your own module, basically you just have to consider that your doom modules sub-directory (`~/.doom.d/modules` or `~/.config/doom/modules`) is an extension of the `~/.emacs.d/modules` folder coming with the clone

**Comment by Overdr0ne** [comment]
Thank you, that really does help a lot. The way to define the module I agree was pretty clear in the docs. I guess one thing that had me very confused was how to instantiate/activate the module. I was trying to use `package!` alone. That had worked for me in an earlier iteration when it was still def-package. I have things pretty much figured out now. But maybe even a full example $DOOM folder would be very helpful I think for people first working with doom. Digging around the doom .emacs.d code was pretty much how I learned, but it could have been a little more streamlined with just a full, compact example.

**Comment by gagbo** [comment]
Having maybe a few select `doom-dir` repositories in the resources is a discussion coming back often, I think it'll happen at some point :)
