### ISSUE TITLE
I disabeled evil-mode and +bindings [BUG] 

### ISSUE THREAD

**Issue by dagnachewa** [hlissner/doom-emacs#2356]
*** on the dashboard there is no keys for recently opened files and open private configuration

*** the modeline does not show in full there is a cut at the right corner

is this normal ?
https://imgur.com/a/beKyWF0

**Comment by hlissner** [comment]
> on the dashboard there is no keys for recently opened files and open private configuration

The dashboard shows no keys because, without `+bindings` on the `:config default` module there are no keys bound to the commands [for those buttons](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/doom-dashboard/config.el#L44-L88).

> the modeline does not show in full there is a cut at the right corner

This happens because the icons in the modeline push it further to the right. You'll have to add padding to your modeline or arrange it. e.g.

```elisp
(after! doom-modeline
  (doom-modeline-def-modeline 'main
    '(bar window-number matches buffer-info remote-host buffer-position selection-info)
    '(objed-state misc-info persp-name irc mu4e github debug input-method buffer-encoding lsp major-mode process vcs checker "  "))
```

**Comment by dagnachewa** [comment]
thanks for the fast reply,
is it possible to bind keys for recently opened files (C-x C-r) and open
private configuration files ?
I removed +bindings to have a 100% vanilla emacs but with doom.

**Comment by hlissner** [comment]
You can read [about binding keys](http://ergoemacs.org/emacs/keyboard_shortcuts.html) or use the `map!` macro. You'll find documentation and examples of its use with `C-h f map\!`.

**Comment by hlissner** [comment]
e.g. 

```elisp
(map! "C-x C-r" #'recentf-open-files 
      "C-x C-p" #'doom/find-file-in-private-config)
```

**Comment by UndeadKernel** [comment]
Regarding:
   *** the modeline does not show in full there is a cut at the right corner

I've noticed the same problem since a long time ago. With the configuration `(setq doom-modeline-icon t)`, the modeline is cut at the end. I guess this is something that should be brought up in the modeline repo.

**Comment by hlissner** [comment]
As of ac52e64 I've reverted some of the doom defaults for `doom-modeline`, which should resolve the modeline issue. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
