### ISSUE TITLE
Unable to set neo-window-width

### ISSUE THREAD

**Issue by hectorakemp** [hlissner/doom-emacs#2396]
**What did you expect to happen?**
When editing my private configuration, I expect to be able to set the variable `neo-window-width` to a custom value, as the default value is too wide for my tastes. 

**What actually happened?**
Setting the `neo-window-width` value has no effect on the width of the neotree window, even though setting other things (like `neo-window-fixed-size`) seems to work fine. 

I'm on Doom for macOS. This is a screenshot of my relevant private config (the rest is just projectile project directories):
```
;; Relative Line numbers
(setq display-line-numbers-type 'relative)
(global-visual-line-mode t)

(setq org-agenda-files (list "~/Dropbox/org/organiser.org"
                             "~/Dropbox/org/projects.org"
                             "~/Dropbox/org/work.org"
                             "~/Dropbox/org/calendar.org"))
(setq +org-capture-todo-file "~/Dropbox/org/organiser.org")
(setq +org-capture-notes-file "~/Dropbox/org/notes.org")
(setq +org-capture-journal-file "~/Dropbox/org/journal.org")
;; work capture
;; personal capture

(after! org
  (add-to-list 'org-capture-templates
             '("t" "Todo" entry
               (file+headline +org-capture-todo-file "Inbox")
               "* TODO %?\n %i\n"
               :prepend t)
             ))
```

**Comment by hlissner** [comment]
When you file an issue, please do not omit your `M-x doom/info` (as instructed in the template), otherwise I won't know what version of Emacs and Doom you are using, or any other relevant information about your setup (e.g. whether you've set up neotree yourself or are using the `:ui neotree` module).

Also include the code you used when you attempted to "set `neo-window-width`", otherwise I cannot guess how it failed for you.

I'll have to assume:

1. You're running the latest commit of Doom, 
2. You have enabled the `:ui neotree` module,
3. Neotree is up-to-date,
4. This is the code you attempted:

   ```elisp
   ;; in ~/.doom.d/config.el
   (setq neo-window-width X)
   ```

If that is correct, then wrap that `setq` statement in `(after! neotree ...)` to ensure your settings take effect after Doom's defaults.

**Comment by kwrooijen** [comment]
I'm having the same issue.

Changing `neo-window-width` doesn't seem to do anything. I've also tried to wrap it in `(after! neotree ...)`. I'm having trouble pinpointing the issue. Maybe it's in Neotree itself?
<details>

```
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        build      Sep 02, 2019
        buildopts  (--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD c503e8904 2020-01-23 04:15:26 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (/Library/Java/JavaVirtualMachines/graalvm-ce-19.2.1/Contents/Home/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold lispy rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) macos magit :lang clojure data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (with-editor winum transient popup neotree magit highlight-parentheses helm-swoop helm-core helm git-commit dash clojure-mode async)
```
</details>

**Comment by kwrooijen** [comment]
@hlissner, Pinpointed the issue:
https://github.com/hlissner/doom-emacs/blob/de6732b4aea951967b6cb5148b948a8f1d00e9c8/modules/ui/popup/%2Bhacks.el#L223-L226

For some reason we're disabled the resize function for neotree. I have no idea why, since I'm not familiar with "popup".

@hectorakemp 
If you want a quick fix until we figure out how to properly resolve this, then add this to your `config.el`

```emacs lisp
(after! neotree
  (advice-remove #'neo-util--set-window-width 'ignore))
```

**Comment by hlissner** [comment]
As of c395c08 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
