### ISSUE TITLE
making `map!` not require repeated specification of modes

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [hlissner/doom-emacs#249]
I notice that sometimes the `map!` function seems a bit repetitive
And by this I mean that, for example, after using `:n` once we must continue to specify `:n`. I'd be nice if after specifying `:n` once it would be applied until we specified something else.

I'd really like to make it so that something like this.
```
   (map! :n "J" #'evil-scroll-page-down
         :n "K" #'evil-scroll-page-up
         :v "j" #'bloo-bloo-bloo`
         :v "k" #'blah-blah-blah
         :nv "x" #'hoo-hoo-hook
         :nv "y" #'ha-ha-ha)
```
Can look like this:
```
(map! :n "J" #'evil-scroll-page-down
         "K" #'evil-scroll-page-up
      :v "j" #'bloo-bloo-bloo
         "k" #'blah-blah-blah
      :nv "x" #'hoo-hoo-hook
          "y" #'ha-ha-ha)`
```
I suppose a consequence of this would be that general mappings for all modes with would have to be specified before mode-specific bindings, but I think that it's worth it if it means avoiding repetition.

What do you think?
And even if you don't agree do you have any tips for Implementing this? As I will probably want to.

**Comment by hlissner** [comment]
If you remove `(setq states '())` on [line 288 of core/core-keybinds.el](https://github.com/hlissner/doom-emacs/blob/develop/core/core-keybinds.el#L288), that should do it.

```diff
-(setq states '()
+(setq doom--local nil
       desc nil)
```

I had considered this when I first wrote `map!`, but I decided against it because I didn't think the added complexity was worth the benefit:

1. It adds a step to managing keybinds: I must ensure that I haven't affected later ones. Not a big deal for short `map!` blocks, but can be a little more troublesome in something like my [personal bindings](https://github.com/hlissner/doom-emacs/blob/develop/modules/private/hlissner/%2Bbindings.el). There are more of these in certain modules, like [org/org](https://github.com/hlissner/doom-emacs/blob/develop/modules/org/org/config.el#L150).
2. I like to group keybinds by relevance, e.g.

    ```
    "M-;"        #'eval-expression
    :nvime "M-;" #'eval-expression
    "M-:"        #'doom/open-scratch-buffer
    :nvime "M-:" #'doom/open-scratch-buffer
    ```

    That general mappings would have to be placed at the top interferes with this. This is a trivial example, but it could be a different story with my [private bindings](https://github.com/hlissner/doom-emacs/blob/develop/modules/private/hlissner/%2Bbindings.el). 
3. The state switches (e.g. `:nv`) were made to be short to mitigate this issue. They rarely get much longer than `:nv`. I don't think the redundancy cost is that high.
4. Quick linewise rearranging is a lot easier when a single line represents an atomic keybind definition. Considering I tweak my config (and bindings) almost daily, the simplicity of this process is a priority.

Of course, this is all personal preference. `map!` was written to avoid a +bindings.el full of `(evil-define-key* '(normal motion) KEYMAP KEY DEF ...)` and `(define-key evil-normal-state-mode-map KEY DEF)`. I liked how concise `[nviom]map` was in VimL.

One possible improvement would be to add global switches (`:g`) for general mappings, e.g. `:nvimeg "M-:" #'doom/open-scratch-buffer`, but it is a deceptively nontrivial change, so it'll have to wait!

**Comment by Luis-Henriquez-Perez** [comment]
Seeing your reasoning, I think you're right. I think another good reason for keeping `map!` as is is readability. With a lot of bindings it might be hard to figure out what state that binding was bound in as you'd have to scroll all the way up to the first binding set in that state.

 I will keep the `map!` function in my config as is. Though I will look into other ideas on how to reduce the redundancy cost because it still is a bit too high for my tastes. Maybe snippets can provide a solution.
