### ISSUE TITLE
Update org-re-reveal

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2499]
A fix has been made in `org-re-reveal` and it needs to be updated, see https://gitlab.com/oer/org-re-reveal/issues/38#note_284064870

I am not sure how these updates are handled: should I create a PR or what is the standard procedure?

**Comment by hlissner** [comment]
I'm open to "bump" PRs. This once I've done it myself since there were other packages to bump, but in the future, here's how you would've done it yourself:

1. Open `modules/lang/org/packages.el`
2. Place your cursor on `(package! org-re-reveal :pin "29bc467201")`0
3. `M-x doom/update-pinned-package-form`
4. Create a PR with a single commit, following this format:

   ```
   Bump to oer/org-re-reveal@a1b2c3d
   ```

   And replace `a1b2c3d` with the first 7 characters of the new commit.


Anyhow, I've bumped org-re-reveal (and others) in 6d8d8a3. Thanks for bringing it to my attention!

**Comment by tamasgal** [comment]
Many thanks! I missed that in the docs (or the instructions are not present?)

**Comment by hlissner** [comment]
Pinning is quite new, so those instructions aren't documented yet.

**Comment by tamasgal** [comment]
This package (`org-re-reveal`) seems to be removed now. What is the reason for this? See https://github.com/hlissner/doom-emacs/issues/2654
