### ISSUE TITLE
Proposal for a tag-based organizational structure

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [hlissner/doom-emacs#250]
I notice that in `modules` folder there's a `completion` category. If I'm
looking to find a snippets module I'd go in there because snippets are arguably
a type of code completion. But there's no 'snippets' dir in there. Instead it's
in a very general `feature` category (but isn't completion also a feature? shouldn't
it also be in the `feature` folder?). Things like this happen to me all the time
in my personal .emacs.d--I think I put a package config in one file, but it's
actually in another. Anyway, what I'm just trying to
point out that categorizing things into files or folders has significant
limitations when trying to organize things that can fall into 2 or more categories.

So I am proposing a `tag-based` organizational structure where we can tag a
package with multiple categories. One cool thing about it is that DOOM's module
organizational structure and a tag-based organizational structure are not
mutually exclusive. In other words, you wouldn't have to change the way DOOM is
set up if you wanted to tag packages.

What would this look like? Well, I was thinking you'd be able to type in a query
like `completion and evil` and all the `use-package` forms for all packages
tagged `completion` and `evil` could be displayed in a buffer, which you could
edit and which would edit the original files with any changes you made to those
forms.

This would be really nice because you could see packages that need to work
together (latex and company as an example) in a single buffer and without the
clutter of other packages.

What do you think? I don't know maybe something like this exists already? This
reminds me of org-mode tags and agenda view.

**Comment by hlissner** [comment]
I apologize for the late reply, other duties have kept me away. I will respond to your email here as well:

> What are the benefits in having modules as opposed to, for example, having separate files in a config folder  (ie. config-completion.el, config-evil.el, etc.)?

The greatest benefit is organization. The single-file approach gets unwieldy as files grow, and is outright impossible if you'd like to lazy load functions or separate package declaration from configuration (as I needed to do with Doom). Doom gets a good chunk of its performances gains by doing this.

> ...because snippets are arguably a type of code completion

I understand the confusion. The `feature` category is a bit of a wildcard. I use it for modules I think are crucial to _my_ use of Doom (like `evil`), while still giving myself (and others) a way to turn it off, if necessary. `snippets` landed there merely because I can't imagine using Doom without it. As arbitrary a reason as any.

> What do you think? I don't know maybe something like this exists already?

You should look into literate programming. Folks have written their emacs configs in org-mode, and use org-tangle to extract the elisp code blocks into an init.el. [Here's a comprehensive example](http://pages.sachachua.com/.emacs.d/Sacha.html). You could leverage org-mode's tags (and `org-match-sparse-tree`) to get what you want.

It's interesting. I am very tempted to do this for Doom. Perhaps for v3.0. It would solve many of the organizational issues we've mentioned here. The result would likely be more performant than Doom's current approach -- but it needs more consideration, before I can make it so.

I am hesitant about applying it to Doom as it is now, however. The implementation worries me: how do we mark blocks as "belonging to a tag"? If it were simply a matter of marking plugins (i.e. `def-package!` blocks), this would be trivial, but there are tidbits of cross-configuration across Doom that don't fall in one of these blocks. For example:

+ There's some [voodoo](https://github.com/hlissner/doom-emacs/blob/master/core/core-popups.el#L156-L526) in `core/core-popups.el` that tries to get various plugins to co-exist with shackle.
+ There are `(set! :company-backend ...)` blocks in most `lang` modules
+ `feature/evil` [tries to tame the multiple-cursors plugin, as it misbehaves with evil-mode on](https://github.com/hlissner/doom-emacs/blob/master/modules/feature/evil/config.el#L395-L446). 

We could use something like autoload cookies:

```emacs-lisp
;;;###tag completion snippets
(def-package! yasnippet
    [...])

;;;###tag helm
(setq-default helm-reuse-last-window-split-state t
              helm-split-window-in-side-p t)
```

That said, I'm not keen on littering my config with these. With all the cross-configuration going on in Doom, there would be quite a few. And it feels like I'm simply reinventing a lot of the literate programming wheel.

I think this is something best left to literate programming. Doom is headed in that direction, but it needs more consideration, and will take a while to get there.

**Comment by gilbertw1** [comment]
It's funny with the timing of this response, but I've just spent the last few days reimplementing my DOOM based config in literate programming style. Primarily started it because I've always been impressed by literate configs others have written and partially to understand the intialialization process and the various configuration values better.

Editing the literate configuration works out to be a very pleasant experience overall. I've only been at it a couple of days and most of that was ripping and tearing code so it's a bit rough at the moment, but I hope to experiement with the organization of the config and come up with something very nice.

I haven't quite been able to match the speed of doom, although after studying the files in `core` I've been able to increase the speed tenfold from when I started (currently at exactly 1 second). I've also pulled out much of the configurable components of DOOM and just attempted to bring along the parts that I use directly.

I guess I don't really have much to add to this thread other than to share my literate config because I'm really excited about it :)

You can [find it here](https://github.com/gilbertw1/bmacs)

I also experimented with replacing shackle with `display-buffer-alist` after reading [this blog post](http://emacsninja.com/posts/design-is-hard.html), which is actually working out pretty well ... although it's a bit more limited.

**Comment by Luis-Henriquez-Perez** [comment]
Thanks for adding your config @gilbertw1! And thanks for the thorough response @hlissner. I'm going to use Sacha Chua and @gilbertw1 's config as examples to make part of what we spoke of a realit. And I'll be giving some thought to a potential solution to organizing `voodoo` code.

**Comment by hlissner** [comment]
@Luis-Henriquez-Perez No problem!

@gilbertw1 That's really cool! I'm always impressed by literate configs, but I do have a few reservations. Having everything in one gigantic file, for instance. That'd make PRs, diffing, blaming or walking the history a lot tougher. Even if I were to split it up into 'doom-core', 'doom-modules' and 'private'. Ah, why can't the world be perfect?

In fact, that makes me wonder how I'd pull off autoloaded files or package definitions. I suppose they could be tangled to separate files?

> I also experimented with replacing shackle with display-buffer-alist after reading this blog post, which is actually working out pretty well ... although it's a bit more limited.

I think I'll try this myself for 2.0.8. Rewriting Doom's popup system has been staring at me from my todo list since July. Also, this is the first time I'm hearing wasamasa has an emacs blog! Good to know. Who needs sleep anyway!

**Comment by gilbertw1** [comment]
> In fact, that makes me wonder how I'd pull off autoloaded files or package definitions. I suppose they could be tangled to separate files?

I saw [this configuration](https://github.com/howardabrams/dot-files) pretty recently. It's the first literate config that I've seen that uses many files. Could be an alternate strategy that might work for DOOM at some point in the future.

> I'm always impressed by literate configs, but I do have a few reservations. Having everything in one gigantic file, for instance. That'd make PRs, diffing, blaming or walking the history a lot tougher. Even if I were to split it up into 'doom-core', 'doom-modules' and 'private'.

I'm really really digging it right now, but there are definitely small issues I've run into, and it's hard to tell if I'll stick with it in the long run after the honeymoon phase wears off. Luckily for me, I'm the only consumer of my config, so it's a lot easier for me to go hog wild and go all single file literate. I even ended up removing almost any configurable part of doom in the process and just implemented my preferences directly.

I wouldn't know where to start if I were trying to convert DOOM and it's full feature set over to a literate config, but I'm sure if there's anyone that could make it happen, you can :)
