### ISSUE TITLE
Irony doesn't work

### ISSUE THREAD

**Issue by arpd** [hlissner/doom-emacs#251]
It looks like all of the functions in `modules/lang/cc/autoload.el`, save for `+cc/autoclose->-maybe` are not actually loaded.

I guess this is to do with their invocation only being used as a hook (e.g. for `irony-mode`), and as such are never loaded, but with basically no emacs-lisp experience this is all I've got so far.

To reproduce: grab a fresh copy of either `master` or `develop` branches, run `irony-install-server`, and then `meta-x irony-mode`; It will complain that the function `+cc|irony-init-compile-options` is undefined.

I'm currently "working around" this by just copying all of the functions in autoload.el and placing them in config.el, without the `;;;### autoload` comment, which although not really entirely functional, does mean that `irony-cdb-*` functions are defined, and I can now get flycheck feedback.

**Comment by hlissner** [comment]
This is usually caused by an out-of-date autoloads file. Did you run `make` or `make autoloads` after enabling the lang/cc module?

As a rule of thumb, it's a good idea to run `make` after changing your init.el, which will remove unneeded dependencies, install new ones, and regenerate the autoloads file.

**Comment by arpd** [comment]
Closing this; as suggested I wasn't rebuilding autoloads!
I was instead running `make update compile`.
