### ISSUE TITLE
Spacemacs Keybinding Migration Guide

### ISSUE THREAD

**Issue by howdoicomputer** [hlissner/doom-emacs#2542]
So I just migrated from Spacemacs over to Doom and... I'm *really* enjoying the experience so far. Everything seems so much more tightly integrated and fluid and stable and fast that I am just *enamored* so far.

However, I cam across this blurb in the README:

```
Have you migrated from Spacemacs? Help me flesh out this section by letting me know what kind of hurdles you faced in doing so. You’ll find me on our Discord server.
```

I didn't know what channel to use in the Discord for this type of feedback so I thought I would make it an issue.

The biggest problem that I'm having right now with the transition from Spacemacs to Doom is adjusting to the key bindings. As most people probably know, the key bindings to Spacemacs are mnemonic - which really helps with the whole "memorizing a billion keybindings" thing.

Now that I'm transitioning, I'm having a difficult time learning the key combinations and not instinctively using the old key combos. I find myself trying `SPC p t` to bring up treemacs and `SPC g s` to bring up a Magit status buffer. Oh, and `SPC c l` to comment out lines - I've been trying to use the comment line keybind (`C-x C-;`) and keep hitting (`C-x C-l`) instead lol.

My suggestion is to have migration documentation that helps with learning new keybindings. Perhaps a cheat sheet that details common actions taken and translates them to Doom keybindings? I've also been thinking about writing a private module that just replaces all the Doom keybindings with the ones from Spacemacs. Your thoughts?

**Comment by howdoicomputer** [comment]
(also I can help with this if it becomes a markdown page)

**Comment by hlissner** [comment]
> I didn't know what channel to use in the Discord for this type of feedback so I thought I would make it an issue.

The #development channel is best suited for these kinds of discussions.

> My suggestion is to have migration documentation that helps with learning new keybindings. Perhaps a cheat sheet that details common actions taken and translates them to Doom keybindings?

I'm all for it. Trouble is: I'm clueless on the matter -- I've never used Spacemacs at length. It'd be a great help if you could flesh out [the Spacemacs migration stub in our Getting Started page](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#from-spacemacs). Or at least include a link there to a spacemacs cheatsheet from there.

> I've also been thinking about writing a private module that just replaces all the Doom keybindings with the ones from Spacemacs. Your thoughts?

Some ex-Spacemacs users have likely done this already -- at least for their favorite keybinds. Is there a spacemacs cheatsheet somewhere I could refer to? 

I've considered writing a Spacemacs bindings module, but I don't want the responsibility of maintaining a module I have no insight on. Still, I will eventually add a community-contributed module repo (a MELPA for Doom modules, essentially), and such a module would be an excellent addition to it.

**Comment by chenyanming** [comment]
Hi all, I love doom and also spacemacs, so I took sometime to work on the spacemacs module. Please check:
https://github.com/chenyanming/spacemacs_module_for_doom
The current status:
1. Default spacemacs leader keybindings.
2. All org layer keybindings.
3. Github layer keybindings.
4. PDF layer keybindings.
5. epub layer keybindings.
5. dash layer keybindings.

**Comment by WarFox** [comment]
I was looking for an alternative to `spacemacs` since it has become too slow for my use case. Found `doom-emacs` yesterday and found this issue listed here.

Today I installed `doom-emacs`. I can see how it is a lot faster than `spacemacs`, thank you and keep up the good work @hlissner, your optimisations are phenomenal. 

I agree with @howdoicomputer regarding the ease to remember keybindings from `spacemacs`. One of the features or spacemacs is `Mnemonic key bindings`, with feels very natural. I've pressed `SPC p t` for `treemacs` and `SPC p l` for layout so many times already for no use.

I've tried out @chenyanming 's spacemacs module setup. It works out of the box for many things. Perhaps we can work in bringing some of it natively to `doom`?

Another thing I noticed is `Spacemacs` it has great documentation. They've built a static website from the `org-mode` file documentation. It's quite nice to have it. Is this something we can do for `doom`?

Overall what I'd like to say here, is `doom-emacs` looks very promising and is fast. We could make it a bit more better with mnemonic key bindings and better documentation.

**Comment by dit7ya** [comment]
Slightly off-topic: people who have used both Spacemacs and Doom, do you recommend not switching the default keybindings to Spacemacs-like? Is there some long-term reason for why I should try to learn doom keybindings rather than changing them to spacemacs defaults?

**Comment by dmusican** [comment]
I just came across this discussion. I've been a Spacemacs user for a few years, and have been recently bouncing back and forth between it and Doom, in trying to decide where I want to land. There's a lot about Doom Emacs to like.

I have definitely found the keybindings to be a sticking point in transitioning, especially since I'm a non-evil user. Similar to Doom, Spacemacs has well thought out keybindings for evil users, initiated by SPC as a leader key. A critical difference for me, though, is when using non-evil standard emacs bindings. In Spacemacs, nearly all of the fabulous Spacemacs menus/keys easily come along for the ride if you just change the leader config. For me, I've set my leader to be `M-\` (since it's an uncommon chord and it's about as comfortable as alt-tab), and then all of the key menus work great.

Doom, on the other hand, has an amazing set of keybindings for evil. I found them so amazing and convenient that I even spent a week moving over to using evil just so I could use Doom as it was intended. I may still land there, but I honestly prefer to use non-modal editing and would prefer not to go to the dark side. :) So I tried the Spacemacs trick of going non-evil and setting my own leader, which Doom lets you do, but I found it to be quite messy. A small subset of the Doom leader-based keybindings came along for the ride, since the Doom non-evil system is largely (but not entirely) to use the original standard keybindings. As best as I understand it, in non-evil mode for Doom ctrl-c serves two purposes; it is the default leader key as a replacement for SPC, but it also used in its usual role with vanilla emacs bindings. When I reconfigured the leader to M-\, a few keys moved, but a whole lot of them stayed with ctrl-c. I found configuring my own leader not to be very useful, since it left a whole lot behind with ctrl-c. I realized I was happier just leaving ctrl-c fixed as the leader rather than configuring my own as I do in Spacemacs, but I found myself back in the land of using ctrl-key combos all over the place, which is what I gleefully left when I went to Spacemacs years ago.

To recap, one of my favorite parts of Spacemacs is the fantastic menu system that I can invoke with a leader I can configure myself on non-evil mode. It would be awesome if the Doom evil system could similarly be transformed. It's not that I would need something that mimics Spacemacs in the actual keys. Mimicing the Doom system would be fine. The key thing I'd love to see would be a non-chord-based approach to the menus (apart from perhaps the usable configured leader key). That's the #1 thing possibly holding me back at Spacemacs at this point. Spacemacs gets me the best of both worlds, from my own perspective, on keys; I get emacs-style non-evil editing, and a very convenient menu system that's not based around lots of ctrl-key combinations. Currently in Doom, it seems I have to choose one or the other.

Thanks again for all of the hard work!
