### ISSUE TITLE
[REQUEST] Remove pyenv, rbenv

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#2621]
**Describe the feature**
Doom Emacs supports pyenv with `+pyenv` flag, but [pyenv-mode](https://github.com/pythonic-emacs/pyenv-mode) doesn't work well with `persp-mode`. It uses `PYTHON_VERSION` of the previous workspace.

Actually we don't need `pyenv-mode` because the executables under `${PYENV_ROOT}/shims` find the local version of Python by the working directory. All we have to do is inserting `${PYENV_ROOT}/shims` in the head of `PATH`.

**Comment by hlissner** [comment]
> but pyenv-mode doesn't work well with persp-mode. It uses PYTHON_VERSION of the previous workspace.

Is this not the expected behavior? `pyenv` affects the global environment. It is not buffer-local, or workspace-local, or project-local, unless you combine it with, say, direnv, or virtualenv, or use `pyenv-mode-auto`, in which case it should change whenever you change buffer focus.

Generally speaking, the python module needs to be rethought in light of all its env managers. Frankly, I'd love to remove all that env management cruft in general and just leave it to direnv.

**Comment by sei40kr** [comment]
@hlissner 
> Is this not the expected behavior? pyenv affects the global environment. It is not buffer-local, or workspace-local, or project-local, unless you combine it with, say, direnv, or virtualenv, or use pyenv-mode-auto, in which case it should change whenever you change buffer focus.

I think no. `pyenv` should read the version from `.python-version` if it exists in the ancestors of the working directory.

pyenv generates a wrapper script by default to run the command with the local Python version. For example, this is my `~/.pyenv/shims/pip`

```sh
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/sei40kr/.pyenv"
exec "/Users/sei40kr/.pyenv/libexec/pyenv" exec "$program" "$@"
```

Please refer this too:
https://github.com/pyenv/pyenv/blob/master/libexec/pyenv-exec
