### ISSUE TITLE
Incompatible mac-option-modifier and system-wide alt-key definitions

### ISSUE THREAD

**Issue by mikeonly** [hlissner/doom-emacs#277]
On macOS I have a problem with doom-emacs config that my system-wide <kbd>alt</kbd> keymappings are ignored by Emacs and are interpreted as keybindings if I set `mac-option-modifier` to `alt`. I rely on keybindings with `alt` inside Emacs for text movement, but if I try to input a symbol with <kbd>alt</kbd>, I get an undefined error.

_To reproduce_:
- Have `emacs-mac` port installed. 
- Execute `(setq mac-option-modifier 'alt)`
- Press <kbd>alt</kbd>+<kbd>s</kbd>

_Expected behaviour_:
Insert `ß` (for my keyboard layout) to the buffer. 

_Observed behaviour_: 
Error: `A-s is undefined`.

I can have `(setq mac-option-modifier 'nil)` and get special symbols for input, but then I cannot use my `alt` key for my usual keybindings.

I use Mitsuharu Yamamoto `emacs-mac` build installed through `brew`. 

With other configurations for Emacs, vanilla or Spacemacs, I get the expected behaviour, but doom somehow overwrites this.

I am lost in guesses of how it is possible. Can anyone suggest why this is the case in doom and how to fix it? Thanks.

**Comment by hlissner** [comment]
After some research, I've discovered how to fix this:

```emacs-lisp
(setq ns-alternate-modifier 'none)
```

However, this will break most alt bindings, if you have any. Doom, by default, only has 2, `A-;` and `A-x`, as aliases for `M-;` and `M-x`. This could be worked around by binding keys to the unicode key, e.g. `(map! "Ø" #'dosomething)` instead of `(map! "A-o" #'dosomething)`, but this isn't cross-platform compatible.

OR, you could do this to only your right-alt key:

```emacs-lisp
(setq ns-right-alternate-modifier 'none)
```

Alternatively, you could use counsel's `M-x counsel-unicode-char` command for finding/inserting unicode.

Hope that helps!

**Comment by hlissner** [comment]
I'll close this for now. Feel free to reopen this if the above doesn't solve your issue.

**Comment by Bargsteen** [comment]
The proposed solution with the `ns` prefix did not work for me. It is likely that things have changed during the past couple of years.

What did work, however, was this addition to the `config.el` file:
```emacs
(setq mac-right-option-modifier 'none)
```

**Comment by hlissner** [comment]
@Bargsteen Depends on what build of Emacs you're running on macOS. The `emacs-mac` build has its own `mac-*` versions of the same variables. It's `ns-*` in all other builds.
