### ISSUE TITLE
Scaling down icons globally?

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#278]
Hi, I am starting out with this awesome Emacs config (and with Emacs in general) and I would like to have icons little bit smaller. I know about `all-the-icons-scale-factor`, but when I tweak it in my private init.el, it only affects for example neotree and not modeline, because there are explicitly specified local values of `all-the-icons-scale-factor` in doom-modeline module's config.el.  
Do you think it is worth it to introduce additional complexity in form of global variables which would hold scale value for buffer-info and vcs parts of modeline and which user could tweak somewhere in his private module, or should I rather fork doom-modeline's module and tweak it there?  
Or maybe there is another way to solve this I am not aware of?

**Comment by hlissner** [comment]
Sadly, there is no way to do this with those local bindings there. I'll look through ui/doom-modeline and see if those are necessary anymore, then you'll be able to use `all-the-icons-scale-factor` again.

**Comment by hlissner** [comment]
Sorry for the late response; I've removed the all-the-icon-scale-factor let-bindings in `develop`, so you should be able to modify that yourself from here on out. As it turns out, they aren't necessary anymore; either the font glyphs have been adjusted since, or I simply can't find the edge cases where they were needed.

Please give it a try. I will keep this open until it has been merged into `master`.

**Comment by AloisJanicek** [comment]
Thank you.  
After 2+ weeks of using Doom, I could not identify this need for changing icon size anymore. I just tried it, it works, but even little change seems odd now - I got used to how look by default.   
Nevertheless it is good that anyone now can easily change icons' size in doom if such need surface.

**Comment by hlissner** [comment]
You're very welcome! This has now been merged into master, so I'll consider this resolved.
