### ISSUE TITLE
+roam org-roam-directory variable gets reset

### ISSUE THREAD

**Issue by bdarcus** [hlissner/doom-emacs#2810]
**What did you expect to happen?**

Using the `org` module `+roam` flag, when I set `org-roam-directory` in my `config.el` it will apply when I start `org-roam.`

**What actually happened?**

When I start emacs, the variable is set as expected, but when I load `org-roam` (by opening an org file via `org-roam-find-file`), it gets reset to `org-directory`.

**Additional details:**
- [private config](https://github.com/bdarcus/.doom.d)

**System information:**
<details>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Dec 10, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop 84d2e6763 2020-03-31 15:20:58 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64
        path       (/usr/local/bin /usr/local/sbin ~/.local/bin /usr/share/Modules/bin /usr/bin /usr/sbin ~/bin /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools (eval +overlay) (lookup +docsets) lsp magit make pdf :lang data emacs-lisp julia (latex +lsp) markdown (nim +lsp) (org +gnuplot +dragndrop +hugo +pandoc +pomodoro +present +roam) (python +lsp) sh web :config (default +bindings +smartparens))
        packages   ((org-ref) (pandoc-mode) (org-super-agenda) (org-chef) (org-fancy-priorities) (origami))
        unpin      (org-roam)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I've been sitting on a fix for a while. I've pushed it in 4434abf, so this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by yangsheng6810** [comment]
This problem seems to have re-appeared.

**Comment by yangsheng6810** [comment]
In fact, this is what I experienced: I set `org-roam-directory` to another directory (`~/Documents/org`) in my `config.org`, which is a literate config file (I believe this is one of the sources of the problem). When I run `doom refresh && emacs`, the roam db file is created at `~/org/roam/org-roam.db`, which is already an incorrect behavior. When I start using org-roam, constant complaints for "attempt to write a readonly database" emerge when I try to edit files managed by roam. I believe this is because `org-roam-db-location` defaults to `nil`, and org-roam thinks the file location should be `~/Documents/org/roam/org-roam.db`, but the file it created and opened was `~/org/roam/org-roam.db`.

I managed to workaround this by modifying `~/.emacs.d/modules/lang/org/contrib/roam.el`, manually setting `org-roam-db-location` and `org-directory`. Due to lack of knowledge on the way doom initializes `org-directory`, `org-roam-directory`, etc. I am unable to come up with a PR.

**Comment by hlissner** [comment]
@yangsheng6810 have you updated to the latest commit of doom? If so it's probably because the hook that sets  org-directory runs after org-roam-mode in org-load-hook. Will fix in the morning.

**Comment by hlissner** [comment]
@yangsheng6810 Looking into it now, the hook order of org-load-hook is correct and I cannot reproduce the behavior you describe with the following:

```elisp
;; in ~/.doom.d/config.el
(setq org-directory "~/projects/org/"
      org-roam-directory (concat org-directory "notes/"))
```

**Comment by yangsheng6810** [comment]
@hlissner I just bisect my `~/.doom.d/config.org`, and here is the mysterious finding. With
```
;; in ~/.doom.d/config.el
(setq org-directory "~/projects/org/"
      org-roam-directory (concat org-directory "notes/"))
```
Everything is behaving correctly. The problem is introduced when I enable `lispy` before that, i.e.
```
;; in ~/.doom.d/config.el
(use-package! lispy)
(setq org-directory "~/projects/org/"
      org-roam-directory (concat org-directory "notes/"))
```
It seems doom already has `lispy` enabled as a module, so an explicit `(use-package! lispy)` should not be needed (It was there the first place due my migration from another Emacs config distribution). The problem can also be fixed if I add `:defer t` to the `use-package` call. Therefore you can safely consider this as closed. It would be even better if you could explain or show me a pointer on the mysterious org loading process.

**Comment by hlissner** [comment]
Ah, that would explain it. Lispy certainly [pulls in a lot](https://github.com/abo-abo/lispy/blob/master/lispy.el#L135-L157). Org, or one of its dependencies, is likely somewhere down that load graph. Thanks for looking into it (and letting me know)!

**Comment by madjestic** [comment]
I am experiencing the same issue: org-roam directory is resetting to a default, despite what's in init.el.  However, if I do "revert this sessions customization", the (correct) value from init.el gets picked up again... untill I restart the org-mode session.

**Comment by hlissner** [comment]
@madjestic Sounds like you may have used `M-x customize` to set its value, which immortalizes the setting in `~/.doom.d/custom.el`. You'll need to either delete the file or remove it by hand. I don't recommend using `M-x customize` ever.

**Comment by madjestic** [comment]
Will it stop resetting to the default though?
