### ISSUE TITLE
LSP mode disabled in C/C++ buffers when project root not specified

### ISSUE THREAD

**Issue by anihm136** [hlissner/doom-emacs#2823]
**What did you expect to happen?**
LSP mode is enabled in buffer even when root folder is not in `lsp-workspace-folders`

**What actually happened?**
I'm working on a c++ file, which is standalone i.e, project root is not required. On the initial prompt to select project root, I selected to ignore the folder as a project. Now, LSP is disabled by default in the buffer, and I have to manually enable each time

**Additional details:**
- This has been recreated with minimal config file i.e, no custom configs, only the defaults

**Steps to reproduce:**
1. Enable LSP for cc-mode in init.el
2. Create a new c++ file
3. On the prompt, choose to ignore folder as project
4. Close and reopen the file

**Comment by dotnwat** [comment]
Sounds related to https://github.com/hlissner/doom-emacs/issues/3880

**Comment by hlissner** [comment]
As far as I know, the C/C++ LSP servers require a project. If you tell it to ignore the current project, you don't get LSP support. You could try enabling `:tools (lsp +eglot)` and see if `eglot` handles things any differently, but otherwise this isn't a bug, nor is it something I can fix on my end. Better to bring this up [upstream](https://github.com/emacs-lsp/lsp-mode).
