### ISSUE TITLE
+org-unfold-to-2nd-level-or-point-h never executes

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2848]
**What did you expect to happen?**
When opening an org buffer with no `STARTUP` visibility, I expect this function to unfold the first level of headlines.

**What actually happened?**
No headlines are expanded - everything is fully folded.

**Additional details:**

This function only runs if `org-agenda-inhibit-startup` is nil:
https://github.com/hlissner/doom-emacs/blob/cc6d4aa7d19947bf8b5f775ab778b58b33661930/modules/lang/org/autoload/org.el#L433-L444 

However doom sets it to `t` by default (I assume as a performance optimization) - https://github.com/hlissner/doom-emacs/blob/6d81f9b5f48bb56be32382bf57f971269f2a4995/modules/lang/org/config.el#L68-L74

So I wonder how this function is intended to be used? Would it make sense to eliminate the `(unless org-agenda-inhibit-startup`?

**Comment by hlissner** [comment]
I think it'd be best to remove the `org-agenda-inhibit-startup t` from `+org-init-agenda-h`. The guard in `+org-unfold-to-2nd-level-or-point-h` is there to prevent doing potentially expensive/emacs crashing work on buried buffers that are being processed by `org-agenda`, because `org-agenda` doesn't use the correct mechanism for reading files non-interactively.

**Comment by hlissner** [comment]
As of 73f89fd this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
