### ISSUE TITLE
Don't rebind other-window to ace-window

### ISSUE THREAD

**Issue by mindlike** [hlissner/doom-emacs#2862]
The `window-select` module has `(global-set-key [remap other-window]
#'ace-window)`.

I see `ace-window` as useful for navigating in frames with many window.
`other-window` is ideal for quickly moving between ~2-4 windows on the same
frame (I have it bound to key-chord `fk`). 

If my understanding of these different use-cases is correct, it seems better to
give `ace-window` its own binding.

**Comment by WhatDothLife** [comment]
For 2 windows `ace-window` has the same behavior as `other-window`. For more than 2 windows `other-window` doesn't seem as the best option, due to its cyclic ordering. If you instead map `ace-window` to `SPC-w-w` you reach every window with 4 keystrokes. 
You might also use `evil-window-mru` for switching to the last used buffer in another window or `evil-avy-goto-char-2` with a prefix argument to jump to the exact location.

I guess with this whole set of fine options hlissner found `other-window` to be kinda obsolete.

**Comment by mindlike** [comment]
> For 2 windows `ace-window` has the same behavior as `other-window`. 

I thought this was the case, but that's not what I saw. I now realize it was because of a quirk in EXWM. If I have 2 Emacs windows open in the same workspace as an X window (e.g. Firefox), then ace-window sees 3 windows, but only gives me the option to switch between the 2 Emacs windows.

I'll close, since it's easy enough for EXWM users to just add their own `ace-window` config:

```
(use-package! ace-window
  :config
  (map! "C-M-SPC" #'ace-window)
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
```
