### ISSUE TITLE
Format on save ignore editorconfig for bash script and always use tabs

### ISSUE THREAD

**Issue by Mayeu** [hlissner/doom-emacs#2905]
*See [this comment](https://github.com/hlissner/doom-emacs/issues/2905#issuecomment-617008911) for the last news on my research*

**What did you expect to happen?**

When saving a shell script (in that case bash), I expect the formater to kick in and use space as indentation. As per my global configuration, and my `.editorconfig` file

**What actually happened?**

On save my script get reformated, but all the space indentation is replaced by tab.

**Additional details:**
- [My doom configuration](https://github.com/Mayeu/dots/blob/master/doom.d.symlink/config.el#L60)
  - I have tried to add configuration that force the `indent-tabs-mode nil` but those don't have effect
- Here is the local `.editorconfig`
<details><pre>
# top-most EditorConfig file
root = true

# Script: 2 space indentation
[*.sh]
indent_style = space
indent_size = 2

# Makefile: Tab indentation
[Makefile]
indent_style = tab
</pre></details>
- Screen cast of the issue:
![2020-04-15 13 03 04](https://user-images.githubusercontent.com/222375/79330275-8de92c00-7f19-11ea-9215-6d11c5f0bf16.gif)

**Steps to reproduce:**
1. Create a shell script,
2. Indent it with space
3. Save it

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2")
  (build . "Mar 24, 2020")
  (buildopts "--with-mac --enable-mac-app=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --prefix=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --enable-mac-self-contained --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 1cb753cbb 2020-04-14 19:27:33 -0400")
  (dir . "~/.dots/doom.d.symlink/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/ruby/bin" "~/.platformsh/bin" "~/.bin" "/usr/local/opt/mysql-client/bin" "/usr/local/opt/make/libexec/gnubin" "/usr/local/opt/gnu-getopt/bin" "{/Users/cast}/.yarn/bin" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/MacGPG2/bin" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets word-wrap :emacs dired electric vc :checkers syntax :tools ansible editorconfig (eval +overlay) lookup macos magit make terraform :lang clojure data emacs-lisp javascript markdown (org +dragndrop +babel +roam) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by Mayeu** [comment]
Additional weirdness: If I run `gg=G` in my buffer, it's correctly reindented with spaces.

**Comment by Mayeu** [comment]
OK so it seems to boil down to an issue between the `shfmt` tool (which is used to format shell scripts) and Emacs/Doom.

If I open a shell script that is using tabs, saving it will always result with Doom keeping the tabs, even if `shfmt` correctly returned a space indented version when run in the shell.

As an example, [here is a repo](https://github.com/Mayeu/shfmt-editorconfig-doom-bug) with an EditorConfig file that configure sh script to be indented with 2 space. But where the script is currently using tabs.

If you open it with Doom (with format on save) and change it, then save it, it will not use space as indentation, but if one first do `:retab` then save it, the spaces are kept. 

It seems to highlight some kind of bug with `dtrt-indent` (maybe? I'm a fairly new emacs user).

Is there a way to deactivate `dtrt-indent` for some file type?

Also, there is work ongoing [on the format-all repository](https://github.com/lassik/emacs-format-all-the-code/issues/27#issuecomment-588302734) to support configurable formatter. Maybe it would be time to unpin the current `format-all` version of Doom to ensure that `shfmt` is aligned with the rest of Doom by using space as default?

Hope that helps :)

**Comment by rbutoi** [comment]
I think I've run into this as well. I saw something telling me to `brew install shfmt`, and I did. Grepping through my .doom-emacs/ I can't find any references to `shfmt`, so I'm not quite sure where that came from. `shfmt` does look quite useful, and I wouldn't have run into otherwise, but it doesn't seem to work properly (at least not being called properly). I tried installing https://github.com/purcell/emacs-shfmt and added that as an after save hook with my custom, non-tab arguments, but that didn't work.

**Comment by Mayeu** [comment]
> This issue has been mentioned on Doom Emacs Discourse. There might be relevant details there

Would love to have access to this discussion ^^

**Comment by tchajed** [comment]
This is now affecting me and it makes it really hard to use Doom for shell scripts. Every time I make a change I have to manually run `shfmt -w` on the files before committing, otherwise everything changes from spaces to tabs. Other than that I really like the shell module, between syntax highlighting, lsp, and shellcheck it catches a lot of my bugs before they get committed!

**Comment by peterhoeg** [comment]
I had a look at my config some time ago and realized that while I had `(format +onsave)` enabled, I had created a helper
for easily disabling it and then actually disabled it in most cases because it was just too annoying.

I changed from opt-out to opt-in and then manually added `shfmt`.

```elisp
(when (featurep! :lang sh)
  ;; use shfmt directly instead of format-all which fucks up tabs
  (use-package! shfmt
    :hook (sh-mode . shfmt-on-save-mode)
    :config
    (setq
     shfmt-arguments
     `(
       ;; indent with spaces, has to be 2 different strings due to the space
       "-i" ,(format "%s" tab-width)
       ;; indent switch case
       "-ci"))))
```

I have only opted in in modes where the formatter doesn't require customization.

**Comment by tchajed** [comment]
@peterhoeg that is very helpful! For anyone else using this workaround, you might also need `(package! shfmt)`.

I'm confused why I actually need the `-i` flag because I thought that the `.editorconfig` file would be enough. When I run `shfmt` from the command line that is sufficient to get spaces. My only guess is that `shfmt` is somehow not being run from the correct directory, but anywhere in the project would be sufficient.

**Comment by jman-schief** [comment]
I think a simpler version of @peterhoeg suggestion to disable formatting for a specific file type can be achieved wih:
```
;; ./doom.d/init.el
(doom! :input
     ...
     (format +onsave)
      ...)

;; ./doom.d/config.el
(setq +format-on-save-enabled-modes
      '(not sh-mode
            ))
```
This setting is explained [here](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/format/README.org#disabling-the-lsp-formatter).

Still, I'd love to see this issue fixed.

**Comment by hlissner** [comment]
Give this a try instead:

```lisp
(after! sh-script
  (set-formatter! 'sh-mode `("shfmt"
                             ("-i" "%d" (if indent-tabs-mode tab-width))
                             "-ci")))
```

**Comment by hlissner** [comment]
As of 99fbdb1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jman-schief** [comment]
I've run `doom upgrade` and tested the change, seems all good, thank you!
