### ISSUE TITLE
An upstream regression pulled in d6c5d18

### ISSUE THREAD

**Issue by myshevchuk** [hlissner/doom-emacs#2993]
**What actually happened?**
When `#+SETUPFILE:` keyword is present in an org-mode buffer, the buffer's fontification is screwed up.

See explanation in https://github.com/hlissner/doom-emacs/issues/2775#issuecomment-620311173

This bug was introduced upstream. Doom pulls the regression in d6c5d18.

**Comment by guraltsev** [comment]
I can confirm! What should one do?

**Comment by AloisJanicek** [comment]
Looking at org-mode upstream repo [commit log](https://code.orgmode.org/bzg/org-mode/commits/master), it may have been fixed by `80865bab64`.

If you can't afford to wait, use `(package ... :pin ...)` as described in [Pinning packages to specific commits](https://github.com/hlissner/doom-emacs/blob/d6c5d18a87829846cafa917ae80669bea2c7f508/docs/getting_started.org#pinning-packages-to-specific-commits)

```
;; file: packages.el
(package! org-mode :pin "80865bab64")
```
or `(unpin! ...)` org-mode completely and use always latest commit

```
;; file: packages.el
(unpin! org-mode)
```

**Comment by hlissner** [comment]
I've bumped org in d34633c, so this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by myshevchuk** [comment]
Thank you!

**Comment by guraltsev** [comment]
Works! Thanks!
