### ISSUE TITLE
The after! statement works with lsp-mode instead of lsp

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#3058]
Edit:
It seems to be a problem with the `after! lsp` statement, it works with `after! lsp-mode`. Is that intentional?

**What did you expect to happen?**
I mapped `"C-b"` to `lsp-format-buffer` and after a recent upgrade it stopped working as before.
Probably related to #2952 

**What actually happened?**
It just does the default `evil` mapped behaviour.

**Additional details:**
I used to have:
```lisp
(after! lsp
  (map!
   :nv "C-b" #'lsp-format-buffer
   )
)
```
Now I need to have the `map!` outside of `after! lsp`.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 0f696ec8b 2020-05-07 03:19:00 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64")
  (path "~/.zplug/bin" "~/.cargo/bin" "~/miniconda3/bin" "~/miniconda3/condabin" "/usr/local/cuda/bin" "~/.krew/bin" "~/.emacs.d/bin" "~/.local/bin" "~/local/bin" "~/bin" "~/go/bin" "/usr/local/go/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.fzf/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold multiple-cursors rotate-text snippets :emacs dired electric (ibuffer +icons) undo vc :checkers syntax spell :tools docker (eval +overlay) lookup (lsp +peek +bindings) magit pdf :lang (cc +lsp) data emacs-lisp (json +json) (javascript +lsp) (latex +latexmk) markdown (org +dragndrop +pandoc +present) (python +cython +conda +lsp) sh solidity (web +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (ag) (smartparens :recipe (:host github :repo "Fuco1/smartparens")) (org-ref) (org-fancy-priorities) (org-super-agenda) (platformio-mode) (yapfify) (lsp-python-ms :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Some time ago the [lsp-mode](https://github.com/emacs-lsp/lsp-mode) package [deprecated `lsp.el` as its entry point](https://github.com/emacs-lsp/lsp-mode/commit/4f4932bb715b9d6652e5d332022e87d3ce1b1152). It wants us to load `lsp-mode` instead, and we do, so `lsp` will never be loaded [and doesn't need to be](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp.el).

So this _is_ intentional. `(after! lsp-mode ...)` and `(map! :after lsp-mode ...)` is what you want.

**Comment by vakker** [comment]
I see, thanks!

**Comment by steven-lang** [comment]
Can we maybe note this somewhere, e.g. the `lsp` module documentation?

The issue is that in the `after!` [documentation](https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org#after), it is explicitly stated, not to use `xyz-mode` but `xyz` which is a good hint but lead me to believe to use `lsp` instead of `lsp-mode` when configuring the `lsp-mode` package. The naming is a bit confusing all over the place since the doom module is also called `lsp`. 

Maybe another solution would be to throw an error or a warning whenever `(after! xzy ...)` has been called where `xyz` is not a valid package? Right now it just fails silently.
