### ISSUE TITLE
Yanking with C-y works in minibuffer but not in org-mode

### ISSUE THREAD

**Issue by antoan** [hlissner/doom-emacs#3127]
**What did you expect to happen?**
Paste text copied from browser to clipboard into org-mode buffer using C-y
...

**What actually happened?**
A single asterix is printed instead of text in clipboard
...

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

I can however copy the text  using M-x clipboard-yank which is not bound to any keys. Is this intentional? 

The only editing I've done so far on my private configuration is to enable the cc module.

Cheers.

**Comment by hlissner** [comment]
I ran `F1 k C-y` in org and it yields `evil-copy-from-above`, which is the default behavior of `C-y` for evil users. If you don't want evil, I'd recommend [disabling it](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#removing-evil-mode). Otherwise, here are some "evil" ways to paste things in insert mode:

1. `C-r +` 
2. `C-o p` (`C-o` = exit insert mode for a single command).
3. If you're on macOS -- I can't tell because you didn't include your `M-x doom/info` -- cmd+v will work too
4. Turn on `cua-mode` (by adding `(cua-mode +1)` to `~/.doom.d/config.el`), and `C-v` will become available for pasting.

Hope that helps!

**Comment by antoan** [comment]
I see, thank you, I really appreciate it.
