### ISSUE TITLE
Persp workspace modeline indicators

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#314]
Hi, I'm starting to use +workspace module to replace eyebrowser. However, it doesn't display any workspace info on the modeline, which is a bit inconvenient. I'd like to show the number and the related projectile name (or None) for each workspace. Is there a configuration for this feature?

**Comment by amosbird** [comment]
Yup, I've noticed that it shows in the echo area. Can I customize it to be on the modeline? Also, it doesn't create new workspaces when I switch to a new project.

**Comment by hlissner** [comment]
I suppose you could try putting the output of `(+workspace--tabline)` in the modeline, but I'm afraid there are few configuration options for feature/workspaces.

I'll look into this after New Years. There are many overdue improvements for feature/workspaces I need to do

>it doesn't create new workspaces when I switch to a new project
It turns out counsel doesn't respect projectile's settings (like `projectile-switch-project-action`), which is what feature/workspaces taps into. I'll post a fix for this soon.

---

I'll look into improving feature/workspaces right after new years; including an option to show the current open project in (or next to) the tab name.

**Comment by amosbird** [comment]
Great! And happy new year Henrik :fireworks:

**Comment by hlissner** [comment]
Now that we've adopted the doom-modeline package, there is a persp display in the modeline (you have to activate it with `(setq doom-modeline-persp-name t)` though). I'll consider this issue resolved. Thanks for bringing it to my attention!
