### ISSUE TITLE
Clean before executing shell commands

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#316]
When I execute functions **like** ```projectile grep```, ```guru find definition```, seems that the doom send it to the bash to execute, and it initialises everything from .bashrc or .zshenv. 

 Here is the problem that I came to: I have a list of environment configurations that needs to be exported to the shell environment whenever I initialise my terminal, which contains a lot of exports, my ```.bashrc``` looks like this:
```
export GOROOT=/usr/local/go
export GOPATH=/Users/andy.pan/gopath
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH=$PATH:$GOPATH/src/github.com/myteksi/go/scripts
export PATH=/usr/local/bin:$PATH

export GP=$GOPATH/src/gitlab.myteksi.net/gophers/go
export SUFFIX=ci
source $GP/scripts/set-env.sh $SUFFIX

```

and when I open a new terminal window, or open a new tap, the terminal will have output messages like 
```
+++ export SEXTANT_CONF=/Users/andy.pan/gopath/src/gitlab.something.net/here/go/geo/sextant/config-ci.json
+++ SEXTANT_CONF=/Users/andy.pan/gopath/src/gitlab.something.net/here/go/geo/sextant/config-ci.json
+++ export MESSAGING_CONF=/Users/andy.pan/gopath/src/gitlab.something.net/here/go/messaging/grab-messaging/config-ci.json
+++ FOOD_CE_CONF=/Users/andy.pan/gopath/src/gitlab.something.net/here/go/food/food-ce/config-ci.json
...
+++ set +x
```
Real message is much longer. And when I use the commands I mentioned from the beginning, I will have to    **scroll down** in order to see the results. 

Is there any way to clean up the terminal output and only show the necessary information for those commands?

**Comment by hlissner** [comment]
Is `set +x` necessary to your config? I can't fathom how it is useful (besides debugging) and there is no simple way to comprehensively filter command output from within Emacs, without advising a lot of its shell library.

If that `set +x` _is_ somehow important, you could put it in your `.zshrc` (or `.bashrc`) instead of your `.zshenv`/`.bash_profile`, then you'll only see this output in interactive sessions (and thus, not from `M-x shell-command`).

---

All that said, I'm awfully confused. Are you a bash or zsh user? You _seem_ surprised that Doom would use bash to pick up your shell environment, but it simply uses the shell defined in `$SHELL`. If that's bash, _it should not pick up zsh dotfiles_. If it's zsh, _it should not pick up bash dotfiles_. However, `set +x` should do nothing in a zsh session.

There is some strange behavior here. I can only imagine that your bash/zsh dotfiles are sourcing each other (or the same files), which is causing this overlap. Or that you manually set $SHELL.

Would you happen to have your dotfiles up somewhere I can see them? It would give me a lot more context around these issues.

**Comment by andyafter** [comment]
Ok not sure where does the set +x comes from but, the issue here is that, I believe it would be great if the output of any ```guru``` or ```prelude``` search should be displayed with only a list of results. I will checkout how prelude or spacemacs is handling this and get back to this issue.

**Comment by hlissner** [comment]
I'm afraid this isn't an Emacs problem. Projectile grep, guru, etc. all communicate through shell commands. If your shell is incorrectly configured, you will get issues like these.

From what I can gather, there is an `set +x` or `set -o xtrace` in one of your dotfiles causing all this output that you must find and remove.

I'll close this issue since it isn't something that can be reliably solved at the Emacs level.
