### ISSUE TITLE
cursor after Expand-region cancellation should be back to original position  

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#317]
When I expand region in any more, after canceling with C-g, the cursor always stops at the beginning of the region. It should be in the original position so that whenever you regret about this expanded region you could just cancel and restart.

**Comment by hlissner** [comment]
The fix is now in `develop`. I'll leave this open until it is in master.

How `expand-region` resets itself on `C-g` in vanilla Emacs is it advices all the quit commands (e.g. `keyboard-quit`, `minibuffer-keyboard-quit`, etc), but in Doom, `evil-escape` is bound to `C-g` in visual mode. There is no advice for `evil-escape`, so I added one.

**Comment by andyafter** [comment]
@hlissner Hi there, not sure if this is released but the cursor place still doesn't go back to original position after the cancellation.

**Comment by hlissner** [comment]
@andyafter i believe this is a recent regression caused by the introduction of doom/escape. I’ll look into this soon.

**Comment by hlissner** [comment]
@andyafter Sorry for the late response. This issue should be fixed now. Let me know if that isn't the case.
