### ISSUE TITLE
doctor report issues

### ISSUE THREAD

**Issue by ModarYaghi** [hlissner/doom-emacs#3197]
Hello, I am new in emacs world and trying to follow emacs experts' instructions as far as I can. After making some uncomment to some of init.el available choices and did bin/doom/install, I ran bin/doom doctor and I received this message! Any idea how to fix these issues? Please. 

<img width="651" alt="doctor_repo" src="https://user-images.githubusercontent.com/60154664/82682594-2cbf2180-9c58-11ea-8807-96ade896276f.png">

**Comment by chr-zrv** [comment]
You should run `doom sync` whenever you modify init.el (and packages.el). Hopefully that fixes the errors.

**Comment by hlissner** [comment]
gls, cmake, markdown compilers, pipenv, nosetests, spellcheck, stylelint and js-beautify are all external programs that certain packages in Doom need to function. However, Doom will function fine without them, so if you don't know what they do or don't need them, you can ignore them.

Otherwise, you'll need to install them through your OS's package manager (homebrew, in your case), or your language's package manager (pip or npm). e.g.

```sh
brew install coreutils cmake sbcl markdown shellcheck node python3
pip install pipenv nosetests
npm i -g stylelint js-beautify
```

**Comment by ModarYaghi** [comment]
> gls, cmake, markdown compilers, pipenv, nosetests, spellcheck, stylelint and js-beautify are all external programs that certain packages in Doom need to function. However, Doom will function fine without them, so if you don't know what they do or don't need them, you can ignore them.
> 
> Otherwise, you'll need to install them through your OS's package manager (homebrew, in your case), or your language's package manager (pip or npm). e.g.
> 
> ```shell
> brew install coreutils cmake sbcl markdown shellcheck node python3
> pip install pipenv nosetests
> npm i -g stylelint js-beautify
> ```

Thank you very much hlissner, your answer did solve the issue. 
Best regards.
