### ISSUE TITLE
what do I need to add and edit to make doom-emacs as perfect as it could as a python IDE?

### ISSUE THREAD

**Issue by ModarYaghi** [hlissner/doom-emacs#3218]
**What are you trying to achieve?**
Making doom-emacs my main python IDE

**What have you tried?**
Uncomment python lang in init.el
declare elpy and flycheck-color-mode-line in packages.el

**Comment by hlissner** [comment]
1. Enable `:lang (python +lsp)`
2. Run `doom sync`.
3. Restart Emacs.
4. Install `mspyls`: `M-x lsp-install-server`, then select `mspyls`

And you're good to go.

Since you included no other details, about your system or needs, I cannot guess what else you want to know. Please visit [our discord](https://discord.gg/qvGgnVx) if you want usage/config help for Doom.

I will delete this issue shortly, because usage/config questions do not belong on our issue tracker any longer.
