### ISSUE TITLE
UI Issue: Frames without borders (or modeline) blend between each other

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#324]
More than a bug, this is a report for a UI improvement.

To understand the issue, first open the list of open buffers (with` C-x C-b`) and then open the scratch buffer using `M-x  doom/open-scratch-buffer` (don't try using `SPC x`). The result will be that there are three windows, yet the bottom most window blends with the middle one. That is, it's difficult to distinguish where one window starts and ends.

This problem occurs in many scenarios. I don't use evil in general and have observed many windows blending with other windows in this manner.

How could we fix this? I have thought of two things:

1. Unfocused windows could change their background color. This would not solve the problem, however, if there are three or more blended windows (as only one of the three would be highlighted).
2. Add some type of border to popups or windows that do not have a modeline. I don't know if this can be easily done in emacs.

Have you experiences this issue @hlissner?

**Comment by hlissner** [comment]
I've noticed this issue myself. With the upcoming rewrite of the popup system, I've tried mitigating it by being more conservative about when popups are allowed to stack like that (if ever).

However, there _is_ one readily available fix:

```emacs-lisp
(setq-default window-divider-default-bottom-width 1)
```

In `core/core-ui.el`, this is set to `0`, mostly because it looks better in all but cases like these. It is exactly what you're asking for though.

>Unfocused windows could change their background color. 

Changing background colors are a messy business, especially when you have plugins like solaire-mode trying to do the same thing. I'd prefer to avoid that.

But perhaps there's a third option: don't hide the mode line in popups, as I do now.

```emacs-lisp
(remove-hook 'doom-popup-mode-hook #'doom|hide-modeline-in-popup)
```

**Comment by hlissner** [comment]
Now that the new popup system is done, I've found a new solution to this problem: defining a special modeline that doesn't have the `bar` segment (which is what gives modelines their artificial vertical padding), and using that exclusively popups. For example:

```emacs-lisp
(def-modeline! popup
  (matches " " buffer-info)
  (media-info major-mode))

(map-put +popup-default-parameters 'modeline 'popup)
```

Which produces something like ![this screenshot](https://i.snag.gy/oND0pP.jpg)

**Comment by hlissner** [comment]
With the new popup system, as well as `window-divider-default-bottom-width` now set to `1`, and a dark vertical-border between windows (in my doom-themes package) to improve contrast, I'll consider this issue resolved.
