### ISSUE TITLE
Change the leader keybinding based on the active mode.

### ISSUE THREAD

**Issue by senthilbaboo** [hlissner/doom-emacs#3246]
Based on the comment [here](https://github.com/hlissner/doom-emacs/issues/920#issuecomment-425654279), I guess we cannot have the same key (under leader) bound to different functions based on active mode.

For instance, I want to override `SPC g s` to display mercurial status using monky when in mercurial repo as opposed to using magit. As of now I am not finding any good way to achieve this. Similarly I want to invoke different build commands for `SPC c c` based on the active minor mode (like c++ or java).

I tried the suggestion linked in the above comment of using `:after` but it overrides the binding everywhere.

I don't like using localleader as it adds one more key press. What is the recommended way here? Thanks in advance!

**Comment by hlissner** [comment]
Your best bet is to rebind `SPC g s` to a dispatcher command that detects the type of repo you're in, then invokes the correct command. E.g.

```lisp
(map! :leader "g s" 
      (cmd! 
        (call-interactively
          (cond ((locate-dominating-file default-directory ".git")
                 #'magit-status)
                ((locate-dominating-file default-directory ".hg")
                 #'monkey)
                ((user-error "Not in a supported repo"))))))
```

Likewise for `SPC c c`. Otherwise, you could enable the `:tools taskrunner` module. This uses [taskrunner](https://github.com/emacs-taskrunner/emacs-taskrunner), which has customizable mode-specific build commands. I will eventually replace `SPC p c` and `SPC c c` with taskrunner, but haven't gotten around to it yet.

**Comment by senthilbaboo** [comment]
Thanks for the input.
