### ISSUE TITLE
org-goto (C-c C-j RET) is broken out of the box

### ISSUE THREAD

**Issue by werediver** [hlissner/doom-emacs#3254]
**What did you expect to happen?**

With a fresh installation of doom-emacs on emacs-plus on macOS in org-mode I expect `org-goto` C-c C-j RET to work (to perform a jump when RET is pressed).

**What actually happened?**

When I press C-c C-j I see the `org-goto` interface as expected, but neither RET nor C-m does anything. I cannot perform a jump.

**Additional details:**
- Use the default out-of-the-box configuration to reproduce
- Not reproducible via `emacs -Q` (or `-q`)
- There is either no warnings on screen or "buffer is not editable" depending on something I haven't quite figured out
- Can be worked around as described [here](https://github.com/abo-abo/swiper/issues/986#issuecomment-300482804) (**suggests a conflict with Ivy**)
  <details>
  <summary>The workaround quoted</summary>
  For `org-goto` to work nicely with Ivy, you also want to adjust `org-outline-path-complete-in-steps`.

  ```elisp
  (setq org-goto-interface 'outline-path-completion)
  (setq org-outline-path-complete-in-steps nil)
  ```
  </details>

**Steps to reproduce:**
1. Have a fresh doom-emacs install on emacs-plus on macOS with default configuration
2. Open an org-file with multiple headlines
3. Press C-c C-j to recall `org-goto` interface
4. Choose a place to jump to and press RET or C-m
5. Nothing happens; the only way to proceed is to cancel the jump by pressing C-g

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Nov 17, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 200fd52b6 2020-05-28 22:01:23 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.0.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64")
  (path "~/.platformio/penv/bin" "~/opt/anaconda3/bin" "~/bin" "~/.local/bin" "~/.emacs.d/bin" "~/.pub-cache/bin" "~/Library/Android/sdk/platform-tools/" "~/.rbenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "/Applications/Wireshark.app/Contents/MacOS" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
There are a few issues at work here.

1. Evil rebinds `RET` in normal mode.
2. When `org-goto-interface` is set to `'outline`, org-goto uses a regular org buffer so you can select the heading you want to go to. This buffer is in normal mode.
3. Ivy (counsel) provides a `counsel-org-goto` command, but `C-c C-j` specifically calls `org-goto` which has nothing to do with ivy until `org-goto-interface` is set to `'outline-path-completion`.

So either I remap `org-goto` to `counsel-org-goto` universally, or I default `org-goto-interface` to `'outline-path-completion`. I'm leaning toward the former, since the latter could break org-goto for non-ivy users.

**Comment by hlissner** [comment]
As of 8e34998 and 416f155 I've made three changes:

1. `RET` should behave correctly in `org-goto`'s buffer.
2. The `*Org Help*` buffer will now be treated as a popup, rather than consuming a whole window.
3. I've remapped `org-goto` to `counsel-org-goto` for ivy users.

This should resolve your issues. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
