### ISSUE TITLE
How to install term or vterm in win10?

### ISSUE THREAD

**Issue by HakunanMatatat** [hlissner/doom-emacs#3280]
hi,I install term or vterm in win10 but failed.The error as following.
term:spawning child process:Invalid argument.
vterm:your build of emacs lacks dynamic modules support and cannot load vterm.(I have installed vterm in win10.It still cannot be loaded.)
Thank you very much for your help.

**Comment by hlissner** [comment]
This should be asked [upstream](https://github.com/akermu/emacs-libvterm). Since its docs do not mention any instructions for Windows, and it only has [one issue open](https://github.com/akermu/emacs-libvterm/issues/12) about Windows support, it doesn't seem possible at the moment. Since it isn't a Doom issue, I will close this for now.

Eshell is an excellent alternative however; it's a platform-agnostic shell that will work anywhere you have access to Emacs.

**Comment by channyeintun** [comment]
"Your build of emacs lacks dynamic modules support and cannot load vterm", in Linux Mint.

**Comment by hlissner** [comment]
@channyeintun Your issue has nothing to do with this one. Please ask how to install Emacs with dynamic modules support on our Discord or /r/emacs.
