### ISSUE TITLE
Running emacsclientw.exe on windows can't attach to running emacs server

### ISSUE THREAD

**Issue by Whil-** [hlissner/doom-emacs#3324]
**What did you expect to happen?**
That after I've started doom-emacs in daemon-mode in windows with runemacs.exe --daemon, and after that run emacsclientw.exe -n -e "(raise-frame)", get a emacs started instantly, connected to the emacs deamon.

**What actually happened?**
A new emacs session is started when running the emacsclientw.exe command above.

Running on Windows-10, Emacs 27.0.91.

**Solution**
I think I've found a reason and possible solution... It seems the move of .emacs.d/server/ to .emacs.d/.local./cache/server is the culprit. When trying to attach to the daemon, emacs by default looks in .emacs.d/server/ for the address to it. Since that file doesn't exist in that location it fails to find the running emacs deamon.

One can work around it by specifying the full path to the server-file as an argument to emacsclientw.exe. Or by customizing server-auth-dir. But best would probably be to not hide the server folder in core/core.el to begin with! Since it disables the ability to use emacs in server mode.

**Comment by hlissner** [comment]
As of c2c81ec this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Whil-** [comment]
Can confirm that it's fixed, thank you.

**Comment by seanfarley** [comment]
The commit for this fix (which I won't argue against; probably never should have changed the default since it's assumed by so many projects) was a real hammer to the back of the head. So, thanks for that.

For those of us that worked around the original source of this issue by updating our own environment variables (i.e. `EMACS_SERVER_FILE`), we now had a bunch of stuff just straight up not working. That was bad enough, fixable, but still annoying. The real issue here is that doom caches the environment variables so the old `EMACS_SERVER_FILE` was still saved and processes launched within emacs would just fail for no obvious reason (any command calling `emacsclient` specifically). One cache, (usually more than) one bug.

The cherry on top is that you didn't even add the `server` to `gitignore` in this repo. It's just a nice reminder (along with your decision about discord) that this isn't a community project. It's Henrik's project. And we're just lucky enough to use it.

**Comment by hlissner** [comment]
> The cherry on top is that you didn't even add the server to gitignore in this repo

Sorry for failing to notice this until now. As of a78c397, `~/.emacs.d/server` is now git ignored.
