### ISSUE TITLE
It's be cool if Doom would add .projectile to .gitignores automatically.

### ISSUE THREAD

**Issue by olav35** [hlissner/doom-emacs#3363]
This is useful for nested projects / monorepos. For example I have this project https://github.com/olav35/fullstackopen-2020 which consists of (among other things) many React projects. I want to be able to visit each React project as their own project and therefore I added .projectile files to them. Then I have to add .projectile to .gitignore.

This is of course a very small improvement, but I can't see a situation where it would be problematic so I think it makes sense to add it.

Olav

**Comment by robbert-vdh** [comment]
I think in general it would be better practice to just globally ignore these kinds of environment or editor specific files since you'd probably never want to check them in anways. By default git's global excludes file is located at `~/.config/git/ignore` and it can be changed using the `core.excludesFile` setting. There's also a per-repository equivalent in `.git/config/exclude`. There's more info on this in the `gitignore` man page.

**Comment by hlissner** [comment]
I'll leave this up to the user to add to their global or local ignore files (see @robbert-vdh's suggestion), so I'll close this as a `nofix`. In line with Doom's "Your system, your rules" mantra, it is not Doom's responsibility to (automatically) configure things beyond Emacs. Thanks for the suggestion, in any case!
