### ISSUE TITLE
Are popups supposed to stack horizontally by default?

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#337]
### Observed behavior
In **develop** branch.
When opening multiple popups, e.g., view-lossage (C-h l) and view-echo-area-messages (C-h e), the two popups are open horizontally to each other. Is this expected behavior? 

![popups1](https://user-images.githubusercontent.com/6165006/34733739-bf87cbd6-f569-11e7-98f3-caffe51edbca.png)

### Expected behavior

I would've expected that the popups would stack vertically.

### Steps to reproduce

1. Open emacs
1. C-h l
2. C-h e

### System information

<details>
<summary>Click to expand</summary>

DOOM Doctor
Running Emacs v25.3.1, commit fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux OfficeZombie 4.14.10-1-ARCH #1 SMP PREEMPT Fri Dec 29 20:17:35
  UTC 2017 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 56a3c817789f1438aaac4a492c8c3ef551728d61

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

</details>

**Comment by hlissner** [comment]
This is the correct behavior of `display-buffer-in-side-window`. It is much more predictable (and controllable) than the previous implementation, but I agree, I'm not entirely sure if I like it either. I am looking into it.

**Comment by hlissner** [comment]
Alright, here is something to try (in the latest `develop`; don't forget`make autoloads`!):

```emacs-lisp
(remove-hook '+popup-display-buffer-actions 'display-buffer-in-side-window)
(add-hook '+popup-display-buffer-actions #'+popup-display-buffer t)
```

This enables an experimental display-buffer action that is closer to how `shackle` used to make popup windows. This behavior will allow popups to stack as you expect, but doesn't support `slot` yet, so there is no limit to how many popups can stack. Please give it a try and let me know if you come across any issues. I'll be testing it myself as I polish it.

**Comment by UndeadKernel** [comment]
This explains why I was not able to properly use the popup system to change how magit displays buffers. In particular, I was trying to show  \*magit-log\* next to the main \*magit\* window using the *slots* system.

With the new popup system, how would you configure magit to display to the right side and choose which magit windows should stack instead of replacing the main magit window? I have not been able to figure it out yet.

**Comment by hlissner** [comment]
Unfortunately, until I have implemented `slot` support into `+popup-display-buffer`, you can't achieve that level of control. With this system or the previous. 

+ With `display-buffer-in-side-window` you can control whether a new popup replaces the old (popups with the same `slot` replace each other), or gets its own window next to the first (different `slot`s), but you _can't_ control how they stack. In fact, magit is unusable with this, so you'll have to tell Doom to ignore it: `(set! :popup "^\\*magit" :ignore)`, which I just added support for.

+ With `+popup-display-buffer` buffers will stack, but you get no control over where and how. However, it works better with magit (albeit clunky). You'll need `(set! :popup "^\\*magit-diff" nil '((select)))` to make sure the diff buffer doesn't get focus instead of commit buffers.

  slot support for `+popup-display-buffer` will give 2-dimensional control over where popups go, but it may take me a while, so best `:ignore` magit and let it do its own thing.

**Comment by UndeadKernel** [comment]
Today I noticed a probably undesired side-effect of the **:ignore** popup flag:
When using the flag, an entry is added to **display-buffer-alist** that will take precedence over what a package might want to do with their buffers.

Take magit as an example. Without anything related to magit inside of **display-buffer-alist**, magit will open a small window on the bottom and manage its own windows. Contrast this behavior when the following code is used:
```lisp
(set! :popup "^\\*magit:*" :ignore).
```
An entry such as `("^\\*magit:*" nil)` will be added to **display-buffer-alist** and magit will start reusing windows instead of managing its own windows (by creating new ones).

I'm starting to see how managing "popups" in emacs is like entering the seventh ring of hell.

**Comment by fuxialexander** [comment]
@UndeadKernel For `magit`, I'm currently using the following settings and in my use cases i think it works fine. I'm not sure whether I missed something... 
```lisp
(after! magit
  (set! :popup "^\\*Magit" '((slot . -1) (side . right) (size . 80)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit.*popup\\*" '((slot . 0) (side . right)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit-revision:.*" '((slot . 0) (side . right) (window-height . 0.6)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit-diff:.*" '((slot . 0) (side . right) (window-height . 0.6)) '((modeline . nil) (select . nil)))
  (add-hook! 'magit-popup-mode-hook #'doom-hide-modeline-mode))
```

**Comment by UndeadKernel** [comment]
Thank you @fuxialexander.
I almost converged exactly to your solution: I ended up with something similar to what you have. However, I don't believe the **slot** variable is working yet.

**Comment by fuxialexander** [comment]
@UndeadKernel Well it's at least partially working, say if we change the `-1` in "^\\*Magit" rule to `0`, the magit-popup actually will replace the magit dashboard, while with a value of `-1` it actually doing well.
![image](https://user-images.githubusercontent.com/8258908/34836587-4b9977d0-f733-11e7-9618-b254635d3611.png)

Something I cannot make work is that when I have both the dashboard and a revision panel split vertically at the right side, calling the popup dispatch will actually make it appear in the middle rather than bottom, even I change the slot setting to:
```lisp
(after! magit
  (set! :popup "^\\*Magit" '((slot . -1) (side . right) (size . 80)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit.*popup\\*" '((slot . 1) (side . right)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit-revision:.*" '((slot . 0) (side . right) (window-height . 0.6)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit-diff:.*" '((slot . 0) (side . right) (window-height . 0.6)) '((modeline . nil) (select . nil)))
  (add-hook! 'magit-popup-mode-hook #'doom-hide-modeline-mode))
```
![image](https://user-images.githubusercontent.com/8258908/34836690-a0f65310-f733-11e7-837f-0b492cda4c68.png)

**Comment by hlissner** [comment]
> Today I noticed a probably undesired side-effect of the :ignore popup flag:
> When using the flag, an entry is added to display-buffer-alist that will take precedence over what a package might want to do with their buffers.

@UndeadKernel After more testing, this doesn't seem to be true. Yes, the new magit entry takes precedence, but since its cdr is nil, `display-buffer` should fall back to other defaults. To quote its documentation:

> The ‘display-buffer’ function builds a function list and an alist by combining the functions and alists specified in ‘display-buffer-overriding-action’, ‘display-buffer-alist’, the ACTION argument, ‘display-buffer-base-action’, and ‘display-buffer-fallback-action’ (in order).  Then it calls each function in the combined function list in turn, passing the buffer as the first argument and the combined alist as the second argument, until one of the functions returns non-nil.

When I use `(set! :popup "^\\*magit" :ignore)`, magit manages its windows just fine to me, on 25.3, 26.1 and 27.0. In fact, [this rule is already in `feature/version-control`](https://github.com/hlissner/doom-emacs/blob/develop/modules/feature/version-control/+git.el#L84). Could you double check this?

---

@UndeadKernel @fuxialexander I added a `vslot` parameter as well, which controls vertical popup positioning (or horizontal for popups on the left/right), while `slot` will always control lateral positioning. Perhaps that can help?

**Comment by fuxialexander** [comment]
@hlissner Yes the vslot works fine. And actually the appearance of dispatch popup in the middle is not the fault of `slot`, the popup just alway appear below the main panel.

![image](https://user-images.githubusercontent.com/8258908/34925169-972eae16-f9e2-11e7-87ce-24b045660d28.png)

**Comment by hlissner** [comment]
With the introduction of `vslot`, I think I can consider this issue resolved. It needs some good documentation, probably with visual aids.

In any case, I _might_ revisit this later to make vslot a little more robust, but it should do for now.
