### ISSUE TITLE
Specific Instructions for Powershell Users.

### ISSUE THREAD

**Issue by crawftv** [hlissner/doom-emacs#3400]
**What did you expect to happen?**
...
I expected this to work when using powershell and windows
```
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

**What actually happened?**
...
The installation went to wrong place.

**Solution
...
```
git clone https://github.com/hlissner/doom-emacs /.emacs.d
/.emacs.d/bin/doom install
```

**Comment by hlissner** [comment]
This seems like a local issue. 

1. Powershell understands `~` afaik, to mean the user's home directory. This is where Doom should be installed.
2. An absolute path starting with `/` equates to the root of one of your drives -- this may work, but isn't recommended (folks shouldn't be installing Doom to the root of your drive, unless you know what you're doing),
3. That it is cloned somewhere you consider "wrong" seems like an issue with powershell, the local value of `HOME` in your environment variables, or your expectations for where you want Doom installed (just a guess, since you didn't clarify where you wanted it and where it ended up). 

I'll close this, as this doesn't appear to be a Doom issue.
