### ISSUE TITLE
 icons  broken

### ISSUE THREAD

**Issue by kecode** [hlissner/doom-emacs#3417]
doom install 
![image](https://user-images.githubusercontent.com/23140388/85145542-4a939c80-b27f-11ea-94b5-caa6dc49239b.png)

**Comment by hlissner** [comment]
There is too little information to diagnose the issue. Please include the output of `~/.emacs.d/bin/doom info`. If you can't, then include what commit of Doom you're on. At first glance this seems like a connection issue, rather than a Doom issue, which I can't do anything about (Do you live/work somewhere where your ISP has blocked githubusercontent.com? Are you using a proxy?)

What's more, Doom doesn't install anything from raw.githubusercontent.com anymore (it used to, some months ago), so perhaps you've cloned an old version of Doom, somehow?

Can you provide any more information?

**Comment by kecode** [comment]
Thank you very much for your answer. Yes, I use the proxy. I can visit Google. In the browser, I can visit“ raw.githubusercontent.com ”.  at doom, I don't know where to set up the proxy. I tried, but I failed.

**Comment by kecode** [comment]
My operating system is windows 10
