### ISSUE TITLE
org-contrib-plus does not install correctlly 

### ISSUE THREAD

**Issue by OrionRandD** [hlissner/doom-emacs#3489]
I have this in my packages.el
(package! org-plus-contrib)

This in my config.el
 (use-package! org-plus-contrib)
 
And have installed it with 
list-packages

And doom sync
But, when I open Emacs, it complains with this error

Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-plus-contrib)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

Why? Everything seems to be right.

I need to install:

org-eww
and 
org-w3m 
for this function to work:

http://www.bobnewell.net/publish/35years/webclipper.html

My doom is:
Doom v2.0.9 (00ebbafb96980e99d96ed73d46fbf8c93af3ba5d)
Emacs v26.3
Branch: develop
Build date: 2020-06-25 15:27:26 -0400

**Comment by hlissner** [comment]
There are three issues here.

> Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-plus-contrib)

That's because the package is only called `org-plus-contrib`, but there is no library files named `org-plus-contrib`. It's `org` that you want.

> And have installed it with list-packages

`list-packages` lists packages installed with Emacs' built-in package manager, `package.el`, but Doom doesn't use `package.el`, it uses [straight.el](https://github.com/raxod502/straight.el).

Straight does not have a `list-packages` command, but Doom does have `doom/help-packages` (on `SPC h p` / `C-h p`). This lists all available package recipes, not just installed ones.

> (package! org-plus-contrib)

Doom's `:lang org` module [already installs org-plus-contrib for you](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el#L26-L30), but from a mirror. There is no need to install it yourself, but if you don't want to deal with the module then install it from the mirror than from org-plus-contrib directly and make sure `:lang org` isn't enabled.

---

Since this isn't really an issue with Doom I will close this. Feel free to follow up here if you have more questions.
