### ISSUE TITLE
Add `vimrc-mode` (or similar) for syntax highlighting on `.vim` files.

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3506]
**Describe the feature**
  - This seems fitting for a project centered around Vim emulation, maybe even as a default on `:editor (evil)`. There are probably many people editing `.vim` files on Emacs. Merely adding [vimrc-mode](https://github.com/mcandre/vimrc-mode) and making sure it's active for `.vim` files will suffice. Extra features such as indentation, completion, and syntax checking would also be nice—but that's not a hard requirement.

**System information**
- Irrelevant.

**Comment by hlissner** [comment]
I like the sentiment, but I choose not to include `vimrc-mode` primarily because it only needs a single line of configuration (a `(package! vimrc-mode)` in `~/.doom.d/packages.el` and you're good to go). This is too trivial to warrant a whole module. It also isn't a good candidate for Doom core because this is Emacs; editing vimscript is entirely avoidable -- I'm hardpressed to consider support for it a reasonable default.

Perhaps if an ecosystem of vimrc plugins were to emerge, to provide any of those extra features you mentioned, I'll reconsider, but for now I leave it to users to set up themselves.
