### ISSUE TITLE
How to integrate slight changes in the upstream packages?

### ISSUE THREAD

**Issue by zenny** [hlissner/doom-emacs#3524]
Hi,

I am trying to use org-ref package in Doom-emacs, but with a slight modifications in the upstream code. When I specify `(package! org-ref)`  in `~/.doom.d/package.el`, it directly pulls the package from upstream which does not reflect the changes I intend to make. 

Unlike in Scimax, I could not figure out the location of the byte-compiled source code inside `.emacs.d/` as well as `.doom.d` folders so that I can make my changes directly.

Did I miss something?

Cheers, and stay safe,
/z

**Comment by wedens** [comment]
You can fork it and use the fork. See https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#installing-packages-from-external-sources.

Alternatively, you can use [el-patch](https://github.com/raxod502/el-patch) to modify the package.

**Comment by hlissner** [comment]
Wedens method will work, but it makes it a little hard to iterate on, because you have to keep re-compiling the package (running `doom sync`) every time you make a change for it to be reflcted. Here are two suggestions:

1. What wedens suggested, forking the project and installing the fork:

   ```elisp
   (package! org-ref :recipe (:host github :repo "zenny/org-ref" :no-byte-compile t))
   ```

   _But_ I added `:no-byte-compile t` to the recipe. This way you can modify the package files without bothering to `doom sync` all the time.

2. Install the package from a local directory:

   ```elisp
   (package! org-ref (:local-repo "~/projects/org-ref" :no-byte-compile t))
   ```

   Again, remember to `:no-byte-compile t` to save yourself that hassle.

You may need to specify `:files` if you need more than the top-level `*.el` files in a package.

----

> Unlike in Scimax, I could not figure out the location of the byte-compiled source code inside .emacs.d/ as well as .doom.d folders so that I can make my changes directly.

For posterity, packages are cloned to `~/.emacs.d/.local/straight/repos/` and then "built" to `~/.emacs.d/.local/straight/build/`. Building means symlinking the *.el files then byte-compiling them. You can quickly access a package's files by pressing `SPC h P` then searching for the package by name. E.g. `SPC h P org-ref` should open `~/.emacs.d/.local/straights/repos/org.ref.el`.

Hope that helps!
