### ISSUE TITLE
Inconsistent startup benchmark time

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#353]
### Observed behavior

When DOOM emacs starts, it displays a small benchmark stating how much time was spent during initializatipon. If running emacs directly, the result is different than when running emacs using `make run`. 

### Expected behavior

Shouldn't the benchmark report the same time regardless of these commands?
1. `emacs`
2. `make run` (`emacs -q -l init.el)

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.1, commit e571060063234b126d74670b36b0a5d13a26f9b5

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux OfficeZombie 4.14.10-1-ARCH #1 SMP PREEMPT Fri Dec 29 20:17:35
  UTC 2017 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision e571060063234b126d74670b36b0a5d13a26f9b5

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by hlissner** [comment]
This happens because I use `after-init-time` and `before-init-time` to do the calculation. These are wrong when you load `init.el` _after_ initialization, as is the case with `emacs -q -l init.el`.

So I've changed it to grab the current time as soon as it displays the benchmark. This makes benchmarks for `make run` much more accurate, but the extra overhead of loading init.el post-init will likely add another 40-70% to the runtime.

I could solve this by simply wrapping the doom config in my own benchmark, but it would reduce overall accuracy, and I'm not sure I'd like to do that.

Give it a try and let me know if it's acceptable.

**Comment by UndeadKernel** [comment]
The fix is working as expected.

Out of curiosity. What's your startup time? Mein would be:
1. No complication   - ~1.4s
2. With Compilation - ~1.2s

**Comment by hlissner** [comment]
On average, aboot this fast:

|            | desktop (beefy i7 w/ ssd's; Arch)  |  old toaster (2009 Core-2 Duo macbook pro) |
|----------|-------|------|
| No compile | ~0.97s | ~3.64s |
| `make compile-core` | ~0.79s | ~2.88s |
| `make compile` | ~0.71s | ~2.7s |

So far, it seems, you get most of the benefit from:

```sh
make compile-core      # compiles core/* and init.el
make compile-feature   # compiles feature/* modules
```
