### ISSUE TITLE
Set fonts based on the language

### ISSUE THREAD

**Issue by avronr** [hlissner/doom-emacs#3622]
**Ability to automatically change font when switching to a different language**
- It would be great if we could set a font that will be used when the buffer we use has a different language.

**Comment by wedens** [comment]
What if a buffer has multiple languages? What if there are multiple buffers with different languages? Fonts in emacs are set per-frame, not per-buffer.

**Comment by hlissner** [comment]
> It would be great if we could set a font that will be used when the buffer we use has a different language.

Buffer-local fonts could be pulled off with careful application of face-remap (to apply a font on a per-buffer basis). This could interfere with plugins that use face-remap, however, like solaire-mode, mixed-pitch-mode and variable-pitch-mode.

Alternatively, you could add a hook to `input-method-activate-hook` to call `set-frame-font` when a certain input method is detected:

```elisp
(add-hook! 'input-method-activate-hook
  (pcase current-input-method
    ("welsh"
     (set-frame-font (font-spec :family "Hack" :size 13)))
    ("ucs"
     (set-frame-font (font-spec :family "Fira Code" :size 15)))
    ...))
```

You could also use `set-fontset-font` to remap certain character sections of a font to other fonts.

---

In any case, this seems like too broad a request for Doom with too vague a concept or purpose (beyond my expertise, anyway). I think it'd make a good, independent Emacs plugin, since it has little to do with Doom Emacs, in particular.
