### ISSUE TITLE
How do I check a shortcut for a function?

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#363]
As the question states.

**Comment by hlissner** [comment]
I'm afraid I don't understand the question. What do you mean by "check"? And by "shortcut for a function" do you mean an alias?

**Comment by fuxialexander** [comment]
@andyafter I think by default `counsel-M-x` list the keybinding for function.
![image](https://user-images.githubusercontent.com/8258908/35037013-0e75581a-fbb1-11e7-83e3-57497181b63e.png)

If you mean check what function a key is assigned to, use `describe-key` or `helpful-key` (if you have `helpful` installed).

**Comment by andyafter** [comment]
@fuxialexander @hlissner the picture above is what I have been using. Ok problem is that most of the key bindings is now shown in the drop down list. Here is an example:

![screen shot 2018-01-18 at 11 13 00 am](https://user-images.githubusercontent.com/3354145/35079141-a2a9dbb6-fc40-11e7-914d-db36c86c3b02.png)

In the picture expand region does not have any bindings shown. 

But turns out expand region is already bind to "v". Is there anywhere we can go to check the key binding of a function?

**Comment by fuxialexander** [comment]
@andyafter It's not missing keybindings. What happened here is because keybindings have "states" (or domains if you like) which are called `keymaps`. For example if you first press `v`, then `M-x expand`, you will find that the bindings is shown.
![image](https://user-images.githubusercontent.com/8258908/35079578-6c44cab0-fc43-11e7-8f68-31a2bf00aa35.png)

That's because by default you are in `evil-normal-state-map`, and a press of `v` lead you to `evil-visual-state-map`, where `er/expand-region` is bind to `v`.

If you have a specific function that you would like to look after, another one possible (although tedious) way is grep/ag/rg the `.emacs.d` config, especially the user-defined `+bindings.el` file and the package file which provide that function.
If you do not have specific function to look after, maybe you can just `descirbe-keymap`

Still, I think the most simple way is to let `M-x` to tell you when you have a function in mind.

**Comment by andyafter** [comment]
Actually I have been reading +bindings.el for a while and most of the time I have specific function name in mind. Do you think it would be a good idea to just put the keybinding in the function description mode? Or at least the key map information?

**Comment by hlissner** [comment]
I think the best way to address this is to incorporate [helpful](https://github.com/Wilfred/helpful), which provides a superior alternative to `describe-*` commands. `M-x helpful-callable RET er/expand-region` will list all its keybinds, even in evil keymaps. Its predecessors cannot.

I've been meaning to do this anyhow. I'll keep you posted.

**Comment by fuxialexander** [comment]
@hlissner I wasn't aware that helpful-callable actually list the map and keybindings! Thanks for the information!

Not sure whether it will be helpful or not, but here are my current immature `helpful` config:
```elisp
(def-package! helpful
  :commands (helpful-callable
             helpful-function
             helpful-variable
             helpful-macro
             helpful-symbol
             helpful-command
             helpful-key
             helpful-at-point)
  :init
  (set! :popup "^\\*helpful.*"
    '((size . 80) (side . right))
    '((transient . nil) (select . t) (quit . t)))
  (setq counsel-describe-function-function 'helpful-callable
        counsel-describe-variable-function 'helpful-variable))
```

**Comment by igorvolnyi** [comment]
I think there should be a dedicated wiki page about doom-emacs key bindings and their corresponding vanilla emacs counterparts.

**Comment by hlissner** [comment]
And done. helpful is now in `develop`. You can try `SPC h f er/expand-region RET`, which will open a *helpful* buffer with a list of keybindings, among other things. In this case: `evil-visual-state-map v`. I hope that makes it easier to hunt down keybinds.

@fuxialexander Thanks for the config, it was a big help!

@igorvolnyi I hear you. The documentation needs a _lot_ of work. Starting with a README.org file for `private/default`, with some insight into the keybinding scheme. After 2.1 is out I'll focus a little more on that. Although, I'm not sure how well I can cover vanilla keybinds, as I don't use them (and never have), being a staunch evil-mode user.
