### ISSUE TITLE
How to config python-mode complete with company-files and company-yasnippet

### ISSUE THREAD

**Issue by lengyueyang** [hlissner/doom-emacs#3631]
Set company backend in org-mode is OK as below, 

```elisp
(set-company-backend! '(text-mode
                        markdown-mode
                        gfm-mode
                        org-mode)
  '(:seperate company-ispell
              company-files
              company-yasnippet))
```

In python-mode below config

```elisp
(set-company-backend! '(python-mode)
  '(:separate company-capf
              company-files
              company-yasnippet
              ))
(setq python-shell-interpreter-args "--simple-prompt -i")
```

is not work

**Comment by hlissner** [comment]
It works for markdown and org because there is no default backend set for them.

Python _does_ have a default. To overwrite a default you need to wrap your config in `(after! PACKAGE ...)`. e.g.

```lisp
(after! python
  (set-company-backend! '(python-mode)
    '(:separate company-capf
                company-files
                company-yasnippet
                )))
```

In the future please ask usage and config questions on [our Discord](https://discord.gg/qvGgnVx) as Doom's issue tracker is no longer the place for them. This will be deleted shortly after some inactivity.

**Comment by lengyueyang** [comment]
thanks very much
