### ISSUE TITLE
Doom-emacs ignores files and current directory when launched from command line

### ISSUE THREAD

**Issue by igorvolnyi** [hlissner/doom-emacs#371]
When I launch (doom-)emacs from command line being in some directory, for instance:
$ cd ~/tmp/emacs
$ emacs test.el
emacs ignores both the directory (:!pwd gives ~/.emacs.d/) and the file (instead I see splash screen with the start menu).
I understand that doom-emacs is a very "opinionated" guy, but... Don't you think that violating even the man page is a bit too much?

**Comment by UndeadKernel** [comment]
Hi @igorvolnyi.
I'm using the develop branch and I do not see this behavior you describe.
Could you try and see if this issue of yours is also present in the **develop** branch?

**Comment by igorvolnyi** [comment]
Yup. Develop branch has this issue solved.
Maybe it's worth to commit bug fixes to master more frequently so issues do not stay unresolved so long?

**Comment by hlissner** [comment]
I hear you. I already intend to adopt a more frequent minor release cycle after 2.1, but what Doom would really benefit from is a more disciplined commit workflow that I've had swimming around in my head, but never entirely committed to. I'll work on that!

In any case, I'll leave this open once the fix is in `master`.
