### ISSUE TITLE
"revert-buffer" in dired is counterintuitive 

### ISSUE THREAD

**Issue by egils-consulting** [hlissner/doom-emacs#3714]
Hi
I searched today for dired-refresh or dired-reload but found nothing. Also did not find dired-revert. I finally had to google to find out how to "revert" the buffer in emacs speak. I suggest adding one or all of the above aliases to revert-buffer (when visiting a dired-buffer).
Thanks for making doom-emacs. Its totally awesome ❤

**Comment by hlissner** [comment]
Hi! Thanks for the suggestion and kind words.

Re:revert-buffer, I don't agree that this is a problem. Perhaps it could be made more obvious, but polluting the symbol table with `PLUGIN-revert` aliases is not a great solution. In fact, I think `revert-buffer` (and its effect on dired) is sufficiently covered by the Emacs manual [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired-Updating.html) and/or [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Reverting.html). It's also mentioned in `revert-buffer`'s documentation (see `C-h f revert-buffer` or `SPC h f revert-buffer`):

> This command also implements an interface for special buffers
> that contain text that doesn't come from a file, but reflects
> some other data instead (e.g. Dired buffers, buffer-list
> buffers).  This is done via the variable revert-buffer-function.
> In these cases, it should reconstruct the buffer contents from the
> appropriate data.

Plus, searching the `M-x` menu for `revert` should yield `revert-buffer` among the top 3-5 results -- aliases would make this more difficult.

I think this is more a documentation problem rather than a UX one, and is better suited to the Emacs mailing list (for dired's developer) rather than Doom.

----

Side note: in the future please include your `M-x doom/info` in all bug reports. Even if they are consecutive bug reports.
