### ISSUE TITLE
No Slack or Gitter Channel in this repo

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#373]
I think we should have one.

**Comment by hlissner** [comment]
How about Discord? I already run a couple servers and am most available on it.

**Comment by andyafter** [comment]
yeah that should also be cool!!!

**Comment by amosbird** [comment]
Please also consider setting up an IRC channel :)

**Comment by ocharles** [comment]
Please use one or the other. I actually don't see a need for any channel
personally, and just watch this repo - but the last thing I want is
communication spread over 3 channels.

**Comment by UndeadKernel** [comment]
I think having a Discord would be great for the development of Doom.
There are many questions that I haven't asked because I don't believe they deserve an "Issue".
With a DIscord, people could with similar package interests can coordinate to create or extend them. You are not alone Mr. @hlissner .

**Comment by hlissner** [comment]
Alright, Discord it is: https://discord.gg/bcZ6P3y Hop on and say hi!

I'll add a badge to the project readme soon. I'll leave this open until I have (and it's in `master`).

@amosbird Sorry, I like IRC, but Discord is a much more attractive option to me, and (to parrot @ocharles) I'd like comms split up as little as possible.

**Comment by amosbird** [comment]
That's fine. Discord seems a decent option :)

**Comment by smythp** [comment]
Just want to throw in that Discord isn't currently accessible to people with disabilities.

**Comment by hlissner** [comment]
@smythp That sucks. Is that also true for Discord's web UI or is it just an issue for the desktop apps/Electron?

**Comment by smythp** [comment]
Yes, unfortunately.. I could probably pull something together for myself using Emacs and the Discord API, but in practice it probably wouldn't help anyone else and I only have so much patience for weekend hacks for random proprietary chat applications that pop up every 18 months. Got Slack working for myself in Emacs last year and from my perspective (not caring about green and purple color schemes), it's just a poorly-engineered IRC. Admittedly sighted non-developers seem to like these services.

Hate to be a total wet blanket here, I don't blame you if you move ahead with Discord. But if you're wavering between IRC and Discord, maybe it's a data point for you. If you do use Discord, you can help out by pulling on any levers you have to get them to make the app accessible. Tweet at them, especially if you use Discord at your day job. It should be accessible by US law, but the way these things work it'll probably be 3 or 4 years before they feel enough regulatory pressure to actually fix things.

If it's been a few years since you've used IRC and it seems like a dinosaur to you, check out IRCCloud. I've been hearing good things about it and it doesn't shut anyone out.

https://www.irccloud.com/

Thanks, keep up the good work on a cool project!

**Comment by hlissner** [comment]
@smythp I'm sorry to hear that. I wasn't aware the situation was that bad for Discord. I'm no stranger to web development, but I am to Electron and screen readers. I'm shocked to hear Discord hasn't factored in accessible design into their web client, at least.

However, I have chosen Discord. I do prefer irc, personally, as a weirdo that lives in the shell, but a Discord server is much easier to deal with as an administrator, and the barrier of entry is lower for users. Not to mention I already use it extensively for friends, family and work; which guarantees my availability -- my highest priority selecting a platform for Doom.

> Hate to be a total wet blanket here, I don't blame you if you move ahead with Discord.

Not at all. I sympathize. Judging from [the timestamp on this feature request](https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/17458522-screen-reader-accessibility) and [responses to this reddit post](https://www.reddit.com/r/discordapp/comments/69dsbt/a_community_closed_off_from_discord/), it certainly does seem neglected. I'll do some more research and see what I can do to add my voice to the mix.

**Comment by smythp** [comment]
Yes, it's surprising that they can't invest the relatively small amount of
effort into making their web app accessible. The reality is, they don't
have to, or at least not yet. I can't blame you (too much) for choosing
Discord as it's ultimately their responsibility to make their platform
accessible. Thanks, looking forward to reading more about Doom in the
future.

**Comment by hlissner** [comment]
Sorry for following up so late, but I've made our discord badge a lot larger (and placed it at the top of the readme). The upcoming FAQ will also have a couple links to it as well. I think it is visible enough now to consider this resolved.

**Comment by chee** [comment]
really disappointing response, "it's easier for me to administrate so i'm going to exclude people with disabilities from the conversation"

**Comment by hlissner** [comment]
Since https://github.com/hlissner/doom-emacs/issues/3589#issuecomment-660712035, I've been planning a [Discourse](https://www.discourse.org/) for Doom Emacs. I updated [this entry in the FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#is-discord-the-only-option-for-interacting-with-your-community) last month to reflect that. This should be a more inclusive platform.

> really disappointing response, "it's easier for me to administrate so i'm going to exclude people with disabilities from the conversation"

@chee I'm really sorry that that is how it turned out, but please don't twist my words. Its disingenuous to pretend that I owe you something, or that I'm _simply_ pursuing convenience to spite you. Doom is a one man show and that one man has to make concessions to keep his workload from spiraling beyond his control. I offer Doom and my support for free, out of my spare time, with no guarantee of availability.

_But_ it won't stop me from trying. I've learnt a great deal working on Doom and it's a blast. Its users have been understanding and supportive, even when they are critical.

Not to say the project has no issues. It has plenty, in and outside its code -- inaccessility is one of them-- but I'm working through them as fast a solo dev with a day job can manage. Consider contributing [code or some coffee](https://github.com/hlissner/doom-emacs#contribute). It will go a long way to help me allocate more hours to Doom.
