### ISSUE TITLE
How can I change key binding 'M-,'

### ISSUE THREAD

**Issue by JaewonHur** [hlissner/doom-emacs#3745]
Hi, I'm newbie to emacs and also doom emacs.

I wanna change the key binding of `M-,`
from `better-jumper-jump-backward` to `xref-pop-marker-stack`.

I did some research and found the similar issue. https://github.com/hlissner/doom-emacs/issues/1364#issue-437519668
So I did as like the answer 
`(evil-define-key* 'insert general-override-mode-map "\M-," #'xref-pop-marker-stack)`

But it doesn't work.

Is there any way?

**Comment by hlissner** [comment]
`xref-pop-marker-stack` is [remapped to `better-jumper-jump-backward`](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L319-L321) because better-jumper does the same thing, but better. I don't recommend you bind it.

But if you must, you must un-remap it:

```elisp
(map! [remap xref-pop-marker-stack] nil)
```

In the future, please divert usage and configuration questions [to our Discord](https://discord.gg/qvGgnVx). Our issue tracker is not the place for these questions. Thanks!
