### ISSUE TITLE
Crashes in terminal using emacsclient

### ISSUE THREAD

**Issue by TimWSpence** [hlissner/doom-emacs#3749]
```
 emacs --daemon=/tmp/term-emacs.sock > /tmp/log 2>&1
#followed by
 emacsclient -s /tmp/term-emacs.sock
```

gives me a frozen emacs screen for a few seconds and then it just crashes and kills the server and seemingly corrupts mu shell so I have to run `reset` or the output of future commands looks a bit crazy with lots of random whitespace. 
The only thing I saw in /tmp/log is:
[Treemacs] Warning: couldn’t find hl-line-mode’s background color for icons, falling back on unspecified-bg.
Starting Emacs daemon.

Sorry, I'm not sure how to debug emacs crashes or get more output. Very happy to provide any more info if you tell me what to run!

**Comment by TimWSpence** [comment]
Actually, this might not be doom/treemacs related. I also tried
```
emacs -Q --daemon=/tmp/term-emacs.sock 
# followed by
emacsclient -s /tmp/term-emacs.sock
```
If my understanding is correct, the `-Q` bypasses all my emacs config (including doom)? In which case I guess it's related to the 27 upgrade

**Comment by hlissner** [comment]
> If my understanding is correct, the -Q bypasses all my emacs config (including doom)? 

That is correct. `-Q` means Doom isn't being loaded. I've never seen this issue so I'm afraid I can't offer any insight into it. 

I'll close this for now, since this isn't a Doom issue. I'd recommend asking about it on [our Discord](https://discord.gg/qvGgnVx). Perhaps someone else has experienced it before.

-----

Side note: in the future, please follow the issue template. It asks you to include the output of `M-x doom/info` or `~/.emacs.d/bin/doom info`. Without it I have very little to go on if I can't recognize the issue at first glance (which happens rarely). At the very least, it'll tell me what OS you're on.
