### ISSUE TITLE
How do I install a local package (clarification on the instructions)?

### ISSUE THREAD

**Issue by klorax** [hlissner/doom-emacs#3842]
I have tried to get [this package](https://github.com/naokiri/subtitle-mode/blob/master/subtitle-mode.el) to work as described in the [getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#usingloading-local-packages).

I have tried different methods described and gotten it to build successfully during `doom sync`, but it is never available in Emacs. For example, these attempts in `packages.el` (package in `doom-private-dir/subtitle-mode/subtitle-mode.el`):

``` elisp
(use-package subtitle-mode
  :load-path (lambda () (concat doom-private-dir "subtitle-mode")))
```

or (package at different locations):

``` elisp
(package! subtitle-mode :recipe (:local-repo "subtitle-mode"))
```

The only thing that has worked is to place the first one in `config.el`, but that is in conflict with the described way. So what am I doing incorrectly, and what is the canonical way to install a simple local packages like this?

**Comment by gagbo** [comment]
You should use the Discord for that, it's probably getting closed soon.

With that being said
```lisp
;; in doom-private-dir/packages.el
(package! subtitle-mode :recipe (:local-repo "subtitle-mode"))
;; in doom-private-dir/config.el
(use-package subtitle-mode)
```
and then doom sync.

You can also tell straight to fetch directly from github : `(package! subtitle-mode :recipe (:host github :repo "naokiri/subtitle-mode"))`

**Comment by klorax** [comment]
Yes, I saw that message when opening this, **_sorry to everyone offended by that!_** I hoped that, since I would claim that the documentation could be clearer, that this might be allowed (in addition to the fact that I do not use Discord). :smiley:

I am unable to test this right now, but will do, and report back, but I already have two follow up questions (not answered in the documentation):

1. Where is this directory `subtitle-mode` (containing `subtile-mode.el`) supposed to be located?
2. In the documentation, I get the impression that **either** you use `(use-package my-package :load-path "/path/to/my/package")` (without `!`) **or** `(package! my-package :recipe (:local-repo "/path/to/my/package"))` (with `!`)?

I have been using `use-package` for several years to get and install packages, but my elisp skills are still to low to understand all subtle differences between `package`, `use-package` (with or without `!` --- I understand of course to avoid `:ensure t` in Doom). I was under the impression that I used them in `packages.el` and then `(after! my-package)` (or some other appropriate term other than `use-package`) in `config.el`.

Thanks for your help!

**Comment by gagbo** [comment]
`package!` is specific to doom (it registers the package so that subsequent `doom sync` fetch and builds the package). It does the downloading, and only downloading following the recipe in the macro

`use-package` configures the package, optionally including downloading the package.
- `:ensure t` is used to download the package if not found in the system. Never use that with Doom (because package fetching is handled "offline")
- `:local-repo` is used to point to a manual, local copy of the repository. If you use that you don't need the `package!` statement because there is no downloading to do (and `package!` is a doom specific macro that only handles downloading). Since this handles downloading, the `package!` macro has been adapted to handle that as well and it's better for our case to use it from `package!`
- Otherwise. the `:mode`, `:commands`… sections are used to configure the package like in use-package doc. Those are necessary to load the package in emacs once it's downloaded

When using `:local-repo` (which is a valid kw both for `package!`), the path should be a relative path (from doom-private-dir) to the repo you manually cloned

**Comment by hlissner** [comment]
> Where is this directory subtitle-mode (containing subtile-mode.el) supposed to be located?

It checks `~/.emacs.d/.local/straight/repos/$LOCAL-PATH`, then `~/.doom.d/$LOCAL_PATH`, and uses the first one that exists.

> use-package :local-repo

To clarify, `use-package` does not have a `:local-repo` property. Perhaps gagbo meant `:load-path`?

> In the documentation, I get the impression that either you use (use-package my-package :load-path "/path/to/my/package") (without !) or (package! my-package :recipe (:local-repo "/path/to/my/package")) (with !)?

Emacs has a `load-path`. This contains a list of directories for Emacs to look in when you load an elisp file. e.g. `(require 'magit)` will search for a `magit.el` in all the directories of `load-path` until it finds one.

use-package's `:load-path` property adds a directory to `load-path`.

`package!` tells Doom what packages to install and where from, which it will later add to `load-path`.

The former is very simple. The latter is a fully fledged package (because there's more to installing a package that just adding it to `load-path`, such as indexing autoloads and byte-compilation). If you don't know the difference, then the latter is the better option (fewer surprises). I'll make this clearer in the documentation.

----

As an example:

1. Clone subtitle-mode to `~/.doom.d/lisp/subtitle-mode`
2. Add this to `~/.doom.d/packages.el`:

  ```elisp
  (package! subtitle-mode 
    :recipe (:local-repo "subtitle-mode" :no-byte-compile t))
  ```
3. Run `doom sync`
4. Restart Emacs

And you should be good to go.

Note: with `:no-byte-compile t`, you don't have to run `doom sync` every time you make a change to the package.

Hope that helps!

**Comment by gagbo** [comment]
> To clarify, use-package does not have a :local-repo property. Perhaps gagbo meant :load-path?
I keep mixing up stuff

**Comment by klorax** [comment]
Took a while before I could get back to testing this.

Thanks for the clarification and for updating the documentation @hlissner!

**Comment by oatmealm** [comment]
@hlissner  Is it possible to prefer the local version to the official one? i.e. If I want to test a local version while leaving doom's configuration and module flags as is.

This does not seem to work:
```
(package! org-roam :disable t)
(package! org-roam
  :recipe (:local-repo "lisp/org-roam" :no-byte-compile t))
```
