### ISSUE TITLE
emacs freeze when hitting keys during "help popup" shows on macos

### ISSUE THREAD

**Issue by merrickluo** [hlissner/doom-emacs#3862]
**What did you expect to happen?**
emacs won't freeze

**What actually happened?**
emacs freezes and needs to be killed.

**Additional details:**
Although I can't reproduce this every time, this happens quite frequently recently, whenever I hit keys fast when the "help popup" (or "space menu") is about to show up, emacs freezes. It only happens on mac and mine is built from source with patches from emacs-mac.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1495875/91540929-1c50ce00-e94e-11ea-82b6-eb54f73d93bd.png">

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. hit a prefix key
1. hit another key very fast

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin18.6.0")
  (shell . "/opt/local/bin/fish")
  (uname . "Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64")
  (path "~/.rbenv/shims" "~/Projects/go/bin" "~/.asdf/shims" "~/.asdf/bin" "~/.emacs.d/bin" "~/.cargo/bin" "~/.bin" "/usr/local/opt/sqlite/bin" "/opt/local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/local/libexec/emacs/27.1.50/x86_64-apple-darwin18.6.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1.50")
  (build . "Aug 25, 2020")
  (buildopts . "--prefix=/opt/local --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/opt/local/share/emacs/site-lisp --with-xml2 --with-gnutls --with-json --with-modules --with-ns --disable-ns-self-contained --without-imagemagick CFLAGS=-I/usr/local/opt/sqlite/include CPPFLAGS=-I/usr/local/opt/sqlite/include LDFLAGS=-L/usr/local/opt/sqlite/lib")
  (features . "RSVG DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS JSON PDUMPER LCMS2")
  (traits batch envvar-file))
 (doom
  (dir . "~/.config/doom/")
  (version . "2.0.9")
  (build . "HEAD -> develop 6e22a15e4 2020-08-24 23:36:11 -0400")
  (elc-files . 0)
  (modules :input chinese :os macos :completion (company +childframe) (ivy +fuzzy +prescient) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc undo :term vterm :checkers spell :tools direnv docker (eval +overlay) (lookup +docsets) (lsp +peek) (magit +forge) pass :os tty :lang (cc +lsp) data (elixir +lsp) emacs-lisp erlang (go +lsp) (java +meghanada) javascript lua markdown (org +dragndrop +hugo +roam +journal +present) python rest (ruby +rbenv +rails) rust sh (web +html +css) yaml :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages (alchemist :disable t) (alchemist-company :disable t) (evil-escape :disable t) (liberime :recipe (:local-repo "~/Projects/liberime" :files ("CMakeLists.txt" "Makefile" "emacs-module" "src" "liberime.el"))) (pyim :recipe (:host github :repo "tumashu/pyim")) (posframe :recipe (:host github :repo "tumashu/posframe")) (vimrc-mode) (transmission) (fish-mode) (modus-operandi-theme) (modus-vivendi-theme) (versuri :recipe (:host github :repo "mihaiolteanu/versuri")) (vuiet :recipe (:host github :repo "mihaiolteanu/vuiet")) (shrface :recipe (:host github :repo "chenyanming/shrface")) (org-super-agenda) (org-web-tools) (xkcd) (mu4e-alert) (verb) (anki-editor) (hl-line+) (lsp-tailwindcss :recipe (:local-repo "lsp-tailwindcss")) (maple-preview :recipe (:host github :repo "honmaple/emacs-maple-preview" :files ("*.el" "index.html" "static"))))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Can you reproduce this [in vanilla-doom+?](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)

**Comment by merrickluo** [comment]
I'll try and report back.

**Comment by qcfu-bu** [comment]
I also have a similar issue. I am using emacs-mac 27 installed following the instructions on the doom emacs page. 

The extension that I'm using when the freezes happen is :lang ocaml.

This is weird because sometimes I might have 2 frames open on different monitors. When one frame freezes, the other frame would still be operational.

**Comment by hlissner** [comment]
Have either of you changed `which-key-idle-delay`?

**Comment by qcfu-bu** [comment]
No, I'm using very minimal configuration. I could switch to another distro (spacemacs) to see if it's an issue with ocaml-merlin or doom.

**Comment by merrickluo** [comment]
Didn't change `which-key-idle-delay` either, I find it's hard to reproduce it now, but I can confirm this only freezes a frame and seems just not response to keyboard event, for example mouse clicks changes menu bar.

**Comment by qcfu-bu** [comment]
I just want to report back that this issue does not seem to happen on spacemacs.

**Comment by erikc96** [comment]
I've been having the same exact issue.

**Comment by nate** [comment]
I've had this issue for quite a long time, even switched away from doom for a while because of it. I've only had it happen once or twice since switching to `(modeline +light)` so I suspect it has something to do with the modeline, maybe something to do with fonts. I just upgraded to 27.1 which has new font stuff so we'll see if that changes anything.

**Comment by nate** [comment]
Also I did a debug build in order to catch this and see where it's stuck and _of course_ it doesn't happen in the debug build...

**Comment by nate** [comment]
I've been using emacs in a tty for a week and haven't hit this issue so it seems to be related to the use of a GUI.

**Comment by hperrey** [comment]
I have also had this (?) issue with the same symptoms on OSX 10.13 for a while now, even after upgrades from 26.3 -> 28.0.5 (changing from homebrew binary to self-compiled). It doesn't happen particularly often, but maybe once a week (after rather intensive use). That means that I lose a lot of my working environment, though autosave usually saves any unsaved data in time. I have not seen this on my GNU/Linux install.

Usually in these cases, emacs freezes with the modeline in a state just before the popup would appear. Sometimes, when changing desktops (or what they are called on OSX: I run emacs full screen) and coming back, the popup would actually be there -- but no amount of `C-g` would bring control back. Usually `pkill -SIGUSR2 Emacs` would just kill Emacs without ever showing the debugger. But today, it did show up while still being frozen and dying quickly after. It showed:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

I found potentially related issues: https://github.com/syl20bnr/spacemacs/issues/8557, https://github.com/syl20bnr/spacemacs/issues/8943 and https://github.com/TheBB/spaceline/issues/123. I understand that these are related to spacemacs, but there, a remarkably similar issue seems to be triggered by a font change/unicode character causing an endless loop in the redisplay routine.

I am happy to contribute to any debugging efforts though I have found this frustratingly difficult so far: the issue is rather annoying and always sets me back a few minutes but too infrequent to be anywhere near reproducible. What is more, my usual debugging approaches don't really work.

**Comment by QinBa** [comment]
I am using a mac. I seem also to have the same issue for quite a while now. Emacs freezes quick often actually when i press short cut quickly (I guess?). I tried to wait for it to recover but it never recovered on itself. Had to simply force quite the app every time. The frustrating part is that I don't know how to reproduce and debug the problem. That is partly the reason I never reported the issue, as I have no idea what is happening.

I would search for the issue once a while when it drove me crazy. Then I found this thread seemingly related and decided to leave the above comment. Forgive me that it may not be helpful due to the lack of useful information.

**Comment by hperrey** [comment]
I *just* had the issue appearing again (after having had a break from it for a while). I noticed that Emacs *does* take keypresses and reacts to them. However, nothing on the screen updates, and the window appears to be without focus. When I move between Desktops (or whatever they are called in OSX) using `Ctrl-[cursor]` and back again, any other Emacs window/frame than the one where I triggered the freeze in would have updated and showing e.g. a prompt in the minibuffer. It would still not update immediately, but I can e.g. save all buffers and similar by either doing it completely blindly or by moving desktops back and forth. Opening new frames works as well (`C-x 5 2`).
I am in the process of moving to Ubuntu, so this is one of the issues I am looking forward to not having anymore then =)

**Comment by corasaurus-hex** [comment]
I no longer have this issue, but I did move from emacs-plus to emacs-mac at some point.

**Comment by merrickluo** [comment]
I didn't notice it in a while either, gccemacs from source.

**Comment by hperrey** [comment]
For me the issue disappeared after moving from OSX to Ubuntu :)
Using the same configuration though.
