### ISSUE TITLE
doom/window-enlargen goes to infinite loop

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#3936]
**What did you expect to happen?**
- `doom/window-enlargen` should enlarge the current buffer-window.

**What actually happened?**
- Emacs hangs and CPU usage goes up to 100% and stays there.
- No stacktrace is produced upon force-quit.

**Steps to reproduce:**
1. Start a fresh emacs.
2. Open some project (`SPC p p`), and open some file.
3. Vertical split the buffer `SPC w v`
4. Enlarge current window `SPC w o`

**System information:**
https://pastebin.com/N3FtSpr6

**Comment by rodelrod** [comment]
Had the same problem.

**Comment by hpfr** [comment]
I stopped using this because of this issue. Has anyone tried it recently?

**Comment by hlissner** [comment]
I'm inclined to close this because there isn't enough information here and the issue (and included information) is wildly out of date. Also, I can't reproduce the original issue. 

If you're still seeing this, please produce a backtrace by sending a `USR2` signal to the Emacs process while it is hanging:

```sh
kill -USR2 $EMACSPID
```
