### ISSUE TITLE
building epdfinfo crashes emacs

### ISSUE THREAD

**Issue by aith** [hlissner/doom-emacs#3961]
**What did you expect to happen?**
I was prompted to build epdfinfo after using 'org-capture' on a new build of Doom. During the build it ran into errors and crashed froze emacs. 

I'm on Ubuntu 18.04. #3244 also had Ubuntu-specific issues with epdfinfo building.
</pre></details>
![epdfbug](https://user-images.githubusercontent.com/62635784/93662453-0c8c4d00-fa15-11ea-8190-1227476e1fb1.png)

**Steps to reproduce:**
1) Cloned and built doom with empty config.el and packages.el
2) Ran 'org-capture'
3) Agreed to build epdfinfo

**Comment by even4void** [comment]
In the past I also encountered some issues when building `epdinfo` from Emacs. The problem came out to be related to `pkginfo` missing some critical lib on macOS, and I just had to eval this before running `pdf-tools-install`: `(setenv "PKG_CONFIG_PATH" "/usr/local/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig")`. If that doesn't help, could you try building the exec directly from the straight repos? At least, you'll get the complete output of the `configure` and `make` steps, and perhaps some clues to move forward.

**Comment by aith** [comment]
Thanks for the suggestions! I tried those, but it worked after I updated gcc.
