### ISSUE TITLE
`counsel-projectile-switch-project` temporarily switches back to *doom* buffer during file select

### ISSUE THREAD

**Issue by nbfalcon** [hlissner/doom-emacs#3990]
**What did you expect to happen?**

An ivy prompt, prompting me first for the project and then for the file, without changing the current buffer until having selected the file.

**What actually happened?**
An ivy prompt, prompting me first for the project, then switching to the doom buffer, while prompting me to select a file within that project.

**Additional details:**
I'll add some if needed.

**Steps to reproduce:**
1. Run `M-x counsel-projectile-switch-project`
2. Select a project.
3. Observe that the doom buffer is now current.

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
EMACS   dir        ~/.local/share/doom-emacs/.emacs.d/
        version    28.0.50
        build      Jul 29, 2020
        buildopts  --with-libsystemd --with-xwidgets --with-json --with-pdumper --with-dbus
        features   XPM JPEG TIFF GIF PNG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER
        traits     (server-running)
DOOM    dir        ~/.config/doom-emacs/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 1456108d5 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo minimap modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold format lispy parinfer snippets word-wrap :emacs dired electric undo vc :term eshell vterm :checkers syntax spell grammar :tools debugger (eval +overlay) lookup lsp (magit +forge) make pdf :lang (cc +lsp) common-lisp data emacs-lisp (json +lsp) latex lua markdown (org +pretty) (python +lsp +pyright) (rust +lsp) (&nopath inscheme) sh web yaml :config (default +bindings +smartparens))
        packages   ((imenu-list) (package-lint) (dap-mode :recipe (:local-repo ~/Projects/dap-mode-contrib/)) (lsp-mode :recipe (:local-repo ~/Projects/lsp-mode-contrib/)) (ptemplate :recipe (:local-repo ~/Projects/emacs/plugins/ptemplate)) (page-break-lines) (polymode) (poly-markdown))
        unpin      (markdown-mode)
        elpa       (n/a)
```
</details>
(PATH removed as it is unrelated to the issue and may have personal details)

**Comment by nbfalcon** [comment]
Strangely, I can't reproduce in doom/sandbox with my config. I will investigate.

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom, on 26.3 or 27.1, so I will chalk this up to a local issue for now. Feel free to follow up if you've determined otherwise.

**Comment by nbfalcon** [comment]
I would like to follow up on this, because I have found the cause of the issue: (control flow in order of bullets)
- `counsel-projectile-switch-project`
- `counsel-projectile-switch-project-action`, index=1
- `+workspaces-switch-to-project-h`
- `+workspace-new`
- `switch-to-buffer` `(doom-default-buffer`), on [this line](https://github.com/hlissner/doom-emacs/blob/febf960c4e6247f20946fd0a832bf5d3c3febaf3/modules/ui/workspaces/autoload/workspaces.el#L139).
It shows a `*DOOM*` buffer in every workspace, and should be replaced with code that just adds it, without displaying it. I will make a PR soon, so please reopen and assign this to me.

This issue only occurs with the `:ui workspaces` module enabled and when switching to a project that doesn't already have a workspace.

**Comment by loafofpiecrust** [comment]
I observe the same behavior in my doom setup with latest `native-comp`. The main annoyance for me is that if I realize I chose the wrong project once I get to the file selection, then I hit `C-g`, I'm in a workspace with `*doom*` that I have to delete before finding the project I actually wanted.

**Comment by nbfalcon** [comment]
@hlissner you may want to reopen and assign to me. I will probably be able to come up with something (perhaps asking for the first).

**Comment by hlissner** [comment]
This is trickier than it sounds. `+workspaces-switch-project-function` needs to run in the context of the workspace it should affect, so creating this workspace is inevitable. Moving it up to prompt sooner won't cut it, because this will introduce edge cases for custom `+workspaces-switch-project-function` commands.

The most reliable way to pull this off is to wrap the segment of `+workspaces-switch-to-project-h` in a `condition-case` that checks for a `quit` event. If received, we a) check if the current workspace is empty, and delete it if it is and b) switch back to the workspace we were in before being prompted.

**Comment by nbfalcon** [comment]
True. I also considered the case where the user might select multiple files using `C-SPC` to be opened at once. The empty buffer problem can be solved by adding a version of `+workspace-new` that uses `persp-add-buffer`, and reimplementing `+workspace-new` in terms of it.

**Comment by hlissner** [comment]
> I also considered the case where the user might select multiple files using C-SPC to be opened at once. 

This shouldn't be a problem with the current implementation. The ivy/helm command is executed in the context of the new workspace. Whether you open one or more files, it will work fine.

The problem (and what appears to be the issue here) is what the user expects to happen when you abort this prompt, abruptly. Do you undo the new workspace and return to the last? Should it do nothing and leave you in the new workspace (after all, you could delete it with `SPC TAB d` if you don't want it, or simply carry on if you do). That's what I've addressed in my earlier reply.

> persp-add-buffer

I don't understand why you bring this function up. It is important that `+workspace-new` uses `switch-to-buffer` so that any blank workspace's initial buffer is the fallback buffer, rather than the last open buffer. I haven't done this merely to add the fallback buffer to the workspace, but to actively switch to it.
