### ISSUE TITLE
Shortcuts to major modes outside emacs

### ISSUE THREAD

**Issue by ghost** [hlissner/doom-emacs#402]
Hey there,
I was wondering if there is a way to open major modes like elfeed or the rss-client in emacs without opening emacs first. For example, I'd like to bind elfeed to a specific key in i3wm so that I can open elfeed with one push of a button. Of course, this can only work effectively when emacs is started as a daemon.

Thank you and good luck with everything :)

**Comment by hlissner** [comment]
I think it's possible. I've done something similar to org-capture and rofi on bspwm, invoked via [bin/org-capture](https://github.com/hlissner/doom-emacs/blob/develop/bin/org-capture).

It simply needs something to conditionally [open the frame](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/autoload/org-capture.el#L56) and [clean it up afterwards](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/%2Bcapture.el#L37).

In elfeed's case, we just need:

+ a function that creates the frame and marks it as temporary (maybe a `transient` frame parameter?).
+ a `kill-buffer-hook` to check when the elfeed buffer is killed (and then conditionally close the frame).
+ A shell script that creates the remote frame:

   ```sh
   emacsclient -a "" \
           -c -F '((name . "elfeed") (width . 70) (height . 25) (transient . t))' \
           -e "(+elfeed/open-frame)"
   ```

I'll look more into it after I'm done with this 2.1 release (sometime between today and Wednesday).

**Comment by hlissner** [comment]
To follow up on this, I think the best course of action (with Doom anyway) would be to `emacsclient -a"" -c --eval "(=rss)"`. This would open an Emacs frame with elfeed in it. Due to the complexity of elfeed and its complimenting packages, there's no reliable way to pull out elfeed without carrying Emacs' (and Doom's) weight with it.

In any case, I'll consider this question answer and close this issue.
