### ISSUE TITLE
Default to XDG

### ISSUE THREAD

**Issue by xerus2000** [hlissner/doom-emacs#4040]
Currently, the Readme suggests to clone to HOME, and `doom install` also always installs to `.doom.d` - so I have to manually move it after installing.
I think it should default to XDG, or, as a more conservative approach, use XDG if XDG_CONFIG_HOME is explicitly set.

So with emacs27 one can use the following:
```
git clone --depth 1 https://github.com/hlissner/doom-emacs ${XDG_CONFIG_HOME:-$HOME/.config}/emacs
${XDG_CONFIG_HOME:-$HOME/.config}/doom install
```
Where `doom install` could then either:
1) Always default to `${XDG_CONFIG_HOME:-$HOME/.config}/doom`
2) Detect whether the emacs config is under ${XDG_CONFIG_HOME:-$HOME/.config} and if yes, use XDG, otherwise .doom.d (or detect whether there is a `~/.emacs.d` i.e. the other way around)
3) Default to XDG when the XDG_CONFIG_HOME is explicitly set

The more conservative approach, which would fit with (2) or (3) would be:
```
git clone --depth 1 https://github.com/hlissner/doom-emacs $(test -n "$XDG_CONFIG_HOME" && echo "$XDG_CONFIG_HOME/emacs" || echo "~/.emacs.d")
$(test -n "$XDG_CONFIG_HOME" && echo "$XDG_CONFIG_HOME/emacs" || echo "~/.emacs.d")/bin/doom install
``

But a great first step would be to at least add some option to have `doom install` use XDG, if you don't wanna make it default.

**Comment by hlissner** [comment]
> Currently, the Readme suggests to clone to HOME, and doom install also always installs to .doom.d - so I have to manually move it after installing.
I think it should default to XDG, or, as a more conservative approach, use XDG if XDG_CONFIG_HOME is explicitly set.

Hi! Thanks for the suggestion, but I don't think this is appropriate for "quick start" instructions. It complicates the first steps for beginners and is only noise for experienced users. I won't make it more complicated than it has to be.

> Detect whether the emacs config is under ${XDG_CONFIG_HOME:-$HOME/.config} and if yes, use XDG, otherwise .doom.d (or detect whether there is a ~/.emacs.d i.e. the other way around)

Done in 1255ebd. `doom install` will now create `~/.doom.d` or `~/.config/doom` depending on the location of your emacs config.

> Default to XDG when the XDG_CONFIG_HOME is explicitly set

And what of users who have set XDG_CONFIG_HOME but prefer their emacs config in `~/.emacs.d` (for backwards compatibility or because they use Emacs 26)? I think this is too eager a default. I will leave it to users to put their config where they want it.

Thanks for bringing it to my attention!

**Comment by xerus2000** [comment]
Alright, that's fine with me, thanks :)
