### ISSUE TITLE
Bump `format-all` (to get TOML support)

### ISSUE THREAD

**Issue by rassie** [hlissner/doom-emacs#4041]
`format-all`'s pin is quite old, in the meantime it started supporting TOML (and some other niceties), which is quite popular in some areas right now. Would be nice to update the pin, thanks!

**Comment by hlissner** [comment]
Hi! Thanks for the request. I won't be bumping format-all because a) too much has changed upstream for a simple bump to work and b) I am working on replacing it with [apheleia](https://github.com/raxod502/apheleia). I have a WIP module for it [in my private config](https://github.com/hlissner/doom-emacs-private/blob/master/modules/editor/format/config.el).

Unfortunately, there is much to do to finish it and I just came back from break to a monstrous backlog, so it'll be a while until there's movement here.

Since format-all itself won't be bumped, I'll close this and add a nofix tag.

**Comment by rassie** [comment]
Ok, understood. I've unpinned the package locally, which seems to work so far. Thanks!

**Comment by hlissner** [comment]
I'm honestly surprised that it works at all. There are many breaking incompatibilities a few commits ahead of where Doom currently pins it, which are the real blockers here.

**Comment by rassie** [comment]
I've had very limited testing so far, spent the day writing TOML, but little other code. Might need to re-pin tomorrow, who knows :)

**Comment by rassie** [comment]
But I'm curious: which changes do you see? AFAICS, there are no big changes on master branch there apart from using `language-id` for mode-language matching. The `multi-formatter` branch with lots of incompatibility is still unmerged if I'm looking correctly.
