### ISSUE TITLE
format html code file?

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#4106]
Hi,

I work with Vue.js and use web-mode + lsp.
lsp for html is install:  npm install -g vscode-html-languageserver-bin
The completion is working fine but impossible to format with lsp and 
if I try to format-buffer, it calls tidy, that badly format the buffer. (do not 
respect line break ....)
I have also tryed: html-mode, mhtml-mode, vue-mode but that does not solve 
anything for the formatting. :((

The file name ends with: ".html"

Did I miss something?
Any tip(s) / help welcome.
It is weird, because all is fine with VS Code.

Rgds,

**Comment by rebyatyonok** [comment]
Hi! I have been facing this issue as well, and I did not found a perfectly working solution. 

The major problem here is that checking buffer is handled by `flycheck` but formatting is handled by `format-all` and they are not connected with each other. Last one uses prettier under the hood for `.vue` files. So it needs a very accurate and difficult configuration of all plugins inside emacs and plugins inside your environment as well. I've tried a lot to do that but have no success.

So I suggest you to became a 'editor agnostic' and to try insert linter in your build and enable formatting on the fly. Then disable formatting inside emacs because now it will be handled by webpack or anything you use. 

If someone here knows how to configure it I will be glad to know also.

**Comment by MrMic** [comment]
Thanks for the reply.
I have struggled a lot, but cannot make it work correctly, so far.
I will go on with VS Code.

**Comment by jcf** [comment]
Assuming you're using `(format +onsave)`, you can disable formatting HTML files with `htmltidy` like so:

``` emacs-lisp
(setq +format-on-save-enabled-modes
      '(not emacs-lisp-mode  ; elisp's mechanisms are good enough
            sql-mode         ; sqlformat is currently broken
            tex-mode         ; latexindent is broken
            web-mode
            latex-mode))
```

Note the addition of `web-mode` to the list that Doom provides out of the box.

**Comment by hlissner** [comment]
This was likely fixed by #4120 (formatting is now done by LSP when possible). Please update Doom and let me know.

**Comment by MrMic** [comment]
Nope.
- If I try +format/buffer =>look uo for tidy which I do not want, because the result is ugly.
- If I try with lsp: lsp-format-buffer: Capability not supported by the language server: "documentFormattingProvider"

So I still got nothing helping me.
I would like to format with prettier. It works great and even better with a prettierrc file.
I also find a workaround: web-beautify ....

**Comment by MrMic** [comment]
I have now add this to config.el:
(setq-hook! 'web-mode-hook +format-with 'prettier-prettify)

And it seems to work as expected :))
I also have installed prettier on my system.
Hope that will help others.
