### ISSUE TITLE
Need a warning when using package-install

### ISSUE THREAD

**Issue by JasonMFry** [hlissner/doom-emacs#4157]
I'm filing this as a bug and not a feature request because this is unexpected, bad behavior, and from a user's perspective it is a bug. Doom has a helpful warning for at least one other command it doesn't support, namely `M-x customize-variable RET org-modules`. If you insist it be a feature request I'll change it.

**What did you expect to happen?**
Stupid me, I expected package-install to install packages

**What actually happened?**
Apparently nothing? And I'm only finding this out today after months of using Doom and using `package-install` idk how many times

**Additional details:**
N/A

**Steps to reproduce:**
Use package-install

**System information:**
N/A

I'm pretty frustrated by this and that's probably coming out in my language here, but I do want to say Doom Emacs is amazing, I was able to switch from Neovim to Doom with very little learning curve, and I appreciate all the work that's done to make Doom great.

**Comment by JasonMFry** [comment]
The warning that exists in the readme would be great
> WARNING: Do not install packages directly (with M-x package-install or M-x straight-use-package). Without an accompanying package! declaration somewhere these packages will be forgotten when you restart Emacs and uninstalled the next time you run doom sync or doom purge.

**Comment by hlissner** [comment]
Hi! I'll add a `doom doctor` warning to complain if packages have been installed with package.el, however, I won't add one like the one for `customize` because:

1. It's not that `package-install` is unsupported, just discouraged. Otherwise, it works exactly as designed (this is not Doom specific). If package.el is never initialized, it never gets the opportunity to rediscover what packages it has previously installed. Adding `(package-initialize)` to `~/.doom.d/config.el` will do it.
2. While I don't recommend you use package.el (because Doom offers you a superior package manager, free of cost), it remains for users who want to use it -- and there are legitimate reasons to use it, e.g. folks are holding off on learning a new package manager, or want to quickly install a package to test it or dig into its source code. Adding a warning will only serve to inconvenience them and create a false impression that Doom doesn't support package.el.
3. Our getting started guide has a whole section on Doom's package manager and how to use it (as well as the section you quoted). I believe there is enough information here for folks to realize the problem and solution.

I'm sorry this has caused you frustration. I'm only now noticing your posts on DIscord (I've been working on other commitments the past few days).

**Comment by JasonMFry** [comment]
No worries, I really appreciate all you do!

**Comment by hlissner** [comment]
I've moved this and many other issues to #4273. Please keep track of it there.
