### ISSUE TITLE
Find file in new window

### ISSUE THREAD

**Issue by kujohn** [hlissner/doom-emacs#4175]
How does one modify the `SPC SPC` behavior so that it opens the file in a new window?

**Comment by gilbertw1** [comment]
You should be able to do it directly from ivy (the minibuffer that pops up). Just highlight the file you want to open and press `C-o`, when you do that you should see a list of actions you can take, one of which is `other-window` which opens the file in a new window or a different window than the one currently selected.

This is a common keybinding that works in many different contexts. For example if you press `SPC p p` highlight a project and press `C-o` you can then do a set of project specific actions instead of the default (which opens the project in a new workspace).
