### ISSUE TITLE
I've got stuck opening an elm file and found that lsp doesn't work at all

### ISSUE THREAD

**Issue by korsmakolnikov** [hlissner/doom-emacs#4223]
I couldn't get it to work. I see this error opening an elm file: 
`LSP :: Error from the Language Server: Unhandled method textDocument/codeAction`

It seems lsp can't do anything, even the simplest jump to definition. 
Strangely I see `LSP :: elm-ls:51011 initialized successfully` in the messages. 

Ideas?

**Comment by SebastienWae** [comment]
This looks more like an issue with `elm-language-server`, a full dump of your config, system info, `*Messages*` and `*lsp-log*` buffer would help. Try to also call `lsp-toggle-trace-io` it will create a new buffer that display all the requests/responses between emacs and the lsp server but you'll probably get more help on [emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode) or [elm-tooling/elm-language-server](https://github.com/elm-tooling/elm-language-server) because Doom is basically just loading `lsp-mode`.

**Comment by SebastienWae** [comment]
This looks more like an issue with `elm-language-server`, a full dump of your config, system info, `*Messages*` and `*lsp-log*` buffer would help. Try to also call `lsp-toggle-trace-io` it will create a new buffer that display all the requests/responses between emacs and the lsp server but you'll probably get more help on [emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode) or [elm-tooling/elm-language-server](https://github.com/elm-tooling/elm-language-server) because Doom is basically just loading `lsp-mode`.

**Comment by korsmakolnikov** [comment]
I'm supposing Doom doesn't find the language server. How can I specify the path?

**Comment by SebastienWae** [comment]
> I'm supposing Doom doesn't find the language server. How can I specify the language server path?

The language server path can be customised with `lsp-elm-elm-language-server-path` but this is not modified by Doom so it relies on `lsp-mode` default that uses `npm` so as long as it is properly installed it shouldn't be an issue and if it was the issue you would get an error telling you that no language server was found and you would not get `LSP :: elm-ls:51011 initialized successfully`.
IMO this is not an issue with Doom, looks like someone had a similar issue [elm-tooling/elm-language-server/issues#305](https://github.com/elm-tooling/elm-language-server/issues/305#issuecomment-671782392).
