### ISSUE TITLE
SPC

### ISSUE THREAD

**Issue by Gahamelas** [hlissner/doom-emacs#4298]
I am a potential DOOMS user... one silly question. If SPC bar is a functional key... how do you write a space when typing in Org mode? :D

**Comment by hlissner** [comment]
`SPC` is the leader key when evil is enabled. Evil provides vim emulation in Emacs. Vim editing is modal, meaning there are different modes you can be in. You start in normal mode. To insert text you have to switch to insert mode. Insert mode is where you insert characters (and where pressing `SPC` will insert a space). In any other mode, `SPC` will invoke the leader key.

Doom binds the leader key to `M-SPC` (meta + SPC) in insert mode, if you aren't willing to leave insert mode before using the leader key.

When evil is not enabled, `C-c` is the leader key (because with evil off, it's like you're in perpetual insert mode, so `SPC` can't have multiple meanings without sacrificing the ability to insert whitespace).

Hope that answers your question.

**Comment by Gahamelas** [comment]
Thanks, sounds very comfy for the hands, I will give it a try! I wonder why Emacs wasn't based on that principle, pressing SPC is so natural, easy, and smooth as opposed to C-c ... Thanks so much for your answer.
