### ISSUE TITLE
ivy +fuzzy search is slow on large project

### ISSUE THREAD

**Issue by dbalatero** [hlissner/doom-emacs#4305]
Hello! When using `SPC SPC` file search with `(ivy +fuzzy)` on a repo with 200K files (my work's corporate monorepo), the file filtering chugs to a halt as you type for about 15 seconds.

I have ripgrep and fd installed and on my PATH.

fzf.vim handles the same repo like a dream. Is there something I need to do to get usable file finding?

**Comment by gagbo** [comment]
Hello,

As you seem to have fzf in path you can bind `SPC SPC` to counsel-fzf it might help, but unsure.

The reason ivy is slow here is that counsel has to gather the whole list to start filtering. It seems that fzf is able to stream the file list so that you get immediate results as soon as some filenames are coming. FZF was not initially built to be integrated in anything other than fzf, I don't know how far integration went.

But worst case scenario, you can install [fzf.el](https://github.com/bling/fzf.el) and use this instead, it basically spawns a shell in a terminal that launches fzf just to select a file. You get the same speed as anything else with it, at the cost of not being integrated with the complete ivy/counsel experience.

**Comment by jsravn** [comment]
`+fuzzy` is very slow on large projects - this is an issue w/ the module (flx) that is used. I suggest using `+prescient` instead which provides similar functionality and is much faster.

**Comment by dbalatero** [comment]
Tried suggestions:

* `counsel-fzf` still takes 10 seconds between each input update
* `+prescient` is still extremely slow and not usable
* `fzf.el` seems to work well, I'll try to get it to open in a split with `ctrl + x` and `ctrl + v` like fzf.vim

**Comment by gagbo** [comment]
counsel-fzf still spawns a new fzf process at each input yeah, so it's going to be slow... You can play with fzf/args variable to set these behaviour maybe ?

**Comment by dbalatero** [comment]
> counsel-fzf still spawns a new fzf process at each input

Yeah that's not going to work unfortunately. It needs to be an interactive filter or bust.

**Comment by jsravn** [comment]
> +prescient is still extremely slow and not usable

That's really strange! In my experience, on giant repos (16-30k files) prescient is fine, being nearly instantaneous. While flx is very slow. Maybe something else is going wrong with your setup.

**Comment by jsravn** [comment]
> +prescient is still extremely slow and not usable

Okay, I see you're at 200k files. It is instant for me but the largest repo I have is around 30k files.

It might be worth opening an issue w/ the counsel repo to see if counsel-fzf can be sped up.

This would be a great improvement to have in doom I think.
