### ISSUE TITLE
All headlines are expanded although `org-startup-folded` is set to overview and `org-agenda-inhibit-startup` is set to nil

### ISSUE THREAD

**Issue by mfcabrera** [hlissner/doom-emacs#4318]
**What did you expect to happen?**
If I set those variables:

```elisp
(setq
   org-startup-folded 'overview
   org-agenda-inhibit-startup nil
   )
```

I expect that when I open a file  (either with the normal find-file, org-roam or clicking a headline from the agenda) the org headlines should appear folded. In the case of opening from the agenda, except for the one I clicked on. 

**What actually happened?**
No matter what I do, if I open a org-mode file all the  headlines are unfolded as well as the drawers. The only way to avoid this is if I specifically add a per-file configuration (i.e.):

```
#+STARTUP: fold
```

**Additional details:**

Link to my configuration: https://github.com/mfcabrera/dotemacs/blob/doom-migration/.doom.d/config.el#L182

**Steps to reproduce:**
1.  Set-up the variables as described
2.  Open a org-mode file 

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64
        path       ((eval) 1  can't change option  zle(eval) 11  unmatched '/Users/$USER/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/munki (eval) 1  can't change option  zle/Users/$USER/bin ~/.emacs.d/bin /usr/local/anaconda3/bin /usr/local/anaconda3/condabin ~/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 12, 2020
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
        traits     (gui server-running envvar-file)
DOOM    dir        ~/dotemacs/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Hack nil nil nil nil nil 18 nil nil nil nil>
        theme      doom-dracula
        build      HEAD -> develop e4890f6a 2020-11-25 00:40:43 -0500
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp markdown (org +roam +journal +dragndrop +jupyter +pomodoro +present +pretty +gnuplot) (python +conda +lsp) sh :config (default +bindings +smartparens))
        packages   ((elpy) (org-roam-server) (org-ref) (org-roam-bibtex :recipe (:host github :repo org-roam/org-roam-bibtex)) (org-fancy-priorities) (editorconfig) (dash-docs) (pyvenv))
        unpin      (org-roam company-org-roam)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
Are those settings wrapped in an `(after! org ...)` block? e.g.

```lisp
(after! org
  (setq org-startup-folded 'overview
        org-agenda-inhibit-startup nil))
```

**Comment by mfcabrera** [comment]
@hlissner  yes they are :)

```elisp

(after! org
  (setq org-agenda-files (append (bigui/find-org-file-recursively "~/Dropbox/Notational Data/org/" "org")))
  (add-hook 'org-agenda-mode-hook '(lambda () (hl-line-mode 1)))
  (setq
   calendar-week-start-day 1 ;; start week on monday
   org-default-notes-file  (concat org-directory "org/" "Inbox.org")
   org-default-work-file   (concat org-directory "org/" "work.org")
   org-default-work-files   (list org-default-work-file)
   org-default-learning-file  (concat org-directory "org/" "learning_profdev.org")
   org-columns-default-format "%25ITEM %TODO %3PRIORITY %TAGS Effort"
   org-startup-folded 'overview
   org-agenda-inhibit-startup nil
   )
(...)
``` 

I've been trying to debug a bit more but I cannot find the culprit. It looks that something is being executed after org-mode is loaded that I do not have control of. The weird thing is that it works if I add a buffer local variable.

**Comment by hlissner** [comment]
Actually, this appears to be an upstream issue with `org`. Its documentation suggestions you can set `org-startup-folded` to `fold`, `nofold`, `content` or `showeverything`, but only `content` and `showeverything` [are supported](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L6555-L6562). Instead of `fold` you need to set it to `t`, and instead of `nofold`, set it to `nil`.

**Comment by hlissner** [comment]
Side note, you're eagerly loading a lot of packages in your config by using `use-package` without a deferring keyword, like `:defer t`, `:hook` or `:commands`, and your startup time is likely suffering tremendously.

If this matters to you, I suggest replacing any instances of

```lisp
(use-package! X
  :config
  ...)
```

With

```lisp
(after! X
  ...)
```

**Comment by hlissner** [comment]
More side notes (not an exhaustive list, just the most glaring issues):

1. [You're using `exec-path-from-shell`](https://github.com/mfcabrera/dotemacs/blob/doom-migration/.doom.d/config.el#L98-L101). Are you aware of the `doom env` command? It will create a snapshot of your shell environment that doom will load at startup. I'd recommend this, it's faster and less error prone.

2. [Doom does this for you already](https://github.com/mfcabrera/dotemacs/blob/doom-migration/.doom.d/config.el#L113-L117).

3. [Doom lazy loads babel plugins for you, so these lines aren't necessary and only serve to add to your startup time](https://github.com/mfcabrera/dotemacs/blob/doom-migration/.doom.d/config.el#L402-L411).

4. Either use `:lang (org +roam)` or set up org-roam yourself, it's not a good idea to do both. You're duplicating a lot of org-roam config that Doom already does for you otherwise.

5. Enable `:tools editorconfig` instead [of this](https://github.com/mfcabrera/dotemacs/blob/doom-migration/.doom.d/config.el#L556-L559).

6. All those empty `(use-package! X)` blocks do nothing but eagerly load the package. They should be removed.

**Comment by mfcabrera** [comment]
@hlissner 
First, thanks a lot for explaining the concepts and giving me advice on the Emacs configuration. I just migrated a couple of days ago and I probably should have read the doc with more detail. I have your advice and indeed the start-up time improved a lot! 

As for the problem I was facing, indeed it was solved after setting `org-startup-folded`  to `t` thanks for that! - The documentation is indeed misleading.
