### ISSUE TITLE
company-dcd does not working

### ISSUE THREAD

**Issue by route616** [hlissner/doom-emacs#4327]
Hi! I have installed the company-dcd package. He works for Vanilla, but doesn't work for Doom.

**Comment by hlissner** [comment]
Hi! This issue was automatically deleted, because it is not an unacceptable bug report, here are some reasons why:

1. It ignores the issue template, which asks that you include vital information, such as:
   1. Steps to reproduce the issue.
   2. A link to your personal config (if possible).
   3. Your `M-x doom/info`.
2. Your description of the issue is too vague or underesearched.
3. No error messages or backtraces were included.
4. You've used the phrase "X doesn't work" without explaining what "doesn't work" means.

Once you have collected more information, feel free to open another issue, but **please do not ignore the issue template when you do.** If you must omit parts of it, please offer an explanation why.

Sorry for the trouble!
