### ISSUE TITLE
Emacs icon opens regular emacs

### ISSUE THREAD

**Issue by Collatz124** [hlissner/doom-emacs#4329]
Hello, 

I have recently installed emacs 2.7 and Doom. When I open emacs from terminal doom emacs opens (yay), however when I use the emacs icon to open emacs, default GNU emacs opens

**Comment by hlissner** [comment]
Please see https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#i-get-the-vanilla-emacs-splash-screen-at-startup

**Comment by Collatz124** [comment]
Thank you for your comment, however i have no .emacs file in my home directory... and no errors when running doom

**Comment by hlissner** [comment]
Sorry, I need more information to tackle the problem. I'm certain it's not a Doom issue. There are too many possibilities to guess, but here are some that come to mind:

+ Perhaps you cloned this repo to `~/.config/emacs`, but `~/.emacs.d` exists?
+ Perhaps you cloned it to `~/.emacs.d/doom-emacs` instead of `~/.emacs.d`?
+ Perhaps an error occurred at startup (of course, if this were so, the error would pop up quite visibly)
+ You are launching emacs with `emacs -Q`, which disregards any configuration and loads vanilla Emacs.

If none of the these are the case, then I'm afraid I'm out of ideas.
