### ISSUE TITLE
Gnus with Doom : certificat validation failed verification code 42 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [hlissner/doom-emacs#4361]
Hi, 

I've tried to sent an email  with gnus in IMAP  via Doom emacs but it was not possible: 
certificat validation failed  verification code 42
I have not this problem with my usual version of emacs. 

The same problem was mentioned here, three months ago
[https://www.reddit.com/r/emacs/comments/imi8n7/gnus_on_doom_certificate_validation_failed/](url)

I would be happy to get the solution. 

Thanks !

**Comment by hlissner** [comment]
For posterity, [these are Doom's security (tls/gnutls) settings](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L327-L351). Occasionally, I find a user for whom these settings do not work. The reason why gnus may work for you in vanilla Emacs (or Spacemacs) is because their settings are much more relaxed.

I have no intention on relaxing these settings, but I am open to improving them, if you can determine their cause. Maybe your root certs or network are compromised? Perhaps your SSL software needs updating? Perhaps the IMAP server you're trying to connect to is old and doesn't support TLS 1.2 or newer?

If you don't care about security, feel free to turn it off: `(setq gnutls-verify-error nil)`.

**Comment by joseph-vidal-rosset** [comment]
Hi Henrik, 
First, many thanks for your quick reply. I tried (setq gnutls-verify-error nil)  in my gnus.el  but I have again a message error: please authenticate first 502 . 
The other line does not work either. 
I'm using GNU/Linux Debian 10 : gnutls-bin_3.6.7-4+deb10u5_amd64.deb  and I am using the bridge of ProtonMail, I do not think that there is a problem with their IMAP server. 
I paste also this: 
smtpmail        --      open    *trace of SMTP session to 127.0.0.1* --           Main         (network connection to 127.0.0.1:1025) 

220 127.0.0.1 ESMTP Service Ready
250-Hello mx
250-PIPELINING
250-8BITMIME
250-STARTTLS
250 AUTH PLAIN LOGIN
220 Ready to start TLS
\0vnSBTL|PK9cMsi%5
ReHNLf";Oi`B5y.kFgr?rTI7gA2)R"Z33o
O1s>374|qpXpu
_@~Twm/vG&

**Comment by joseph-vidal-rosset** [comment]
Hi Henrik, 

Put in my ~/.doom/init.file   finally the line (setq gnutls-verify-error nil) does the job, my emails can be sent via Gnus . Thanks !
