### ISSUE TITLE
smartparens-strict-mode not working in some major modes

### ISSUE THREAD

**Issue by 15joeybloom** [hlissner/doom-emacs#4374]
**What did you expect to happen?**
When smartparens-strict-mode is active and when point is after a pair of closing parens (like `()|`) and I type `DEL` aka backspace, I expect the closing paren to _not_ be deleted so I end up with `(|)`.

**What actually happened?**
In major mode `emacs-lisp-mode` this works as expected.

But in other modes including `clojure-mode` and `c-mode` the closing paren is deleted so I end up with `(|`.

I reproduced this bug with a fresh install

**Investigation so far**
It seems that in `emacs-lisp-mode`, when `smartparens-strict-mode` is active, `DEL` is bound to `sp-backward-delete-char` due to `smartparens-strict-mode-map`. But in, for example, `clojure-mode`, when `smartparens-strict-mode` is active, `DEL` is bound to `evil-delete-backward-char-and-join`.

**Comment by hlissner** [comment]
[These are Doom's smartparens settings](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/config.el#L74-L207). PRs welcome.

**Comment by 15joeybloom** [comment]
I'm looking a little closer and it seems like smartparens-strict-mode works just fine in emacs state. So evil mode seems to be causing the problem.

**Comment by 15joeybloom** [comment]
I was not able to figure out why smartparens-strict-mode prevents parentheses from becoming unbalanced in `emacs-lisp-mode` but not other modes like `clojure-mode`. However, I did discover the package `evil-smartparens` which seems to fix my problem so I'll just enable that mode along with smartparens.

To be explicit:
I added
```
(package! 'evil-smartparens)
```
to my `.doom.d/init.el` and added `evil-smartparens-mode` to `smartparens-enabled-hook`. This is the snippet from my `.doom.d/config.el`.
```
(use-package! smartparens
  :init (add-hook 'smartparens-enabled-hook #'evil-smartparens-mode)
  :hook ((clojure-mode . smartparens-strict-mode)
         (lisp-mode . smartparens-strict-mode)
         (emacs-lisp-mode . smartparens-strict-mode)))

**Comment by hlissner** [comment]
Sorry for the late response. I've decided that Doom doesn't officially support `smartparens-strict-mode`, as smartparens is only being used for auto-pairing in insert mode (and may be replaced someday with something simpler). Any other use case is beyond Doom's scope (largely because the permutations of possible configuration for smartparens are endless and not very interesting to maintain).

In any case, I'll tag this as `has-workaround` since `evil-smartparens` seems to fix your issue, but `nofix` because it likely won't be addressed internally, especially when smartparen's future in Doom (at least, as a core package) is so uncertain. Sorry for the trouble, but thanks for bringing it to my attention!
