### ISSUE TITLE
Guide On How To Make this problem work?

### ISSUE THREAD

**Issue by jorschach-g** [hlissner/doom-emacs#4390]
> As of right now, nothing works.
> 
> All that stated above have not changed even a bit.
> 
> I have no idea how to change that.
> 
> Can you please help with it?

As for said debugger and running to determine what exactly is wrong, there is no new contribution either.

i.e. Same problem/ result with all methods stated above.

But is that what we have to live with right now regarding this problem.

The system is manjaro Linux, and the emacs version is 27.1.

Please put up a guide regarding which version of emacs can solve this problem, or, if that is the case, this problem can not be solved in the later verions.

Or a step further, it cannot be solved at all.

Please put some kind of document up.

I really need my enter [RET] key to work.

_Originally posted by @jorschach-g in https://github.com/hlissner/doom-emacs/issues/3172#issuecomment-740963529_

**Comment by hlissner** [comment]
Hi! This issue was automatically deleted because it does not meet the minimum requirements for a bug report. There are a couple reasons why this may have happened. Please read the following carefully, because **repeatedly failing to meet these standards is a bannable offense.** 

1. It ignores the issue template, which asks that you include vital information, such as:
   1. Steps to reproduce the issue.
   2. A link to your personal config (if possible).
   3. Your `M-x doom/info`.
2. Your description of the issue is too vague, difficult to understand, and/or under-researched.
   + Avoid phrases like “it doesn’t work” or “X stopped working” without explaining what "working" and "doesn't work" mean to you. Better to explain what happened and what you expected to happen, instead.
   + Link to your personal config. Please don’t paste the contents of your config files in your post – these only pollute the search results. Use services like pastebin or gist, or better: github.
   + Screenshots and gifs go a long way to communicate an issue. Try to include them, if possible.
3. You've mentioned errors without including error messages or [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error). If you can't get either, include the last 15-20 lines of the \*Messages\* buffer after the error occurred (<kbd>SPC</kbd><kbd>h</kbd><kbd>e</kbd> or <kbd>C-h</kbd><kbd>e</kbd> will open this buffer).

Once you are ready, feel free to open another issue, but **please do not ignore the issue template when you do.** If you must omit parts of it, please offer an explanation why.

I apologize if this is an inconvenience, but please understand it is a lot of work to support and maintain this project on my own. I depend heavily on you to meet me half way on issues.

Thanks for using Doom!
