### ISSUE TITLE
layout +bepo does not work with notmuch

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#4391]
In `notmuch-show-mode` with `layout +bepo` enabled, the navigation keys do not work, except `t` to go down and `c` to go left:
- `s` is still notmuch-search
- `r` is a prefix key
- `C-t` opens a new workspace (instead of going to the next message)
- `C-s` starts isearch (instead of going to the previous message)

**Comment by gagbo** [comment]
Hi, thanks for using it :)

I'll take a look at it. Can you also run `SPC h k s` or `C-h k s` and tell me in which `map` is the binding for `s` ?

Just to double check, you do have `:editor (evil +everywhere)` active as well don't you ?

**Comment by gagbo** [comment]
Note for later :

Looks like I found the [s binding](https://github.com/emacs-evil/evil-collection/blob/c9ccc3065f46c1654f1cc0d41cd2f5cff184d273/modes/notmuch/evil-collection-notmuch.el#L119) but didn't find anything about `"r"` as a prefix.

It'll probably require custom code in layout bepo

**Comment by brabalan** [comment]
Well, thank you for writing it!

I do use `:editor (evil +everywhere)`.

Regarding `r`, the only binding is `r c` and here is what I found about it:
```
notmuch-mua-new-mail is an interactive and compiled function defined
in notmuch-mua.el.

Signature
(notmuch-mua-new-mail &optional PROMPT-FOR-SENDER)

Documentation
Compose new mail.

If PROMPT-FOR-SENDER is non-nil, the user will be prompted for
the From: address first.

Key Bindings
evil-collection-notmuch-common-keymap-normal-state-backup-map C
evil-collection-notmuch-common-keymap-normal-state-backup-map c c
evil-collection-notmuch-show-mode-map-normal-state-backup-map C
evil-collection-notmuch-show-mode-map-normal-state-backup-map c c
notmuch-common-keymap <normal-state> L
notmuch-common-keymap <normal-state> l c
notmuch-common-keymap m
notmuch-hello-mode-map <normal-state> R
notmuch-hello-mode-map <normal-state> r c
notmuch-search-mode-map <normal-state> R
notmuch-search-mode-map <normal-state> r c
notmuch-show-mode-map <normal-state> R
notmuch-show-mode-map <normal-state> r c
notmuch-tree-mode-map <normal-state> R
notmuch-tree-mode-map <normal-state> r c
```

**Comment by gagbo** [comment]
## s is notmuch-search
`k` is never explicitely bound in evil-collection-notmuch maps so `s` never gets swapped with it. 

I will map manually search to `k` and remove the binding on `s`

## r is a prefix key
This is the weirdest one. `evil-collection-notmuch` maps that [function on `cc`](https://github.com/emacs-evil/evil-collection/blob/c9ccc3065f46c1654f1cc0d41cd2f5cff184d273/modes/notmuch/evil-collection-notmuch.el#L122) and the lines you see in the binding :

```
evil-collection-notmuch-common-keymap-normal-state-backup-map C
evil-collection-notmuch-common-keymap-normal-state-backup-map c c
evil-collection-notmuch-show-mode-map-normal-state-backup-map C
evil-collection-notmuch-show-mode-map-normal-state-backup-map c c
notmuch-common-keymap <normal-state> L
notmuch-common-keymap <normal-state> l c
```
Mean that it got remapped correctly by the hook away from c.

But then 
```
notmuch-show-mode-map <normal-state> R
notmuch-show-mode-map <normal-state> r c
```
This was badly remapped to r instead of c, even though it was the same hook that handled the call.

And the `notmuch-tree-mode-map` isn't even touched. It feels like there was an error in hook execution somehow and it'll get tricky to findout :(

## C-t C-s
I forgot to remap `C-` and `M-` bindings in normal mode in the `evil-collection-hook`, I'll try to fix that at least. It might have the side-effect of handling #4393 but I can't repro that one for now

**Comment by brabalan** [comment]
I just checked and without `layout bepo`, `r` is not bound to anything (well, technically it is bound to `ignore`).

**Comment by gagbo** [comment]
Yeah that r part is weird, I'll try to get the other 2 fixes merged, as I'm sure I won't need to look into evil-collection code, but that might be another story to understand where that `r c` binding comes from

**Comment by brabalan** [comment]
Thank you, I can work around a missing binding. The showstopper for me is #4393 as I rely heavily on `org-store-link` in my daily workflow.

**Comment by gagbo** [comment]
You can checkout https://github.com/hlissner/doom-emacs/pull/4403 (I put instructions in the first post) it should fix this. I try to rebase the PR on develop to keep latest changes

**Comment by brabalan** [comment]
I confirm that #4403 and https://github.com/emacs-evil/evil-collection/pull/428 fix the problem. Once they are merged or integrated, this can be closed. Thanks!

**Comment by brabalan** [comment]
Everything is working fine now in notmuch mode.
