### ISSUE TITLE
opening init.el on new install causes hanging or seg fault - Doom 2.0.9 Emacs 27.1

### ISSUE THREAD

**Issue by potongct** [hlissner/doom-emacs#4395]
**What did you expect to happen?**
Open init.el file for configuration

**What actually happened?**
emacs hangs/freezes or seg faults

**Additional details:**
Check top and see 100% cpu on emacs-wrapper

**Steps to reproduce:**
1. open emacs
2. Enter Space f P
3. Select init.el from dropdown.

**Solution:**
Remove line 33 from ~/.doom.d/init.el which contains: `;;(emoji +unicode)  ; 🙂`
or
Uncomment above line and `run doom sync`

**Comment by hlissner** [comment]
I'll chalk this up to Emacs having issues with some font that the emoji module was trying to use. Since I cannot reproduce this on any of my test systems I'll consider it a local issue. Make sure you have `Symbola` installed and that Doom is up-to-date, as there have been many improvements to Doom's font/unicode rendering since this issue was first opened.

Feel free to follow up here if this issue persists.
