### ISSUE TITLE
after! support :any :all like action in use-package and modules

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#442]
### Observed behavior

1. sometime customize section need excute after packages has been loaded for
   flexible.
2. after! support module for determine some module has been loaded.

### Expected behavior

``` emacs-lisp
(after! (:all evil popup)
    ...)
```

``` emacs-lisp
(after! (:module :feature workspace)
    ...)
```

**Comment by hlissner** [comment]
Added support for `:all` and `:any` to `after!`, however, I will not introduce `:module` support because the implementation is non-trivial, and Doom doesn't support the workflow where modules are toggled during interactive sessions, so it doesn't make sense to do this.

Instead, you can conditionally run code based on module presence with:

```emacs-lisp
(when (featurep! :feature workspaces)
    ...)
```

**Comment by driftcrow** [comment]
It's enogh, thanks
