### ISSUE TITLE
Can't find emacs in your path

### ISSUE THREAD

**Issue by jacinthsamuel** [hlissner/doom-emacs#4453]
**What did you expect to happen?**
...Install doom

**What actually happened?**
...
The command line says can't find emacs in your path. I have attached a screenshot.

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
![2020-12-19-232214_1366x768_scrot](https://user-images.githubusercontent.com/71582349/102696073-9dabd380-4251-11eb-9ace-67af13dd1b05.png)

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>

Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by slebedev** [comment]
Hi @jacinthsamuel!

Have you installed emacs? It's required for doom-emacs

<img width="883" alt="doom-emacs-required" src="https://user-images.githubusercontent.com/2689220/102698383-ebbed800-424d-11eb-95a6-f04a356f845d.png">

**Comment by hlissner** [comment]
Hi! This issue was automatically deleted because it does not meet the minimum requirements for a bug report. There are a couple reasons why this may have happened. Please read the following carefully, because **repeatedly failing to meet these standards is a bannable offense.** 

1. It ignores the issue template, which asks that you include vital information, such as:
   1. Steps to reproduce the issue.
   2. A link to your personal config (if possible).
   3. Your `M-x doom/info`.
2. Your description of the issue is too vague and/or under-researched.
   + Avoid phrases like “it doesn’t work” or “X stopped working” without explaining what "working" and "doesn't work" mean to you. Better to explain what happened and what you expected to happen, instead.
   + Link to your personal config. Please don’t paste the contents of your config files in your post – these only pollute the search results. Use services like pastebin or gist, or better: github.
   + Screenshots and gifs go a long way to communicate an issue. Try to include them, if possible.
3. You've mentioned errors without including error messages or [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error). If you can't get either, include the last 15-20 lines of the \*Messages\* buffer after the error occurred (<kbd>SPC</kbd><kbd>h</kbd><kbd>e</kbd> or <kbd>C-h</kbd><kbd>e</kbd> will open this buffer).

Once you are ready, feel free to open another issue, but **please do not ignore the issue template when you do.** If you must omit parts of it, please offer an explanation why.

I apologize if this is an inconvenience, but please understand it is a lot of work to support and maintain this project on my own. I depend heavily on you to meet me half way on issues.

Thanks for using Doom!
