### ISSUE TITLE
[Suggestion] Integrate el-patch to keep advice up-to-date

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4495]
**Describe the feature**

As Doom uses quite a number of pieces of `:override` advice, `grep` counts 49 instances as of 0c92564, I thought it might be useful to integrate [`el-patch`][] into Doom and the Doom CLI to ensure the advice is updated whenever the original function definition changes. This should make Doom more resistant to regressions caused by upstream changes.

From the `README.md` of `el-patch`:
> ### What is it
>
> Like the [advice][advice] system, `el-patch` provides a way to customize the behavior of Emacs Lisp functions that do not provide enough variables and hooks to let you make them do what you want. The advantage of using `el-patch` is that you will be notified if the definition of a function you are customizing changes, so that you are aware your customizations might need to be updated.
>
> Using the same mechanism, `el-patch` also provides [a way][lazy-loading] to make lazy-loading packages much more easy, powerful, and robust.

`el-patch` is most useful in instances where you `:override` a function just to change a few forms of its definition. An example would be `+popup--evil-command-window-a` in [`modules/ui/popup/+hacks.el`](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/%2Bhacks.el).

Once the advice is ported to `el-patch`, checking for regressions caused by upstream changing patched functions should be as easy as calling `el-patch-validate-all` which can be integrated into `doom doctor`. It would also benefit any user that is using `el-patch` to have it integrated with Doom, for example by being notified whenever an update (`doom update` or `doom sync -u`) breaks their personal patches.

I am not affiliated with `el-patch` in any way, I just read of it and thought it might be useful as Doom liberally uses advice.

[`el-patch`]: https://github.com/raxod502/el-patch/blob/master/el-patch.el
[advice]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html
[lazy-loading]: https://github.com/raxod502/el-patch#lazy-loading-packages

**Comment by hlissner** [comment]
Hi! Thanks for the suggestion. I'm aware of el-patch and have already considered using it, but decided against it because it doesn't gel well with Doom's design. There are too many advice behind conditional or autoloaded code paths that won't be checked by `el-patch-validate-all`, and can't reasonably be consulted at runtime without considerable infrastructure. Building that infrastructure is a much more difficult endeavor than it may initially seem. 

In any case, I'm already working on a specialized tool for static analysis of advice, but it'll be quite some time until it is finished (much of it hinges on big changes introduced by #4273. In any case, thanks for the suggestion and for bringing it to my attention!
