### ISSUE TITLE
Change default email address from "jon@doe.com" to "jon@example.com"

### ISSUE THREAD

**Issue by bee-san** [hlissner/doom-emacs#4553]
In the default `config.el` we get:

```
user-mail-address "jon@doe.com"
```

`doe.com` is a private domain name.

We should use [example.com](https://en.wikipedia.org/wiki/Example.com) for the email, such as `jon@example.com`. This means that if someone uses a service and doesn't change the domain, someone might buy `doe.com` and bad things could happen.

We can guarantee that example.com will always be the de-facto example email.

**Comment by hlissner** [comment]
Thanks for the suggestion, but this is not a real problem. The closest `user-mail-address` comes to being used for sensitive information is to look up your _public_ ssh/pgp key by email address (instead of by fingerprint). If this were truly exploitable, there would be nothing stopping malicious third parties from using `john@example.com` instead. There is no legitimate security concern here.
