### ISSUE TITLE
Using map! to rebind an existing prefix map

### ISSUE THREAD

**Issue by aldanor** [hlissner/doom-emacs#4569]
I would like to have an alternative keybinding to workspace prefix map (`SPC TAB` by default), e.g. something like `SPC e`. But I can't seem to figure out how to do that with `map!` without copying a large chunk of code from default evil-bindings config module - wonder if there's a way to do it?

(Reason: `SPC TAB` is a much more ergonomic keyboard shortcut for switching between windows, like in spacemacs; any shortcut with a repeated letter like `SPC w w` is not a great fit for frequent use).

**Comment by n-clark** [comment]
Wondering the same thing. I rebound "v" to "g" for magit ended up just copy/pasting the entire leader key def. Surely there's a better way...

**Comment by hlissner** [comment]
```lisp
(map! :leader 
          "e" doom-leader-workspace-map
          "TAB" ...)
```

You'll notice [our leader prefixes](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el#L297) use `:prefix-map`. This defines a keymap named `doom-leader-<description>-map` that you can rebind like above. However, this isn't perfect, because it doesn't move the which-key labels with them. If that matters to you, your best bet is to just copy them into your local config.
