### ISSUE TITLE
Consider changing prefix for workspace and keybind for window switching

### ISSUE THREAD

**Issue by aldanor** [hlissner/doom-emacs#4572]
Suggestion, in brief:
- Change `:leader [tab]` to `:leader e` as a workspace prefix
- Bind `evil-window-next` to `:leader [tab]` and `evil-window-prev` to `:leader [backtab]`

Explanation and reasoning:
- Switching between windows is very likely to be a frequent action. Especially if you work with dual panes and have left window and right window that you constantly switch between. `SPC w w` is a very bad shortcut for it for two reasons:
  - It's three symbols and not two.
  - It contains a repeated character, `w w`, which is one of the most unergonomic two-character combinations since you're forced to use the same finger; it puts unnecessary repeated strain on the 4th left finger. Two repeated characters is also the *slowest* combination to type.
- The most frequent workspace actions, I believe, would be `SPC TAB 1` and `SPC TAB 2` (perhaps also `SPC TAB TAB`):
  - `SPC TAB TAB` is not nice due to having a repeated character, same as above.
  - `SPC TAB 1/2` is less ergonomic than `SPC e 1/2` - because the former involves fingers 5 and 3/4 and the latter - fingers 2/3 and 3/4/5.
- Unless I'm missing something, `e` prefix-map is not currently used; unless there's other plans for it, it's a great prefix key as it's super close to home row and it's not 4th/5th finger.
- If I remember correctly, `SPC TAB` is what Spacemacs used to use for window switching, so it will be an easier transition unless they've changed it.
- `SPC TAB` is logical in that it's like operating system's "alt-tab" or "cmd-tab".
- `SPC w w` and `SPC w W` can stay as they are, no need to remove them.
- As an experiment, try quickly mashing these combinations 10 times each and see which ones are faster and easier to type:
  - `SPC w w` or `SPC TAB`?
  - `SPC w W` or `SPC Shift-TAB`?
  - `SPC TAB TAB` or `SPC e TAB`?
  - `SPC TAB 1` or `SPC e 1`?
  - `SPC TAB 2` or `SPC e 2`?

**Comment by ymarco** [comment]
I think you're supposed to use `M-1` through `M-9` instead of `SPC TAB 1` through `SPC TAB 9`. At least I do. Both are bound.

**Comment by aldanor** [comment]
@ymarco Yea, `M-1` is definitely more ergonomic than `SPC TAB 1`.

In fact, it's even better - if noone's using `SPC TAB <n>` anyway, would be less of a problem to move the prefix to another letter.

**Comment by hlissner** [comment]
Repeated keys aren't ideal and tab is a bit out of the way, but unless you're typing these whole key sequences consecutively, in rapid succession (e.g. `SPC TAB TAB SPC TAB TAB SPC TAB TAB`), I don't think `SPC TAB` is a problem. I reach for `SPC TAB` maybe 2-4 times a minute during casual use. Keys that might be overused to such an extent have shorter alternatives (like `M-{N}` as ymarco mentioned or `gt`/`gT` & `[w`/`]w` for next/previous tab).

Repeated keys are in fact common in our keybind scheme, to indicate and emphasize the "primary" command of a prefix. e.g. `SPC f f` = find file in project, `SPC p p` = switch project. `SPC g g` = open magit. It's easy to remember. More common ones are given a shortcut, e.g. `SPC f f` is on `SPC SPC` too, by default.

> SPC w w is a very bad shortcut for it for two reasons:

If `SPC w` is not to your liking, I'd suggest `C-w`. They are aliases. The former only exists as a convenience to `SPC` acolytes and spacemacs refugees. Vim users should be used to `C-w`. The same key is also available on `C-w C-w` for this reason.

> Unless I'm missing something, e prefix-map is not currently used; unless there's other plans for it, it's a great prefix key as it's super close to home row and it's not 4th/5th finger.

The mnemonic of `e` makes little sense to me. It's on TAB because workspaces were designed to emulate vim tabs. Not sure where else to put it, but I think it's fine where it is.

> SPC TAB is what Spacemacs used to use for window switching, so it will be an easier transition unless they've changed it.

This is trivial to do so I leave it to users:

```elisp
(map! :leader "TAB" #'whatever-spacemacs-does-on-spc-tab)
```

But I think it's more sensible to have window commands under the window prefix. Whats more, I've remapped `other-windw` (on `SPC w w` to `ace-window`, so with the exception of jumping between two splits, you don't really need to press it more than once when 3+ splits are involved (it prompts for you to select one directly). If you are using `:ui (window-select +numbers)` you can use numbers to jump directly to a window via `C-w {N}` ,where N = 0-9.

Those are my thoughts for now. I'll revisit this once I've cleared my plate a bit.
