### ISSUE TITLE
All-the-icons broken again

### ISSUE THREAD

**Issue by trevarj** [hlissner/doom-emacs#4668]
I believe it is related to this issue: #724
When you install doom and it asks you to install the all-the-icons fonts it gets stuck. It may be due to the all the icons repo not being correct

From all-the-icons.el:
```
-    (let* ((url-format "https://raw.githubusercontent.com/domtronn/all-the-icons.el/master/fonts/%s")
+    (let* ((url-format "https://github.com/domtronn/all-the-icons.el/blob/master/fonts/%s?raw=true")
```

**Comment by hlissner** [comment]
The fonts install fine for me, on NixOS, Arch, MacOS (Big Sur), and Ubuntu. The URL seems to be correct. This is likely a networking issue. Perhaps your ISP/place of work has blocked githubusercontent.com?

As this is not a Doom issue, I will close this. If you believe there is an issue with the url, better to report this to all-the-icons, rather than Doom.
