### ISSUE TITLE
How rebind C-x 0 to delete-window rather than the (+workspace/close-window-or-workspace)

### ISSUE THREAD

**Issue by AbstProcDo** [hlissner/doom-emacs#4722]
Doom binds C-x 0 to `(+workspace/close-window-or-workspace)`, which is not handy. because, the function closes not only the window but also the buffer as well.

For instance, when I open a eshell window and C-x 0 to close the window.  The eshell buffer is destroyed at the same time. You cannot strike C-x 4 b to invoke the previous eshell again.

So I want to rebind C-x 0 to `delete-window` just as vanilla emacs does.

`(global-set-key (kbd "C-x 0") 'delete-window)
`

Unfortunately, it fails to works, while C-x 0 still bind to  `(+workspace/close-window-or-workspace)`, 

How could I rebind C-x 0 to delete-window?

**Comment by hlissner** [comment]
> the function closes not only the window but also the buffer as well.

False. `+workspace/close-window-or-workspace` does not kill buffers. The reason eshell dies is because of the `:ui popup` module cleaning up after itself. `M-x eshell` will produce a popup window.

Use `SPC o e` (`+eshell/toggle`) or `SPC o E` (`+eshell/here`) instead. The former creates a popup. The latter uses the currentw indow. Neither will kill themselves when the window is closed.

Otherwise, remove the `:ttl` property [from `+popup-defaults`](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/autoload/settings.el#L13). `ttl` = time to live (for the buffer after the popup's been closed). The default of `5` means kill the buffer after 5 seconds. Though, removing this may have other side effects.

```lisp
(plist-put +popup-defaults :ttl nil)
```

> I want to rebind C-x 0 to delete-window just as vanilla emacs does.

[Why you can't bind it.](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/workspaces/config.el#L179-L181)

To "fix" it, either:

```lisp
(map! "C-x 0" (cmd! (delete-window)))
```

or

```lisp
(map! :after persp-mode
      :map persp-mode-map
      [remap delete-window] nil)

(map! "C-x 0" #'delete-window)
```
