### ISSUE TITLE
M-x doom/info clogs issue search

### ISSUE THREAD

**Issue by edrex** [hlissner/doom-emacs#4742]
By encouraging reporters to include a list of all enabled packages in the issue text, the issue search is rendered much less useful. Most of my searches have hundreds of matches, and the ones at the top are completely unrelated to my search. Consider encouraging reporters to use a pastebin or similar?

**Comment by hlissner** [comment]
Yes, you're right. I am painfully aware of how much it has polluted the search results. Unfortunately, our Github issue tracker is too far gone.

That said, very soon, we will move to Discourse (as our issue tracker and place for discussion/support). There, I have much more control over posts and how they are displayed, validated, and indexed. I'm brainstorming a solution to this that won't require an extra step from users (or, if it must, they will be warned at submission-time, rather than a moderators' pestering). The concept I'm experimenting with: those `M-x doom/info` blocks are encoded into, say, base64 -- meaningless to the search engine -- but with a little JS trickery will still be perfectly readable to humans.

In any case, we will have a better search engine for issues soon, but Github won't be it. I will close this since I'm in the process of cleaning up out github in preparation for the switch, but feel free to follow up here.

**Comment by edrex** [comment]
Discourse does seem like a good fit for a project like this. I wish you success in the transition!
