### ISSUE TITLE
 cl-lsp 

### ISSUE THREAD

**Issue by OrionRandD** [hlissner/doom-emacs#4747]
Is that possible to add cl-lisp to doom new updates/version?
Although I still think there are lots of things in the list to be done and
I am not sure if it is in a good state to be added to doom.

https://github.com/cxxxr/cl-lsp

**Comment by hlissner** [comment]
Hi! Thanks for the suggestion, but without a compelling argument to demonstrate that it can stand up to the behemoth that is `sly` I cannot add `cl-lsp` to Doom. I do not include packages to check boxes and it appears to be trivial for users to add themselves. If you can supply such a demonstration feel free to follow up here -- I'm willing to change my mind. Otherwise I'd like to wait until it reaches such a level.
