### ISSUE TITLE
Remap ':' to ';'

### ISSUE THREAD

**Issue by gs** [hlissner/doom-emacs#4779]
How do I remap the command key from ':' to ';'.

This can be done in spacemacs by overwriting the 

```
  ;; The key used for Vim Ex commands (default ":")
   dotspacemacs-ex-command-key ";"                                   
```
and in vim 
```nnoremap  ;  :  ```

how do I do that in `doom-emacs` ?

**Comment by steven-lang** [comment]
You can use doom's `map!` definition for that, see [here](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-bind-my-own-keys-or-change-existing-ones) for more information on that.

The command you're looking for would be something like this:
```emacs-lisp 
(map! :nv ";" #'evil-ex)
```

**Comment by hlissner** [comment]
Steven's answer is correct.

Anyhow, this post has been marked for deletion because our issue tracker is not for questions, how-to's, and discussion. Instead, please post to one of:

+ [Our discourse](https://discourse.doomemacs.org) (will be up soon)
+ [Our discord](https://discord.gg/qvGgnVx)
+ [On r/emacs](https://www.reddit.com/r/emacs/)
+ [On r/orgmode](https://reddit.com/r/orgmode/)
+ [The relevant StackOverflow sites](https://www.emacswiki.org/emacs/EmacsStackExchange)
+ [One of the Emacs IRC channels](https://www.emacswiki.org/emacs/EmacsChannel)
