### ISSUE TITLE
SPC g Y and SPC g o O for browsing-at-remote commit

### ISSUE THREAD

**Issue by verhovsky** [hlissner/doom-emacs#4784]
When copy and pasting links to a remote git repo, I always want to include the commit hash in the link so that it doesn't become stale as the underlying file changes. I am constantly doing `SPC g o` and then pressing "y" in the browser which (at least on Git{Hub,Lab}) changes the URL to include the hash instead of the branch. So I added the following to my config

```elisp
(after! browse-at-remote
  (setq browse-at-remote-prefer-symbolic nil))
```

But sometimes when I just want to look at the file and do stuff in the web browser I want to open the file at the branch name. So I think we should have a second binding that has the same effect as having the above in your the config, so that I'm able to use `SPC g y` normally and get a branch name url still. 

Or maybe `SPC g y` should copy a URL with the commit hash but `SPC g o o` should open on the branch.

I think this would require changes upstream. There's a config option to just always use the commit hash instead of branch names here https://github.com/rmuslimov/browse-at-remote/blob/fadf99d6d8e891f3b112e36c772e0eea0b9bc7f2/browse-at-remote.el#L68-L77

**Comment by hlissner** [comment]
As of fa4f03d I've made two changes:

+ Default `browse-at-remote-prefer-symbolic` to `nil` because permanent links are generally more desirable for developers sharing links.
+ Add prefix arg support to 'SPC g y' and 'SPC o o'. The prefix arg will negate the default value of `browse-at-remote-prefer-symbolic` for that call. e.g. `SPC g y` = copies the link with commit hash, `SPC u SPC g y` = copies the link with branch name.
