### ISSUE TITLE
OCaml module requires manual specification of `(package! merlin-company)`

### ISSUE THREAD

**Issue by aschaap** [hlissner/doom-emacs#4864]
Starting with the default config, I enabled the OCaml layer and tried `C-c t` in an open `.ml` file to see the type of what was under the cursor. The error shown was that `merlin-company` package was missing. After specifying `(package! merlin-company)` in `packages.el` and running `doom sync`, `C-c t` works as expected. Would it be possible to install it automatically when enabling the `ocaml` module (and when `:completion company` is set, as outlined in the `ocaml` module's `README.org`)?

**Comment by hlissner** [comment]
Hi! This issue was closed and marked for deletion because it does not meet the minimum requirements for a bug report. There are a couple reasons why this may have happened. Please read the following carefully, because **repeatedly failing to meet these standards is a bannable offense.** 

1. It ignores the issue template, which asks that you include vital information, such as:
   1. Steps to reproduce the issue.
   2. A link to your personal config (if possible).
   3. Your `M-x doom/info`.
2. Your description of the issue is too vague and/or under-researched.
   + Avoid phrases like “it doesn’t work” or “X stopped working” without explaining what "working" and "doesn't work" mean to you. Better to explain what happened and what you expected to happen, instead.
   + Link to your personal config. Please don’t paste the contents of your config files in your post – these only pollute the search results. Use services like pastebin or gist, or better: github.
   + Screenshots and gifs go a long way to communicate an issue. Try to include them, if possible.
3. You've mentioned errors without including error messages or [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error). If you can't get either, include the last 15-20 lines of the \*Messages\* buffer after the error occurred (<kbd>SPC</kbd><kbd>h</kbd><kbd>e</kbd> or <kbd>C-h</kbd><kbd>e</kbd> will open this buffer).

Once you are ready, feel free to update your issue and this will be reversed (or let the timer run out and it will be removed), but **please do not ignore the issue template when you do.** If you must omit parts of it, please offer an explanation why.

I apologize if this is an inconvenience, but please understand it is a lot of work to support and maintain this project on my own. I depend heavily on you to meet me half way on issues.

Thanks for using Doom!

**Comment by hlissner** [comment]
@gagbo, on Discord, let me know that `merlin-company` was moved out of the `merlin` package [a short while ago](https://github.com/melpa/melpa/commit/17598d9a0e9f88db28014019769f3181c863e99e). I've added a `package!` declaration for it to the `:lang ocaml` module as of ee1885e, so I'll consider this resolved.

In any case, please do not ignore the issue template in the future. Thanks for bringing it to my attention!

**Comment by aschaap** [comment]
My apologies. Thank you for all your hard work on Doom!
