### ISSUE TITLE
Evil remains active in calc-mode

### ISSUE THREAD

**Issue by elecprog** [hlissner/doom-emacs#4906]
**What did you expect to happen?**
Evil to be fully disabled in calc-mode.

**What actually happened?**
Evil mode remains (partially) active. Particularly the `hjkl` keys, interfering with, for instance help.

**Additional details:**
None, really. However, a default keybind for calc and/or quick-calc might be useful (eg. `SPC t c`), but that would be a separate issue.

**Steps to reproduce:**
1. Open calc mode (`M-x` `calc` or `calc-mode`).
2. Press (for instance) the `h` key.

**System information:**
<https://pastebin.com/34GUJJAE>

**Comment by hlissner** [comment]
We use evil-collection, which provides evil integration for `calc`. Your options:

1. Study [evil-collection-calc](https://github.com/emacs-evil/evil-collection/blob/master/modes/calc/evil-collection-calc.el) to learn how to use it.
2. Disable `evil-collection-calc`: `(add-to-list '+evil-collection-disabled-list 'calc)`
3. Or forcibly revert to emacs state in calc-mode: `(set-evil-initial-state! 'calc-mode 'emacs)`

Since this isn't a bug and our issue tracker isn't for how-to or config help questions I will close this.

**Comment by elecprog** [comment]
```
;; "h" 'calc-help-prefix ; TODO: Rebind?
```

This explains it. Thank you!
