### ISSUE TITLE
Customize the path to zstd executable

### ISSUE THREAD

**Issue by minyez** [hlissner/doom-emacs#4927]
**Describe the feature**

Hi all. When I try to save changes to a file, the following zstd error occurs

```plain
Error while executing "zstd -c -q < /var/folders/k6/tempfilexxxxx"

zstd: error 11 : Unsupported parameter
```

It seems that this happens because `which zstd` points to zstd installed by miniconda (pyenv).
When using Homebrew zstd, things go without error. So I am thinking about if it is possible to customize the path to zstd executable in Doom.

Actually, I am not sure what the two zstd differ (both in version 1.4.9) and whether it is an issue of Doom or some upstreams, so I open this issue as a feature request. Any advice will be appreciated.

**System information**

https://pastebin.com/jY9zGHCG

**Comment by hlissner** [comment]
The `jka-compr-compression-info-list` variable contains a list of commands and switches for each type of compressed file.

You can add a corrected entry to it:

```elisp
(add-to-list 'jka-compr-compression-info-list
             ["\\.zst\\'"
              "zstd compressing"   "/path/to/zstd" ("-c" "-q")
              "zstd uncompressing" "/path/to/zstd" ("-c" "-q" "-d")
              t t "\050\265\057\375"])
```

Otherwise, the first `zstd` in your `PATH` is used. If it's not locating the correct std, you need to correct your `PATH`. Check `C-h v exec-path` in Emacs to see the `PATH` as Emacs sees it. You can regenerate your envvar file (which provides the initial value for `exec-path` at startup) by running `doom env`.

But if you're using a plugin like pyenv.el to activate the pyenv per-buffer, then `exec-path` is likely being changed on the fly, in which case you'll have to use the first solution above.

As this is not really a bug or issue with Doom (or one that Doom can solve for you) I will close it, but feel free to follow up here.

**Comment by minyez** [comment]
Thank you very much for your time and the clarification!
