### ISSUE TITLE
Install issue on Windows 10

### ISSUE THREAD

**Issue by nmillington** [hlissner/doom-emacs#4951]
**What did you expect to happen?**

Reinstalled doom emacs on a Windows system using doom install after cleaning out .emacs.d. while trying to fix an org-brain issue caused by recent commits.  Now will not install.

**What actually happened?**

Throws a void function exception.  doom build will build packages, but doom install and doom sync fail with identical errors.  New behaviour.

**Additional details:**
I'm aware this is a very niche configuration for Doom Emacs, but I've been trying to keep it working on a very heavily locked down system and until now have been working fine, albeit a bit slow.

Full log trace:  https://pastebin.com/gbzTQfnm

**Steps to reproduce:**
1.  Get precompiled emacs 27.1, set up path correctly.
2. Use stand alone git configuration (git.exe, in local user path)
3. Run git clone doom-emacs as normal
4. Run doom install

**System information:**
uname is obviously not installed :)

**Comment by myshevchuk** [comment]
I had a similar issue on MacOS (this is irrelevant probably) during an upgrade. The error was not exactly the same but also similar: `(void-function straight--process-buffer)`. I was able to fix it by going to `$DOOM/.local/straight/repos/straight.el` and checking out manually the latest commit bumped into Doom core:
```sh
cd .doom/.local/straight/repos/straight.el
git checkout 253d7db
doom upgrade
```

Since you are installing afresh, you may need to manually clone `straight.el`.

**Comment by ihdavids** [comment]
I am running into something similar.
The build is complaining about void-function straight-call.

**Comment by ihdavids** [comment]
How did you determine this: 
and checking out manually the latest straight.el commit bumped into Doom core:

**Comment by ihdavids** [comment]
I am however using a locally built 28.0.50 on Windows in the hopes that it helps with my performance woes on windows.

**Comment by ihdavids** [comment]
About a month ago I upgraded on my windows laptop to 28.0.50 and it has been much much faster. I was trying to run 28.0.50 through WSL and X410 on my desktop and while it is even faster, accessing files on the windows filesystem results in lockups and major performance problems.

However, on my fresh install with msys2 I am now getting these straight.el issues.

**Comment by myshevchuk** [comment]
I just reasonably assumed that the issue was related to `straight.el`. I then checked recent commits in Doom that had something to do with `straight.el`. Indeed, commit f60f5760481ec15725ddec623b4d19be3a53709c from yesterday "upgrades" `straight.el` from `0f9b828` to `253d7db`. I then went to `.doom/.local/straight/repos/straight.el` and found out that straigth.el was not upgraded, the head was on `0f9b828`. Upgrading `straight.el` manually to the version Doom expects (`253d7db`) fixed the problem.

Probably, Doom internals rely on the newer version of straight.el. But the new version cannot be installed, because it is not installed yet. Something of these sorts.

**Comment by myshevchuk** [comment]
Probably it has nothing to do with Windows or 28.0.50.

**Comment by ihdavids** [comment]
I checked straight.el and it was synced to that changeset already. I tried syncing to head but that resulted in the same behaviour, I am wondering if I need to regenerate the elc and or clean some cached data as straight--call is a function defined in the synced version.

**Comment by myshevchuk** [comment]
This may help I think.

**Comment by ihdavids** [comment]
??
Looking back through the straight.el history it looks like we want 0ac2df7 right before: 

Refactor external process API. (#714) …
@progfolio
progfolio committed on Mar 18

Which is where they removed straight--call

I am struggling to sync there at the moment.

**Comment by ihdavids** [comment]
Heh, sync there and now I get problems with straight--process-buffer!
So I need head I guess.

**Comment by ihdavids** [comment]
Seems replacing straight--call with straight--process-run does get things running.

**Comment by ihdavids** [comment]
PR: https://github.com/hlissner/doom-emacs/pull/4952

**Comment by ihdavids** [comment]
Not sure how to get this reviewed.

**Comment by hlissner** [comment]
#4952 was merged, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by nmillington** [comment]
Cheers guys, looks like my issue is fixed and emacs is defiantly sitting on a locked down windows laptop again.
