### ISSUE TITLE
Setting custom formatter using setq-hook! results in error message

### ISSUE THREAD

**Issue by ohhskar** [hlissner/doom-emacs#4956]
**What did you expect to happen?**
Setting a formatter for web-mode using `(setq-hook! 'web-mode-hook +format-with 'prettier)` to work and format buffers using prettier. The formatter chose was based on the name of the formatter set in https://github.com/lassik/emacs-format-all-the-code/blob/master/format-all.el.

**What actually happened?**
Running the `+format/buffer` results in `apply: Wrong type argument: stringp, t`

**Additional details:**
Config: https://github.com/ohhskar/.doom.d

**Steps to reproduce:**
1. Set formatter using `(setq-hook! 'web-mode-hook +format-with 'prettier)` in config.el.
2. run `doom sync`
3. Restart emacs
4. Open HTML File
5. Run `+format/buffer`

**System information:**
https://pastebin.com/DHGbhhNp

**Comment by hlissner** [comment]
The format module is overdue a rewrite, so your best bet is to use `set-formatter!` to set a prettier shell command to pipe to instead:

```elisp
(after! web-mode
  (set-formatter! 'prettier '("prettier" "--stdin-filepath" buffer-file-name)
    :modes 'web-mode))
```

Otherwise, try the [prettier.el](https://github.com/jscheid/prettier.el) package until our format module is rewritten.

As this is nothing immediately actionable here (and a summary issue for rewriting the format module is in the works) I will close this, but feel free to follow up here.

If that doesn't work, please provide a backtrace of your error. Please include one whenever you report an error message in bug reports.
