### ISSUE TITLE
Crash when using the 'repeat' function (".") after exporting to Latex in org mode

### ISSUE THREAD

**Issue by loopdreams** [hlissner/doom-emacs#5047]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When in org mode, I make an edit. Then, I export to a pdf via Latex. 

Then, I want to repeat my previous edit someplace else so I press the vim 'repeat' command "."

### What actually happened?

After exporting to Latex/pdf, pressing the repeat/dot key causes emacs to crash. I presume it's trying to repeat the 'export' command again and fails.

There were no error messages or anything. It just completely locked up and had to be force-killed. 

### Describe your attempts to resolve the issue

I tried the same process on another machine with the same result. I also tried it from within a normal .tex document, using the C-c C-a export function and it didn't crash (just re-exported the file). 

I don't have any programming/computer knowledge so I couldn't do much to try fix it. I'm just posting this here in case it is helpful. If not, I am very sorry.

### Steps to reproduce

1. Open a file in org mode
2. Export the file (space - m - e - l - p) (org export - latex - to pdf)
3. press "."

### System Information

https://pastebin.com/8XHGeCVi

**Comment by hlissner** [comment]
Try this:

```elisp
;; ~/.doom.d/config.el
(after! evil
  (evil-add-command-properties 'org-export-dispatch :repeat nil)
  (evil-add-command-properties 'org-latex-export-to-pdf :repeat nil))
```

This should stop evil-repeat from repeating org exporting.

To try to address the crash directly:

+ Your doom/info says you're on ce65645, but you checked ` I can reproduce my issue on the latest commit of Doom Emacs`. Which is true? Make sure you're on the latest version of Doom.
+ Crashes are rarely Doom issues. It's more likely that you have a faulty install of Emacs. Try another version or package on your system. Or reinstalling Emacs.
+ Are you able to "escape" the freeze by mashing <kbd>ctrl</kbd><kbd>g</kbd> for a minute or so?
+ Run `kill -USR2 $PID` in your shell, but replace $PID with Emacs' process id. You can find that with `ps aux | grep emacs` (second column from the left). This should hopefully "break" emacs out of its freezes then produce a backtrace. A backtrace would go a long way toward helping me figure out the crash.
+ Try to use [another font](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-fonts) on your system. If that doesn't help, make sure you have the `Symbola` font installed on your system. Crashes due to insufficient font support are common.

If none of these work, then I'm not sure there is anything Doom or I can do without more leads.

**Comment by loopdreams** [comment]
Hi, thank you so much for the reply, it helps a lot.

- I am sorry for not realising I wasn't on the current version of Doom, I updated it and the crash still happens.

- I tried changing fonts and installing Symbola but it didn't seem to change it. 

- Typing `ctrl g` does indeed escape the freeze, almost instantly.

For now, I'll add the lines disabling the repeat command for org-export, that should work perfectly for me :) I will try reinstalling Emacs eventually.

I did kill the process using the method you suggested and got this output. I'll link it here in case it helps, but I'm not sure how to read/debug it.

[https://pastebin.com/EPELk1v7](url)
 
Thank you so much again, I've only been using doom/emacs for about a month now but I'm absolutely in love with it!
