### ISSUE TITLE
make task  tar all needed files for works on nointernet pc

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#514]
`make quickstart` is simple but convenient, I think somebody need another task
that  tar all config and  package files for move doom to a PC without internet connect.

**Comment by bitwalker** [comment]
Seems to me that you could just run `git archive -o backup.tar` and copy the tarball to wherever, not sure it really needs to be a make task provided by doom. If you want it to backup private configs or customizations too, that's going to be too prone to failure, since people may symlink things into their config directory, or reference external files, etc. I would recommend building something based on your own needs, whether that's a custom backup script or maybe something  built on GNU Stow, or something else entirely.

**Comment by hlissner** [comment]
This is currently beyond the scope of Doom's makefile. This may change around 2.1.6, but for the time being there are no plans to do this, and I'd rather not crowd Doom's makefile.

If it's something you expect to do often, I suggest creating a `~/.doom.d/bin` directory, putting it into your `PATH` and adding a backup script there.
