### ISSUE TITLE
neotree doesn't update with project switches

### ISSUE THREAD

**Issue by Dentrax** [hlissner/doom-emacs#5148]
### 

- [ ] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [ ] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [ ] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I don't know exactly neither this is bug nor unsupported operation. I was just wanted to add all the project in the `neotree`. I couldn't add more than one project to neotree, so I decided to swtich between the projects.

Neotree should be updated between project switches.

Similar to this issue: https://github.com/hlissner/doom-emacs/issues/1348
But it seems it only fixed for treemacs in this PR: https://github.com/hlissner/doom-emacs/pull/2819

### What actually happened?

_I couldn't follow that debugging guidelines because doomemacs.org requires _sign-up_. Is there anywhere else I can read at these? (i.e. README, docs, etc.)_

### Describe your attempts to resolve the issue

1. Switch project `SPC p p`
2. Close neotree `SPC o p`
3. Open neotree `SPC o p`

### Steps to reproduce

I have two workspaces open, each with different projects.
Open neotree in one workspace.
Switch to another workspace `SPC TAB [`, the project tree is still open with the old project.

1. Jump to project path and: `$ emacs .`
2. Open `neotree`
3. Add new project `SPC p a`
4. Switch project `SPC p p`

### System Information

https://paste.ubuntu.com/p/6v8rF3W2ph/

**Comment by hlissner** [comment]
This is not something neotree is really capable of. You may prefer treemacs if you want to be able to add multiple projects to your project tree, or try `(add-hook 'projectile-after-switch-project-hook #'neotree)`, but remember that "switching projects" to projectile is when you explicitly called `SPC p p` (`counsel-projectile-switch-project`).

As that would be a terribly intrusive default, I will leave it to users to configure.

Since there is nothing to do here I will close this, and since this is more of a how-to/config question than an issue (which don't belong on our issue tracker) I will mark it for deletion, but feel free to follow up here.
