### ISSUE TITLE
Multi core native compilation?

### ISSUE THREAD

**Issue by tsoernes** [hlissner/doom-emacs#5164]
### 

- [X] I have read the [contributing guidelines](https://discourse.doomemacs.org/how2contribute).
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues?q=label%3A%221.+request%22+) for similar requests.
- [X] I have searched [the module list](https://doomemacs.org/docs/modules.org) in case my feature was already implemented.
- [X] I have confirmed that my request remains unfulfilled on [the latest commit of Doom](https://github.com/hlissner/doom-emacs/commit).

### Describe your request

I'd like doom to incorporate multi core native compilation. After a `doom sync -u`, there's 1200 files to compile, and only one of 6 physical cores are in use!

### Briefly explain its use-case

Faster upgrades

**Comment by fosskers** [comment]
I personally see all my cores being used.

**Comment by destroyer449** [comment]
Whenever I update doom, the native compilation always uses all of my cores. Perhaps there is an issue in your private config that prevents the same from happening for you?

**Comment by petr-tik** [comment]
> I'd like doom to incorporate multi core native compilation. After a `doom sync -u`, there's 1200 files to compile, and only one of 6 physical cores are in use!

This is the relevant code 
https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/comp.el#L3860-L3879

Try `C-h v comp-num-cpus`. If that is nil, try evaluating the sexp that ends on this line
https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/comp.el#L3878

this should give you the number of cores that native-comp uses

**Comment by hlissner** [comment]
By default, `comp` uses half your cores to native compile packages. Doom alters this to use *all* your cores (but will fall back to `1` if your system lacks all [the common methods of reading your number of cores](https://github.com/hlissner/doom-emacs/blob/develop/core/autoload/system.el#L81-L107)). Since you did not provide your `M-x doom/info` I cannot determine anything more from your circumstances.

You can explicitly set the number of cores to use by throwing `(setq native-comp-async-jobs-number N)` into `~/.doom.d/init.el`.

In any case, since this is not a Doom issue I will close this.
