### ISSUE TITLE
`org-mode` freezes on some files

### ISSUE THREAD

**Issue by tobiasBora** [hlissner/doom-emacs#5183]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I expect to be able to type into an org-buffer without freezes.

### What actually happened?

When starting `org-mode`, when I don't type during more than a few seconds the buffer sometimes freezes until I press `C-g`. I then need to type quickly and continuously otherwise I may hit another freeze.

This freeze is not systematic. I encounter much more often on some big files (around 46K or 67K). Sometimes, I get this bug many times in a raw, and sometimes I don't encounter it during much longer.

I tried to check in the message buffer, I can't see any error.

### Steps to reproduce

1. Open in doom emacs a big org-mode file
2. Naviguate in the file, start to type, and do sometimes some ~5 seconds breaks. "Hopefully" your buffer will freeze.

### System Information

https://pastebin.com/Hpa1KTED

**Comment by hlissner** [comment]
Hi! This issue was closed and marked for deletion because it does not meet the minimum requirements for a bug report. There are a couple reasons why this may have happened, but generally it means the bug report could not be reproduced in any of our test environments and/or was too vague to act on or investigate further.

Please feel free to contest this if you think this was a mistake or follow up with more information to reverse this ruling. Perhaps our [how to debug issues](https://discourse.doomemacs.org/how2debug) guide can help you gather more information (our discourse requires an account for the time being).

I apologize for the inconvenience, but please understand it is a lot of work to support and maintain this project on my own and every unactionable bug report is attention taken from actionable ones.

Thanks for using Doom!
