### ISSUE TITLE
Creating a git commit with emacsclient kills the entire session.

### ISSUE THREAD

**Issue by prati0100** [hlissner/doom-emacs#5195]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I open a file in a Git repo with emacsclient, open Magit, press `cc` to commit, it opens an editor window. Once I am done writing the commit message, I press `C-c C-c` (`SPC h k` maps it to `with-editor-finish`) to finish the editing and create the commit.

It should create the commit and drop me back to the Magit status page.

### What actually happened?

It creates the commit successfully, but it also ends the entire client session and kills all the buffers I opened in that session. The window still remains open, it just drops me to the "Doom Emacs" landing page. I then need to reopen all the files manually.

This used to work correctly at one point. I can't say when exactly this got broken since I don't upgrade very often.

Committing still works fine if you open the full emacs. This just happens when using emacsclient.

### Describe your attempts to resolve the issue

I tried to read through the source, but to little gain. My lisp is not very fluent.

### Steps to reproduce

1. Open a file in a Git repo with emacsclient.
2. Open Magit using `SPC g g`
3. Stage a file and commit using `c c`
4. Write the commit message, and finish commiting with `C-c C-c`
5. Now the entire client session should be closed, instead of just the commit message buffer.

### System Information

https://pastebin.com/Duj2nsXM

**Comment by jakeisnt** [comment]
Do you have any sort of stack trace from emacs that you can provide? Client or server.

**Comment by yqrashawn** [comment]
Same thing happens here. But I find it only happends the first time on each `emacs --daemon`.

**Comment by yqrashawn** [comment]
Ok. It's caused by this `(add-hook 'server-done-hook #'+workspaces-delete-associated-workspace-h)` at https://github.com/hlissner/doom-emacs/blob/2731685095d1e6101b3215aa689426e1834ce00f/modules/ui/workspaces/config.el#L185

The call stack is 
`with-editor-finish` https://github.com/magit/with-editor/blob/5519b6a67ecd66865b4fdd5447425eee900c54f4/with-editor.el#L333
`with-editor-return` https://github.com/magit/with-editor/blob/5519b6a67ecd66865b4fdd5447425eee900c54f4/with-editor.el#L342
`server-done` https://github.com/magit/with-editor/blob/5519b6a67ecd66865b4fdd5447425eee900c54f4/with-editor.el#L396
`server-buffer-done` https://github.com/magit/with-editor/blob/5519b6a67ecd66865b4fdd5447425eee900c54f4/with-editor.el#L396
`run-hooks` https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/server.el?h=2540701f300144fba8a3871f1f0c046c0ff41c5a#n1525

one thing might relate to this is the `server-clients` returns two proc, the `emacsclient` I started and the `emacsclient` with-editor started.
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/server.el?h=2540701f300144fba8a3871f1f0c046c0ff41c5a#n1495

might be related to 
https://github.com/magit/magit/issues/2197 and https://github.com/magit/magit/commit/5c0291021ba73b94c971e400dd58b4c0964e9a88

my solution here is a temp hack, which just skip the `+workspaces-delete-associated-workspace-h` when current buffer is named `"COMMIT_EDITMSG"`, which is definitely not the right way to fix this.

```elisp
(defadvice! ++workspaces-delete-associated-workspace-h (orig-fn &optional frame)
  :around #'+workspaces-delete-associated-workspace-h
  (when (not (string= (buffer-name (current-buffer)) "COMMIT_EDITMSG"))
    (orig-fn frame)))
```

**Comment by howdoicomputer** [comment]
Ah, so that's what was going on. Was unsure of what to put into a ticket.

**Comment by hlissner** [comment]
@yqrashawn Thanks for the thorough investigation! That's made things much easier for me.

Could you try this advice instead and see if it solves the issue?

```elisp
(defadvice! ++workspaces-delete-associated-workspace-h (orig-fn &optional frame)
  :around #'+workspaces-delete-associated-workspace-h
  (unless (bound-and-true-p with-editor-mode)
    (apply orig-fn frame)))
```

**Comment by hlissner** [comment]
As of 3aeb0c0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
