### ISSUE TITLE
shell doesn't work as expected with Starship: disabled due to TERM=dumb > (tmux - zsh)

### ISSUE THREAD

**Issue by Dentrax** [hlissner/doom-emacs#5201]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I do `M-x :shell`, it should work?

### What actually happened?

```
Ptmux;]1337;SetKeyLabel=F1=👉 public/foo\Ptmux;]1337;SetKeyLabel=F2=🎋 main\Ptmux;]1337;SetKeyLabel=F3=🔥[?]\Ptmux;]1337;SetKeyLabel=F4=🔼 push\Ptmux;]1337;SetKeyLabel=F5=🔽 pull\Ptmux;]1337;SetKeyLabel=F6=F6\]2;~/src/public/foo[ERROR] - (starship::print): Under a 'dumb' terminal (TERM=dumb).
Starship disabled due to TERM=dumb > 
```

https://user-images.githubusercontent.com/16493751/123158835-f2384180-d474-11eb-9c51-f8dd50f3db28.mov

### Describe your attempts to resolve the issue

🤷‍♂️

### Steps to reproduce

1. Open the Terminal (zsh) with Starship installed
2. Start the doom `$ emacs . &`
3. Call `M-x :shell`

### System Information

https://paste.ubuntu.com/p/sNmKB4CJSD/

**Comment by destroyer449** [comment]
As described in the FAQ, shell is more of a repl for your shell environment, and is not capable of most graphical display cases. The term, and vterm modules however are more sophisticated and will be able to handle starship with no problems at all.

**Comment by jakeisnt** [comment]
I second using vterm. "TERM=dumb" is expected behavior here.

**Comment by hlissner** [comment]
What @destroyer449 said. `shell` is not a terminal emulator and it's current behavior is behaving correctly. Use `vterm` or `term` if you want a terminal emulator.

**Comment by Dentrax** [comment]
Thanks! I tried both of `term` and `vterm` but I got some issues:

`term`:

![Screen Shot 2021-07-12 at 09 54 46](https://user-images.githubusercontent.com/16493751/125243773-32ae1100-e2f7-11eb-9bee-c028b7670b9b.png)

`vterm`:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../vterm-module.so] Error 1
make[1]: *** [CMakeFiles/vterm-module.dir/all] Error 2
make: *** [all] Error 2
```

Should I create another issue for the `vterm` compilation error? 🤔

**Comment by hlissner** [comment]
@Dentrax In this case, starship is putting out ansi codes that `term` does not recognize. Perhaps starship can't cope with `TERM=eterm-color` either. Try setting it to `xterm256-color` in your shell dotfiles when you're in Emacs. Otherwise this seems like a configuration issue on starship's side, but I'm not familiar with starship so I'm afraid you're on your own with that.

As for vterm, it tries to compile `vterm-module.so` at startup. If that process fails, you'll have to compile it manually. There are instructions for doing so in [the vterm module's readme](https://github.com/hlissner/doom-emacs/blob/develop/modules/term/vterm/README.org). If none of those work or you are on an unsupported system (Windows), then vterm is no longer an option.
