### ISSUE TITLE
Huge slow down with tables in org-mode

### ISSUE THREAD

**Issue by pgronkievitz** [hlissner/doom-emacs#5250]
### What did you expect to happen?

When I open new org file and create table with a few h-lines it should be as fast as usual.

### What actually happened?

It's starting to degrade speed gradually and after ~30 seconds of moving between cells it's barely usable.

### Describe your attempts to resolve the issue

I tried disabling minor modes one by one, but none of my ideas work. I've also tried to run profiler but everything I've found is (according to it) that ivy is using the most of the CPU time

### Steps to reproduce

1. Create new org file
2. create table
3. move around for a while
4. moving is terribly slow (but only in this file, others opened in splits are unaffected)

### System Information

https://pastebin.com/aHcBNdjT

**Comment by hlissner** [comment]
Hi! This issue was closed and marked for deletion because it does not meet the minimum requirements for a bug report. There are a couple reasons why this may have happened, but generally it means the bug report could not be reproduced in any of our test environments and/or was/is too vague to act on or investigate further.

Please feel free to contest this if you think this was a mistake or follow up with more information to reverse this ruling. Perhaps our [how to debug issues](https://discourse.doomemacs.org/how2debug) guide can help you gather more information (our discourse requires an account for the time being).

I apologize for the inconvenience, but please understand it is a lot of work to support and maintain this project on my own and every unactionable bug report is attention taken from actionable ones.

Thanks for using Doom!
