### ISSUE TITLE
Layout bepo is remapped by evil-snipe

### ISSUE THREAD

**Issue by rbocheux** [hlissner/doom-emacs#5260]
### What did you expect to happen?

In the dashboard or in a file, the expected behavior is to use `ctsr` to move the cursor in the bepo layout.

### What actually happened?

Since the last doom upgrade, in the dashboard the `s` key is mapped to `evil-snipe-s`, and in a file, the `t` and `s` keys are mapped to `evil-snipe-t` and `evil-snipe-s` respectively.
I don’t know why the `t` key is correct in the dashboard (I don’t use the doom dashboard but dashboard.el).

In other buffers like mu4e or dired, the bepo layout is correct.

### Describe your attempts to resolve the issue

The only way I have to actually fix this is to turn off `evil-snipe-mode` and `evil-snipe-override-mode`, although I didn’t find a way to disable these modes automatically at startup in the config file (I tried  `(evil-snipe-mode -1)` etc, but in the end, I have to turn it off manually after doom’s start).

And this fix is not permanent because it means we can’t use evil-snipe with the bepo layout, which is a bit sad.

### Steps to reproduce

1. Having the `(layout + bepo)` line uncommented in your init.el
2. Open doom emacs after the last upgrade.
3. Type `s` in the dashboard after startup, or in a file
4. You should see in the modeline, the characters `1>` or `2>` because it launched the command `evil-snipe-t` or `evil-snipe-s`.

### System Information

https://pastebin.com/er4qxWzk

**Comment by gagbo** [comment]
Hello,

Sorry @hlissner , I've been meaning to create a proper issue for that once I figured it out, but I guess this one will do.

Currently the only way to work around it is to deactivate `evil-snipe`, either by disabling the package, or by waiting for being in the first buffer to `M-x evil-snipe-mode` and `M-x evil-snipe-override-mode` to disable both. More methods are in the [readme of evil module](https://github.com/hlissner/doom-emacs/tree/develop/modules/editor/evil#restoring-old-substitution-behavior-on-ss)

The core of the issue is that the function that is being used to remap keys, `evil-collection-translate-keys` does not seem to work with the new way `evil-snipe` binds keys. I've reported upstream hoping that someone will eventually have time to explain it : https://github.com/emacs-evil/evil-collection/issues/498 . For the time being no one had enough time to dig into this code it seems, I'll probably do it when I have time (but no ETA on "me having time")

No full solution for this for the time being.

In my "to try" list of alternatives :
- try to use a bare `map!` to remap `evil-snipe`, but I wouldn't be surprised if it failed, general.el might use the exact same elisp API behind the scenes that's failing.
- repin `evil-snipe` to the commit before the change. Main issue is that the bump came to fix an issue, so maybe this is a local-only solution

**Comment by rbocheux** [comment]
@gagbo Thanks for the link to the evil documentation, I know now why I couldn’t disable the `evil-snipe-mode` in the config.el, because `evil-snipe-mode` uses the hook `doom-first-input-hook`, and I tried to set the mode to -1 with the same hook, with no result.
So, thanks to you I have a workaround until a proper fix !

**Comment by gagbo** [comment]
I can confirm that the revert commit mentioned above fixes the issue (so if you ["unpin"](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#pinning-packages-to-specific-commits) `evil-snipe` you can enable it again after `doom sync -u` if you need it)

**Comment by brabalan** [comment]
I’ve updated to latest doom, and I still need to have `(remove-hook 'doom-first-input-hook #'evil-snipe-mode)` to keep the correct binding to `s`. In addition, I need to run `(evil-snipe-override-mode)` to get `t` back.

**Comment by gagbo** [comment]
Did you unpin evil-snipe and `doom sync` afterwards ?

**Comment by brabalan** [comment]
I never had it pinned. I did not notice this before as I restart emacs very rarely.

**Comment by gagbo** [comment]
> I never had it pinned. I did not notice this before as I restart emacs very rarely.

The [default is pinned](https://github.com/hlissner/doom-emacs/blob/46732c0adaef147144418f9f284ca6b1183ab96f/modules/editor/evil/packages.el#L16), so you actually have to add an `(unpin! evil-snipe)` statement in your packages.el

**Comment by brabalan** [comment]
Sorry, I had misunderstood. Yes, I confirm everything is fixed here.

**Comment by hlissner** [comment]
As of a0a45ce this issue should now be resolved (due to https://github.com/hlissner/evil-snipe/commit/1a28d718c835a21591a170af78a03a366cd60c0d). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
