### ISSUE TITLE
LSP persists stale error messages

### ISSUE THREAD

**Issue by tomasmik** [hlissner/doom-emacs#5280]
### What did you expect to happen?

When writing code, I expect that lines and bits of code that were written correctly will not be displayed as an error.

### What actually happened?

Sometimes even if the code is written correctly it is still highlighted as error as if the emacs can't see that I finished the line.

You can see that here:
![image](https://user-images.githubusercontent.com/40318863/126607685-1439360a-e153-444e-9a4e-f20b2a7a4523.png)

But if I remove/delete one character (lets say the number 4) and type it again, the error disappears:

![image](https://user-images.githubusercontent.com/40318863/126607756-e1dd12b9-7ff1-4867-a960-a20551a8919a.png)

### Describe your attempts to resolve the issue

I've tried to update my language server, emacs/doom version and specific package version as well as supplying different configs for the suggestion packages.

### Steps to reproduce

This seems to reproduce itself when you stop for a brief second as you're typing out a variable or a method name.

### System Information

https://pastebin.com/kP3v6Xrk

**Comment by hlissner** [comment]
Please try to reproduce this [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox) in:

+ Vanilla doom (where your private config is disabled)
+ And vanilla Emacs (where Doom is entirely disabled)

Use the following bootstrap code as a basis:

```elisp
(require 'lsp-mode-autoloads)
(require 'lsp-mode)
(require 'lsp-ui)
;; load any additional LSP packages you need here

(add-hook 'find-file-hook #'lsp)
;; Replace this with any LSP enabled file on your system
(find-file "~/path/to/code/file")
```

If you can reproduce it in vanilla Emacs, this is an upstream issue and should be reported to [lsp-mode](https://github.com/emacs-lsp/lsp-mode). If you _can't_ reproduce it in vanilla Doom, the issue lies in your private config. If you can reproduce it in both, then the issue lies in Doom and I'll investigate further.

**Comment by tomasmik** [comment]
I was not able to reproduce it in spacemacs and I assume they use the same package, but I will also try to do for the environments you've listed. Thanks for a quick response.

**Comment by tomasmik** [comment]
This seems to have fixed itself with updates.
