### ISSUE TITLE
Link(s) in README.md leads to 404

### ISSUE THREAD

**Issue by electron271** [hlissner/doom-emacs#5282]
### What did you expect to happen?

Those links should bring up the proper page

### What actually happened?

Some of the links I found to be broken are these:
```
https://github.com/hlissner/doom-emacs/projects/3
https://github.com/hlissner/doom-emacs/projects/2
```
These links all redirect to a 404.

### Steps to reproduce

1. Go to README.md
2. Scroll to roadmap
3. Click on either the `Development Roadmap` or the `Plugins under review` links

### System Information

This isn't needed, because this is a documentation issue.

**Comment by elken** [comment]
To quote https://github.com/hlissner/doom-emacs/pull/4709#issuecomment-788068213, our in-repo docs are undergoing a total rewrite, and this will be indirectly fixed in that change. Also, I am not currently accepting PRs to our in-repo docs (`docs/*`) (see our [do-not-PR](https://discourse.doomemacs.org/t/development-roadmap/42#do-not-pr) list). In any case, thanks for bringing it to my attention.

_Originally posted by @hlissner in https://github.com/hlissner/doom-emacs/issues/5276#issuecomment-883821477_

**Comment by electron271** [comment]
I do not have a discourse, so did not know about the do-not-PR list, closing issue.
