### ISSUE TITLE
org-mode customization / question

### ISSUE THREAD

**Issue by zaiste** [hlissner/doom-emacs#532]
Would you be willing to share your `org-mode` customization as seen on the screenshots ? i.e. 

- [ ] `#` arrow sign for headers
- [ ] tags starting for `#`
- [ ] done tasks are greyed out

**Comment by fuxialexander** [comment]
enable the org module in `(doom! )` and you will get those

**Comment by zaiste** [comment]
Thanks! I'm using the default configuration which has the following fragment

```
(org               ; organize your plain life in plain text
  +attach          ; custom attachment system
  +babel           ; running code in org
  +capture         ; org-capture in and outside of Emacs
  +export          ; Exporting org to whatever you want
  +present         ; Emacs for presentations
  +publish)        ; Emacs+Org as a static site generator
```

Despite it being enabled, I'm getting a different look.

**Comment by UndeadKernel** [comment]
Hi @zaiste, you can already find the private configuration of @hlissner [here](https://github.com/hlissner/doom-emacs-private).

You might be interested in
```lisp
(setq org-ellipsis " ▼ ")
```
from his `init.el`. Also in the lines
```lisp
(add-hook 'org-mode-hook #'auto-fill-mode)
;; The standard unicode characters are usually misaligned depending on the font.
;; This bugs me. Personally, markdown #-marks for headlines are more elegant.
(setq org-bullets-bullet-list '("#"))
```
from his `config.el`.

I believe the greyed tasks are on by default. At least I had that but disabled it in my private config because I couldn't read properly what was already done :D

**Comment by zaiste** [comment]
@UndeadKernel Thank you! It solved the issue.
