### ISSUE TITLE
The lsp does not list the local variable for sh[bash] in the pop-up window for auto-completion

### ISSUE THREAD

**Issue by ylorn** [hlissner/doom-emacs#5381]
### What did you expect to happen?

The `local` variable is not listed as a auto-completion candidate.

### What actually happened?

Only the global variable is listed in the pop-up window

### adding the `local` directive:
<img width="1440" alt="Screen Shot 2021-08-14 at 2 22 40 AM" src="https://user-images.githubusercontent.com/1502810/129437656-fc7e6df3-8f9b-423e-aadc-05ffc6db5f5c.png">

### removing the `local` directive:
<img width="1440" alt="Screen Shot 2021-08-14 at 2 36 48 AM" src="https://user-images.githubusercontent.com/1502810/129437667-36448ab8-6ceb-4b05-9dbc-7d79dadfa94a.png">

### System Information

https://pastebin.com/7Y3GGTkg

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion because it does not meet the minimum requirements for a bug report.** There are several reasons why this happened below. I've checked off the ones that apply to your issue:

+ [ ] Issue could not be reproduced with vanilla Doom in any of our test environments.
+ [ ] Vital information in your issue is inaccessible, missing, or insufficient.
   + [ ] [Backtraces](https://discourse.doomemacs.org/how2backtrace) for errors.
   + [ ] `M-x doom/info`.
   + [ ] An explanation of the issue.
   + [ ] Steps to reproduce the issue.
+ [X] Issue cannot be acted on or investigated further because:
  + [X] It's too vague or open ended. _(Too little information to act on)_
  + [ ] It's undecipherable; it's unclear what you are trying to say.
  + [ ] Your tone and/or language is offensive or unwarranted.
  + [ ] Issue is a support request or question, which does not belong on our issue tracker. It belongs on [Discord](https://doomemacs.org/discord) or [Discourse](https://doomemacs.org/discourse) instead.
+ [X] The issue is unlikely to be a Doom issue, and may be caused by personal configuration, hardware, the OS, shell environment, a plugin, a corrupt Emacs installation, etc. _(In your case, your LSP server is likely the issue; raise this upstream instead)_

**This ruling is not absolute and _can be reversed_.** Feel free to follow up with more information (or, better yet, update your original post). Consult our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide for assistance (note: our discourse currently requires an account).

**If you don't know where to go from here I recommend taking this to [Discord](https://doomemacs.org/discord).** One of us may be able to help you investigate your issue at length.

Sorry for the trouble and thank you for using Doom!

-----
<sup>
I apologize if this is inconvenient or you feel lost, but it takes a lot of time and work to support this project on my own, so our issue tracker is restricted issues that are actionable, reproducible, or can be investigated in a reasonable amount of time.
</sup>
