### ISSUE TITLE
My OSX GUI seems to only partially function, while the CLI doom works as normal

### ISSUE THREAD

**Issue by tokuchan** [hlissner/doom-emacs#5393]
### What did you expect to happen?

When I open EMACS in GUI mode on OSX, I expect DOOM EMACS to open as normal.

### What actually happened?

When I open DOOM EMACS on the GUI, the theme doesn't load, and the leader key doesn't function at all.
![Screen Shot 2021-08-18 at 10 08 58](https://user-images.githubusercontent.com/1869319/129913384-6907ea00-e06d-4fd7-85e9-317aa2989eb4.png)

### Describe your attempts to resolve the issue

I note that, when I open DOOM EMACS from the command, by using `doom run` it works fine and is fully functional. I also used the Doom sandbox from the GUI to load the vanilla doom EMACS, so my own configuration wouldn't be a factor. Nevertheless, it appears not to make a difference. The colors are still messed up and the leader key still doesn't work. I also tried `doom doctor` which says nothing is wrong, `doom sync`, `doom build` also complete without errors.

### Steps to reproduce

Open DOOM EMACS on OSX in GUI mode. (Use the OSX launcher to open the GUI version.)

### System Information

https://pastebin.com/s4TMxtsR

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion because it does not meet the minimum requirements for a bug report.** Reasons why this may have happened are listed below; I've checked off the ones that apply to your issue:

+ [X] Could not be reproduced with vanilla Doom in any of our test environments.
+ [ ] Vital information in your issue is inaccessible, missing, or insufficient.
   + [ ] [Backtraces](https://discourse.doomemacs.org/how2backtrace) for errors.
   + [ ] `M-x doom/info`.
   + [ ] Insufficient explanation of the issue.
   + [ ] Steps to reproduce the issue.
+ [X] Issue cannot be acted on or investigated further because:
  + [X] Not enough information to act on.
  + [ ] It's too vague or open ended.
  + [ ] It's unclear what you are trying to say.
  + [ ] User's attitude is not constructive.
+ [ ] Issue is a support request or question. (belongs on [Discord](https://doomemacs.org/discord) or [Discourse](https://doomemacs.org/discourse) not our issue tracker)
+ [X] Issue is unlikely to be a Doom issue. More plausible explanations: misconfiguration, hardware, the OS, shell environment, a plugin, a corrupt Emacs installation, etc.

**This ruling is not absolute and _can be reversed_.** Feel free to follow up with additional information or edit out the error in your earlier posts. Please consult our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide before you do (note: our discourse currently requires an account).

If you don't know where to go from here, I recommend our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org). Perhaps someone in our community has experienced what you have.

Otherwise, the timer will eventually elapse at this issue will be automatically deleted.

Sorry for the trouble and thank you for using Doom!

-----
<sup>
I apologize if this is inconvenient or you feel lost, but it takes a lot of time and work to support this project on my own, so our issue tracker is restricted to issues that are actionable, reproducible, or can be investigated in a reasonable amount of time. Issues that don't meet these requirements should be raised on [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) instead, and escalated to Github only once a cause has been identified and your private configuration has been ruled out.
</sup>
