### ISSUE TITLE
Always I press period or semicolon and a SPACE in markdown-mode, the cursor goes back one character

### ISSUE THREAD

**Issue by maikol-solis** [hlissner/doom-emacs#5396]
### What did you expect to happen?

While I'm in `markdown-mode` or  `poly-markdown-R-mode` I have this annoying behavior. 

I start writing any phrase (The symbol `|` means the cursor)

`Today is Monday|`

After I press `.` (the period key) and the space key

`Today is Monday.|<SPC>`

But for an inexplicable reason the cursor goes back one character and stays before the period 

`Today is Monday|.`

The behavior also happens with semicolon. 

### What actually happened?

1. Start with the text 
```
test.|
```
2. Toggle the doom profiler `SPC h T`
3. Add a space to the text after the period
```
test.|<SPC>
```
4. Stop the profiler

The result is this. 

My best guess  that the evil part is triggering something for triggering the behavior. 
```
615  64% + ...
292  30% + timer-event-handler
 19   2% + redisplay_internal (C function)
  8   0% - command-execute
  8   0%  - funcall-interactively
  2   0%   + execute-extended-command
  2   0%   - evil-insert
  2   0%    - evil-insert-state
  1   0%     - evil-normalize-keymaps
  1   0%        evil-state-keymaps
  1   0%       evil-echo
  2   0%   + doom/toggle-profiler
  1   0%   + self-insert-command
  5   0% + #<compiled -0x1ff9b408f31f41cf>
  3   0% - jit-lock--antiblink-post-command
  3   0%  - syntax-ppss
  2   0%   - syntax-propertize
  2   0%    - polymode-syntax-propertize
  2   0%     - pm--call-syntax-propertize-original
  2   0%      - markdown-syntax-propertize
  2   0%       - markdown-syntax-propertize-fenced-block-constructs
  2   0%        - markdown-find-previous-block
  2   0%           cl-mapcar
  3   0% - polymode-post-command-select-buffer
  3   0%  - pm-switch-to-buffer
  3   0%   - pm-innermost-span
  3   0%    - pm--innermost-span
  3   0%     - pm--get-intersected-span
  2   0%      - pm-get-span
  2   0%       - apply
  2   0%        + #<compiled -0x17084e0fea6ed1b3>
  1   0% + #<compiled 0xdf3fb2f99606467>
  1   0% + which-key--hide-popup
 

```

### Describe your attempts to resolve the issue

Somewhere read those could help, but it doesn't 

```
(setq evil-move-cursor-back nil)
(setq evil-move-beyond-eol  t)
```

### Steps to reproduce

Described before

### System Information

https://pastebin.com/53HmVSrH

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package may be (mis)behaving in a way you're not expecting.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing dependencies, or a corrupt Emacs installation).

**This ruling is not absolute and _can be reversed_** if you follow up with more information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
>
> Issues that don't meet these requirements should be raised on <a href="https://doomemacs.org/discord">Discord</a> or <a href="https://discourse.doomemacs.org">Discourse</a> instead, and escalated to Github once Doom is identified as the cause.

**Comment by maikol-solis** [comment]
Thanks no problem. 
I found the problem was with `LaTeX-auto-activating-snippets`  
https://discord.com/channels/406534637242810369/406554085794381833/877986300400107570
