### ISSUE TITLE
Using snippets even when `condition` is `nil`

### ISSUE THREAD

**Issue by MithicSpirit** [hlissner/doom-emacs#5404]
### What did you expect to happen?

If a snippet has a `condition` directive set, such as 
```elisp
# condition: (eq 1 (line-number-at-pos))
```  
for `#!`, it should never activate, even when using `C-SPC` (`company-complete-common`).

### What actually happened?

The snippet can be activated with `C-SPC` (`company-complete-common`) regardless of whether the condition evaluates to `nil` or not (although it can't be activated with `TAB` as expected). I am not sure whether this is a doom issue, an upstream issue with company, or just company and yasnippet not playing well together.

### Describe your attempts to resolve the issue

I tried looking through yasnippet's and company-mode's issue trackers to see if someone else had this problem did not find anything.

### Steps to reproduce

1. Create/edit a snippet
2. Set the following in the directives
```elisp
# condition: (eq 1 (line-number-at-pos))
``` 
3. Open a new file and enable any mode(s) necessary for the snippet
4. Try to use the snippet on the first line (it should work)
5. Go down a few lines and try to use the snippet again (it shouldn't work, but does)

### System Information

https://pastebin.com/uGpUXGF6

**Comment by hlissner** [comment]
I believe this is an issue for `company-yasnippet` (built into [company](https://github.com/company-mode/company-mode)) and should be reported there. I'm not sure they're interested in doing this because it cause be arbitrarily expensive to run conditions on X snippets every time `company-yasnippet` was consulted, but that's my guess.

In any case, this isn't a Doom issue so I will close this.
