### ISSUE TITLE
Email with Latex Equation in org-msg (mu4e) does not convert and send

### ISSUE THREAD

**Issue by TS-CUBED** [hlissner/doom-emacs#5416]
### What did you expect to happen?

Using mu4e with org-msg, I include a LaTeX equation in the email body and expect it to be included as a png image.

### What actually happened?

When attempting to send the message (C-c C-c), the message is not sent if it includes a LaTeX eqyuation (tex:dvipng)

Error (message-send-hook): Error running hook "org-msg-prepare-to-send" because: (void-variable source)

### Describe your attempts to resolve the issue

Email does get sent with 

- images attached, or created using babel source blocks (e.g. Python or Julia blocks)
- other rich text formatting using org-mode (headers, tables, lists, etc.)

only LaTeX equations trigger the error above.

Using `tex:dvisvgm` works, and attaches the LaTeX equation, but email clients don't handle svg files well.

### Steps to reproduce

1. Open Emacs
2. Start Mu4E
3. "C" to compose message, enter recipient
4. In message body, enter equation: $\sin(\alpha)$ 
5. "C-c C-c"
6. error message:
`Error (message-send-hook): Error running hook "org-msg-prepare-to-send" because: (void-variable source)`

### System Information

https://pastebin.com/tPcqXb2Y

**Comment by Samickey** [comment]
I experienced the same issue.
It seems like the problem comes from the function [`+org-html-latex-fragment-scaled-a`](https://github.com/hlissner/doom-emacs/blob/7e1f7915c0bcefb2794bf19f3ef4ec33c9c4f112/modules/email/mu4e/autoload/advice.el#L58) in the file [`advice.el`](https://github.com/hlissner/doom-emacs/blob/7e1f7915c0bcefb2794bf19f3ef4ec33c9c4f112/modules/email/mu4e/autoload/advice.el).
There's a mention of the variable `source` in the definition of `attributes` ([here](https://github.com/hlissner/doom-emacs/blob/7e1f7915c0bcefb2794bf19f3ef4ec33c9c4f112/modules/email/mu4e/autoload/advice.el#L84), but those variables are defined in the same let statement. 
A possible fix is : 
```elisp
         (let ((source (org-export-file-uri (match-string 1 formula-link))))
              (let ((attributes (append (list :alt latex-frag
                                            :class
                                            (concat "latex-fragment-"
                                                    (if (equal "\\(" (substring latex-frag 0 2))
                                                        "inline" "block")))
                                      (when (memq processing-type '(dvipng convert))
                                        (+org-msg-img-scale-css source)))))
              (org-html--format-image source attributes info))))))

```
There's another error because of a typo I guess : in the same file, in function [`+org-msg-img-scale-css`]( https://github.com/hlissner/doom-emacs/blob/7e1f7915c0bcefb2794bf19f3ef4ec33c9c4f112/modules/email/mu4e/autoload/advice.el#L38), the variable there's a d missing in the declaration of variable `width-call` [here](https://github.com/hlissner/doom-emacs/blob/7e1f7915c0bcefb2794bf19f3ef4ec33c9c4f112/modules/email/mu4e/autoload/advice.el#L42)

Once those two things corrected, I managed to send latex code without error hitting `C-c C-c` 

Hope it helps, maybe @tecosaur can quickly fix that ? 
I'm not familiar with the Github way of solving issues. Sorry for the inconvenience if it's not how it should be done. (Should I really fork the entire repo and make a pull request just to propose those two small fixes !?) 

Cheers,

**Comment by tecosaur** [comment]
Thanks for the ping. I can create a PR just fixing those two small things. If you might happen to have a patch file you could chare on hand that would be handy though @Samickey.

**Comment by Samickey** [comment]
Sure ! Here is a zip file [advice.el-fix.zip](https://github.com/hlissner/doom-emacs/files/7271066/advice.el-fix.zip) with fixed `advice.el` and the git diff if it's useful. Hope that's what you expected. 
I'm not a lisp developer, so I don't know if there's a cleaner way to fix the code for the definition of  `attributes`.
Also, thanks for all the work you do !

**Comment by tecosaur** [comment]
Thanks, I've just made a PR to fix this.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
