### ISSUE TITLE
Treemacs makes Emacs Freeze

### ISSUE THREAD

**Issue by Raghav-Dixit** [hlissner/doom-emacs#5437]
### What did you expect to happen?

I expected Treemacs to open.

### What actually happened?

Instead of Treemacs opening, Emacs freezes. None of the shortcuts work, including the one to close the application. The only way to close it is to force quit.

### Describe your attempts to resolve the issue

1. I checked if Treemacs was enabled in `$DOOMDIR/init.el`, which it was.
2. I tried both the shortcut (`SPC o p`) and `M-x +treemacs/toggle`. They both freeze the app.

### Steps to reproduce

1. Open Emacs
2. Enable `:ui treemacs` in init.el.
3. Do `M-x +treemacs/toggle`

Please let me know if I should also post this in the [Treemacs Github](https://github.com/Alexander-Miller/treemacs).

### System Information

https://pastebin.com/TKRN6F0Y

**Comment by anonimitoraf** [comment]
I noticed that this happens to me on PGTK + native-comp but not for just native-comp.
Are you on PGTK?

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing dependencies, or a corrupt Emacs installation).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
