### ISSUE TITLE
Doom Startup Errors From Org-Babel Derived config.el

### ISSUE THREAD

**Issue by eklebanow** [hlissner/doom-emacs#5441]
### What did you expect to happen?

Launch doom emacs without errors

### What actually happened?

1.  I created literate config using org-mode titled README.org     https://dpaste.com/BK85REAAZ
2. I org-babel-tangled README.org to create config.el https://dpaste.com/9PAJFUZD5
3. Killed emacs
4. Doom Sync
5. If I try to start doom from dmenu run launcher or if I shut off laptop and restart Doom via cli, doom starts with errors about start up hooks https://dpaste.com/C7KETU8AM
6. If I start doom via cli using `emacs` doom starts up and works normally with no evidence of start up errors.  

### Describe your attempts to resolve the issue

1. I obtained backtrace but I do not know how to interpret it by starting doom with `emacs --debug-init` https://dpaste.com/DJVZ6MEPV
2. I loaded README.org and config.el in vanilla emacs  with `emacs -Q` Both files open without errors
3. I attempted to google errors to find out how to resolve them without success

### Steps to reproduce

1. Start from literate config org file README.org
2. Refresh local setup by C-c, C-c
3. Org-babel-tangle....get message that 11 source blocks from README.org tangled
4. kill emacs
5. dmenu run launcher or shut down laptop and restart and then from cli launch doom
6. See errors about start up hooks (see above)

### System Information
https://dpaste.com/4FDQETJEJ

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [ ] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing dependencies, or a corrupt Emacs installation).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
