### ISSUE TITLE
void-function mu4e~start

### ISSUE THREAD

**Issue by JoelSass** [hlissner/doom-emacs#5478]
### What did you expect to happen?

When i press spc o m it should prompt me with the mu4e view

### What actually happened?

When i press the keychord i get:
```
Debugger entered--Lisp error: (void-function mu4e~start)
  (mu4e~start 'mu4e~main-view)
  =mu4e()
  funcall-interactively(=mu4e)
  call-interactively(=mu4e nil nil)
  command-execute(=mu4e)
```

### Steps to reproduce

Get fresh installation of doom emacs on emacs 27 , remove the gmail flag from mu4e

### System Information

https://pastebin.com/hMaxucWi

**Comment by sdbversini** [comment]
Since you are on archlinux, are you using the [mu-git](https://aur.archlinux.org/packages/mu-git/) AUR package? (or generally compiling from git clone)

It provides mu1.7 that is for the moment incompatible [because of a large amount of function and variable renames.](https://github.com/djcb/mu4e/blob/master/NEWS.org)

If that is the case, the solution for now is to switch to the [1.6.6 release tarball](https://github.com/djcb/mu/releases/tag/1.6.6) or using the simple [mu](https://aur.archlinux.org/packages/mu/) aur package

**Comment by JoelSass** [comment]
Thank you now everything works
