### ISSUE TITLE
Update `info+.el` package remote

### ISSUE THREAD

**Issue by mangkoran** [hlissner/doom-emacs#5503]
### What did you expect to happen?

Latest `info+.el` from https://github.com/emacsmirror/emacswiki.org/blob/master/info%2b.el should be pulled when I add `(package! info+)` in `packages.el`

### What actually happened?

`info+.el` pulled from https://github.com/emacsmirror/info-plus, which is outdated based on https://www.emacswiki.org/emacs/info%2b.el.

### Describe your attempts to resolve the issue

For the time being I use this code:
```
(package! info+ :recipe
    (:host github
        :repo "emacsmirror/emacswiki.org"
        :branch "master"
        :files ("info+.el"))
    :pin "69732dcdd497607978ac14881831bd4ed690799a")
```

### Steps to reproduce

1. Open `packages.el`
2. Add `(package! info+)` into `packages.el`
3. Run `doom sync`
4. You will get an error regarding https://github.com/syl20bnr/spacemacs/issues/15010, which has been resolved in the upstream `info+.el`

### System Information

https://gist.github.com/mangkoran/e41623e9cf11c1e87ba47e75c6bdcff0

**Comment by mangkoran** [comment]
I don't know where is the actual upstream of `info+.el` is, but [info+.el EmacsWiki page](https://www.emacswiki.org/emacs/info%2b.el) redirects the Git link to https://github.com/emacsmirror/emacswiki.org/blob/master/info%2b.el

**Comment by hlissner** [comment]
This is not a Doom issue: that `info+` maps to `emacsmirror/info-plus` is a recipe issue that needs to be addressed in emacsmirror's index. That, or `emacsmirror/info-plus` should be updated.

`(package! emacswiki.org)` is more likely to work, however, it is a big repo with a lot of noise in it, and straight.el installs packages from emacsmirror with [a generic recipe](https://github.com/raxod502/straight.el/blob/develop/straight.el#L3285-L3286) by default, which will download (and build) it all. The only way around this is to specify your own recipe.

In any case, since this isn't a Doom issue I will close this.

**Comment by mangkoran** [comment]
Alright then. So what I am using now is the intended use-case of `:recipe`?

**Comment by hlissner** [comment]
> Alright then. So what I am using now is the intended use-case of :recipe?

Yes.

> Edit: I also curious: `info+.el` added this way is not loaded automatically by `emacs` whenever I open `emacs`. I need to add `(require 'info+)` into my `config.el`. Is this also the intended behaviour?

Yes. `~/.doom.d/packages.el` is where you control what packages to install.

`~/.doom.d/config.el` is where you control how they're used, loaded, and/or configured.

An installed package does nothing until it is loaded.
