### ISSUE TITLE
Last upgrade break projectile

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#5518]
### What did you expect to happen?

LIsting of recent projects

### What actually happened?

nothing ...

### Steps to reproduce

~/.emacs.d/bin/doom doctor
> Executing 'doom doctor' with Emacs 27.1 at 2021-09-24 21:48:42
  The doctor will see you now...
  
  > Checking your Emacs version...
  > Checking for Doom's prerequisites...
  > Checking for Emacs config conflicts...
  > Checking for great Emacs features...
  > Checking for private config conflicts...
  > Checking for stale elc files...
  > Checking for problematic git global settings...
  > Checking Doom Emacs...
      (org-roam) total: Δ0, files-modified: Δ0, ids: Δ0, links: Δ0, tags: Δ0, titles: Δ0, refs: Δ0, deleted: Δ0
      simple profile: ON
      Ignoring ':ensure t' in 'mu4e' config
    ✓ Initialized Doom Emacs 3.0.0-alpha
    ✓ Detected 70 modules
    ✓ Detected 310 packages
    > Checking Doom core for irregularities...
      x There was an unexpected error
        Message: Wrong type argument
        Data: (wrong-type-argument . sequencep)
        Backtrace:
          (append 0 0)
          (projectile-merge-known-projects)
          (projectile--cleanup-known-projects)
          (projectile-mode 1)
          (progn (projectile-mode 1) (let ((sym 'projectile-relevant-known-projects)
          (condition-case err (progn (projectile-mode 1) (let ((sym 'projectile-rele
          ((closure (t) nil (condition-case err (progn (projectile-mode 1) (let ((sy
          (eval-after-load-helper "/home/mic/.emacs.d/.local/straight/build-27.1/pro
          (run-hook-with-args eval-after-load-helper "/home/mic/.emacs.d/.local/stra
          (do-after-load-evaluation "/home/mic/.emacs.d/.local/straight/build-27.1/p
      ! Extended backtrace logged to .emacs.d/.local/doom.error.log

### System Information

https://pastebin.com/QkAiU5qJ

**Comment by MrMic** [comment]
- The shortcut SPC-p-p does not list projects
- So I run:
$> doom doctor
And notice the error above ...

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package may be (mis)behaving in a way you're not expecting.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing dependencies, or a corrupt Emacs installation).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
>
> Issues that don't meet these requirements should be raised on <a href="https://doomemacs.org/discord">Discord</a> or <a href="https://discourse.doomemacs.org">Discourse</a> instead, and escalated to Github once Doom is identified as the cause.
