### ISSUE TITLE
Disabling `terraform-format-on-save-mode` does not disable `format-on-save-mode` for `terraform-mode`

### ISSUE THREAD

**Issue by brorbw** [hlissner/doom-emacs#5534]
### What did you expect to happen?

Disabling `terraform-format-on-save-mode` in a terraformbuffer does not disable `format-on-save` for a buffer in `terraform-mode`. I have no problem with formatting on save, but changing one line in a configuration file for work and suddenly 150 lines of tf gets reformatted is not ideal.

### What actually happened?

The buffer is formattede on save.

### Describe your attempts to resolve the issue

I have no idea where to start.

### Steps to reproduce

1. Create a buffer
2. switch to tf mode `M-x terraform-mode`
3. Paste
```tf
testvariable = {
	"test":                 "some value"
	"a_long_variable_name": "some other value"
}
```
4. disable `terraform-format-on-save-mode`
5. Save file
5. Result
```tf
testvariable = {
  "test" : "some value"
  "a_long_variable_name" : "some other value"
}
```

### System Information

https://pastebin.com/fY2CJFj7

**Comment by brorbw** [comment]
I solved my own issue. Using `(setq +format-with-lsp nil)` from the `format` module documentation (https://github.com/hlissner/doom-emacs/tree/f74debdea8042c3a19cf83781d9560bb467d86ce/modules/editor/format#disabling-the-lsp-formatter).

**Comment by brorbw** [comment]
The problem is also present in `markdown` mode

**Comment by sei40kr** [comment]
@brorbw 
It seems you enabled `:editor format +onsave`.

Is your `+format-on-save-enabled-modes` is set to `t` or a list including `terraform-mode`?
If you don't want `terraform-mode` buffers formatted on save, you need to set `+format-on-save-enabled-modes` to `'(not terraform-mode)`.
Don't use `terraform-format-on-save-mode` because it conflicts `:editor format +onsave`.

In addition, `+format-on-save-enabled-modes` had had a bug and it was fixed a few hours ago.
So make sure your Doom Emacs updated to the latest.

**Comment by brorbw** [comment]
Yep, you are right. Toggling `format-all-mode` also works. Thank you.
