### ISSUE TITLE
LSP seems unable to format C++ code

### ISSUE THREAD

**Issue by robertodr** [hlissner/doom-emacs#5538]
### What did you expect to happen?

I have `clangd` configured as my language server. From what I understand in the documentation, it's supposed to embed `clang-format` and thus be able to format my code.

1. I'd expect `SPC c f` to run the formatter embedded in `clangd`.
2. I expected to be able to use `SPC c l = =` to run the formatter of the language server. 

### What actually happened?

1. The message says it's using `clang-format`. This is problematic when I edit a remote file with TRAMP: the formatter won't respect the `.clang-format` on the remote filesystem.
2. I get `SPC c l = =` is undefined.

### Steps to reproduce

1. Install `clangd` and configure Doom Emacs to use it as language server.
2. Try to format a C++ file (local or remote)

### System Information

https://pastebin.com/W6iFSj1L

**Comment by gagbo** [comment]
Hello,

Did you try to reproduce your issue with Vanilla Doom, because I couldn't reproduce your issue on my machine, neither could I in a gitpod with the basic c project ( https://gitpod.io/#ORG=emacs-lsp,PROJECT=demo-projects,PROFILE=doom/https://github.com/emacs-lsp/lsp-gitpod ).

In both cases `SPC c l = =` worked fine (even format on save and whatnot). Maybe the version of clangd you have isn't recent enough to handle this. Looking at `lsp-mode` code, it looks like the `= =` binding is only made if the server [advertised its formatting capabilities](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L2401)

**Comment by robertodr** [comment]
Thanks for the hints! I have a recent version of `clangd`, but somehow the Doom configuration was fubared. Starting from vanilla Doom helped.
