### ISSUE TITLE
Improve smartparens emacs bindings

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#5575]
### What did you expect to happen?

sexp movements bindings should not be more incompatible than necessary with traditional ones, except for a very good reason.

sexp movements should include basic functionality like going up and down a sexp, and moving to the next and previous list sexp item.

### What actually happened?

[Traditionally](https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-by-Parens.html) there has been a set of list (parenthetical group) movements:

* C-M-d/u: down/up list
* C-M-n/p: forward/backward list

These are very important bindings.

But in doom emacs:

* They aren't assigned to similar smartparens functions.
* C-M-d has been replaced with a comparatively exotic binding.

```
      (:after smartparens
        :map smartparens-mode-map
        "C-M-a"     #'sp-beginning-of-sexp
        "C-M-e"     #'sp-end-of-sexp
        "C-M-f"     #'sp-forward-sexp
        "C-M-b"     #'sp-backward-sexp
        "C-M-d"     #'sp-splice-sexp
        "C-M-k"     #'sp-kill-sexp
        "C-M-t"     #'sp-transpose-sexp)
```

### Describe your attempts to resolve the issue

I just rebound everything in the most conservative fashion:

* C-M-d/u: sp-down/up-sexp
* C-M-n/p: sp-next/previous-sexp
* C-M-f/b: sp-forward/backward-sexp
* C-M-a/e: sp-beginning/end-of-sexp
* C-M-k: sp-kill-sexp

I think doom emacs should be as close to these semantics as possible because these are similar to the traditional meanings and they have always made sense (this is not a case of having to correct archaic defaults at all).

Of course doom could add additional functionality if so desired, but please don't override the basic ones.

See also: https://ebzzry.com/en/emacs-pairs/ (but don't use the bindings suggested there, like C-up/down, which require key arrows, are already taken by the macOS desktop and, furthermore, are unnecessarily at odds with tradition).

### Steps to reproduce

I don't think this is necessary.

### System Information

https://pastebin.com/QBtDe97W

**Comment by memeplex** [comment]
Moreover, having been a vim user for many years and also an emacs user for many years, I would say that sexp movements and operations outshine vim text-object movements, I mean for the particular case of balanced expressions. This is not surprising given the close relationship between emacs and lisp. Maybe evil's text-objects better incorporate sexps semantics than vim's, I don't know. But consider adding these bindings to evil doom also. I'm saying this wrt:

> None of smartparen’s commands have default keybinds for evil users because they are redundant with motions and text-objects provided by evil/vim. If you disagree, I recommend trying the :editor lispy or :editor parinfer modules.

in the FAQ.

**Comment by hlissner** [comment]
> I think doom emacs should be as close to these semantics as possible because these are similar to the traditional meanings and they have always made sense (this is not a case of having to correct archaic defaults at all).

Your argument makes sense to me, so I'd happily accept a PR to implement these changes. As I don't use vanilla keybinds and am not as familiar with them as I am with vim/evil's, I defer to our vanilla users to polish them.

> I don't know. But consider adding these bindings to evil doom also

Smartparens is in an odd position. I brought it into Doom core to serve a specific function: as-you-type pair completion. I wanted nothing else from it, and for as long as it's a core package I'd like to keep it that way. The vanilla keybinds were an exception because its commands were practically drop-in replacements. I won't extend it to evil because it costs free keybind real estate, for a function that's only relevant to lisp major modes. Meanwhile, text objects/motions apply universally, with no assembly required.

In any case, smartparens has proven slow, so I'm searching for a replacement and have plans to move smartparens to its own module sometime mid-next-year. Once that's done, I'd be happy to add keybinds for both sides of the coin. It'd stand next to our lispy and parinfer modules.

**Comment by memeplex** [comment]
> PR to implement these changes

Sure thing.

Wrt everything else, your arguments make sense to me. I'm not stubbornly interested in changing anything, it would be easier for me to just hack it at my side, I've just started using doom very recently, I saw it referenced as a "starter kit" but it's not that for me, I see it as a place where to coordinate a curate set of settings that one can leverage and customize in an orderly fashion, so I raise some petty concerns that may be of upstream interest from this perspective (and I also learn a lot about existing packages and cool configurations).
