### ISSUE TITLE
highlight-numbers-mode interferes with my major mode

### ISSUE THREAD

**Issue by krux02** [hlissner/doom-emacs#5749]
### What did you expect to happen?

numbers should highlight properly

### What actually happened?

numbers don't highlight properly

### Describe your attempts to resolve the issue

I search through the doom emacs repository to check if doom emacs fucks with prog-mode, yes indeed it does so here:
https://github.com/hlissner/doom-emacs/blob/4eeb3c7a19c324f5a7839a2e3edb03fc87d23034/core/core-ui.el#L480

### Simple

open the following line in some a buffer and make it load prog-mode
```
  let myArray: array(7)[int] = [123, -456, 789.123, -234, 567, 891, -123]
```
negative numbers won't get any form of highlighting. I am not 100% sure why, but somehow this number highlighting has conflics with my syntax rules that now don't get applied anymore.

### Full

clone https://github.com/krux02/golem and load `golem-mode.el`, then open `dome.golem` and see that numbers don't get highlighted. But in emacs without doom they do get highlighting.

https://github.com/krux02/golem/blob/master/demo.golem

### System Information

https://pastebin.com/R9syTCgk

**Comment by gagbo** [comment]
```lisp
(package! highlight-numbers :disable t)
```

**Comment by hlissner** [comment]
Doom installs and activates `highlight-numbers-mode` because an unfortunate number of major modes lack highlighting for numerics. Naturally, this shotgun approach will have edge cases, but it seems that the few major modes (c++-mode + modern-cpp-font-lock) do not struggle with highlight-numbers-mode like yours does, so this may be an issue with your mode's font lock keywords.

In any case, Doom does not have a golem module, so there is no appropriate place to specify it as an exception, and I'm not keen on maintaining a list of out-of-tree exceptions. This may change in the future, but sorry to say there is nothing that can be done here, at the moment.

For the time being, this can be disabled on a per-mode basis with:

```elisp
(add-hook! 'golem-mode-hook (highlight-numbers-mode -1))
```

Or globally (see gagbo's answer).

**Comment by krux02** [comment]
I also did some investigation and as far as I can tell right now, highlight numbers does apparently not break number highlighting in my mode, it just made this appearance. The problem is there is no specified color/style for Numbers and my mode picked a different style than highlight-numbers-mode. It just looked like my style was broken. 

But what I can say though is `highlight-numbers-mode` does not highlight negative numbers at all. Putting the `-` in front of the number makes the pattern not match the number at all anymore. If the `-` sign is part of the number literal is unfortunately different from programming language to programming language. Lisp/Scheme generally does have negative literals while languages with unary operators such as C/C++ do not have negative literals.

Anyway thanks for showing your attention and support.
