### ISSUE TITLE
`SPC i r` fails with: `command-execute: Wrong type argument: commandp, evil-ex-registers`

### ISSUE THREAD

**Issue by aeberts** [hlissner/doom-emacs#5753]
### What did you expect to happen?

When doing `SPC i r` I expect emacs to run `evil-ex-registers` but I get an error message instead:

`command-execute: Wrong type argument: commandp, evil-ex-registers`

### What actually happened?

I get the error message `command-execute: Wrong type argument: commandp, evil-ex-registers` in the mini buffer.

### Describe your attempts to resolve the issue

If I use help to find out what function `SPC i r` is bound to I get:

`user-error: SPC i r is bound to evil-ex-registers which is not a command`

I'm assuming that the `evil-ex-registers` command was removed or renamed.

### Steps to reproduce

1. Open doom emacs
2. Hit `SPC i r` 
3. Get the error message in the console

### System Information

https://pastebin.com/UFfvvFik

**Comment by mbuchel** [comment]
i was struggling with this for over 3 months, finally i decided it is easier to fix it rather than switching to vim to paste text.

so the issue is your .doom.d/init.el is wrong, the evil-ex-registers is only allowed if you use the ivy search engine instead of the new default of vertico.

YOU CANNOT USE DOOM RELOAD TO ACCOMPLISH CHANGING THESE, you need to actually restart emacs.

**Comment by nizish** [comment]
@mbuchel 
Your suggestion fixed the issue.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ngharrison** [comment]
Is there any way for it to show ALL the evil registers? Right now it just shows the 0 register and any letter registers I have specifically saved into.
