### ISSUE TITLE
doom-load-envvars-file does not set environment but rather only defaults for subprocesses to inherit

### ISSUE THREAD

**Issue by leezu** [hlissner/doom-emacs#5760]
### What did you expect to happen?

`(doom-load-envvars-file "~/.doom.d/env")` sets all environment variables declared in "~/.doom.d/env", adding and updating variables in the environment of the running emacs process as needed.

To solve this issue, the implementation of doom-load-envvars-file needs to be changed to avoid only `setq-default process-environment` but rather call the `setenv` function for each variable defined in the environment file. [load-env-vars.el](https://github.com/syl20bnr/spacemacs/blob/7786e11/core/libs/forks/load-env-vars.el) implements the required functionality.

### What actually happened?

`(doom-load-envvars-file "~/.doom.d/env")` sets `process-environment` variable, specifying defaults for subprocesses to inherit but does not change the environment variables of the running emacs process.

### Describe your attempts to resolve the issue

For the variables important to me, I manually called `setenv`

```elisp
(setenv "TZ" "America/New_York")
```

### Steps to reproduce

1. Create a new environment configuration `doom env -o ~/.doom.d/myenv`. Modify the TZ variable in the new myenv to a value different to your default TZ. For example, if `echo $TZ` in your shell returns `UTC`, set `TZ` to `America/New_York` in myenv.
2. Modify `~/.doom.d/config.el` to `(doom-load-envvars-file "~/.doom.d/myenv")`
3. Start Emacs
4. Run `M-x doom/info` and note the time shown i based on `TZ` in your shell environment, not based on the `TZ` specified in the `~/.doom.d/myenv`.

### System Information

https://pastebin.com/kQswzLhX

**Comment by hlissner** [comment]
As of 9dad269 this issue should now be resolved. This happens because `TZ` is the one exception to this rule. It is a special case in `setenv` and causes Emacs to call `set-time-zone-rule` for it. For _any_ other envvar, `doom-load-envvars-file` is sufficient. 

Anyhow, I've modified `doom-load-envvars-file` to properly process `TZ` if it is present. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
