### ISSUE TITLE
Scroll and input lag (maybe lsp related)

### ISSUE THREAD

**Issue by gjm** [hlissner/doom-emacs#5794]
### What did you expect to happen?

Expect scrolling and text input to be fast.

### What actually happened?

When scrolling and typing text emacs is very slow and laggy

### Describe your attempts to resolve the issue

Tried profiling while scrolling and typing. Here is the report:

```
 5410  78% - command-execute
 5410  78%  - call-interactively
 5410  78%   - funcall-interactively
 2905  41%    - next-line
 2905  41%     - line-move
 2394  34%        line-move-visual
 2110  30%    - previous-line
 2110  30%     - line-move
 1086  15%        line-move-visual
  364   5%    + windmove-left
   24   0%    + self-insert-command
    7   0%    + indent-for-tab-command
 1280  18% - timer-event-handler
 1280  18%  - apply
 1200  17%   - jit-lock-deferred-fontify
 1200  17%      redisplay
   36   0%   + amx-idle-update
   13   0%     #<compiled 0x12c5831a94983022>
    3   0%   + c-type-finder-timer-func
  222   3% + ...
    8   0% + redisplay_internal (C function)
    4   0% + winner-save-old-configurations

```

### Steps to reproduce

1. Open emacs
2. Open a file in and lsp supported mode (php for example)
3. Scroll or type

### System Information

https://pastebin.com/0cpLbGwN

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by hlissner** [comment]
See https://discourse.doomemacs.org/t/why-is-emacs-doom-slow/83 (requires a login for now).
