### ISSUE TITLE
Doom emacs configuration location

### ISSUE THREAD

**Issue by Yumasi** [hlissner/doom-emacs#580]
Hi !

I'm slowly exploring Doom emacs (on the develop branch) and discovered the *.doom.d* directory in which my *init.el* file is stored. I am wondering what is the exact purpose of this directory, since, according to the wiki, the configuration shall be in a *private* module in *.emacs.d*.

Is *.doom.d* a new way of configuring doom that will replace the *private* module ? Or are both supposed to be used at the same time, each having a different purpose ?

**Comment by hlissner** [comment]
`~/.doom.d` will indeed replace the private module (or `~/.config/doom`, which is detected first). This is already the case in `develop`. This also supports private modules, under `~/.doom.d/modules/`.

I highly recommend you switch over. Doing so is simply a matter of copying your old `doom!` block from `~/.emacs.d/init.el` to `~/.doom.d/init.el`, and reverting `~/.emacs.d/init.el` to its original.

Important: your `~/.doom.d/init.el` _should not_ contain a `(require 'core ...)` line, or you'll get recursive errors.

**Comment by Yumasi** [comment]
Thanks for your answer !

I have a quick followup questions, just to be sure I understand it correctly: 
- my understanding is that `.doom.d` and `.config/doom` are considered as modules and should be structured in the same way. Is that correct ?
- If this is the case, is that module loaded after every other modules ? Or should I use the `after!` macro ?

**Comment by hlissner** [comment]
>my understanding is that .doom.d and .config/doom are considered as modules and should be structured in the same way. Is that correct ?

You are correct.

>If this is the case, is that module loaded after every other modules ? Or should I use the after! macro ?

The load order in Doom is:

+ `~/.doom.d/init.el`
+ `~/.emacs.d/modules/*/*/init.el`
+ `~/.emacs.d/modules/*/*/config.el`
+ `~/.doom.d/config.el`

Whether to use `after!` or not depends on whether or not the package is lazy loaded. What package do you have in mind?

**Comment by Yumasi** [comment]
> Whether to use after! or not depends on whether or not the package is lazy loaded. What package do you have in mind?

Actually none in particular. The reason I ask this, is because I try to enable whitespace-mode in every programming mode and I'm having trouble getting it to work. Here is what I inserted in my `init.el` before the `doom!` block:

```lisp
(add-hook! prog-mode-hook '(whitespace-mode t))
```
I was thinking that maybe a package loading after my `init.el` overwrite my hooks, hence my question.

**Comment by hlissner** [comment]
The formatting of the command is incorrect is a couple ways. It should be `(add-hook 'prog-mode-hook #'whitespace-mode)`.

1. If `add-hook!`'s first argument is unquoted, it will append `-hook` to it. If you want to add a hook to prog-mode-hook, you either do `(add-hook! prog-mode ...)` or `(add-hook! 'prog-mode-hook ...)`.

2. You quoted `'(whitespace-mode t)`, so `add-hook!` will treat them as a list of hooks, rather than a lisp expression. Meaning the above expands to:

```el
(add-hook 'prog-mode-hook-hook 'whitespace-mode)
(add-hook 'prog-mode-hook-hook 't)
```

I think you _meant_ `(add-hook! 'prog-mode-hook (whitespace-mode t))`, which would correctly expand to `(add-hook 'prog-mode-hook (lambda () (whitespace-mode t)))`.

3. The `(whitespace-mode t)` create a closure (lambda), which is unnecessary overhead for such a simple operation, so `(add-hook 'prog-mode-hook #'whitespace-mode)` alone is equivalent, minus the extra function call.

**Comment by Yumasi** [comment]
Indeed, I completely misunderstood how to use `add-hook!` (and how lisp works too). Thanks for your help !

**Comment by hlissner** [comment]
No problem, glad to be of help!
