### ISSUE TITLE
Can't write in Bengali properly

### ISSUE THREAD

**Issue by avishekdutta531** [hlissner/doom-emacs#5806]
### What did you expect to happen?

I could write in Bengali in GNU Emacs. But can't write in Doom Emacs...

### What actually happened?

![image](https://user-images.githubusercontent.com/74361331/142768291-f9e25ee0-bc15-49cd-b22c-9c484a29054c.png)

### Steps to reproduce

I edited ~/.doom.d/init.el to solve this problem, but it's not working...

```emacs-lisp
(setq default-input-method "bengali-itrans")
(set-fontset-font "fontset-default" 'bengali (font-spec :family "Kalpurush" :size 18))
```
then,
```bash
~/.emacs.d/bin/doom sync
```

### System Information

https://pastebin.com/XpMAEyU7

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [ ] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [ ] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [ ] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by avishekdutta531** [comment]
I also followed this guide, but it doesn't work in Doom Emacs

https://md-arif-shaikh.github.io/2021/05/27/typing-bangla-in-emacs.html

**Comment by hlissner** [comment]
Can you be more specific about what "doesn't work" means to you? I neither speak nor write Bangla, so I can't test this and have little insight into the matter from the linguistic side. I've known users who write Hebrew, Cyrillic, and Arabic in (Doom) Emacs, so theoretically this should be possible.

See if this makes a difference:

```elisp
(setq default-input-method "bengali-itrans")
(add-hook! 'after-setting-font-hook
  (set-fontset-font "fontset-default" 'bengali (font-spec :family "Kalpurush" :size 18)))
```

**Comment by avishekdutta531** [comment]
Thanks, it's working.
