### ISSUE TITLE
`+default/search-project-for-symbol-at-point` looks for symbol starting at buffer directory instead of project directory

### ISSUE THREAD

**Issue by razzmatazz** [hlissner/doom-emacs#5816]
### What did you expect to happen?

I expected for the symbol to be looked at project root, instead of only at subdirectories starting at the file's directory.

### What actually happened?

Symbol was being looked at starting from the directory of the file I use `SPC *` at a symbol, not from project root directory as it was before.

### Describe your attempts to resolve the issue

The behaviour has changed since 411ed0c8f8e12d106a64a56ae437ba45c1bcd1f2 

Since then I have to add a `.dir-locals.el` that sets `default-directory` to project root, to make `+default/search-project-for-symbol-at-point` actually look at project for symbol, not at project subdirectories starting from the file dir.

I have a workaround for this, just wasn't sure if this new behaviour was intended or not by the change, as it looks somewhat erroneous for my case.

This workaround, however has side effects for `M-x compile` and other things that read `default-directory` and now point to project base, which is not wanted..

### Steps to reproduce

(i) open multi dir project:
- root
- root/file0.txt (contains symbol `sym`)
- root/subdir
- root/subdir/file1.txt (also contains symbol `sym`)

(ii) reproduce:
- open file1.txt
- hit `SPC *` on symbol `sym` that is present in file0.txt too
- notice how file0.txt is not shown on the match list as `SPC *` didn't look for symbol in all project files
  - (even though the name `+default/search-project-for-symbol-at-point` suggests it should)

### System Information

emacs 28

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [ ] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by jvalkeejarvi** [comment]
I'm also facing this issue. Here is the output of `doom/info`: https://pastebin.com/ptfVizY4

**Comment by razzmatazz** [comment]
> I'm also facing this issue. Here is the output of `doom/info`: https://pastebin.com/ptfVizY4

@jvalkeejarvi I see there is a duplicate issue to follow:
- https://github.com/hlissner/doom-emacs/issues/5831

**Comment by hlissner** [comment]
#5831 helped me realize what the cause of this issue was. Sorry about that! As of f0ba6c99b26b0bf23495323a3097cab7d057ea3d this should be fixed.

**Comment by razzmatazz** [comment]
❤️
