### ISSUE TITLE
Whitespace mode is not enabled

### ISSUE THREAD

**Issue by bkchr** [hlissner/doom-emacs#5854]
### What did you expect to happen?

Whitespace mode is enabled by `(global-whitespace-mode +1)`. However, it is not activated. I checked the code and then disabled the custom `whitespace-enable-predicate`, after that it works. 

FYI: I'm using emacs 28. 

### What actually happened?

whitespace mode is not enabled.

### Describe your attempts to resolve the issue

Removed setting `whitespace-enable-predicate` and that solves it.

### Steps to reproduce

Enable global white space mode.

### System Information

https://pastebin.com/APsYsM2t

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by hlissner** [comment]
Some likely explanations for this behavior:

1. You've modified `whitespace-global-modes` in your config, because unsetting `whitespace-enable-predicate` suggests you have changed it from its default of `t` (i.e. "enable whitespace-mode in all major modes").
2. You are testing in a buffer whose name starts with whitespace or asterix (i.e. a temporary/special buffer). This is one of the tests in [the default `whitespace-enable-predicate` function](https://github.com/emacs-mirror/emacs/blob/master/lisp/whitespace.el#L1002-L1016) (this includes the `*scratch*` buffer).

**Comment by hlissner** [comment]
I figured out the cause and solution for this issue in #5856. See https://github.com/hlissner/doom-emacs/issues/5856#issuecomment-984254309.

**Comment by bkchr** [comment]
@hlissner ty for reporting back and ty for fixing it!

Sorry for the bad issue.
