### ISSUE TITLE
Doom git hooks installing on my home directory

### ISSUE THREAD

**Issue by Sleepful** [hlissner/doom-emacs#5878]
### What did you expect to happen?

I am working on random git bare repository and when I try to commit, the doom hook tells me I cannot

### What actually happened?

```
$ git commit -m "something" 

 hook: master

> Executing 'doom ci hook-commit-msg /Users/poop/.cfg/COMMIT_EDITMSG' with Emacs 27.2 at 2021-12-09 03:57:58
  > Linting 1 commits
    > CURRENT multiplatform
      ! Subject is short (<20); are you sure it's descriptive enough?
      x Commit has no detectable type
      x Commit has no summary
  ! Warnings: 1
  ! Failures: 2
  
  See https://docs.doomemacs.org/-/conventions/git-commits
```

### Describe your attempts to resolve the issue

```
$ rm ~/.githooks/pre-push
$ rm ~/.githooks/commit-msg
```
worked pretty well

### Steps to reproduce

Fresh install of Doom on a new computer. 
```
$ rm -rf ~/.emacs.d
$ git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
$ ~/.emacs.d/bin/doom install
```
I have doom in another pc since a year ago and this isn't a problem, i Imagine it is something with the install

### System Information

OSX

**Comment by gagbo** [comment]
For the record it happened again to someone else, also [on MacOS](https://discord.com/channels/406534637242810369/406554085794381833/927954746151682048)

So the issue seems to be that the `default-directory` let-binding to get the [path to hooks](https://github.com/hlissner/doom-emacs/blob/78324248435b395e25edbd2e06c352b1062e5395/core/cli/ci.el#L17-L18) isn’t working in those 2 cases.

As the doc of `call-process` suggests, if it can’t find a proper directory, the working directory of the process will be `~`, which deploys hooks for all repos of the user.

Since `call-process` has a [C implementation](https://github.com/emacs-mirror/emacs/blob/a0263cfee3cf64f4a77f90591af7ef7d8d78d8db/src/callproc.c#L243-L314) relying on another [C subroutine](https://github.com/emacs-mirror/emacs/blob/a0263cfee3cf64f4a77f90591af7ef7d8d78d8db/src/fileio.c#L488-L514), I didn’t really look much further into this. Especially if it turns out a MacOS specific thing, since there would be extra patches to look for (in the recipes used to build/install Emacs on the OS), and I don’t have apple hardware anyway

**Comment by hlissner** [comment]
1c1ad3a adds a `--no-hooks` switch to `doom install`, which should allow folks to get around this issue, so I'll consider this resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by msolglu** [comment]
I'm using the git config option [core.hooksPath](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corehooksPath) to set some global hooks that should run on all my repositories. When I ran `doom install` it replaced both my commit-msg and pre-push hooks with the doom's hooks. Luckily I keep my git hooks under source control, so I could restore them.

This line is probably the culprit
https://github.com/hlissner/doom-emacs/blob/fca8bd7f3fa697a91774c2ddedcd1a47cd7da01a/core/cli/ci.el#L18

because `git rev-parse --git-path hooks`  is returning the global hook path unless it's been overridden locally (e.g via `git config --local core.hooksPath .git/hooks`)
