### ISSUE TITLE
Modeline font is not a sans font

### ISSUE THREAD

**Issue by vooop-binary** [hlissner/doom-emacs#5891]
### What did you expect to happen?

The modeline font should be the font I specified in ``config.el``

### What actually happened?

here's an image
![Screenshot 2021-12-13 at 11 42 58 PM](https://user-images.githubusercontent.com/68045994/145866355-92f75474-96ee-41ee-9815-a4691de1c2b5.png)

### Describe your attempts to resolve the issue

Tried looking in Customize group couldn't find anything.

### Steps to reproduce

New installation of doom emacs.

### System Information

https://pastebin.com/zKg3xyRT

**Comment by hlissner** [comment]
This is not technically a bug. Emacs 29 introduced the `mode-line-active` face which, by default, inherits the `variable-pitch` face, which means the mode line will use your default variable-pitch font instead of your fixed-pitch font (what you have set for `doom-font`).

As such, this "issue" depends entirely on your choice of theme. Since I think a monospace font is the more sensible default, I've [addressed this in the doom-themes package](https://github.com/hlissner/emacs-doom-themes/commit/7d1a56623c08da769fd424e901916e9c3d8fdb25) (which affects all of our `doom-*` themes), **but** this issue will arise again if you use themes that haven't done this for you.

In those cases add this to your config:

```elisp
;; add to $DOOMDIR/config.el
(custom-set-faces! '(mode-line-active :inherit mode-line))
```

Anyhow, I'll consider this resolved, as far as Doom is concerned. Thanks for bringing it to my attention!

**Comment by vooop-binary** [comment]
This worked for me, thanks a lot.
