### ISSUE TITLE
all-the-icons not work

### ISSUE THREAD

**Issue by mathslimin** [hlissner/doom-emacs#5906]
### What did you expect to happen?

 no icon show in the emacs

### What actually happened?

M-x all-the-icons-install-fonts

install succes
 no icon show in the emacs

### Steps to reproduce

just start

### System Information

  generated    Dec 17, 2021 20:59:10  system       Ubuntu 20.04.1 LTS Linux 4.19.104-microsoft-standard x86_64  emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/  doom         21.12.0-alpha grafted, HEAD -> develop, origin/develop, origin/HEAD 45a55c0 2021-12-16 15:05:28 +0100 ~/.doom.d/ -> ~/.doom.d/  shell        /bin/bash  features     XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER $  traits       tty envvar-file  modules      :completion company vertico :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :ed$

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
