### ISSUE TITLE
in c/c++-mode, of syntax highlighting for double quotes is wrong

### ISSUE THREAD

**Issue by horchi** [hlissner/doom-emacs#5922]
### What did you expect to happen?

I use GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0
and have the same problem as descried here https://github.com/hlissner/doom-emacs/issues/1626

### What actually happened?

I always have to put a third " in between and than delete it after or closing and opening the file again to fix the highlighting.

### Describe your attempts to resolve the issue

tried on different host with plain new installation

### Steps to reproduce

it happens not always but mostly when you do two " right after each other. In JavaScript mode it works without errors.

### System Information

Ubuntu 21.10

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
