### ISSUE TITLE
Company-fuzzy (+fuzzy)

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#5938]
### Describe your request

Would be very nice to have company-fuzzy on doom.  

I tried very hard to use but doom do some magics and changes the backend (company-fuzzy).  Would be nice to have just an hook after all that magic that just sets the company-fuzzy

### Briefly explain its use-case

on my environment i have some variables like

send_boleto_letter_with_confirmation
send_boleto_letter_with_notification
send_boleto_letter_with_foo_bar

And is much easier to type sendconfir or sendnotif instead send C-n C-n C-n C-n C-n.

**Comment by hlissner** [comment]
Sorry to say: I don't intend to add `company-fuzzy` or fuzzy completion to company because `company-fuzzy` is buggy, slow, and has poor interoperability with other backends (most of them). I don't want to officially use or endorse it, much less maintain it, so I leave it to users to add to their own config if they want it.

I'd like to eventually transition Doom away from company and toward [corfu](https://github.com/minad/corfu) (and native completion-at-point-function -- aka CAPF), for whom fuzzy completion would be much easier layer over. Perhaps https://github.com/minad/cape can allow us to do this sooner, by making corfu company's front-end, but I haven't looked into cape yet. I'd welcome a PR to do so if it is capable of it, however.

Anyhow, it won't be until CAPF sees wider adoption by major modes and server plugins that I introduce corfu to Doom.
