### ISSUE TITLE
+lookup/definition with python doesn't jump to external dependencies

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#5952]
### What did you expect to happen?

If I have a simple python file, e.g.:
```python
from skimage import data, filters


def asd():
    print("asd")


image = data.coins()
edges = filters.sobel(image)
print(edges.shape)
asd()
```
and do a `+lookup/definition` on `asd()` then it jumps to `def asd`, but doing it on `coins` or `sobel` doesn't work. 
This used to work in earlier versions, with the lookup it would jump to the library function (if it's available). 

This is reproducible with a fresh install and adding `lsp` and `(python +lsp +pyenv +poetry)` to `init.el`. It happens both with pyenv and poetry, I haven't tried conda.

### What actually happened?

The lookup doesn't jump anywhere, or just points to the import.

### Describe your attempts to resolve the issue

I tried to narrow it down in case it's only pyenv or poetry, but it seems to happen with both. 
I didn't back up my previous `.emacs.d`, but I remember this working with my previous install that was pulled approx half a year ago.

### Steps to reproduce

1. Clone new repo,
2. Change init.el
3. Open a test file (see above) (add `.python-version` or `pyproject.toml` and run `pip install scikit-image`)
4. Run `+lookup/definition` (or `G d`)

### System Information

https://pastebin.com/1tTcyPZz

**Comment by hlissner** [comment]
Since you're using `:lang python +lsp`, the LSP server (e.g. pyls, mspyls, pyright, etc) is responsible for telling our `+lookup/definition` command where to send you. And it's [lsp-mode](https://github.com/emacs-lsp/lsp-mode)'s responsibility to request and respond to that information from the LSP server. 

1. If you know your LSP server indexes external dependencies, make sure LSP server is up-to-date (`M-x lsp-update-server`).
2. If you use mspyls, try unpinning the lsp-python-ms package:
   ```elisp
   ;; add to $DOOMDIR/packages.el
   (unpin! lsp-python-ms)
   ```
   Then run `doom sync -u` and restart Emacs.
3. Otherwise, something upstream may have changed, either in [lsp-mode](https://github.com/emacs-lsp/lsp-mode) or your LSP server, and the issue should be reported to them.

That said, this ball is not in Doom's court to fix, so I will close this, but feel free to follow up here if you discover otherwise.

**Comment by vakker** [comment]
Thanks for pointing in the right direction!

For reference:
The problem was that I had pylsp installed in the base environment, and that way it doesn't jump to the virtual env's definition. Installing the server in the virtual env (i.e. `pip install python-lsp-server`) makes `lsp-mode` to pick up pylsp from the activated virtual env and everything works fine.
I'm not sure how this works with `mspyls` or `pyright`, but the corresponding issue for pylsp is [here](https://github.com/python-lsp/python-lsp-server/issues/29) (which points to the clients to set `pylsp.plugins.jedi.environment` properly), and `lsp-mode` has [this](https://github.com/emacs-lsp/lsp-mode/issues/1290) and [this](https://github.com/emacs-lsp/lsp-mode/issues/393) issue that's related, and the consensus seems to be to just install the server in the virtual env.

Also, there's `lsp-pylsp-plugins-jedi-use-pyenv-environment`, which does exactly that (for pyenv at least). So I guess there should be the same for `poetry` and maybe `conda` in `lsp-mode`.
