### ISSUE TITLE
Set `lsp-ui-doc-show-with-cursor` to `t` as default

### ISSUE THREAD

**Issue by mangkoran** [hlissner/doom-emacs#5970]
### Describe your request

Currently both `lsp-ui-doc-show-with-cursor` and `lsp-ui-doc-show-with-mouse` are set to `nil`. It would confuse people as they would think that `lsp-ui-doc` is not showing on both cursor and mouse hover.
![image](https://user-images.githubusercontent.com/57625126/148643524-c5d097e1-3d51-4996-862e-fd7815655b5f.png)

### Briefly explain its use-case

Well I think my request are clear enough..

**Comment by hlissner** [comment]
Doom prioritizes keyboard-centricity (why I disable the menu and tool bars, for instance). I don't intend to accommodate mouse/cursor workflows any more than the defaults already do (unless it's provided by the terminal). What's more, both `lsp-ui-doc-show-with-{cursor,mouse}` are both `nil` by default, so I don't think this is will be a source of confusion with Doom in particular.

In any case, because this can be trivially enabled by the user, I will leave it to them to enable themselves:

```elisp
;; add to $DOOMDIR/config.el
(after! lsp-ui
  (setq lsp-ui-doc-show-with-mouse t
        lsp-ui-doc-show-with-cursor t))
```

**Comment by mangkoran** [comment]
If both variable are not enabled by default (by Doom), then why this line is defined?
https://github.com/hlissner/doom-emacs/blob/67a9573f0de2f2cf10408c646cb5ff8781b51ce8/modules/tools/lsp/%2Blsp.el#L167

**Comment by hlissner** [comment]
> then why this line is defined?

In case the user enables it. `0.2` triggers the docs too often and is a cause of performance issues, so I've reduced its default delay.
