### ISSUE TITLE
Error loading org-mode with (org +roam2) module.

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#5981]
### What did you expect to happen?

`org-roam2` module should load correctly without error messages.

### What actually happened?

With `(org +roam2)`, whenever I start Emacs, or when I try to activate `org-mode`, I get the message 
`condition-case: Error in a Doom startup hook: org-load-hook, +org-init-roam-h, (void-function :when)`. `org-mode` is prevented from loading. I tried removing all my settings for Org and Org-roam and the issue persists.

### Describe your attempts to resolve the issue

Removing the hook with `(remove-hook 'org-load-hook '+org-init-roam-h)` allows org to be loaded, but it still get the message `progn: Symbol’s function definition is void: :when. ` I haven't tested if `org-roam` actually works this way.

### Steps to reproduce

1. Open emacs with module`(org +roam2)` installed.
2. `M-x org-mode`
3. See if Org loaded correctly and if there's any error message

### System Information

https://pastebin.com/h1XtFmaE

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible. (Need a [backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error), at least)
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [X] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
