### ISSUE TITLE
Unable to install Doom on GccEmacs on Windows

### ISSUE THREAD

**Issue by rzikm** [hlissner/doom-emacs#6012]
### What did you expect to happen?

When I run doom install, the doom emacs correctly installs

### What actually happened?

```
❯ .\bin\doom install
Debugger entered--Lisp error: (native-compiler-error (lambda (&rest arg0) (let ((f #'run-hooks)) (apply f arg0))) "Compiling c:/Users/radekzikmund/.emacs.d/.local/ca...")
  signal(native-compiler-error ((lambda (&rest arg0) (let ((f #'run-hooks)) (apply f arg0))) "Compiling c:/Users/radekzikmund/.emacs.d/.local/ca..."))
  comp--native-compile((lambda (&rest arg0) (let ((f #'run-hooks)) (apply f arg0))) nil "c:/Users/radekzikmund/.emacs.d/.local/cache/eln/29...")
  comp-trampoline-compile(run-hooks)
  comp-subr-trampoline-install(run-hooks)
  advice--add-function(:override (#f(compiled-function () #<bytecode 0x34008019df7e91>) . #f(compiled-function (gv--val) #<bytecode 0x9c83cbbba7cb3c2>)) doom-run-hooks nil)
  advice-add(run-hooks :override doom-run-hooks)
  load-with-code-conversion("c:/Users/radekzikmund/.emacs.d/core/core.el" "c:/Users/radekzikmund/.emacs.d/core/core.el" nil t)
  load("c:/Users/radekzikmund/.emacs.d/core/core.el" nil t)
  load-with-code-conversion("c:/Users/radekzikmund/.emacs.d/bin/doom" "c:/Users/radekzikmund/.emacs.d/bin/doom" nil t)
  command-line-1(("-scriptload" ".\\doom" "--" "install"))
  command-line()
  normal-top-level()
```

### Steps to reproduce

Install windows GccEmacs distribution from https://github.com/kiennq/emacs-build/releases/tag/v0.220101.1d3020908
try installing doom

### System Information

Unavailable

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [ ] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] This issue doesn't appear to be a Doom issue; more likely explanations are:
  + [ ] A pilot error.
  + [ ] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [X] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.
