### ISSUE TITLE
Symbol’s function definition is void: if-let

### ISSUE THREAD

**Issue by Fibrasek** [hlissner/doom-emacs#6051]
### What did you expect to happen?

I needed to update my emacs env and when I try to run any of the commands I get the following:

```
~ on ☁️  (eu-west-1)
❯ ~/.emacs.d/bin/doom env
Symbol’s function definition is void: if-let

~ on ☁️  (eu-west-1)
❯ ~/.emacs.d/bin/doom sync
Symbol’s function definition is void: if-let

~ on ☁️  (eu-west-1)
❯ ~/.emacs.d/bin/doom upgrade
Symbol’s function definition is void: if-let
```

### What actually happened?

When I try to run any commands from `bin/doom` I get `Symbol’s function definition is void: if-let`

### Describe your attempts to resolve the issue

It's happening after a clean install, so I don't know

### Steps to reproduce

1. Do a clean install;
2. bin/doom upgrade
3. bin/doom compile
4. bin/doom <any commands>
5. Symbol’s function definition is void: if-let

### System Information

https://pastebin.com/ya12i4ZU

**Comment by hlissner** [comment]
Your config is byte-compiled. Run `doom clean` to "uncompile" it. I highly recommend against blindly running `doom compile` in the future. If the issue still doesn't go away, reinstall Emacs (preferably from a different source). `if-let` is built into Emacs. If it isn't available, something is amiss with your installation, not Doom.

I'll close this, since I'm 99.99% certain it has nothing to do with Doom. Hope that helps!

**Comment by cjbarroso** [comment]
Had the same issue, just deleted all .elc files in my .emacs.d/ and it fixed it.
