### ISSUE TITLE
Magit performing very slowly after moving to master

### ISSUE THREAD

**Issue by tavurth** [hlissner/doom-emacs#6078]
### What did you expect to happen?

Magit should be as performant as it was a few days ago while on the develop branch

### What actually happened?

I recently moved from the develop branch to the master branch.

Magit in general now feels very sluggish.

### Describe your attempts to resolve the issue

Unknown

### Steps to reproduce

I'm not sure why this broke

### System Information

https://paste.ofcode.org/EuNvyTqDVDHP9ZRHegWupM

**Comment by tavurth** [comment]
Hmm seems to have resolved 🤔

**Comment by tavurth** [comment]
Hmm seems that this issue is actually present after all. 

My latency for magit commands on the develop branch was far less than a second unless I was working with a huge project.

Now each action (staging, unstaging etc) takes around 1.5 seconds to perform.

Any idea what I could do to fix this?

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by hlissner** [comment]
Have you tried re-cloning Doom? Perhaps with `--single-branch`, as not to pull in too much? May help to inspect your local git config or proxy settings. Only other possibility that comes to mind is Forge (which you have enabled). It tends to be expensive in larger repos. That or it's trying (and failing) to compile emacsql. Check your \*Messages\* buffer (press `C-h e`) for errors/warnings after opening Magit.

**Comment by tavurth** [comment]
@hlissner Thank you!
I removed forge and it seems a lot snappier now :)
