### ISSUE TITLE
Latex build 

### ISSUE THREAD

**Issue by onekk** [hlissner/doom-emacs#6085]
### Describe your request

I have problem with latex.

I ussally use a plain emacs configuration with latex calling arara for compiling and unsing zathura as viewer:

usually I have these commands:

```
(with-eval-after-load "tex"
  (add-to-list 'TeX-command-list
        `("Arara" "arara --verbose %s" TeX-run-TeX nil t :help "Run Arara") t))
```

```
(use-package lsp-latex
  :ensure t)

(with-eval-after-load "tex-mode"
 (add-hook 'tex-mode-hook 'lsp)
 (add-hook 'latex-mode-hook 'lsp))
 (add-hook 'LaTeX-mode-hook 'lsp)

;; For bibtex
(with-eval-after-load "bibtex"
 (add-hook 'bibtex-mode-hook 'lsp))

(setq lsp-latex-texlab-executable-argument-list
      '("-vvv"))

(setq lsp-latex-build-executable "arara")
(setq lsp-latex-build-args
      '("-v" "%f" ))

(setq lsp-latex-forward-search-executable "zathura")
(setq lsp-latex-forward-search-args
      '("--synctex-forward" "%l:1:%f" "%p")
```

To make thing works.

I uase auctex too that is correctly loaded by doom emacs, like texlab that seem to be invoked, as i have some buffer with texlab on title.

I've done some question on Discord, but no luck.

Regards

Carlo D.

### Briefly explain its use-case

See above

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] A feature request was a filed for what is clearly a bug report.
+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible (no system info, no steps to repro)
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [X] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by hlissner** [comment]
Please do not use our issue tracker for support requests. Ask on Discord. If you didn't get a response, please wait longer or ask on [r/emacs](https://www.reddit.com/r/emacs/).
