### ISSUE TITLE
Emacs hangs on enabling dart-mode and opening dart file

### ISSUE THREAD

**Issue by p4v4n** [hlissner/doom-emacs#6106]
### What did you expect to happen?

Open dart-mode file normally with syntax highlighting.

### What actually happened?

Emacs hangs with a cpu spike while opening the dart file.

### Describe your attempts to resolve the issue

Hard to debug further as emacs hangs.

### Steps to reproduce

1. Enable dart-mode in init.el  ;; (dart)  and run bin/doom sync
2. Open a dart-mode file with class/flutter syntax
 Example file: https://github.com/bradyt/dart-mode/blob/main/test/faceup/language-samples/classes.dart

### System Information

https://pastebin.com/gvJUvpEq

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by p4v4n** [comment]
Thanks @hlissner for the prompt response. I wasn't aware of doom/sandbox earlier.

Using the sandbox found that the issue was not happening on vanilla doom but on vanilla doom+(without my config). This narrowed it down to something in init.el. After some trial and error narrowed it down to objed module.
**Disabling objed module fixed the issue.**

Thank you once again for all your work on doom-emacs.
