### ISSUE TITLE
Modular load modules on the fly

### ISSUE THREAD

**Issue by BuddhiLW** [hlissner/doom-emacs#6107]
## Contextual
I have a lot of extra packages which are all keen to me. I often use them, just not all at the same time.

So, instead to load everything on start, I would like to call these bits of configurations, packages et al on the fly. The idea is close to lazy-loading, but explicit (up to the user).

### How I have achieved this so far:
This is my file-structure,
```shell
tree ./doom/ -L 2
```
```shell
.
(...)
├── modules
├── my-func
├── Emacs.org
├── emacs.el
(...)
```

In `Emacs.org` my configs are automatically tangle to `emacs.el`. The standard org-mode literate-programming. This file is currently moving toward only having `(map! ...)` bindings and really important startup-functionalities - the _base_ config.

In `my-func`  I have a bunch of home-cooked functions. Each pointing to a file currently. 

In `emacs.el`, I used to call each one of them with `(load! "./my-func/home-cooked.el")`.

Now, to increase startup-speed, I'm doing the following,

In `Emacs.org`,
```el
(load! "./my-func/define-modules.el")

(load! "./my-func/load-modules.el")

(map! :leader
      (:prefix-map ("b" . "buddhi")
       (:prefix ("l" . "load module")
        :desc "Chinese" "c" #'lw/load-chinese
        :desc "LaTeX" "l" #'lw/load-latex)))
```

In `my-func/my-func.org` (explaning `define-modules.el` and `load-modules.el`),

#### Loadable modules

_tangled to `define-modules.el`_
```el
    (defmacro lw/define-loadable (fn-name mod-name)
      `(defun ,fn-name ()
        (interactive)
        (load! (concat "../modules/" ,mod-name))))
```
  
_tangled to `load-modules.el`_
```el
(lw/define-loadable lw/load-chinese "chinese.el")
```

And, finally, inside `chinese.el`, for example, is chinese-related packages and configs. Which, now, I could call, when needed, on the fly, with `<SPC> b l c` mnemonic for [buddhilw load chinese]

Excerpt from `chinese.el`

```el
(setq doom-font
      (set-fontset-font "fontset-default" 'han
                        (font-spec :family "Sarasa Mono Slab HC")))

(package! zh-align
  :recipe (:host github
           :repo "chen-chao/zh-align.el"))

(use-package! pyim-basedict)

(use-package! pyim
  :config
  (require 'pyim-basedict) ; 拼音词库设置，五笔用户 *不需要* 此行设置
  (pyim-basedict-enable)   ; 拼音词库，五笔用户 *不需要* 此行设置
  (setq default-input-method "pyim")
  (setq pyim-page-length 10)
  (pyim-isearch-mode 1))

(use-package! bing-dict
  :config
  (map! :leader
        (:prefix-map ("b" . "buddhi")
         (:prefix ("b" . "bing")
          :desc "Bing dictionary brief" "d" #'lw/bing-dict-brief
          :desc "Personal vocabulary" "p" #'lw/find-vocabulary)))
  ;; :desc "Activate synonym" "s" #'lw/bing-synonym))))

  (setq bing-dict-add-to-kill-ring t)
  (setq bing-dict-show-thesaurus 'both)
  (setq bing-dict-vocabulary-save t)
  (setq bing-dict-vocabulary-file "~/PP/Notes/vocabulary.org"))
```

### Result
Faster startup; when I need **chinese-functionalities**, now I call `<SPC> b l c` and it call the piece of chinese-code that was on `emacs.el` previously and slowed Emacs startup-time.

**Comment by BuddhiLW** [comment]
TODO: do the same process with all current "bloat" packages. And, test against current shown startup-time.

**Comment by hlissner** [comment]
> Example with the chinese module.

Your link does not work.

![image](https://user-images.githubusercontent.com/510883/153654267-29281359-84c0-4fd7-a586-3d2d53f59a7e.png)

-----

If I understood you correctly, your request is to lazy-load Doom's modules.

Doom (and Emacs) already provide lazy loading mechanisms at the package level. I've already experimented with lazy loading at the module level (or even concatenating all modules into one mega elisp file. Neither yielded noteworthy benefits. I saved a negligible ~2ms lazy loading *all* 150+ modules. What's worse, it would *significantly* overcomplicate user and cross-module package configuration. 

I'd rather seek out better ways to achieve faster startup times. pdumper or CRIU integration would yield far better results, for instance.

That said, Doom does provide the means to pull this off. Just move config.el to another file, say, deferred-config.el, then put your custom boostrapper in that module's autoload.el. You can then load deferred-config.el when you, say, execute a command -- as you have -- but this is not a practice I want Doom to adopt. At least not now.

I have been working on an extensive rewrite of how Doom initializes packages and modules and what is cached when running `doom sync`. It will improve startup times and indirectly allow users to lazily activate modules (e.g. when visiting a *.py file, it'll ask to activate `:lang python`), which _could_ be trivially extended to lazy load modules as you've suggested, but I'll revisit its practicality when we cross that bridge.

For now I'll close this issue since I've rejected the core request (to make modules lazy loadable), at least until v3.0.0 of Doom's core, but feel free to bring it up again once we get there, and to follow up here despite the closed thread.
