### ISSUE TITLE
Emacs hangs after opening go file with lsp-mode, ivy, and evil-mode

### ISSUE THREAD

**Issue by aayushoj** [hlissner/doom-emacs#6212]
### What did you expect to happen?

Emacs should work with lsp powered (gopls) completions for golang. 

### What actually happened?

Emacs becomes unresponsive. Key presses don't change anything. In the emacs modeline, I see "loading packages" message. htop shows high CPU usage for emacs.

![image](https://user-images.githubusercontent.com/7604405/159599602-0d21abaf-6216-429b-a23b-df5ac0ef3096.png)

![image](https://user-images.githubusercontent.com/7604405/159599687-15da525e-bdab-4558-8945-d8ed763d6e4b.png)

### Describe your attempts to resolve the issue

Being new to emacs and doom-emacs, I have no idea on how to debug it. I ensure that gopls and gocode are installed in $GOPATH/bin. I checked that after enabling lsp for go, gopls is running (and gocode is not). I think this is the desired behaviour.

### Steps to reproduce

1. Enable lsp, company, (go + lsp), evil-mode and (ivy + fuzzy + prescient)
2. Install gopls 
3. Run doom sync
4. Open or reload Emacs
5. Open a go file
6. Press i to enter in Insert mode (evil). Type 4-5 characters.

### System Information

https://pastebin.com/QWhRMMyK

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [ ] Vital information was omitted or inaccessible.
  + [ ] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by hlissner** [comment]
Try to [unpin](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#pinning-packages-to-specific-commits) the `:lang go` and `:tools lsp` modules, then run `doom sync -u` and restart Emacs.

If that doesn't work then this is likely an issue with the gopls client. It's hard to say, I couldn't reproduce this in a simple go project, and I'm not a Go programmer so I have no insight into the ecosystem. You may have better luck bringing it up to the [lsp-mode](https://github.com/emacs-lsp/lsp-mode) project.

**Comment by hlissner** [comment]
Oh, I just noticed in your `M-x doom/info` that you have `(go + lsp)` enabled. Not `(go +lsp)`. Make sure there is no whitespace between the `+` nad `lsp`, otherwise these are two invalid flags and the result is LSP support for got is never set up properly.

**Comment by aayushoj** [comment]
I tried unpinning, and removing whitespace. Did not see any change in behaviour of doom emacs.
I was thinking this may be due to doom-emacs so I tried emacs with minimal config for lsp-mode with go. I landed into the same issue so it's not a doom emacs issue. Problem here is either lsp-mode or gopls (most likely). 

@hlissner  Thanks for the help on this.
