### ISSUE TITLE
binding for all apps gone?

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#624]
commit 13267250a41f2b9ea32be3a4cd4f01d42ad61e7e removed all apps binding. Is it intended change?

``` elisp
:desc "APP: elfeed"           :n "E" #'=rss
:desc "APP: email"            :n "M" #'=email
:desc "APP: twitter"          :n "T" #'=twitter
:desc "APP: regex"            :n "X" #'=regex
```

**Comment by hlissner** [comment]
This was intentional. These commands were too imposing to put so close to other common keybinds. For example, `SPC o T` (open twittering-mode) and `SPC o E` (open mu4e), are too close to `SPC o t` (open term) or `SPC o e` (open eshell) and are not functionally similar. 

The new recommended workflow is to activate these apps via `M-x` (that is why their commands start with a `=`, which is easy to search for).

**Comment by liujoey** [comment]
Fair enough. Closing it. 👍
