### ISSUE TITLE
typescript-mode.elc failed to define function typescript-tsx-mode

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#6243]
### What did you expect to happen?

Execute typescript-tsx-mode:

### What actually happened?

command-execute: Autoloading file /Users/otavio/.emacs.d/.local/straight/build-27.2/typescript-mode/typescript-mode.elc failed to define function typescript-tsx-mode

### Steps to reproduce

Open a tsx file

### System Information

https://pastebin.com/iymWAhPW

**Comment by hlissner** [comment]
I can reproduce this. Occurs because you don't have `:lang web` enabled, therefore [typescript-tsx-mode](https://github.com/hlissner/doom-emacs/blob/master/modules/lang/javascript/config.el#L124-L128) is never defined, despite it being [autoloaded for the typescript-mode package](https://github.com/hlissner/doom-emacs/blob/master/modules/lang/javascript/config.el#L96). I'll look into a proper fix soon.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
