### ISSUE TITLE
Disable Native Compiling?

### ISSUE THREAD

**Issue by zstg** [hlissner/doom-emacs#6292]
### Describe your request

Is there a way for Doom/Emacs to prevent native-compiling files every time i make changes to my dotfiles ?

Didn’t get this in Emacs 27.2, got it in 28.1

Uncommenting a _single_ line of code in my `init.el` or `packages.el` and running a `doom sync` results in  a `natively compiling 2200 files...`  message which takes **2 and a half hours** on my potato laptop 😢 

To make matters _worse_ , native compiling has **absolutely no** effect on the 2.2 sec startup time for loading 185 packages (pretty vanilla right?)

I'm using Doom on MSYS-MINGW64 on Windows 11

### Briefly explain its use-case

1. Install MSYS64 from the website
2. Get Doom Emacs for MSYS64

**Comment by port19x** [comment]
I'm surprised `doom sync` does that.
Native compilation could give a huge boost to my pinebook pro (arm64).
Shouldn't it just not compile with `sync`?

**Comment by zstg** [comment]
It should 


It doesn’t actually speed it up at all - even with the `cc` module enabled in `init.el`

**Comment by hlissner** [comment]
You can disable native-compilation altogether by throwing `(setq  straight-disable-native-compile t)` into `~/.doom.d/packages.el` or `~/.doom.d/init.el`, but I am currently working on a rewrite of our CLI (#4273), where I will:

- Add `--fast` switch to `doom {sync,install}` for selectively  skipping compilation.
- Add support for deferred native compilation, instead of ahead-of-type.

> To make matters worse , native compiling has absolutely no effect on the 2.2 sec startup time for loading 185 packages (pretty vanilla right?)

Native compilation has no effect on startup times. What it affects is _runtime_ performance, e.g. rapid scrolling, processing completion results, syntax highlighting, etc.

-----

Anyhow, since this issue is covered by #4273 I will close it as a duplicate, but feel free to follow up here.

**Comment by zstg** [comment]
I tried adding to my `init.el` and my `packages.el` - but it still compiles natively 😞 

It did compile a _lesser number_ of files though

**Comment by zstg** [comment]
This no longer seems to work - still compiles natively 😅

**Comment by zstg** [comment]
Should i create an issue in the Emacs repo? 

This can’t be a bug with Doom - just a SERIOUS problem with the Windows(MinGW) Emacs …

**Comment by zstg** [comment]
> This no longer seems to work - still compiles natively 😅
> […](#)

It would be nice if Doom had a way to disable this - not sure if it’s possible though

**Comment by PGaus** [comment]
I fell into the same pitfall.
To omit the native compilation, in my setup throwing `(setq native-comp-deferred-compilation t)` into _init.el_ helped.

My setup:
- GNU Emacs 28.2 (build 2, **x86_64-w64-mingw32**) of 2023-03-12
```
GNU Emacs     v28.2            0b81343376bfc30ea7688c31ce70057aaac68982
Doom core     v3.0.0-pre       HEAD -> master, origin/master, origin/HEAD 042fe0c4 2023-04-12 15:09:23 -0400
Doom modules  v23.03.0-pre     HEAD -> master, origin/master, origin/HEAD 042fe0c4 2023-04-12 15:09:23 -0400
```

**Comment by zstg** [comment]
1) I ended up switching to Arch.
2) I've been using a build without native compilation.
