### ISSUE TITLE
Ivy not used in ex commands completion

### ISSUE THREAD

**Issue by liaowang11** [hlissner/doom-emacs#640]
### Observed behavior

Completions in *ex commands* show up in `minibuffer completion` (not sure its real name) instead of ivy.
![image](https://user-images.githubusercontent.com/255802/40828670-e0aac556-65b3-11e8-8be1-24aadca2b4b9.png)

### Expected behavior

Use `ivy` for completion.

### Steps to reproduce

1. type <kbd>:</kbd>
2. input "doom/d"
3. press <kbd>TAB</kbd> to complete

**Comment by liaowang11** [comment]
The fix no longer works after merging in recent commits.

**Comment by filalex77** [comment]
Can reproduce: starting with e498a7e2cb66ef1d6305a206a3f3924e4c4501ac (`straight` getting merged) this does not work.

I can't easily get back to the old `develop` state without rebuilding a lot of stuff, so I wont do `git bisect` for now.

**Comment by hlissner** [comment]
Sorry for the late response. [This is intentional](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/config.el#L123-L128). Ivy struggles to complete certain types of evil-ex arguments, so it is disabled for it.

If you'd like to try your chances and reverse the advice, use this:

```elisp
(after! ivy 
  (advice-remove #'evil-ex #'+ivy--inhibit-in-evil-ex-a))
```

Alternatively, you can still search evil ex history with ivy via the `C-s` keybind.

Hope that helps!
