### ISSUE TITLE
Strange behavior for setting $PATH

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#687]
I recently run into very strange error where my pyvenv package no longer work. This package basically allows me select one of the python virtual environment I've created and manipulate the $PATH env.

It was working few weeks ago and all of sudden things broken, I've no idea how to trace this issue so I have to ask here.

I'm using Emacs in a Mac system, I launch Emacs from GUI so I'm aware of that Emacs doesn't use $PATH from my .zshrc file.

When I first start Emacs from GUI, the script `(getenv "PATH")` shows this value:
```
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin
```
Which is already different from my terminal, even Doom has `exec-path-from-shell` package enabled. First of all, I don't know why my PATH is not the same as my terminal has.
Nevertheless, if I do `M-! echo $PATH`, I will get the same output as above. Looks good.

Now if I run `pyvenv-workon` command and then choose one of the virtual env, let's say it's name is 'ipsa', this is where strange things happen.

My `(getenv "PATH")` gives me this:
```
"/Users/joey/.virtualenvs/ipsa/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin"
```

Which is good here because the `ipsa/bin` is at the beginning of the PATH, but `M-! echo $PATH` gives me this:
```
/usr/local/bin:/usr/local/sbin:/Users/joey/.virtualenvs/ipsa/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin
```
The biggest shock for me here is, even though `ipsa/bin` is in the $PATH, it was put after `/usr/local/bin` and `/usr/local/sbin`. I tried to search everywhere but can't figure out why would this happen. The code which changes $PATH in pyvenv package looks like this:
```lisp
(setq pyvenv-old-exec-path exec-path
          pyvenv-old-eshell-path eshell-path-env
          pyvenv-old-process-environment process-environment
          ;; For some reason, Emacs adds some directories to `exec-path'
          ;; but not to `process-environment'?
          exec-path (append new-directories exec-path)
          ;; set eshell path to same as exec-path
          eshell-path-env (mapconcat 'identity exec-path ":")
          process-environment (append
                               (list
                                (format "VIRTUAL_ENV=%s" directory)
                                (format "PATH=%s"
                                        (mapconcat 'identity
                                                   (append new-directories
                                                           (split-string (getenv "PATH")
                                                                         path-separator))
                                                   path-separator))
                                ;; No "=" means to unset
                                "PYTHONHOME")
                               process-environment)
          ))
```
It's just setting `process-environment` I have no idea how this change the value to $PATH in the `shell-command` context. But it's really strange for me why the `ipsa/bin` was inserted at the third place.

This is really not a simple issue anymore but I just need some help on where to look at. Thank you.

Here is my environment:

```
Doom Doctor
Emacs v26.1
Doom v2.0.9 (6fe0017e)
shell: /bin/zsh
Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
uname -a:
  Darwin MACC02QJ0ZFG8WM 17.6.0 Darwin Kernel Version 17.6.0: Tue May 8 15:22:16
  PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```

**Comment by liujoey** [comment]
I think I've just found it. In my ~/.zprofile I have these lines:
```zsh
# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)
```
These lines are there from the first day I've never had any issue until now.

This surprised me that pyvenv setup $PATH even before .zprofile was loaded. And I have no idea since when this new behavior started. I'm also not sure which software upgrades cause it, emacs or zsh?

**Comment by hlissner** [comment]
That your `PATH` does not match your shell environment's on startup indicates an issue with a) `exec-path-from-shell`, b) Doom's usage of it or c) your zsh config. 

Here's what's going on: when you run `shell-command` you are spawning a shell which will naturally have your zsh shell environment. However, when you change your pyvenv virtualenv, pyvenv creates a whole new environment _within Emacs_ (with a new `PATH`, derived from the erroneous PATH you started with). This becomes your new super environment, which `shell-command` will inherit from that point on.

I think the best way to fix this is to ensure Doom and `exec-path-from-shell` are doing their job. So try running this in your shell:

```sh
zsh -i -c 'echo $PATH'  # interactive session
zsh -c 'echo $PATH'     # non-interactive session
```

Doom will read your environment from a non-interactive shell. If the second command does not produce the PATH that you want, then the issue is your zsh config. Mainly, you must be setting up your PATH in `.zshrc` and/or `.zprofile`, but not `.zshenv`.

If that command produces the correct PATH, then the issue is likely on Doom's side and I'll have to look into it.

**Comment by liujoey** [comment]
Appreciate your patient. I do believe this is not a Doom's issue but your knowledge helped me a lot.
I did investigate the `exec-path-from-shell` source code and found something interesting.
The `exec-path-from-shell` package uses a command something like this:
```
/bin/zsh -l -c "/usr/bin/printf '__RESULT\\000%s\\000%s\\000__RESULT' \"${PATH-12b36a891fe1d29c921232506ef804b5}\" \"${MANPATH-12b36a891fe1d29c921232506ef804b5}\""
```
And the package author apparently assumed that above command produce same result in terminal as it does in emacs.

Unfortunately for me this is only true when I start emacs from a terminal. If I start Emacs from launcher, the $PATH I will get is always `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin`. Seems like when MacOS start up an app from launcher there's something else controlling the environment variables.

**Comment by hlissner** [comment]
I think there's a misunderstanding. The purpose of the `exec-path-from-shell` package is to resolve exactly this problem. On MacOS, launching Emacs through an *.app bundle launches it in a simple shell environment where your zsh settings are not read.

`exec-path-from-shell` tries to "grab" your shell environment from your shell by running it from Emacs. That is what happens when you do `M-! echo $PATH`. However, if you eval `(setenv "PATH" "my:fake:path")` in Emacs, then all shell commands will obey that `PATH` over your shell. Emacs' process environment has the highest precedence. And changing the process environment is how the pyvenv.el plugin works.

So the way to fix this is to make sure PATH is correct from the beginning.

+ If you run `zsh -c 'echo $PATH' ` from your terminal (not emacs), and it produces the correct PATH, then the issue is in Doom.
+ If you run that command and the PATH is incorrect, then the issue is in your zsh config (you should be setting up `PATH` from `.zshenv` too.

**Comment by liujoey** [comment]
`zsh -c 'echo $PATH'` from terminal gives me correct PATH. It's value is:
```
/Users/joey/Library/Python/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Applications/kitty.app/Contents/MacOS:/Users/joey/.fzf/bin
```
Run same command in Emacs with `M-!` gives me wrong PATH. It's value is:
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin
```

**Comment by hlissner** [comment]
What value does `M-; (getenv "SHELL")` return?

**Comment by liujoey** [comment]
/usr/local/bin/zsh, same as my terminal.

**Comment by liujoey** [comment]
There are two issue related from Spacemacs
https://github.com/syl20bnr/spacemacs/issues/3268
https://github.com/syl20bnr/spacemacs/issues/10906

From my understanding, get env from shell when running emacs from dock in Mac is not reliable. For now I don't even get pyenv work because that package relies on PYENV and PYTHONPATH environment variables.

**Comment by hlissner** [comment]
```sh
#!/bin/sh
$(/Applications/Emacs.app/Contents/MacOS/Emacs "$@") &
```

This script works because it inherits the environment of the zsh shell you run it from. At the very least, it's opening it in bash (`/bin/sh` is `/bin/bash` on MacOS), which you may or may not have configured.

Opening emacs from the shell fixes the problem, but it is not the ideal solution.

It is caused by opening GUI Emacs through the Mac dock, launcher or .app bundle. That is correct. `exec-path-from-shell` is supposed to address this problem. _However,_ it is obvious that it is not doing it's job correctly and I don't understand why.

Doom has configured exec-path-from-shell to use the PATH from `.zshenv`, _not from `.zshrc`/`.zprofile`/etc. Is your PATH configured in zshenv?

**Comment by liujoey** [comment]
you are right, i'm using [prezto](https://github.com/sorin-ionescu/prezto) as my zsh package management, it does many setups in the `.zshrc` implicitly, especially for python. When I manually moved things to `.zshenv`, problem solved.

Thank you for your patient. Closing the issue.
