### ISSUE TITLE
New popups don't pop up... and are hidden behind other frames

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#688]
A picture will be worth a thousand words here:

![image](https://user-images.githubusercontent.com/478606/41444982-3a0a5584-6ffb-11e8-875c-618a7a840139.png)

The error popup used to pop up. But now it seems to be embedded within the text, and as a result, gets hidden behind the right frame. Is there a trick I don't know about to read it without closing the right frame?

**Comment by hlissner** [comment]
Did you update recently? Recently, I got rid of the `:ui posframe` module and moved their respective plugins into other modules. For example, `flycheck-posframe` was moved into `:feature syntax-checker`, and can be enabled with `+childframe`.

Without the childframe feature, you are stuck with the popup mechanism you are currently using, which cannot escape the current window. Childframes can. Give it a try and let me know if that works for you.

**Comment by Ptival** [comment]
Indeed the chilframe seems to be what I am missing. However, I just copied the `init.example.el` from the most recent `develop`. It has `(syntax-checker +childframe)` in the `:feature` section. Yet, it still displays as an embedded frame rather than a floating one.

**Comment by hlissner** [comment]
What version of Emacs are you using? Childframes are an Emacs 26 feature. Are you using 25.x?

**Comment by Ptival** [comment]
Indeed I am on 25.3. Sorry about that! Was there some emulation of the feature earlier?

I guess I'll try and switch ahead to 26 then!

**Comment by hlissner** [comment]
A while ago, Doom used the flycheck-pos-tip package, but it was very buggy (because it used the OS's tooltip system). They were removed, and replaced with flycheck-popup-tip, which looks better and is much more predictable, but is trapped inside windows, as you see.

Alternatively, you can disable `flycheck-popup-tip` and have errors displayed in the mode-line, otherwise, you'll need emacs 26 to get `flycheck-posframe` working.

Also, I'm _slooowly_ moving toward removing Emacs 25 support toward the end of the year, so it is best to stick to 26, if you can. Doom already runs significantly better on there.
