### ISSUE TITLE
Question: private modules

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#704]
I want to have some private modules, such as my own `:lang myhaskell`, but I don't want to maintain my own fork. Is there any way to load modules from `~/.doom.d/modules/lang/myhaskell`. As far as I know, `doom-modules-dir` is defined as a constant. Is there any way around it?

**Comment by hlissner** [comment]
Doom supports modules in `~/.doom.d/modules`. It follows the same structure as `~/.emacs.d/modules/CATEGORY/MODULE/`. e.g. `~/.doom.d/modules/lang/haskell`.

If a private submodule has the same name as a Doom module, like `~/.doom.d/modules/lang/haskell`, then that effectively replaces Doom's.

Otherwise, if you want to put it in `~/.doom.d/modules/lang/myhaskell`, you'll have to add `:lang myhaskell` to your `doom!` block.
