### ISSUE TITLE
projectile-switch-project no longer works

### ISSUE THREAD

**Issue by skosch** [hlissner/doom-emacs#715]
An issue I've run into lately with the develop branch:

* `SPC p p` shows me recent project folders under `~/projects/` (I've set `(setq projectile-project-root "~/projects")`), as usual
* I can type or select a path, as usual – say, `~/projects/blog/`
* I hit enter, and it says `Switched to 'projects'`, and I'm still in `~/projects/` instead of in `~/projects/blog`.

This has always worked fine before and I haven't changed anything in my configuration. I could not find any relevant projectile bugs – could this be a doom issue?

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.2 (Sep 12, 2017)
- Doom: 2.0.9 (develop 25bc9cfbafa4a127e97cf225729995f8fa949c8f)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux wreck 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash (popup +all +defaults) neotree vc-gutter vi-tilde-fringe window-select :editor :emacs ediff electric imenu vc :tools :lang cc clojure data elixir elm emacs-lisp go (haskell +intero) (java +meghanada) javascript julia latex ledger lua markdown nix ocaml (org +attach +babel +capture +export +present +publish) perl purescript python rest ruby rust scala sh web :config)
  packages:  n/a
  exec-path: (~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/lib/x86_64-linux-gnu/emacs/25.3/x86_64-linux-gnu ~/.nvm/versions/node/v7.4.0/bin)
  ```
```
</details>

**Comment by hlissner** [comment]
I am surprised that this has not been an issue for you before. That is not the purpose of `projectile-project-root`. That variable determines the root of the project you're _currently_ in, not a directory for projectile _to search_ for your projects in.

It exists so that, if projectile's built-in mechanisms fail to find the root of the current project, you can set it manually. Instead, you've set it _globally_, and to a fixed path, telling projectile to forever consider `~/projects` the root of any project you are in.

Unset `projectile-project-root` and your issue should go away. Besides, you do not have to tell projectile where to look for your projects. Navigate to project files and projectile will remember their roots (which you access via `SPC p p`).

**Comment by skosch** [comment]
:man_facepalming:

Yeah, that solves it. I don't understand why this never caused issues before. Thanks for the explanation, I promise I'll double-check the manual next time!
