### ISSUE TITLE
Setting projectile-require-project-root to nil makes projectile index home

### ISSUE THREAD

**Issue by liaowang11** [hlissner/doom-emacs#733]
### Observed behavior

1. Open Emacs to DOOM Dashboard
2. Double tap <kbd>Space</kbd>
3. Projectile is initializing cache...
4. Emacs hang, have to <kbd>C-g</kbd> to force abort

### Expected behavior

1. Don't index home directory
2.`(setq projectile-require-project-root t)` fixes this

### Steps to reproduce

As stated above, core-projects sets `projectile-require-project-root` to `nil` for some reason:
```elisp
(def-package! projectile
  :after-call (pre-command-hook after-find-file dired-before-readin-hook)
  :commands (projectile-project-root projectile-project-name projectile-project-p)
  :init
  (setq projectile-cache-file (concat doom-cache-dir "projectile.cache")
        projectile-enable-caching (not noninteractive)
        projectile-indexing-method (if IS-WINDOWS 'native 'alien)
        projectile-known-projects-file (concat doom-cache-dir "projectile.projects")
        projectile-require-project-root nil
        projectile-globally-ignored-files '(".DS_Store" "Icon
" "TAGS")
        projectile-globally-ignored-file-suffixes '(".elc" ".pyc" ".o")
        projectile-ignored-projects '("~/" "/tmp"))
```

### System information

Irrelevant

**Comment by hlissner** [comment]
Thanks for letting me know!

`projectile-require-project-root` is set to nil because I prefer that projectile assume the current directory is the project root in the absence of a valid project, rather than unhelpfully throw an error. I'd rather trust the user to know what they're doing than to do nothing at all.

However, this has been reported before, and seems to be a common issue, so `projectile-require-project-root` is now locally set to `t` in dashboard buffers, which will prevent this issue occurring from the dashboard. Let me know if that isn't the case!

**Comment by hlissner** [comment]
Nevermind, I had to revert this behavior because it causes a breaking error on startup on the daemon. I'll have to figure out a better solution to this.

**Comment by hlissner** [comment]
This should be resolved as of the latest `develop` for both helm and ivy. Their respective `projectile-find-file` commands will invoke `counsel-find-file`/`helm-find-files` if called from `HOME` which will avoid the "indexing" lockup altogether.
