### ISSUE TITLE
exec-path-from-shell and Linux

### ISSUE THREAD

**Issue by Emiller88** [hlissner/doom-emacs#741]
I use `exec-path-from-shell` on Linux, otherwise, it doesn't pick up my path for eshell. 

I don't mind commenting it out on my fork at all, just wondering when it's only for mac.

https://github.com/hlissner/doom-emacs/blob/5dacbb7cb1c6ac246a9ccd15e6c4290def67757c/core/packages.el#L7

**Comment by hlissner** [comment]
@Emiller88 I'm curious why you use `exec-path-from-shell`. Ensuring Emacs starts with the correct environment is much easier on Linux. Most linux app launchers let you determine what shell to run programs in, and that is the ideal way to do it, since `exec-path-from-shell` only captures your PATH and select other envvars, rather than all of them.

In any case, this is an easily fixed bug. I'll have a fix for it up soon.

**Comment by hlissner** [comment]
As of 7eb3ae6 this should be resolved. Let me know if that isn't the case!

**Comment by Emiller88** [comment]
I'm not familiar with how to set the app launcher shell in gnome, I'll look into it. 

I'll test this later today.

Thanks!
