### ISSUE TITLE
Returning to a search

### ISSUE THREAD

**Issue by paschdan** [hlissner/doom-emacs#742]
### Observed behavior

When I am searching in a project (`SPC / p`) and are visiting the result with `RET` the search is lost

### Expected behavior

How can i get back the the search with the term i inserted?

### System information

develop branch

**Comment by AloisJanicek** [comment]
There is `ivy-resume` command which does exactly what you want if it not called from another ivy interface, because in that case it would resume the current active one.  
So you need to call it from `evil-ex` (`:` or `SPC ;`) or set up key binding for it. I've put it on `SPC =` as this is currently free key combination against doom's default config. Another possibility would be `SPC R` or `SPC r r` if you don't mind mixing it into remote prefix.   

This is example of binding `ivy-resume` to `SPC =`:
```lisp
(map!
 :leader
 :desc "resume latest ivy" :nv "=" #'ivy-resume
 )
```

**Comment by paschdan** [comment]
nice, it dit not work when i tried to do `ivy-resume` from evil-ex (triggered with `:`) that's why i thought it did not work, i just missed the point, that by `TAB` in evil-ex i triggered another ivy 🤕 🔫 
thanks for clearing this up for me.

**Comment by paschdan** [comment]
coming back to this, the `resume-ivy` does not fix this issue completely. It works, as long as i do not use any other ivy command. But when i run some ivy commands in my workflow and want then come back to the search it is gone. Any other suggestion?

**Comment by fuxialexander** [comment]
@paschdan  `(ivy-previous-history-element)`, bound to `M-p` usually.

**Comment by hlissner** [comment]
Since no better solution than using history or ivy-resume exists at the moment (and should probably be requested upstream, rather than in Doom), I'll consider this resolved.
