### ISSUE TITLE
treemacs open error

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#766]
+popup*set-popup: Symbol’s function definition is void: +popup--init

this error appeared after 28e21352ec0d083c13ffe5484f41c3d2d10d29ac.

**Comment by hlissner** [comment]
This should be fixed as of 399194e. Let me know if that isn't the case!

**Comment by Alexander-Miller** [comment]
> Other windows would be resized slightly incorrectly because treemacs
opens as a fixed split, rather than a side window.

In my defense: I have explicitly avoided being a side-window a long time ago, so as to avoid trouble with shell-pop. I cannot seem to reproduce what issues were had back then, so the option for treemacs to be a side-window will come back with https://github.com/Alexander-Miller/treemacs/issues/245.

**Comment by hlissner** [comment]
@Alexander-Miller Totally understandable. I've run up with many of Emacs' quirks associated with side and splitting frame-root windows myself. I'll keep an eye on that issue. Thanks for checking in!
