### ISSUE TITLE
LaTeX Refactoring: cannot disable immediate spell check 

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#775]
In large LaTeX documents, immediate spell checks take too long. In the past, something like 
```lisp
(setq-hook! 'LaTeX-mode-hook +spellcheck-immediately nil)
``` 
would disable the check for all latex buffers. This call doesn't work anymore after the big LaTeX refactor. 

What does work is 
```lisp
(remove-hook 'flyspell-mode-hook #'+spellcheck|immediately)
```
However, it disables the check for all buffers.

**Comment by hlissner** [comment]
```elisp
(setq-hook! 'LaTeX-mode-hook +spellcheck-immediately nil)
```

This should work for you, but the fact that it isn't is likely a matter of load order. Meaning, `+spellcheck-immediately` isn't being set soon enough.

Since lang/latex adds flyspell-mode to the end of `TeX-mode-hook`, it is possible this hook runs _before_ `LaTeX-mode-hook` is, so try this instead:

```elisp
(setq-hook! 'TeX-mode-hook +spellcheck-immediately nil)
```
