### ISSUE TITLE
Error while trying to install package.

### ISSUE THREAD

**Issue by karambaq** [hlissner/doom-emacs#780]
develop branch
I installing the package 

    ;; -*- no-byte-compile: t; -*-
    ;;; ~/.doom.d/packages.el

    (package! emojify)

do make in .emacs.d and there is an error:

    Contacting host: orgmode.org:443
    Package refresh done
    Installing emojify
    ✓ DONE
    Finished!
    
    Deleted old autoloads.pkg.el
    ✓ Cached package state
    ✓ Package autoloads included
    ✓ Removed load-path/auto-mode-alist entries
    
    Eager macro-expansion failure: (error "Found package! call in non-packages.el file (~/.doom.d/packages.el)")
    Eager macro-expansion failure: (error "Found package! call in non-packages.el file (~/.doom.d/packages.el)")
    --------------------------------------------------
    
    There was an unexpected error:
      Error in private config (doom-private-error)
      packages.el
      (error Found package! call in non-packages.el file (~/.doom.d/packages.el))
    
    Run the command again with the -d (or --debug) option to enable debug
    mode and, hopefully, generate a stack trace. If you decide to file a bug
    report, please include it!
    
    Emacs outputs to standard error, so you’ll need to redirect stderr to
    stdout to pipe this to a file or clipboard!
    
      e.g. doom -d install 2>&1 | clipboard-program
    Detected a running Emacs session.
    
    Restart Emacs or use ‘M-x doom/reload’ for changes to take effect.

What I did wrong?

**Comment by hlissner** [comment]
This is an odd error. It's complaining you are using `package!` outside of a `~/.doom.d/packages.el` file.

Are you sure you do not have something like 

```elisp
(load! "+packages")
```

in your `~/.doom.d/config.el` or `~/.doom.d/init.el`? That would cause this error. You musn't try to load `init.el`, `config.el` or `packages.el` yourself, these are special files.

**Comment by karambaq** [comment]
@hlissner I have 

    (load! "packages")

In my config.el, you said to me that only `init.el` and `config.el` loads automatically, so I think I should load `packages.el` too

**Comment by hlissner** [comment]
Ah I see. My bad. That is not the whole picture: init.el and config.el are the only files loaded _at startup_, but they are not the only special files. 

These are _all_ the "special" files that a module may have:

```
init.el
config.el
packages.el
doctor.el
autoload.el
autoload/*.el
```

+ packages.el is only loaded when Doom needs to see what packages this module needs (like when you run `bin/doom refresh` or `bin/doom install`. You don't need to load it yourself.
+ doctor.el is called by `bin/doom doctor`, and gives your module a chance to check if its dependencies are properly installed and set up (and complain otherwise).
+ autoload.el and autoload/*.el should contain functions with an `;;;###autoload` cookie. These files aren't loaded until these autoloaded functions are called.
