### ISSUE TITLE
zsh and env variables not being set

### ISSUE THREAD

**Issue by GoingFast** [hlissner/doom-emacs#782]
trying to use golang with doom emacs however env variables like PATH and GOPATH arent being set. M-x getenv shell is /usr/bin/zsh. I have my exports in both .zshrc and .zshenv. If I launch emacs from shell everything is ok, env variables set etc but on GUI not working. distro is ubuntu. not sure whats the problem. using develop branch

**Comment by GoingFast** [comment]
got help from discord. I'm using rofi so I had to start rofi with -run-command "zsh -c '{cmd}'" args to have env variables set

**Comment by hlissner** [comment]
This was resolved on Discord, but I'll repost here for posterity:

-----

Linux users who use app launchers like Unity, rofi, dmenu, etc. may have this issue if their app launcher isn't configured to open programs in the correct shell.

Since you are a rofi user, and rofi doesn't respect the user's SHELL by default, you have two options:

1. To ensure that rofi is invoked with `rofi -run-command "zsh -c '{cmd}'"`

2. Or place a shell script named `emacs` somewhere in your PATH (where rofi will pick it up), where it has higher precedence over `/usr/bin/emacs`:

   ```sh
   #!/usr/bin/env zsh
   zsh -c emacs
   ```
