### ISSUE TITLE
Leader key bindings unavailable in Ledger report

### ISSUE THREAD

**Issue by siddharthshekar** [hlissner/doom-emacs#818]
### Observed behavior

Pressing `SPC` in a Ledger report file has which-key prompt "There are no keys to show".

### Expected behavior

Pressing `SPC` should show the regular leader commands available everywhere else.

### Steps to reproduce

1. Create a Ledger file that you can run a report on.
2. Run a report, say, bal.
3. In the Ledger report window, press `SPC`.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop f9b06bd3a84e7c9a4de95bca905b92d9aaadc2fd)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  elisp
  elc count: 0
  uname -a:  Linux siddharth-VirtualBox 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs popup vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit pdf :lang emacs-lisp latex ledger markdown (org +attach +babel +capture +present) python (sh +fish) :app :config (default +bindings +snippets +evil-commands) sid)
  packages:  (evil-nerd-commenter gruvbox-theme mu4e-alert ox-hugo ox-twbs ranger uuidgen)
  exec-path: (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.1/x86_64-linux-gnu)
  ```
</details>

On a side note, could you explain what happens when you actually press the leader key? Is there some place where you have to register the leader related keybindings for a particular mode's map?

This same thing can also be seen in Org agenda buffers, although I wasn't sure if that was by design or not.

**Comment by hlissner** [comment]
As of ce4891e, this should be fixed. Feel free to reopen this if that isn't the case!

**Comment by siddharthshekar** [comment]
This has introduced another bug with the following error message on opening a ledger file:

```File mode specification error: (error Key sequence S P C starts with non-prefix key S)```

**Comment by hlissner** [comment]
My bad. Forgot to use `kbd`! 18a0b05 should fix that.

**Comment by siddharthshekar** [comment]
I tried that independently but that ends up going back to the same issue as the original post where pressing `SPC` now shows "There are no keys to show". Also, forgive my ignorance, but I'm unclear on how I can re-open the issue, I just seem to have the option to comment -_-

**Comment by guoxiaohu** [comment]
There seems issue of A and M key as well

**Comment by hlissner** [comment]
It turns out that both your issues are caused by `ledger-report-mode` starting in motion mode, rather than normal mode. All leader keys are bound to either normal or visual modes (i.e. none are bound to the motion mode keymap, hence the "There are no keys to show" message).

Give this a try:

```elisp
(set-evil-initial-state! 'ledger-report-mode 'normal)
```

> This same thing can also be seen in Org agenda buffers, although I wasn't sure if that was by design or not

This is not by design. There are many causes for these keybinding issues and I am working on a fix for them all (by introducing [general](https://github.com/noctuid/general.el) to Doom). I'm afraid you'll have to put up with it a bit longer.

> On a side note, could you explain what happens when you actually press the leader key? Is there some place where you have to register the leader related keybindings for a particular mode's map?

All leader keybindings can be found in [modules/config/default/+bindings.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+bindings.el#L474). There is nothing special about them, besides that they should, by convention, be global (i.e. present in all buffers).

Local leader keybinds, however, should be buffer-local by convention. You'll find them bound in their respective modules. `ledger-mode` doesn't have any, but you'll see them [in](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/python/config.el#L115-L124) [other](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/javascript/config.el#L214-L232) [modules](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L336-L345).

Under the hood, there isn't anything too complicated going on. `:leader` is simply an alias for `:prefix doom-leader-key` (i.e. `:prefix "SPC"`), as `:localleader` is `:prefix doom-localleader-key` (i.e. `:prefix "SPC m"`). So `(map! :leader :prefix "y" "z" #'do-something)` is equivalient to `(map! "SPC y z" #'do-something)`.

To bind a localleader key, it is the convention to bind it to a keymap (thus restricting it to a certain mode). e.g.

```elisp
(map! :map ledger-mode-map
      :localleader
      "x" #'do-something)
```

I hope that answers your question!

**Comment by siddharthshekar** [comment]
Setting the initial state to start off in normal mode works like a charm!

Thanks for your detailed explanation regarding the leader key too! I wasn't sure if the leader key action was supposed to be enabled in all buffers by default, or if modes had to be "signed up" to recognize the leader key and handle  them separately. I guess the motion mode in ledger-report-mode was what was throwing me off.

Thanks again for your work in making Doom!
