### ISSUE TITLE
Orgmode insert link tab completion

### ISSUE THREAD

**Issue by njnygaard** [hlissner/doom-emacs#829]
`develop` branch. Basic troubleshooting tried. No modifications (that I remember).

### Observed behavior

- When inserting a link in a `.org` file, `C-c C-l` allows me to type `fil` and hit `RET` to select `file:`.
- It then takes me to the current directory.
- Pressing `Left Arrow` goes up one directory.
- Pressing `Right Arrow` throws the error `Cannot split side window or parent of side window`. `TAB` throws the same error.

### Expected behavior

I would have hoped that I could tab complete my way through a file selection for a link.

### Steps to reproduce

Above.

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop e3f412abb749d7465d99b46a99b7f4a32373d60c)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
```
  elisp
  elc count: 0
  uname -a:  Darwin Admins-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools :lang emacs-lisp markdown (org +attach +babel +capture +export +present) (sh +fish) :config)
  packages:  n/a
  exec-path: (/usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/TeX/texbin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec/)
```

</details>

**Comment by hlissner** [comment]
As of 619ac43, 6b91039 and 933322e:

+ left/right arrow now move the cursor as normal
+ TAB and right arrow should no longer display the "cannot split side window" error.
+ TAB is now bound to `helm-execute-persistent-action`, which will preview the selected file in org-insert-link.

This is more predictable behavior, at least. However, you mentioned tab completion. `helm-execute-persistent-action` will perform tab completion for _some_ commands, but not all. helm-find-files and org-insert-link are two commands for which it does not.

As far as I know, there is no way to ensure that tab completion is performed for all commands. This is by design with Helm, because it is performing live completion for you already, as you type, which makes tab completion superfluous.

Unfortunately, beyond this point, it is a helm issue, rather than a Doom issue, so I'll consider this effectively resolved, but feel free to follow up here if you'd like to discuss it further.

**Comment by njnygaard** [comment]
You worked on this faster than the stuff I get **paid** for.

Tab completion works now, but when I actually select the file for inserting the link, I get `No buffer named *Org Links*`. Any ideas? 

```
git --no-pager log | head

commit 62b9166871afcab83771cd02b586fea6cc57a671
Author: Henrik Lissner <henrik@lissner.net>
Date:   Fri Aug 24 12:36:16 2018 +0200

    Change :make to reuse last command

    Unless given a command.

commit 9eee22e3fcc15412db6d1f69c0294c090cb4aa5a
Author: Henrik Lissner <henrik@lissner.net>
```

`make && make install` run

**Comment by njnygaard** [comment]
Also, up and down in Helm (I think helm) don't really work for selecting files anymore. `SPC b b` then `down` says `End of history; no default available`.

**Comment by hlissner** [comment]
I restored the <kbd>up</kbd>/<kbd>down</kbd> keybinds in https://github.com/hlissner/doom-emacs/commit/469cc7fbc1a0b3f4edfa944d2fbdb7cad5fea955. As for the `No buffer named *Org Links*` error, it's a regression from the fix for the `Cannot split side window or parent of side window` error. I'll have to come up with a better solution; will do in the morning!

**Comment by hlissner** [comment]
With `kbd` tags: `<kbd>up</kbd>/<kbd>down</kbd>` =  <kbd>up</kbd>/<kbd>down</kbd>

**Comment by hlissner** [comment]
Sorry for the long wait! As of b76a095 this issue should be resolved. Please update and let me know if that isn't the case and I will reopen this.
