### ISSUE TITLE
python file incorrect formatting

### ISSUE THREAD

**Issue by nasoundead** [hlissner/doom-emacs#914]
### Observed behavior
 I‘ve opened '(format +onsave)' and 'python' fearture, but when i format python buffer on save, '^M' appears at end of each line.

### Expected behavior

There should be no ^M at end of each line.

### Steps to reproduce

format python buffer on save.

### System information
Windows7-Simplified Chinese

**Comment by hlissner** [comment]
If you open a python buffer and run `M-x format-all-buffer`, do these `^M` characters appear?

If so, this suggests the issue is either with the [format-all](https://github.com/lassik/emacs-format-all-the-code) Emacs package, or the python formatter, [black](https://github.com/ambv/black). Likely to do with EOL encodings on Windows.

**Comment by nasoundead** [comment]
@hlissner Thanks for your reply. I can reproduce this as your suggestion on win7, and can not reproduce on win10.

**Comment by nasoundead** [comment]
And after open the python buffer, I try to run M-x shell.
In the shell of Emacs, i input 'black .', the file is formatted correctly.

**Comment by JustasMasiulis** [comment]
@nasoundead I am using windows 10 and this problem seems to occur to me too.

I have a feeling this might depend on some external tooling - for example to get the formatting working I needed to add `diff` to the PATH environment variable. I ended up using the executable shipped with `git`. Did you happen to use some other version of it?

**Comment by nasoundead** [comment]
Did you happen to use some other version of it?
------------------------------------------------------
@JustasMasiulis Yes, I have installed two tool-chain system, 'Msys2' and 'Git-for-Windows'. Msys2's diff.exe will be called first.

**Comment by nasoundead** [comment]
My go file is also incorrectly formatted. So “emacs-format-all-the-code” has gone wrong?

**Comment by nasoundead** [comment]
After commented ”coding-system-for-read 'utf-8/coding-system-for-write 'utf-8“ in "+format-buffer"(format.el), the file is now formatted well.

**Comment by smallzhan** [comment]
@nasoundead  the trick works.

@hlissner since `format-all-buffer` is advised by function` +format-buffer` in doom-emacs, after remove the advice, there is no additional CR.  Seems really that `coding-system-for-read` and `coding-system-for-write ` issue in function `+format-buffer`..

**Comment by hlissner** [comment]
I've undone `coding-system-for-read` and `coding-system-for-write` on Windows systems in 0c743af. Please update and let me know if that fixes your issues.

**Comment by smallzhan** [comment]
@hlissner  it works here.  I've tested  on python and c files.

**Comment by hlissner** [comment]
In that case, I'll consider this resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
