### ISSUE TITLE
Easy way to set projectile-ignore-files/dirs for each lang

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#976]
If I am not wrong, the following seems the only way to add directories to projectile ignored directories.

```
(def-package haskell-mode
  (after! projectile
    (add-to-list 'projectile-globally-ignored-directories
                 ".stack-work")))
```

Is there any easier way?

**Comment by hlissner** [comment]
You're expected to use your VCS's ignore file (e.g. `.gitignore`), as projectile doesn't respect any of its ignore variables unless you're using the much slower `native` indexing methods.

On windows, `native` is your only option, so on the off chance you're a Windows user, rather than wrap that `add-to-list` call in an `after!` in an `def-package!`, you could a) add them all at once in one place:

```elisp
(after! projectile
  (nconc projectile-globally-ignored-directories
         '(".stack-work" "node_modules" ".local" "..."))
```

Or b) add them after a certain major-mode's package is loaded. It's safe to assume projectile has been loaded by the time any major-mode (besides fundamental-mode) has been loaded:

```elisp
(after! haskell-mode
  (add-to-list 'projectile-globally-ignored-directories ".stack-work"))

(after! js2-mode
  (add-to-list 'projectile-globally-ignored-directories "node_modules"))
```

The only exception to this rule is if you load `haskell-mode` during startup, non-interactively.

**Comment by zeronone** [comment]
Oh I see, I didn't know `.gitignore` is used. Thank you, that solved the problem in my case.
